/* Auto-generated by img2charset.py - do not edit */
#include "blank.h"

/* 1 characters, 11 byte(s) per character */
const unsigned char blank_charset[1][11] = {
    { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }  /* blank_0 */
};
