/* Auto-generated by img2charset.py - do not edit */
#ifndef BLANK_H
#define BLANK_H

/* Character cell dimensions */
#define BLANK_CHAR_WIDTH   5
#define BLANK_CHAR_DEPTH   11
#define BLANK_NUM_CHARS    1

/* Per-character index equates */
#define blank_0  0

/* Table declaration */
extern const unsigned char blank_charset[1][11];

#endif /* BLANK_H */
