/* Auto-generated by img2charset.py - do not edit */
#ifndef BLIP_H
#define BLIP_H

/* Character cell dimensions */
#define BLIP_CHAR_WIDTH   5
#define BLIP_CHAR_DEPTH   11
#define BLIP_NUM_CHARS    8

/* Per-character index equates */
#define blip_0  0
#define blip_1  1
#define blip_2  2
#define blip_3  3
#define blip_4  4
#define blip_5  5
#define blip_6  6
#define blip_7  7

/* Table declaration */
extern const unsigned char blip_charset[8][11];

#endif /* BLIP_H */
