/* Auto-generated by img2charset.py - do not edit */
#ifndef NUMBERS_H
#define NUMBERS_H

/* Character cell dimensions */
#define NUMBERS_CHAR_WIDTH   5
#define NUMBERS_CHAR_DEPTH   11
#define NUMBERS_NUM_CHARS    32

/* Per-character index equates */
#define numbers_0  0
#define numbers_1  1
#define numbers_2  2
#define numbers_3  3
#define numbers_4  4
#define numbers_5  5
#define numbers_6  6
#define numbers_7  7
#define numbers_8  8
#define numbers_9  9
#define numbers_10  10
#define numbers_11  11
#define numbers_12  12
#define numbers_13  13
#define numbers_14  14
#define numbers_15  15
#define numbers_16  16
#define numbers_17  17
#define numbers_18  18
#define numbers_19  19
#define numbers_20  20
#define numbers_21  21
#define numbers_22  22
#define numbers_23  23
#define numbers_24  24
#define numbers_25  25
#define numbers_26  26
#define numbers_27  27
#define numbers_28  28
#define numbers_29  29
#define numbers_30  30
#define numbers_31  31

/* Table declaration */
extern const unsigned char numbers_charset[32][11];

#endif /* NUMBERS_H */
