#pragma once

enum ObjectType {

    // update Attribute[] in attribute.c
    // update AnimateBase[] in animations.c
    // update PickupCharacter[] in animations.c


    TYPE_BLANK,                    // 00      ASSUMED == 0 in code
    TYPE_PLACEHOLDER,              // 01
    TYPE_DIRT,                     // 02
    TYPE_BRICKWALL,                // 03
    TYPE_DOOR,                     // 04
    TYPE_OUTBOX,                   // 05
    TYPE_STEELWALL,                // 06
    TYPE_ROCK,                     // 07
    TYPE_DOGE,                     // 08
    TYPE_MELLON_HUSK_PRE,          // 09
    TYPE_MELLON_HUSK,              // 10
    TYPE_PEBBLE1,                  // 11
    TYPE_DUST_0,                   // 12
    TYPE_DOGE_FALLING,             // 13
    TYPE_ROCK_FALLING,             // 14
    TYPE_DUST_ROCK,                // 15
    TYPE_CONVERT_GEODE_TO_DOGE,    // 16
    TYPE_PUSHER,                   // 17
    TYPE_PUSHER_VERT,              // 18
    TYPE_WYRM,                     // 19
    TYPE_GEODOGE,                  // 20
    TYPE_GEODOGE_FALLING,          // 21
    TYPE_LAVA,                     // 22
    TYPE_PEBBLE_ROCK,              // 23
    TYPE_FLIP_GRAVITY,             // 24
    TYPE_BLOCK,                    // 25
    TYPE_GRINDER,                  // 26
    TYPE_HUB,                      // 27
    TYPE_WATER,                    // 28
    TYPE_WATERFLOW_0,              // 29
    TYPE_WATERFLOW_1,              // 30
    TYPE_WATERFLOW_2,              // 31
    TYPE_WATERFLOW_3,              // 32
    TYPE_WATERFLOW_4,              // 33
    TYPE_TAP,                      // 34
    TYPE_OUTLET,                   // 35
    TYPE_GRINDER_1,                // 36
    TYPE_BELT,                     // 37
    TYPE_BELT_1,                   // 38
    TYPE_CONVERT_PIPE,             // 39
    TYPE_DOGE_FALLING2,            // 40
    TYPE_ROCK_PEBBLE,              // 41
    TYPE_ELECTRIC,                 // 42
    TYPE_INSULATOR,                // 43
    TYPE_STAR,                     // 44
    TYPE_STAR_FALLING,             // 45
    TYPE_STAR_EXPLODE,             // 46
    TYPE_ROCK_BONUS,               // 47
    TYPE_MOUNT,                    // 48
    TYPE_BOMB,                     // 49
    TYPE_CRACKED_BRICK,            // 52
    TYPE_CONCRETE,                 // 53
    TYPE_TELEPORT,                 // 54
    TYPE_KEY,                      // 55

    // A door that has finished the AnimateDoor slide-open (animations.c) -- same walkable/exit
    // attributes as TYPE_OUTBOX, but its own AnimateBase entry is 0 (no animation), so it just
    // sits on CH_DOOROPEN_STATIC forever instead of inheriting TYPE_OUTBOX's AnimFlashOut cycle
    // (that flash is fine for the real level exit, but reads as a bug on an ordinary unlocked
    // door). Also skipped by board.c's per-visit CH_DOOROPEN_0 FLASH()/particle case, for the
    // same reason -- see CH_DOOROPEN_STATIC's own comment.
    TYPE_DOOR_OPEN,                // 56

    // Falls like a rock (same gravity/TOP-BOTTOM split mechanism) but can't be mined (no
    // ATT_MINE) or destroyed by explosions (no ATT_EXPLODABLE), and can't be pushed or picked
    // up by the player (no ATT_PUSH/ATT_PICKUP) -- see attribute.c's own comment on its
    // Attribute[] row for the full reasoning on each omission.
    TYPE_IMMOVABLE,                 // 57
    TYPE_IMMOVABLE_FALLING,         // 58

    // The 1-frame diagonal-roll transition (CH_ROCK_SIDE_1-4, attribute.h) a settled rock passes
    // through when it rolls off something with ATT_ROLL underneath it instead of falling
    // straight down -- see doRollRock()'s comment (board.c) for the full mechanic.
    TYPE_ROCK_ROLLING,              // 59

    TYPE_MAX
};

extern const unsigned int Attribute[];
extern const enum ObjectType CharToType[];

enum ChName {

    // see charSet[] @ characterset.c
    // Objects numbered > 127 cannot be generated by cave data (top bit is flag bit in board)
    // see CharToType[] in attribute.c (for # < 128)

    CH_BLANK,                     // 0
    CH_PLACEHOLDER,               // 1
    CH_DIRT,                      // 2
    CH_BRICKWALL,                 // 3
    CH_DOORCLOSED,                // 4
    CH_DOOROPEN_0,                // 5
    CH_EXITBLANK,                 // 6
    CH_STEELWALL,                 // 7
    CH_PEBBLE1,                   // 8
    CH_PEBBLE2,                   // 9
    CH_ROCK,                      // 10
    CH_ROCK_FALLING,              // 11          +2 offset assumed by code
    CH_DOGE_00,                   // 12
    CH_DOGE_FALLING,              // 13          +2 offset assumed by code
    CH_MELLON_HUSK_BIRTH,         // 14
    CH_LAVA_BLANK,                // 15
    CH_LAVA_SMALL,                // 16
    CH_LAVA_MEDIUM,               // 17
    CH_LAVA_LARGE,                // 18
    CH_MELLON_HUSK,               // 19
    CH_DOGE_STATIC,               // 20 (CAN SWITCH ANIMATIONS ON THIS!)
    CH_PEBBLE_ROCK,               // 21
    CH_ROCK_PEBBLE,               // 22
    CH_ROCK_PEBBLE_1,             // 23
    CH_DUST_0,                    // 24
    CH_DUST_1,                    // 25
    CH_DUST_2,                    // 26
    CH_GEODOGE,                   // 27
    CH_DUST_ROCK_0,               // 28
    CH_DUST_ROCK_1,               // 29
    CH_DUST_ROCK_2,               // 30
    CH_CONVERT_GEODE_TO_DOGE,     // 31
    CH_HORIZONTAL_BAR,            // 32
    CH_PUSH_LEFT,                 // 33       reverse must be +1
    CH_PUSH_LEFT_REVERSE,         // 34
    CH_PUSH_RIGHT,                // 35
    CH_PUSH_RIGHT_REVERSE,        // 36
    CH_VERTICAL_BAR,              // 37
    CH_PUSH_UP,                   // 38
    CH_PUSH_UP_REVERSE,           // 39
    CH_PUSH_DOWN,                 // 40
    CH_PUSH_DOWN_REVERSE,         // 41
    CH_WYRM_BODY,                 // 42
    CH_WYRM_VERT_BODY,            // 43
    CH_WYRM_CORNER_LD,            // 44
    CH_WYRM_CORNER_RD,            // 45
    CH_WYRM_CORNER_LU,            // 46
    CH_WYRM_CORNER_RU,            // 47
    CH_WYRM_HEAD_U,               // 48
    CH_WYRM_HEAD_R,               // 49
    CH_WYRM_HEAD_D,               // 50
    CH_WYRM_HEAD_L,               // 51
    CH_GEODOGE_FALLING,           // 52
    CH_FLIP_GRAVITY_0,            // 53
    CH_FLIP_GRAVITY_1,            // 54
    CH_FLIP_GRAVITY_2,            // 55
    CH_BLOCK,                     // 56
    CH_GRINDER_0,                 // 57
    CH_GRINDER_1,                 // 58
    CH_HUB,                       // 59
    CH_WATER,                     // 60
    CH_WATERFLOW_0,               // 61 must be grouped
    CH_WATERFLOW_1,               // 62 .
    CH_WATERFLOW_2,               // 63 .
    CH_WATERFLOW_3,               // 64 .
    CH_WATERFLOW_4,               // 65 /
    CH_HUB_1,                     // 66
    CH_OUTLET,                    // 67
    CH_BELT_0,                    // 68
    CH_BELT_1,                    // 69
    CH_PUSH_DOWN2,                // 70
    CH_GEODOGE_CONVERT,           // 71
    CH_CONVERT_PIPE,              // 72
    CH_WYRM_TAIL_U,               // 73
    CH_WYRM_TAIL_R,               // 74
    CH_WYRM_TAIL_D,               // 75
    CH_WYRM_TAIL_L,               // 76
    CH_DOGE_FALLING_TOP,          // 77
    CH_DOGE_FALLING_BOTTOM,       // 78
    CH_ROCK_FALLING_TOP,          // 79
    CH_ROCK_FALLING_BOTTOM,       // 80
    CH_GEODOGE_FALLING_TOP,       // 81
    CH_GEODOGE_FALLING_BOTTOM,    // 82
    CH_DOGE_FALLING_TOP2,         // 83
    CH_DOGE_FALLING_BOTTOM2,      // 84
    CH_DOGE_SIDE_1,               // 85
    CH_DOGE_SIDE_3,               // 86
    CH_DOGE_SIDE_2,               // 87
    CH_DOGE_SIDE_4,               // 88
    CH_ELECTRIC_0,                // 89
    CH_ELECTRIC_1,                // 90
    CH_ELECTRIC_2,                // 91
    CH_ELECTRIC_3,                // 92
    CH_BROKEN_DIRT,               // 93
    CH_INSULATOR_TOP,             // 94
    CH_INSULATOR_BOTTOM,          // 95
    CH_STAR,                      // 96
    CH_STAR_FALLING_TOP,          // 97
    CH_STAR_FALLING_BOTTOM,       // 98
    CH_ROCK_BONUS,                // 99
    CH_STAR_EXPLODE,              // 100
    CH_INSULATOR_L,               // 101
    CH_INSULATOR_R,               // 102
    CH_ELECTRIC_H0,               // 103
    CH_ELECTRIC_H1,               // 104
    CH_ELECTRIC_H2,               // 105
    CH_ELECTRIC_H3,               // 106
    CH_CROSSED_STREAMS,           // 107
    CH_MOUNT_U,                   // 108
    CH_MOUNT_D,                   // 109
    CH_MOUNT_L,                   // 110
    CH_MOUNT_R,                   // 111
    CH_BOMB,                      // 112
    CH_CRACKED_BRICK,             // 113
    CH_CONCRETE,                  // 114
    CH_TELEPORT,                  // 115
    CH_KEY,                       // 116

    // The board byte AnimateDoor (animations.c) ends on and updateDoorUnlock()/board.c's
    // CH_DOORCLOSED case commit to once the slide-open finishes -- same graphic as CH_DOOROPEN_0
    // (both map to the same charSet[] cell) but its own TYPE_DOOR_OPEN (attribute.h/.c) so it
    // doesn't inherit TYPE_OUTBOX's flashing (see TYPE_DOOR_OPEN's own comment). Real board
    // character, deliberately kept < 128 unlike CH_DOORSLIDE_1 -- it's what the tile actually
    // and permanently becomes, not a mid-flight animation-only frame.
    CH_DOOROPEN_STATIC,           // 117

    // An indestructible falling block -- see TYPE_IMMOVABLE's own comment (above) for the
    // attribute reasoning. CH_IMMOVABLE_FALLING reuses CH_IMMOVABLE's own graphic (same
    // convention as CH_ROCK/CH_ROCK_FALLING both pointing at one charSet[] cell); the TOP/
    // BOTTOM pair are the one-frame split used while it's mid-fall between two board rows,
    // same mechanism as CH_ROCK_FALLING_TOP/BOTTOM.
    CH_IMMOVABLE,                 // 118
    CH_IMMOVABLE_FALLING,         // 119
    CH_IMMOVABLE_FALLING_TOP,     // 120
    CH_IMMOVABLE_FALLING_BOTTOM,  // 121

    // Diagonal-roll transition, same 1-frame-then-resolve idea as CH_DOGE_SIDE_1-4 but for a
    // settled CH_ROCK rolling off an ATT_ROLL surface instead of a doge: _1/_2 are the departing
    // (current) square for a roll right/left respectively, and become blank next scan; _3/_4 are
    // the arriving square, and become the ordinary CH_ROCK_FALLING_TOP/BOTTOM pair next scan (so
    // the rock immediately continues falling from its new column) -- see doRollRock() (board.c).
    // Artwork: same horizontal-split technique CH_ROCK_FALLING_TOP/BOTTOM already use vertically
    // -- the rock's own image shifted 3px sideways (of its 5px cell width) and cut at the column
    // boundary, so _1/_2 show the trailing sliver still left in the departing cell and _3/_4 show
    // the leading bulk that's already arrived, together reading as one rock straddling both
    // squares for that single frame.
    CH_ROCK_SIDE_1,               // 122
    CH_ROCK_SIDE_2,               // 123
    CH_ROCK_SIDE_3,               // 124
    CH_ROCK_SIDE_4,               // 125

    // 126, 127 unused -- 2 free board-resident slots (CH_DOGE_01 below is pinned to 128 via an
    // explicit enum initializer, so removing entries up here doesn't shrink the virtual range;
    // it just reopens gap slots like this one)

    // 127 is limit of board-resident character numbers

    // 128 onward are virtual characters from animations
    // these can't go on board but can be displayed via realtime animation

    CH_DOGE_01 = 128,      // 128
    CH_DOGE_02,            // 129
    CH_DOGE_03,            // 130
    CH_DOGE_04,            // 131
    CH_DOGE_05,            // 132
                           //
    CH_BOMB_FLASH,         // 133
                           //
    CH_CRACKED_BRICK_1,    // 134
    CH_CRACKED_BRICK_2,    // 135
    CH_CRACKED_BRICK_3,    // 136
    CH_CRACKED_BRICK_4,    // 137
    CH_CRACKED_BRICK_5,    // 138
    CH_CRACKED_BRICK_6,    // 139
    CH_CRACKED_BRICK_7,    // 140

    CH_0,    // 141
    CH_1,    // 142
    CH_2,    // 143
    CH_3,    // 144
    CH_4,    // 145
    CH_5,    // 146
    CH_6,    // 147
    CH_7,    // 148
    CH_8,    // 149
    CH_9,    // 150

    CH_A,    // 151
    CH_B,    // 152
    CH_C,    // 153
    CH_D,    // 154
    CH_E,    // 155
    CH_F,    // 156
    CH_G,    // 157
    CH_H,    // 158
    CH_I,    // 159
    CH_J,    // 160
    CH_K,    // 161
    CH_L,    // 162
    CH_M,    // 163
    CH_N,    // 164
    CH_O,    // 165
    CH_P,    // 166
    CH_Q,    // 167
    CH_R,    // 168
    CH_S,    // 169
    CH_T,    // 170
    CH_U,    // 171
    CH_V,    // 172
    CH_W,    // 173
    CH_X,    // 174
    CH_Y,    // 175
    CH_Z,    // 176

    CH_CAP_A,    // 177
    CH_CAP_B,    // 178
    CH_CAP_C,    // 179
    CH_CAP_D,    // 180
    CH_CAP_E,    // 181
    CH_CAP_F,    // 182
    CH_CAP_G,    // 183
    CH_CAP_H,    // 184
    CH_CAP_I,    // 185
    CH_CAP_J,    // 186
    CH_CAP_K,    // 187
    CH_CAP_L,    // 188
    CH_CAP_M,    // 189
    CH_CAP_N,    // 190
    CH_CAP_O,    // 191
    CH_CAP_P,    // 192
    CH_CAP_Q,    // 193
    CH_CAP_R,    // 194
    CH_CAP_S,    // 195
    CH_CAP_T,    // 196
    CH_CAP_U,    // 197
    CH_CAP_V,    // 198
    CH_CAP_W,    // 199
    CH_CAP_X,    // 200
    CH_CAP_Y,    // 201
    CH_CAP_Z,    // 202

    CH_PLUS,    // 203

    CH_BIG_0,    // 204
    CH_BIG_1,    // 205
    CH_BIG_2,    // 206
    CH_BIG_3,    // 207
    CH_BIG_4,    // 208
    CH_BIG_5,    // 209
    CH_BIG_6,    // 210
    CH_BIG_7,    // 211
    CH_BIG_8,    // 212
    CH_BIG_9,    // 213

    // "Animated" chars, never placed on the board (see the >127 comment above the CH_TELEPORT
    // slot) -- the other 7 frames of the teleport tile's spinning-spoke cycle. CH_TELEPORT
    // itself (below 128, since it IS placed on the board via cave data) is frame 0; these are
    // 1-7. See AnimTeleport (animations.c) -- TYPE_TELEPORT auto-advances through all 8 fixed
    // ROM bitmaps like any other animated character (processCharAnimations()), no per-frame
    // hand-holding needed.
    CH_TELEPORT_1,    // 214
    CH_TELEPORT_2,    // 215
    CH_TELEPORT_3,    // 216
    CH_TELEPORT_4,    // 217
    CH_TELEPORT_5,    // 218
    CH_TELEPORT_6,    // 219
    CH_TELEPORT_7,    // 220

    // Door slide-open frame -- AnimateDoor (animations.c). Only the closed (CH_DOORCLOSED) and
    // fully-open (CH_DOOROPEN_0) frames are ever real board bytes; this in-between frame, like
    // CH_TELEPORT_1-7 above, only ever exists as *Animate[TYPE_DOOR] while the animation is
    // mid-flight (drawScreen.c substitutes *Animate[type] for the raw board byte whenever it's
    // set -- see its own comment). Symmetric centre-split opening on a 5px-wide glyph only has
    // room for one such step without the door ending up fully blank -- see AnimateDoor's comment.
    CH_DOORSLIDE_1,    // 221

    CH_MAX
};

// clang-format off

#define ENUM_BIT_VALUE(counter) (1 << counter)

#define DEFINE_ENUM_WITH_BIT_VALUES(enumType, ...) \
    typedef enum { \
        __VA_ARGS__ \
    } enumType

#define ATT(enumConstant) ATT_##enumConstant = ENUM_BIT_VALUE(__COUNTER__)

DEFINE_ENUM_WITH_BIT_VALUES(TypeAttributes,

    ATT(ROLL),                  // 00
    ATT(CONVERT),               // 01
    ATT(EXPLODABLE),            // 02
    ATT(PERMEABLE),             // 03
    ATT(BLANK),                 // 04
    ATT(DIRT),                  // 05
    ATT(GRAB),                  // 06
    ATT(PUSH),                  // 07
    ATT(SQUASHABLE_TO_BLANKS),  // 08
    ATT(HARD),                  // 09
    ATT(EXIT),                  // 10
    ATT(NOROCKNOISE),           // 11
    ATT(BLANKISH),              // 12
    ATT(MINE),                  // 13
    ATT(WATERFLOW),             // 14
    ATT(CONVEYOR),              // 15
    ATT(GRIND),                 // 16
    ATT(PIPE),                  // 17
    ATT(PHASE4),                // 18
    ATT(PHASE2),                // 19
    ATT(PHASE1),                // 20
    ATT(DISSOLVES),             // 21
    ATT(MELTS),                 // 22
    ATT(GEODOGE),               // 23 must match POS_GEODOGE
    ATT(PAD),                   // 24
    ATT(CRUSHES),               // 25
    ATT(CORNER),                // 26  must match POS_CORNER
    ATT(PICKUP),                // 27
    ATT(MASSIVE),               // 28
    ATT(DRIP),                  // 29  can have a rain drip form beneath it
    ATT(SHOVE),                 // 30  can be pushed sideways by the player walking into it
                                //     (distinct from ATT_PUSH/PSH, which is "can be pushed BY
                                //     a pusher-bar MACHINE", board.c's genericPush() -- kept
                                //     last so it doesn't renumber POS_CORNER/POS_GEODOGE below,
                                //     which are pinned to specific counter positions)
);

#define POS_CORNER 26           /* must match ATT(CORNER) #*/
#define POS_GEODOGE 23          /* must match ATT(GEOFOGE) */

#define VALUE_BREAK_GEODE 25

// EOF
