#pragma once

enum ObjectType {

    // update Attribute[] in attribute.c
    // update AnimateBase[] in animations.c
    // update PickupCharacter[] in animations.c


    TYPE_BLANK,                    // 00      ASSUMED == 0 in code
    TYPE_PLACEHOLDER,              // 01
    TYPE_DIRT,                     // 02
    TYPE_BRICKWALL,                // 03
    TYPE_OUTBOX_PRE,               // 04
    TYPE_OUTBOX,                   // 05
    TYPE_STEELWALL,                // 06
    TYPE_ROCK,                     // 07
    TYPE_DOGE,                     // 08
    TYPE_MELLON_HUSK_PRE,          // 09
    TYPE_MELLON_HUSK,              // 10
    TYPE_PEBBLE1,                  // 11
    TYPE_DUST_0,                   // 12
    TYPE_DOGE_FALLING,             // 13
    TYPE_ROCK_FALLING,             // 14
    TYPE_DUST_ROCK,                // 15
    TYPE_CONVERT_GEODE_TO_DOGE,    // 16
    TYPE_PUSHER,                   // 17
    TYPE_PUSHER_VERT,              // 18
    TYPE_WYRM,                     // 19
    TYPE_GEODOGE,                  // 20
    TYPE_GEODOGE_FALLING,          // 21
    TYPE_LAVA,                     // 22
    TYPE_PEBBLE_ROCK,              // 23
    TYPE_FLIP_GRAVITY,             // 24
    TYPE_BLOCK,                    // 25
    TYPE_GRINDER,                  // 26
    TYPE_HUB,                      // 27
    TYPE_WATER,                    // 28
    TYPE_WATERFLOW_0,              // 29
    TYPE_WATERFLOW_1,              // 30
    TYPE_WATERFLOW_2,              // 31
    TYPE_WATERFLOW_3,              // 32
    TYPE_WATERFLOW_4,              // 33
    TYPE_TAP,                      // 34
    TYPE_OUTLET,                   // 35
    TYPE_GRINDER_1,                // 36
    TYPE_BELT,                     // 37
    TYPE_BELT_1,                   // 38
    TYPE_CONVERT_PIPE,             // 39
    TYPE_DOGE_FALLING2,            // 40
    TYPE_ROCK_PEBBLE,              // 41
    TYPE_ELECTRIC,                 // 42
    TYPE_INSULATOR,                // 43
    TYPE_STAR,                     // 44
    TYPE_STAR_FALLING,             // 45
    TYPE_STAR_EXPLODE,             // 46
    TYPE_ROCK_BONUS,               // 47
    TYPE_MOUNT,                    // 48
    TYPE_PIT_L,                    // 49
    TYPE_PIT_R,                    // 50
    TYPE_BOMB,                     // 51
    TYPE_CRACKED_BRICK,            // 52

    TYPE_MAX
};

extern const unsigned int Attribute[];
extern const enum ObjectType CharToType[];

enum ChName {

    // see charSet[] @ characterset.c
    // Objects numbered > 127 cannot be generated by cave data (top bit is flag bit in board)
    // see CharToType[] in attribute.c

    CH_BLANK,                     // 000
    CH_PLACEHOLDER,               // 001
    CH_DIRT,                      // 002
    CH_BRICKWALL,                 // 003
    CH_DOORCLOSED,                // 004
    CH_DOOROPEN_0,                // 005
    CH_EXITBLANK,                 // 006
    CH_STEELWALL,                 // 007
    CH_PEBBLE1,                   // 008
    CH_PEBBLE2,                   // 009
    CH_ROCK,                      // 010
    CH_ROCK_FALLING,              // 011          +2 offset assumed by code
    CH_DOGE_00,                   // 012
    CH_DOGE_FALLING,              // 013          +2 offset assumed by code
    CH_MELLON_HUSK_BIRTH,         // 014
    CH_LAVA_BLANK,                // 015
    CH_LAVA_SMALL,                // 016
    CH_LAVA_MEDIUM,               // 017
    CH_LAVA_LARGE,                // 018
    CH_MELLON_HUSK,               // 019
    CH_DOGE_STATIC,               // 020 (CAN SWITCH ANIMATIONS ON THIS!)
    CH_PEBBLE_ROCK,               // 021
    CH_ROCK_PEBBLE,               // 022
    CH_ROCK_PEBBLE_1,             // 023
    CH_DUST_0,                    // 024
    CH_DUST_1,                    // 025
    CH_DUST_2,                    // 026
    CH_GEODOGE,                   // 027
    CH_DUST_ROCK_0,               // 028
    CH_DUST_ROCK_1,               // 029
    CH_DUST_ROCK_2,               // 030
    CH_CONVERT_GEODE_TO_DOGE,     // 031
    CH_HORIZONTAL_BAR,            // 032
    CH_PUSH_LEFT,                 // 033       reverse must be +1
    CH_PUSH_LEFT_REVERSE,         // 034
    CH_PUSH_RIGHT,                // 035
    CH_PUSH_RIGHT_REVERSE,        // 036
    CH_VERTICAL_BAR,              // 037
    CH_PUSH_UP,                   // 038
    CH_PUSH_UP_REVERSE,           // 039
    CH_PUSH_DOWN,                 // 040
    CH_PUSH_DOWN_REVERSE,         // 041
    CH_WYRM_BODY,                 // 042
    CH_WYRM_VERT_BODY,            // 043
    CH_WYRM_CORNER_LD,            // 044
    CH_WYRM_CORNER_RD,            // 045
    CH_WYRM_CORNER_LU,            // 046
    CH_WYRM_CORNER_RU,            // 047
    CH_WYRM_HEAD_U,               // 048
    CH_WYRM_HEAD_R,               // 049
    CH_WYRM_HEAD_D,               // 050
    CH_WYRM_HEAD_L,               // 051
    CH_GEODOGE_FALLING,           // 052
    CH_FLIP_GRAVITY_0,            // 053
    CH_FLIP_GRAVITY_1,            // 054
    CH_FLIP_GRAVITY_2,            // 055
    CH_BLOCK,                     // 056
    CH_GRINDER_0,                 // 057
    CH_GRINDER_1,                 // 058
    CH_HUB,                       // 059
    CH_WATER,                     // 060
    CH_WATERFLOW_0,               // 061 must be grouped
    CH_WATERFLOW_1,               // 062 .
    CH_WATERFLOW_2,               // 063 .
    CH_WATERFLOW_3,               // 064 .
    CH_WATERFLOW_4,               // 065 /
    CH_HUB_1,                     // 066
    CH_OUTLET,                    // 067
    CH_BELT_0,                    // 068
    CH_BELT_1,                    // 069
    CH_PUSH_DOWN2,                // 070
    CH_GEODOGE_CONVERT,           // 071
    CH_CONVERT_PIPE,              // 072
    CH_WYRM_TAIL_U,               // 073
    CH_WYRM_TAIL_R,               // 074
    CH_WYRM_TAIL_D,               // 075
    CH_WYRM_TAIL_L,               // 076
    CH_DOGE_FALLING_TOP,          // 077
    CH_DOGE_FALLING_BOTTOM,       // 078
    CH_ROCK_FALLING_TOP,          // 079
    CH_ROCK_FALLING_BOTTOM,       // 080
    CH_GEODOGE_FALLING_TOP,       // 081
    CH_GEODOGE_FALLING_BOTTOM,    // 082
    CH_DOGE_FALLING_TOP2,         // 083
    CH_DOGE_FALLING_BOTTOM2,      // 084
    CH_DOGE_SIDE_1,               // 085
    CH_DOGE_SIDE_3,               // 086
    CH_DOGE_SIDE_2,               // 087
    CH_DOGE_SIDE_4,               // 088
    CH_ELECTRIC_0,                // 089
    CH_ELECTRIC_1,                // 090
    CH_ELECTRIC_2,                // 091
    CH_ELECTRIC_3,                // 092
    CH_BROKEN_DIRT,               // 093
    CH_INSULATOR_TOP,             // 094
    CH_INSULATOR_BOTTOM,          // 095
    CH_STAR,                      // 096
    CH_STAR_FALLING_TOP,          // 097
    CH_STAR_FALLING_BOTTOM,       // 098
    CH_ROCK_BONUS,                // 099
    CH_STAR_EXPLODE,              // 100
    CH_INSULATOR_L,               // 101
    CH_INSULATOR_R,               // 102
    CH_ELECTRIC_H0,               // 103
    CH_ELECTRIC_H1,               // 104
    CH_ELECTRIC_H2,               // 105
    CH_ELECTRIC_H3,               // 106
    CH_CROSSED_STREAMS,           // 107
    CH_MOUNT_U,                   // 108
    CH_MOUNT_D,                   // 109
    CH_MOUNT_L,                   // 110
    CH_MOUNT_R,                   // 111
    CH_PIT_L0,                    // 112
    CH_PIT_R0,                    // 113
    CH_BOMB,                      // 114
    CH_CRACKED_BRICK,             // 115

    // 127 is limit of board-resident character numbers

    // 128 onward are virtual characters from animations
    // these can't go on board but can be displayed via realtime animation

    CH_DOGE_01 = 128,      // 128
    CH_DOGE_02,            // 129
    CH_DOGE_03,            // 130
    CH_DOGE_04,            // 131
    CH_DOGE_05,            // 132
                           //
    CH_PIT_L1,             // 133
    CH_PIT_R1,             // 134
    CH_PIT_L2,             // 135
    CH_PIT_R2,             // 136
    CH_PIT_L3,             // 137
    CH_PIT_R3,             // 138
    CH_PIT_L4,             // 139
    CH_PIT_R4,             // 140
                           //
    CH_BOMB_FLASH,         // 141
                           //
    CH_CRACKED_BRICK_1,    // 142
    CH_CRACKED_BRICK_2,    // 143
    CH_CRACKED_BRICK_3,    // 144
    CH_CRACKED_BRICK_4,    // 145
    CH_CRACKED_BRICK_5,    // 146
    CH_CRACKED_BRICK_6,    // 147
    CH_CRACKED_BRICK_7,    // 148

    CH_MAX
};

// clang-format off

#define ENUM_BIT_VALUE(counter) (1 << counter)

#define DEFINE_ENUM_WITH_BIT_VALUES(enumType, ...) \
    typedef enum { \
        __VA_ARGS__ \
    } enumType

#define ATT(enumConstant) ATT_##enumConstant = ENUM_BIT_VALUE(__COUNTER__)

DEFINE_ENUM_WITH_BIT_VALUES(TypeAttributes,

    ATT(ROLL),                  // 00
    ATT(CONVERT),               // 01
    ATT(EXPLODABLE),            // 02
    ATT(PERMEABLE),             // 03
    ATT(BLANK),                 // 04
    ATT(DIRT),                  // 05
    ATT(GRAB),                  // 06
    ATT(PUSH),                  // 07
    ATT(SQUASHABLE_TO_BLANKS),  // 08
    ATT(HARD),                  // 09
    ATT(EXIT),                  // 10
    ATT(NOROCKNOISE),           // 11
    ATT(BLANKISH),              // 12
    ATT(MINE),                  // 13
    ATT(WATERFLOW),             // 14
    ATT(CONVEYOR),              // 15
    ATT(GRIND),                 // 16
    ATT(PIPE),                  // 17
    ATT(PHASE4),                // 18
    ATT(PHASE2),                // 19
    ATT(PHASE1),                // 20
    ATT(DISSOLVES),             // 21
    ATT(MELTS),                 // 22
    ATT(GEODOGE),               // 23 must match POS_GEODOGE
    ATT(PAD),                   // 24
    ATT(CRUSHES),               // 25
    ATT(CORNER),                // 26  must match POS_CORNER
    ATT(PICKUP),                // 27
);

#define POS_CORNER 26           /* must match ATT(CORNER) #*/
#define POS_GEODOGE 23          /* must match ATT(GEOFOGE) */

#define VALUE_BREAK_GEODE 25

// EOF
