#pragma once

#include "main.h"


enum ObjectType {

    // update Attribute[] in attribute.c
    // update AnimateBase[] in animations.c
    // update PickupCharacter[] in animations.c


    TYPE_BLANK,                    // 00      ASSUMED == 0 in code
    TYPE_DIRT,                     // 01
    TYPE_BRICKWALL,                // 02
    TYPE_OUTBOX_PRE,               // 03
    TYPE_OUTBOX,                   // 04
    TYPE_STEELWALL,                // 05
    TYPE_ROCK,                     // 06
    TYPE_DOGE,                     // 07
    TYPE_MELLON_HUSK_PRE,          // 08
    TYPE_MELLON_HUSK,              // 09
    TYPE_PEBBLE1,                  // 10
    TYPE_DUST_0,                   // 11
    TYPE_DOGE_FALLING,             // 12
    TYPE_ROCK_FALLING,             // 13
    TYPE_DUST_ROCK,                // 14
    TYPE_CONVERT_GEODE_TO_DOGE,    // 15
    TYPE_PUSHER,                   // 16
    TYPE_PUSHER_VERT,              // 17
    TYPE_WYRM,                     // 18
    TYPE_GEODOGE,                  // 19
    TYPE_GEODOGE_FALLING,          // 20
    TYPE_LAVA,                     // 21
    TYPE_PEBBLE_ROCK,              // 22
    TYPE_FLIP_GRAVITY,             // 23
    TYPE_BLOCK,                    // 24
    TYPE_GRINDER,                  // 25
    TYPE_HUB,                      // 26
    TYPE_WATER,                    // 27
    TYPE_WATERFLOW_0,              // 28
    TYPE_WATERFLOW_1,              // 29
    TYPE_WATERFLOW_2,              // 30
    TYPE_WATERFLOW_3,              // 31
    TYPE_WATERFLOW_4,              // 32
    TYPE_TAP,                      // 33
    TYPE_OUTLET,                   // 34
    TYPE_GRINDER_1,                // 35
    TYPE_BELT,                     // 36
    TYPE_BELT_1,                   // 37
    TYPE_CONVERT_PIPE,             // 38
    TYPE_DOGE_FALLING2,            // 39
    TYPE_ROCK_PEBBLE,              // 40
    TYPE_ELECTRIC,                 // 41
    TYPE_INSULATOR,                // 42
    TYPE_STAR,                     // 43
    TYPE_STAR_FALLING,             // 44
    TYPE_STAR_EXPLODE,             // 45
    TYPE_ROCK_BONUS,               // 46

    TYPE_MAX
};

extern const unsigned int Attribute[];
extern const enum ObjectType CharToType[];

enum ChName {

    // see charSet[] @ characterset.c
    // Objects numbered > 127 cannot be generated by cave data (top bit is flag bit in board)
    // see CharToType[] in attribute.c

    CH_BLANK,                     // 000
    CH_DIRT,                      // 001
    CH_BRICKWALL,                 // 002
    CH_DOORCLOSED,                // 003
    CH_DOOROPEN_0,                // 004
    CH_EXITBLANK,                 // 005
    CH_STEELWALL,                 // 006
    CH_PEBBLE1,                   // 007
    CH_PEBBLE2,                   // 008
    CH_ROCK,                      // 009
    CH_ROCK_FALLING,              // 010          +2 offset assumed by code
    CH_DOGE_00,                   // 011
    CH_DOGE_FALLING,              // 012          +2 offset assumed by code
    CH_MELLON_HUSK_BIRTH,         // 013
    CH_LAVA_BLANK,                // 014
    CH_LAVA_SMALL,                // 015
    CH_LAVA_MEDIUM,               // 016
    CH_LAVA_LARGE,                // 017
    CH_MELLON_HUSK,               // 018
    CH_DOGE_01,                   // 019
    CH_DOGE_02,                   // 020
    CH_DOGE_03,                   // 021
    CH_DOGE_04,                   // 022
    CH_DOGE_05,                   // 023
    CH_DOGE_STATIC,               // 024 (CAN SWITCH ANIMATIONS ON THIS!)
    CH_PEBBLE_ROCK,               // 025
    CH_ROCK_PEBBLE,               // 026
    CH_ROCK_PEBBLE_1,             // 027
    CH_DUST_0,                    // 028
    CH_DUST_1,                    // 029
    CH_DUST_2,                    // 030
    CH_GEODOGE,                   // 031
    CH_CONGLOMERATE_1,            // 032
    CH_CONGLOMERATE_2,            // 033
    CH_CONGLOMERATE_3,            // 034
    CH_CONGLOMERATE_4,            // 035
    CH_CONGLOMERATE_5,            // 036
    CH_CONGLOMERATE_6,            // 037
    CH_CONGLOMERATE_7,            // 038
    CH_CONGLOMERATE_8,            // 039
    CH_CONGLOMERATE_9,            // 040
    CH_CONGLOMERATE_10,           // 041
    CH_CONGLOMERATE_11,           // 042
    CH_CONGLOMERATE_12,           // 043
    CH_CONGLOMERATE_13,           // 044
    CH_CONGLOMERATE_14,           // 045
    CH_CONGLOMERATE_15,           // 046
    CH_DUST_ROCK_0,               // 047
    CH_DUST_ROCK_1,               // 048
    CH_DUST_ROCK_2,               // 049
    CH_CONVERT_GEODE_TO_DOGE,     // 050
    CH_HORIZONTAL_BAR,            // 051
    CH_PUSH_LEFT,                 // 052       reverse must be +1
    CH_PUSH_LEFT_REVERSE,         // 053
    CH_PUSH_RIGHT,                // 054
    CH_PUSH_RIGHT_REVERSE,        // 055
    CH_VERTICAL_BAR,              // 056
    CH_PUSH_UP,                   // 057
    CH_PUSH_UP_REVERSE,           // 058
    CH_PUSH_DOWN,                 // 059
    CH_PUSH_DOWN_REVERSE,         // 060
    CH_WYRM_BODY,                 // 061
    CH_WYRM_VERT_BODY,            // 062
    CH_WYRM_CORNER_LD,            // 063
    CH_WYRM_CORNER_RD,            // 064
    CH_WYRM_CORNER_LU,            // 065
    CH_WYRM_CORNER_RU,            // 066
    CH_WYRM_HEAD_U,               // 067
    CH_WYRM_HEAD_R,               // 068
    CH_WYRM_HEAD_D,               // 069
    CH_WYRM_HEAD_L,               // 070
    CH_GEODOGE_FALLING,           // 071
    CH_FLIP_GRAVITY_0,            // 072
    CH_FLIP_GRAVITY_1,            // 073
    CH_FLIP_GRAVITY_2,            // 074
    CH_BLOCK,                     // 075
    CH_GRINDER_0,                 // 076
    CH_GRINDER_1,                 // 077
    CH_HUB,                       // 078
    CH_WATER,                     // 079
    CH_WATERFLOW_0,               // 080 must be grouped
    CH_WATERFLOW_1,               // 081 .
    CH_WATERFLOW_2,               // 082 .
    CH_WATERFLOW_3,               // 083 .
    CH_WATERFLOW_4,               // 084 /
    CH_TAP_0,                     // 085
    CH_HUB_1,                     // 086
    CH_OUTLET,                    // 087
    CH_TAP_1,                     // 088
    CH_BELT_0,                    // 089
    CH_BELT_1,                    // 090
    CH_PUSH_DOWN2,                // 091
    CH_GEODOGE_CONVERT,           // 092
    CH_CONVERT_PIPE,              // 093
    CH_WYRM_TAIL_U,               // 094
    CH_WYRM_TAIL_R,               // 095
    CH_WYRM_TAIL_D,               // 096
    CH_WYRM_TAIL_L,               // 097
    CH_DOGE_FALLING_TOP,          // 098
    CH_DOGE_FALLING_BOTTOM,       // 099
    CH_ROCK_FALLING_TOP,          // 100
    CH_ROCK_FALLING_BOTTOM,       // 101
    CH_GEODOGE_FALLING_TOP,       // 102
    CH_GEODOGE_FALLING_BOTTOM,    // 103
    CH_DOGE_FALLING_TOP2,         // 104
    CH_DOGE_FALLING_BOTTOM2,      // 105
    CH_DOGE_SIDE_1,               // 106
    CH_DOGE_SIDE_3,               // 107
    CH_DOGE_SIDE_2,               // 108
    CH_DOGE_SIDE_4,               // 109
    CH_ELECTRIC_0,                // 110
    CH_ELECTRIC_1,                // 111
    CH_ELECTRIC_2,                // 112
    CH_ELECTRIC_3,                // 113
    CH_BROKEN_DIRT,               // 114
    CH_INSULATOR_TOP,             // 115
    CH_INSULATOR_BOTTOM,          // 116
    CH_STAR,                      // 117
    CH_STAR_FALLING_TOP,          // 118
    CH_STAR_FALLING_BOTTOM,       // 119
    CH_ROCK_BONUS,                // 120
    CH_STAR_EXPLODE,              // 121

    // 127 is limit

    CH_MAX
};

// clang-format off

#define ENUM_BIT_VALUE(counter) (1 << counter)

#define DEFINE_ENUM_WITH_BIT_VALUES(enumType, ...) \
    typedef enum { \
        __VA_ARGS__ \
    } enumType

#define ATT(enumConstant) ATT_##enumConstant = ENUM_BIT_VALUE(__COUNTER__)

DEFINE_ENUM_WITH_BIT_VALUES(TypeAttributes,

    ATT(ROLL),                  // 00
    ATT(CONVERT),               // 01
    ATT(EXPLODABLE),            // 02
    ATT(PERMEABLE),             // 03
    ATT(BLANK),                 // 04
    ATT(DIRT),                  // 05
    ATT(GRAB),                  // 06
    ATT(PUSH),                  // 07
    ATT(SQUASHABLE_TO_BLANKS),  // 08
    ATT(HARD),                  // 09
    ATT(EXIT),                  // 10
    ATT(NOROCKNOISE),           // 11
    ATT(BLANKISH),              // 12
    ATT(MINE),                  // 13
    ATT(WATERFLOW),             // 14
    ATT(CONVEYOR),              // 15
    ATT(GRIND),                 // 16
    ATT(PIPE),                  // 17
    ATT(PHASE4),                // 18
    ATT(PHASE2),                // 19
    ATT(PHASE1),                // 20
    ATT(DISSOLVES),             // 21
    ATT(MELTS),                 // 22
    ATT(GEODOGE),               // 23
    ATT(PAD),                   // 24
    ATT(CRUSHES),               // 25
    ATT(CORNER),                // 26
    ATT(PICKUP),                // 27
);

#define POS_CORNER 26
#define VALUE_BREAK_GEODE 25

// EOF
