
#include "defines_dasm.h"

#include "cdfjplus.h"

#include "colour.h"
#include "drawplanet.h"
#include "main.h"
#include "planet.h"
#include "reverseBits.h"
#include "scroll.h"


extern void initStars();


const unsigned short pix85[] = {
    0b0000000000000000,    // 0
    0b0010001000010000,    // 3
    0b0101001001000100,    // 6
    0b0101010100100010,    // 9
    0b0101010100100010,    // 12
    0b1010101010100010,    // 15
    0b1011010101010010,    // 18
    0b1011010101010010,    // 21
    0b1011101101010010,    // 24
    0b1011101101010010,    // 27
    0b1011101101010010,    // 30
    0b1101110110101001,    // 33
    0b1101110110101001,    // 36
    0b1101110110101001,    // 39
    0b1111011101101001,    // 42
    0b1111011101101001,    // 45
    0b1111011101101001,    // 48
    0b1111011101101001,    // 51
    0b1111011101101001,    // 54
    0b1111111011011001,    // 57
    0b1111111011011001,    // 60
    0b1111111011011001,    // 63
    0b1111111011011001,    // 66
    0b1111111011011001,    // 69
    0b1111111011011001,    // 72
    0b1111111011011001,    // 75
    0b1111111011011001,    // 78
    0b1111111011011001,    // 81
    0b1111111011011001,    // 84
    0b1111111011011001,    // 87
    0b1111111011011001,    // 90
    0b1111111011011001,    // 93
    0b1111111011011001,    // 96
    0b1111111011011001,    // 99
    0b1111111011011001,    // 102
    0b1111111011011001,    // 105
    0b1111111011011001,    // 108
    0b1111111011011001,    // 111
    0b1111111011011001,    // 114
    0b1111011101101001,    // 117
    0b1111011101101001,    // 120
    0b1111011101101001,    // 123
    0b1111011101101001,    // 126
    0b1111011101101001,    // 129
    0b1101110110101001,    // 132
    0b1101110110101001,    // 135
    0b1101110110101001,    // 138
    0b1011101101010010,    // 141
    0b1011101101010010,    // 144
    0b1011010101010010,    // 147
    0b1011010101010010,    // 150
    0b1010101010100010,    // 153
    0b1010101010100010,    // 156
    0b0101010100100010,    // 159
    0b0101001001000100,    // 162
    0b0100100010001000,    // 165
    0b0010001000010000,    // 168
};


// Table maps line index to line number in texture
// Generated by spinningGlobe/scale.py
// texture height = chars * trix/char * 3 - fudge (which makes the bottom align)
// sub-position is always 3 (CC)


// Number of table entries (57 for original): 57
// Texture height in pixels:                  120
// Character cell height in scanlines:        30
// Sub-position step [3]:
// Array name [line85]:
// Mapping - (s)pherical or (l)inear [s]:

const short int line85[] = {
    0,      // 0
    9,      // 1
    15,     // 2
    18,     // 3
    21,     // 4
    24,     // 5
    24,     // 6
    27,     // 7
    27,     // 8
    32,     // 9
    35,     // 10
    38,     // 11
    38,     // 12
    41,     // 13
    41,     // 14
    44,     // 15
    44,     // 16
    47,     // 17
    47,     // 18
    50,     // 19
    50,     // 20
    53,     // 21
    53,     // 22
    56,     // 23
    56,     // 24
    56,     // 25
    59,     // 26
    59,     // 27
    64,     // 28
    64,     // 29
    67,     // 30
    67,     // 31
    70,     // 32
    70,     // 33
    73,     // 34
    73,     // 35
    76,     // 36
    76,     // 37
    76,     // 38
    79,     // 39
    79,     // 40
    82,     // 41
    85,     // 42
    85,     // 43
    88,     // 44
    88,     // 45
    91,     // 46
    91,     // 47
    96,     // 48
    99,     // 49
    99,     // 50
    102,    // 51
    105,    // 52
    108,    // 53
    111,    // 54
    114,    // 55
    127,    // 56
    -1,  -1, -1, -1, -1, -1, -1,
};

#define PSS 0

int rotationDelta = PSS;    // 0x8800;    // C80;    // 0xA00;


int scalex;
int planetDir;
int body;


#define SCALE_FAR 0x20000
#define SCALE_NEAR 0x0F000
#define MIDPOINT ((SCALE_FAR + SCALE_NEAR) / 2)    // ~131180
#define DIVISOR 12000

#define MINSCALE SCALE_NEAR
#define MAXSCALE SCALE_FAR


void initPlanet(int planet) {

    scalex = MAXSCALE;
    planetDir = 0;
    rotationDelta = PSS;

    body = planet;

    initStars();

    extern const unsigned char *thePalette;
    thePalette = planets[body].palette;
}


int nextPlanet() {

    if (++body >= (int)(sizeof(planets) / sizeof(planets[0])))
        body = 0;

    initPlanet(body);
    return body;
}


void drawPlanet(int half) {

    const unsigned char *map = planets[body].map;
    const unsigned char *const *charset = planets[body].charSet;

    // oscillate
    planetDir += ((MIDPOINT - scalex) * (0x10000 / DIVISOR)) >> 16;
    scalex += planetDir;

    if (rotationDelta < 0x1100)
        rotationDelta += 30;

#define TEXTURE_WRAP (20 << 16)

    scrollX += planets[body].retrograde * rotationDelta;
    if (scrollX >= TEXTURE_WRAP)
        scrollX -= TEXTURE_WRAP;
    if (scrollX < 0)
        scrollX += TEXTURE_WRAP;

    int shift = 4 - ((scrollX >> 14) & 3);
    int frac = scrollX >> 16;
    const unsigned char *xchar;
    const unsigned char *image[6];

    int trixLine = 12;    // start globe y @

    unsigned char *pf0 = trixLine * 3 + RAM + _BUF_GLOBE_PF + (half ? 0 : (3 * _BUFFER_SIZE));
    unsigned char *pf1 = pf0 + _BUFFER_SIZE;
    unsigned char *pf2 = pf1 + _BUFFER_SIZE;

    int equivalentLine = 0;
    int equiv = 0;

#undef BLK
#undef BLK2
#undef PUT
#undef PUT2
#undef GRAB

#define GRAB(i) image[i] = charset[*xchar++] + (line85[equiv] & 31);

#define BLK(i)                                                                                                         \
    if (mask & (1 << i))                                                                                               \
        p2 = (p2 << 1) | ((p >> (15 - i)) & 1);

#define PUT(i)                                                                                                         \
    if (p2 & (1 << (bitOffset >> 16)))                                                                                 \
        p3 |= 1 << i;                                                                                                  \
    bitOffset += scalex;


#define BLK2(i)                                                                                                        \
    if (mask & (1 << i))                                                                                               \
        p2 = (p2 >> 1) | (((p >> i) & 1) << 15);

#define PUT2(i)                                                                                                        \
    if (p2 & (1 << (15 - (bitOffset >> 16))))                                                                          \
        p3 |= 1 << i;                                                                                                  \
    bitOffset += scalex;

    /*
     * half is constant for the entire call.  Testing it inside the inner loop
     * wastes 3 branches per outer iteration with no possibility of a different
     * result.  Split the loop here so the hot path is branch-free.
     */

    const unsigned char *basex = map + half + frac + 2;


    if (!half) {

        for (; trixLine < (_SCANLINES / 3) - 1 && line85[equiv] >= 0;) {

            xchar = basex + map[0] * (line85[equiv] >> 5);

            GRAB(0)
            GRAB(1)
            GRAB(2)
            GRAB(3)
            GRAB(4)
            GRAB(5)

            int mask = pix85[equiv];
            int roll = roller;

            for (int icc = 0; icc < 3; icc++) {

                int p = (*(image[0] + roll) << 20 | *(image[1] + roll) << 16 | *(image[2] + roll) << 12 |
                         *(image[3] + roll) << 8 | *(image[4] + roll) << 4 | *(image[5] + roll)) >>
                        shift;

                int p2 = 0;
                int p3 = 0;

                BLK(0)
                BLK(1)
                BLK(2)
                BLK(3)
                BLK(4)
                BLK(5)
                BLK(6)
                BLK(7)
                BLK(8)
                BLK(9)
                BLK(10)
                BLK(11)
                BLK(12)
                BLK(13)
                BLK(14)
                BLK(15)
                // BLK(16)
                // BLK(17)
                // BLK(18)
                // BLK(19)

                // screen is 32px wide: output is 2 bytes (bits 0-15 of p3 only)

                int bitOffset = 0x8000;

                PUT(0)
                PUT(1)
                PUT(2)
                PUT(3)
                PUT(4)
                PUT(5)
                PUT(6)
                PUT(7)
                PUT(8)
                PUT(9)
                PUT(10)
                PUT(11)
                PUT(12)
                PUT(13)
                PUT(14)
                PUT(15)

                *pf1++ = p3 >> 8;
                *pf2++ = reverseBits[(unsigned char)p3];

                if (++roll > 2)
                    roll = 0;
            }

            trixLine++;

            equivalentLine += scalex;
            equiv = equivalentLine >> 16;
        }

    } else {

        for (; trixLine < (_SCANLINES / 3) - 1 && line85[equiv] >= 0;) {

            xchar = basex + map[0] * (line85[equiv] >> 5);

            GRAB(0)
            GRAB(1)
            GRAB(2)
            GRAB(3)
            GRAB(4)
            GRAB(5)

            int mask = pix85[equiv];
            int roll = roller;

            for (int icc = 0; icc < 3; icc++) {

                int p = (*(image[0] + roll) << 20 | *(image[1] + roll) << 16 | *(image[2] + roll) << 12 |
                         *(image[3] + roll) << 8 | *(image[4] + roll) << 4 | *(image[5] + roll)) >>
                        (shift + 4);

                int p2 = 0;
                int p3 = 0;

                int bitOffset = 0x8000;

                BLK2(0)
                BLK2(1)
                BLK2(2)
                BLK2(3)
                BLK2(4)
                BLK2(5)
                BLK2(6)
                BLK2(7)
                BLK2(8)
                BLK2(9)
                BLK2(10)
                BLK2(11)
                BLK2(12)
                BLK2(13)
                BLK2(14)
                BLK2(15)
                // BLK2(16)
                // BLK2(17)
                // BLK2(18)
                // BLK2(19)

                // screen is 32px wide: bits 4-19 of p3 used (after <<4: bytes at >>16 and >>8)
                // PUT2(19)
                // PUT2(18)
                // PUT2(17)
                // PUT2(16)
                PUT2(15)
                PUT2(14)
                PUT2(13)
                PUT2(12)
                PUT2(11)
                PUT2(10)
                PUT2(9)
                PUT2(8)
                PUT2(7)
                PUT2(6)
                PUT2(5)
                PUT2(4)
                PUT2(3)
                PUT2(2)
                PUT2(1)
                PUT2(0)

                p3 <<= 8;
                *pf2++ = p3 >> 16;
                *pf1++ = reverseBits[(unsigned char)(p3 >> 8)];

                if (++roll > 2)
                    roll = 0;
            }

            trixLine++;

            equivalentLine += scalex;
            equiv = equivalentLine >> 16;
        }
    }

    while (trixLine++ < _SCANLINES / 3)
        for (int i = 0; i < 3; i++)
            *pf1++ = *pf2++ = 0;

#undef BLK
#undef BLK2
#undef PUT
#undef PUT2
#undef GRAB
#undef TEX
}
// EOF
