#include "defines_dasm.h"

#include "cdfjplus.h"

#include "caveData.h"
#include "colour.h"
#include "draw.h"
#include "drawGridPreview.h"
#include "gameState.h"
#include "joystick.h"
#include "life.h"
#include "main.h"
#include "sound.h"

static int base2;
static int flashTime2;

__attribute__((nonstring)) const char showCaveName[][6] = {
    {";;MARS"},    //
    {"URANUS"},    //
    {"SATURN"},    //
    {"FOUR  "},    //
    {"FIVE  "},    //
    {"SIX   "},    //
    {"SEVEN "},    //
    {"EIGHT "},    //
    {"NINE  "},    //
    {"X     "},    //
};


void initDataStreams_Menu() {

    static const struct dataStreams streams[] = {

        {_DS_MENU_COLUBK, _BUF_MENU_COLUBK},

        {_DS_MENU_PF1_LEFT, _BUF_MENU_PF},
        {_DS_MENU_PF1_RIGHT, _BUF_MENU_PF + 3 * _BUFFER_SIZE},
        {_DS_MENU_PF2_LEFT, _BUF_MENU_PF + 1 * _BUFFER_SIZE},
        {_DS_MENU_PF2_RIGHT, _BUF_MENU_PF + 2 * _BUFFER_SIZE},

        {_DS_MENU_AUDV0, _BUF_AUDV},
        {_DS_MENU_AUDC0, _BUF_AUDC},
        {_DS_MENU_AUDF0, _BUF_AUDF},
        {_DS_MENU_COLUPF, _BUF_MENU_COLUPF},
        {_DS_MENU_COLUP0, _BUF_MENU_COLUP0},

        {_DS_MENU_GRP0A, _BUF_MENU_GRP + 0 * _BUFFER_SIZE},
        {_DS_MENU_GRP1A, _BUF_MENU_GRP + 1 * _BUFFER_SIZE},
        {_DS_MENU_GRP0B, _BUF_MENU_GRP + 2 * _BUFFER_SIZE},
        {_DS_MENU_GRP1B, _BUF_MENU_GRP + 3 * _BUFFER_SIZE},
        {_DS_MENU_GRP0C, _BUF_MENU_GRP + 4 * _BUFFER_SIZE},
        {_DS_MENU_GRP1C, _BUF_MENU_GRP + 5 * _BUFFER_SIZE},

        {DSJMP1PTR, _BUF_MENU_JUMP},

    };

    initDataStreams(streams, sizeof(streams) / sizeof(struct dataStreams));
}


void initKernel_Menu() {

    setJumpVectors(_BUF_MENU_JUMP, _menuLoop, _menuExit, _SCANLINES);
    initDataStreams_Menu();


    killRepeatingAudio();

    flashTime2 = 0;

    static int showCave = -1;
    if (++showCave >= caveCount)
        showCave = 0;

    cave = showCave;
    level = 4;    // tmp;

    colubk = 0;

    sound_max_volume = VOLUME_MAX;

    myMemsetInt((unsigned int *)(RAM + _MENU_BUFFERS_START), 0, _MENU_BUFFERS_SIZE / 4);

    base2 = 0;

    initGridPreview(_SCANLINES + 50, PREVIEW_Y);

    // drawString(FONT_COMPACT, 0x1A, 6, _BUF_MENU_GRP, _BUF_MENU_COLUP0, "=[Conway]|101", PREVIEW_Y + 40);
}

void drawPF(int buffer, const unsigned char image[66][4][3]) {

    // image data generated by pcc.py

    unsigned char *pf = RAM + buffer;

    int roll = roller;
    for (int col = 0; col < 4; col++) {
        for (int i = 0; i < 66; i++) {
            for (int icc = 0; icc < 3; icc++) {
                pf[col * _BUFFER_SIZE + i * 3 + icc] = image[i][col][roll];
                if (++roll > 2)
                    roll = 0;
            }
        }
    }
}


void initGameState_Menu() {

    luminance = -15;
    lumTarget = 0;
    frame = 0;
}


void VB_Menu() {

    initDataStreams_Menu();


    // if (!drawNextChar()) {

    drawGridPreview();
    // }

    getJoystick();

    if (!(inpt4 & 0x80))
        setGameState(GS_GLOBE);    // GS_GLOBE);
}


__attribute__((nonstring)) const char Level[][6] = {

    {""},          //
    {"ARCTIC"},    //
    {"LAVA;;"},    //
    {"MOUNTS"},    //
    {"COASTS"},    //
    {"TROPIC"},    //
    {"JUNGLE"},    //
    {"PLAINS"},    //
    {"OCEAN;"},    //
    {"POLE;;"},    //
};


#include "../icc/icc.c"


void OS_Menu() {


    life(3);

    base2++;

    if (flashTime2)
        --flashTime2;

    interleaveChronoColour(&roller);
    adjustLuminance(1);

    setPFColours((unsigned char *)(RAM + _BUF_MENU_COLUPF));

    drawPF(_BUF_MENU_PF, gfx_image_WenHop_png);
}


// EOF
