#include "defines_dasm.h"

#include "cdfjplus.h"

#include "caveData.h"
#include "colour.h"
#include "draw.h"
#include "grid6.h"
#include "main.h"
#include "menuCharacterSet.h"
#include "random.h"
#include "savekey.h"
#include "sound.h"

int menuLine;
int pushCount;
int base2;
int flashTime2;
// int cave;
// int level;
int menuLineTVType;
int tempName;

#define LETTER_HEIGHT 10

enum MENU_OPTION {

    MENU_OPTION_CAVE,
    MENU_OPTION_LEVEL,
};


__attribute__((nonstring)) const char showCaveName[][6] = {
    {";;MARS"},    //
    {"URANUS"},    //
    {"SATURN"},    //
    {"FOUR  "},    //
    {"FIVE  "},    //
    {"SIX   "},    //
    {"SEVEN "},    //
    {"EIGHT "},    //
    {"NINE  "},    //
    {"X     "},    //
};


void initDataStreams_Menu() {

    static const struct dataStreams streams[] = {

        {_DS_MENU_COLUBK, _BUF_MENU_COLUBK},

        {_DS_MENU_PF1_LEFT, _BUF_MENU_PF},
        {_DS_MENU_PF1_RIGHT, _BUF_MENU_PF + 3 * _BUFFER_SIZE},
        {_DS_MENU_PF2_LEFT, _BUF_MENU_PF + 1 * _BUFFER_SIZE},
        {_DS_MENU_PF2_RIGHT, _BUF_MENU_PF + 2 * _BUFFER_SIZE},

        {_DS_MENU_AUDV0, _BUF_AUDV},
        {_DS_MENU_AUDC0, _BUF_AUDC},
        {_DS_MENU_AUDF0, _BUF_AUDF},
        {_DS_MENU_COLUPF, _BUF_MENU_COLUPF},
        {_DS_MENU_COLUP0, _BUF_MENU_COLUP0},

        {_DS_MENU_GRP0A, _BUF_MENU_GRP + 0 * _BUFFER_SIZE},
        {_DS_MENU_GRP1A, _BUF_MENU_GRP + 1 * _BUFFER_SIZE},
        {_DS_MENU_GRP0B, _BUF_MENU_GRP + 2 * _BUFFER_SIZE},
        {_DS_MENU_GRP1B, _BUF_MENU_GRP + 3 * _BUFFER_SIZE},
        {_DS_MENU_GRP0C, _BUF_MENU_GRP + 4 * _BUFFER_SIZE},
        {_DS_MENU_GRP1C, _BUF_MENU_GRP + 5 * _BUFFER_SIZE},

        {DSJMP1PTR, _BUF_MENU_JUMP},

    };

    initDataStreams(streams, sizeof(streams) / sizeof(struct dataStreams));
}


void initKernel_Menu() {

    setJumpVectors(_BUF_MENU_JUMP, _menuLoop, _menuExit, _SCANLINES);
    initDataStreams_Menu();


    killRepeatingAudio();

    flashTime2 = 0;

    static int showCave = -1;
    if (++showCave >= caveCount)
        showCave = 0;

    cave = showCave;
    level = 4;    // tmp;
    menuLineTVType = 0;

    colubk = 0;

    tempName = rangeRandom(sizeof(showCaveName) / sizeof(showCaveName[0]));

    // ARENA_COLOUR = 0;

    // if (rageQuit) {
    //     rageQuit = false;
    //     SAY(__WORD_RAGEQUIT);
    //     FLASH(0x48, 8);
    // }


    //    bufferedSWCHA = 0xFF;
    //    waitRelease = true;
    sound_max_volume = VOLUME_MAX;

    myMemsetInt((unsigned int *)(RAM + _MENU_BUFFERS_START), 0, _MENU_BUFFERS_SIZE / 4);


    drawString(FONT_COMPACT, 0xC6, 0, _BUF_MENU_GRP, _BUF_MENU_COLUP0, "=()2026", 172);
    while (drawNextChar())
        ;
    drawString(FONT_COMPACT, 0xC6, 0, _BUF_MENU_GRP, _BUF_MENU_COLUP0, "=Andrew Davie", 184);
    while (drawNextChar())
        ;


    // draw6Bitmap(_BUF_MENU_GRP, _BUF_MENU_COLUP0,    //
    //             gfx_grid_menu_planet_gif, gfx_grid_menu_planet_gif_HEIGHT, 94 + 30, 6);

    // draw6Bitmap(_BUF_MENU_GRP, _BUF_MENU_COLUP0,    //
    //             gfx_grid_menu_bravado_gif, gfx_grid_menu_bravado_gif_HEIGHT, 120 + 30, 6);

    menuLine = 0;
    base2 = 0;
    pushCount = 0;

    //    chooseColourScheme();

    //    mustWatchDelay = MUSTWATCH_MENU;
}

void drawPF(int buffer, const unsigned char image[66][4][3]) {

    // image data generated by pcc.py

    unsigned char *pf = RAM + buffer;

    int roll = roller;
    for (int col = 0; col < 4; col++) {
        for (int i = 0; i < 66; i++) {
            for (int icc = 0; icc < 3; icc++) {
                pf[col * _BUFFER_SIZE + i * 3 + icc] = image[i][col][roll];
                if (++roll > 2)
                    roll = 0;
            }
        }
    }
}


void initGameState_Menu() {

    luminance = -15;
    lumTarget = 0;
    frame = 0;
}


void drawCharacter(int x, int y, int ch) {

    if (ch == ' ')
        ch = '0' + 11;

    ch -= 'A';
    if (ch < 0)
        ch += 43;
    const unsigned char *p = charAtoZ + ch * 10;
    unsigned char *col = RAM + _BUF_MENU_GRP + _BUFFER_SIZE * x + y;

    for (int i = 0; i < LETTER_HEIGHT; i++)
        *col++ = *p++;
}

// void xxxdrawString(int x, int y, const char *text, int colour) {

//     while (*text && x < 6)
//         drawCharacter(x++, y, *text++);

//     for (int i = 0; i < LETTER_HEIGHT; i++)
//         RAM[_BUF_MENU_COLUP0 + i + y - 1] = convertColour(colour);
// }

void drawSmallString(int y, const char *smallText) {

    int colour = convertColour(0x98);

    for (int line = 0; line < 6; line++) {
        RAM[_BUF_MENU_COLUP0 + y + line - 1] = colour;
        for (int i = 0; i < 6; i++)
            RAM[_BUF_MENU_GRP + _BUFFER_SIZE * i + y + line] = *smallText++;
    }
}


void VB_Menu() {

    initDataStreams_Menu();

    if (!drawNextChar()) {
    }

    if (frame > 20)
        lumTarget = -15;
    if (frame > 50)
        setGameState(GS_GAME);    // GS_GLOBE);
}


// const char wordTvType0[] = {
//     ________, XXXXXX__, _X___XXX, X___X_XX, XXXXXXXX, XX_X___X, ________, XXXX_XX_, XX__XX__,
//     XX_XXXX_, _XXXX_XX, XX_XX_XX, ________, __X___X_, X____XXX, _XXX__XX, X__X__X_, ___XXXXX,
//     ________, __X___XX, X______X, X_X_____, XX_X__XX, X__X_X_X, ________, __X____X, ____XXXX,
//     X_X__XXX, XX_X__X_, ___X___X, ________, __X____X, ____XXXX, __X__XXX, X__X__XX, XX_X___X,
// };

// const char wordStartAt[] = {
//     ________, ________, ___XXX__, X____XX_, _X__X_XX, XX_XXXXX, ________, ________, ___X__X_,
//     X___XXXX, _XX_X_X_, ___XXXXX, ________, ________, ___X__X_, X___X__X, _XX_X_XX, X____X__,
//     ________, ________, ___XXX__, X___XXXX, _X_XX_X_, _____X__, ________, ________, ___X____,
//     X___X__X, _X_XX_XX, XX___X__, ________, ________, ___X____, XXX_X__X, _X__X_XX, XX___X__,
// };

// const char wordDifficulty[] = {

//     ________, _____XXX, ___XXX__, _XX__X__, X__XX__X, X____XX_, ________, _____X__, XX_XX_X_,
//     XXXX_X__, X_XXXX_X, _X__X__X, ________, _____XXX, ___X__X_, X__X_X__, X_X__X_X, __X_X__X,
//     ________, _____X__, XX_XXX__, XXXX_X__, X_XXXX_X, __X_X__X, ________, _____XXX, XX_X_X__,
//     X__X_XXX, __X__X_X, XXX_XXXX, ________, _____XXX, X__X__X_, X__X__X_, __X__X_X, XX___XX_,
// };


// const char *smallWord[] = {
//     wordStartAt,
//     wordDifficulty,
//     //    wordTvType0,
// };


// const char TV[][6] = {

//     {";;NTSC"},    //
//     {";;;PAL"},    //
//     {";PAL60"},    //
//     {";SECAM"},    //
// };

__attribute__((nonstring)) const char Level[][6] = {

    {""},          //
    {"ARCTIC"},    //
    {"LAVA;;"},    //
    {"MOUNTS"},    //
    {"COASTS"},    //
    {"TROPIC"},    //
    {"JUNGLE"},    //
    {"PLAINS"},    //
    {"OCEAN;"},    //
    {"POLE;;"},    //
};


#include "../icc/icc.c"


void OS_Menu() {


    //    myMemset((unsigned char *)(RAM + _BUF_MENU_PF), 0, _SCANLINES);

    base2++;

    static enum MENU_OPTION sline = 0;
    sline++;
    if (sline >= 2)    //(int)(sizeof(smallWord) / sizeof(smallWord[0])))
        sline = 0;

    if (flashTime2)
        --flashTime2;

    // const char *dLine = 0;

    switch (sline) {

    case MENU_OPTION_CAVE:
        //        dLine = showCave[cave];

        // dLine = showCaveName[tempName];

        break;

    case MENU_OPTION_LEVEL:
        //        dLine = Level[level];
        break;

        // case MENU_OPTION_TVSYSTEM:
        //     dLine = TV[menuLineTVType];
        //     break;
    }

    //    drawSmallString(y, smallWord[sline]);

    // int colour = sline == menuLine ? (flashTime2 & 4) ? 0x0A : ((base2 << 2) & 0xF0) | 0x16 : 0x26;

    // drawString(0, y + 8 + 30, dLine, colour);


    //--------------------------------------------------------------------------
    // Draw ICC menu PF background

    interleaveChronoColour(&roller);
    adjustLuminance(3);

    setPFColours((unsigned char *)(RAM + _BUF_MENU_COLUPF));

    drawPF(_BUF_MENU_PF, gfx_image_WenHop_png);

    //--------------------------------------------------------------------------

    // draw6Bitmap(_BUF_MENU_GRP, _BUF_MENU_COLUP0,    //
    //             gfx_grid_menu_planetx_gif, gfx_grid_menu_planetx_gif_HEIGHT, 62, 0x96);


    // static const char *registered = ":";
    // static int landing2 = (-5) * 256;
    // int landing = landing2 >> 8;

    // static int accel = 190;
    // if (accel)
    //     accel -= 1;

    // int landing3 = landing + 8;

    // if (!rangeRandom(2) && accel)
    //     drawString(5, landing + 8, "<", 0x4C);    //(R)
    // else
    //     drawString(5, landing3, ";", 0x4C);    //(R)

    // drawString(5, landing, registered, 0x06);    //(R)

    // // drawString(5, landing + 11, ";", 0x9C);   //(R)

    // //    if (landing2 > -10 << 8)
    // landing2 += accel;
    // // drawString(5, 62, ":", 0x22); //(R)
}


// EOF
