#pragma once

// Generated by 1bpp.py

extern const unsigned char gfx_grid_andrew_gif[8][6];
#define gfx_grid_andrew_gif_HEIGHT 8
extern const unsigned char gfx_grid_champgames_champ_gif[8][6];
#define gfx_grid_champgames_champ_gif_HEIGHT 8
extern const unsigned char gfx_grid_champgames_games_gif[8][6];
#define gfx_grid_champgames_games_gif_HEIGHT 8
extern const unsigned char gfx_grid_champgames_presents_gif[7][6];
#define gfx_grid_champgames_presents_gif_HEIGHT 7
extern const unsigned char gfx_grid_compliant_gif[7][6];
#define gfx_grid_compliant_gif_HEIGHT 7
extern const unsigned char gfx_grid_couch_compliant_gif[26][6];
#define gfx_grid_couch_compliant_gif_HEIGHT 26
extern const unsigned char gfx_grid_lorem1_gif[8][6];
#define gfx_grid_lorem1_gif_HEIGHT 8
extern const unsigned char gfx_grid_lorem2_gif[8][6];
#define gfx_grid_lorem2_gif_HEIGHT 8
extern const unsigned char gfx_grid_lorem3_gif[8][6];
#define gfx_grid_lorem3_gif_HEIGHT 8
extern const unsigned char gfx_grid_menu_bravado_gif[12][6];
#define gfx_grid_menu_bravado_gif_HEIGHT 12
extern const unsigned char gfx_grid_menu_planet_gif[8][6];
#define gfx_grid_menu_planet_gif_HEIGHT 8
extern const unsigned char gfx_grid_menu_planetx_gif[26][6];
#define gfx_grid_menu_planetx_gif_HEIGHT 26
extern const unsigned char gfx_grid_savekey_gif[8][6];
#define gfx_grid_savekey_gif_HEIGHT 8
extern const unsigned char gfx_grid_savekey_reset_gif[6][6];
#define gfx_grid_savekey_reset_gif_HEIGHT 6
extern const unsigned char gfx_grid_suchislife_gif[20][6];
#define gfx_grid_suchislife_gif_HEIGHT 20
