/* ../main/planetHuffman.c  —  auto-generated by huffman_compress.py, do not edit */
#include "../main/planetHuffman.h"

#define HUFF_MAX 7   /* maximum code length in bits */
#define HUFF_N   31         /* number of symbols */

/* Canonical Huffman decode tables */
/* h_syms : symbols in canonical order (sorted by length then value) */
/* h_count: how many symbols have each code length (index = length)  */
/* h_first: first canonical code at each length                      */
/* h_start: index into h_syms where each length's symbols begin      */

static const uint8_t  h_syms [HUFF_N]        = { 32, 101, 97, 104, 110, 111, 116, 124, 100, 108, 109, 114, 115, 119, 44, 95, 105, 112, 113, 117, 121, 34, 35, 46, 61, 73, 84, 99, 102, 107, 118 };
static const uint8_t  h_count[HUFF_MAX + 1]  = { 0, 0, 0, 2, 6, 6, 7, 10 };
static const uint16_t h_first[HUFF_MAX + 1]  = { 0, 0, 0, 0, 4, 20, 52, 118 };
static const uint8_t  h_start[HUFF_MAX + 1]  = { 0, 0, 0, 0, 2, 8, 14, 21 };

int phrase_decode(const uint8_t *src, char *dst, int max_len) {
    uint32_t win   = 0;
    int      wbits = 0, si = 0, di = 0;

    while (di < max_len - 1) {
        /* Refill bit window from src (MSB first).
           '#' terminates before we exhaust the stream, so no bounds check needed. */
        while (wbits < HUFF_MAX && wbits + 8 <= 32) {
            win   |= (uint32_t)src[si++] << (24 - wbits);
            wbits += 8;
        }

        /* Canonical decode: try each code length shortest-first. */
        for (int len = 1; len <= HUFF_MAX && len <= wbits; len++) {
            uint32_t code = win >> (32 - len);
            uint16_t lo   = h_first[len];
            uint8_t  cnt  = h_count[len];
            if (cnt && code >= lo && code < (uint32_t)(lo + cnt)) {
                char ch = (char)h_syms[h_start[len] + (code - lo)];
                win   <<= len;
                wbits  -= len;
                if (ch == '#') { dst[di] = '\0'; return di; }
                dst[di++] = ch;
                break;
            }
        }
    }
    dst[di] = '\0';
    return di;
}

static const uint8_t p000[ 67] = {0xF3, 0xDB, 0xDA, 0x99, 0xDE, 0xA8, 0xC6, 0x02, 0xF3, 0x6C, 0x04, 0x96, 0x78, 0x21, 0x9E, 0x27, 0x8E, 0x76, 0x82, 0x11, 0xBA, 0x96, 0x78, 0x23, 0xD0, 0xFC, 0xCF, 0x9D, 0x25, 0x1A, 0x82, 0xDD, 0x4E, 0x37, 0x3F, 0x36, 0x38, 0x0A, 0x98, 0x09, 0x39, 0x7B, 0xD0, 0x7D, 0x7B, 0x88, 0x54, 0x89, 0x67, 0x83, 0xA0, 0x46, 0xA0, 0x85, 0x33, 0x97, 0xBD, 0x05, 0x8A, 0x36, 0x27, 0x5A, 0x94, 0xFE, 0x75, 0xF1, 0xDC};  /*  67B ← 121ch  'The planet hums a note not quite any' */

const Phrase phrases[PHRASE_COUNT] = {
    {p000, 1},
};
