/* ../main/planetHuffman.h  —  auto-generated by huffman_compress.py, do not edit */
#pragma once
#include <stdint.h>

/* Decode a Huffman-compressed phrase into dst (null-terminated).
   src     : compressed byte stream (terminated in-band by '#')
   dst     : output buffer
   max_len : capacity of dst including null terminator
   returns : characters written, excluding null */
int phrase_decode(const uint8_t *src, char *dst, int max_len);

#define PHRASE_COUNT 115

typedef struct {
    const uint8_t *data;
    uint8_t        stars : 3;  /* 0-5, fits in 3 bits */
} Phrase;

extern const Phrase phrases[PHRASE_COUNT];
