/* Auto-generated by charset_to_c.py  —  DO NOT EDIT */
/* Source: ../alphanumeric/alphanumeric.png  size: 464x12  chars: 95 */

#pragma once

#include <stdint.h>

#define ALPHANUMERIC_FONT_HEIGHT      12
#define ALPHANUMERIC_FONT_FIRST_CHAR  32
#define ALPHANUMERIC_FONT_CHAR_COUNT  95

extern const unsigned char *alphanumeric_asciiTable[95];
extern const unsigned char  alphanumeric_charWidths[95];
