/* Auto-generated by charset_to_c.py  —  DO NOT EDIT */
/* Source: ../alphanumeric/fontLarge.png  size: 640x12  chars: 95 */

#pragma once

#include <stdint.h>

#define FONTLARGE_FONT_HEIGHT      12
#define FONTLARGE_FONT_FIRST_CHAR  32
#define FONTLARGE_FONT_CHAR_COUNT  95

extern const unsigned char *fontlarge_asciiTable[95];
extern const unsigned char  fontlarge_charWidths[95];
