/* Auto-generated by charset_to_c.py  —  DO NOT EDIT */
/* Source: ../alphanumeric/fontCompact.png  size: 500x9  chars: 95 */

#include "fontcompact.h"

/* '!'  ASCII 33  width=1px  1 byte(s)/row */
static const unsigned char char_033[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000000,  // 🟦
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000000   // 🟦
};

/* '0x22'  ASCII 34  width=1px  1 byte(s)/row */
static const unsigned char char_034[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000   // 🟦
};

/* '#'  ASCII 35  width=1px  1 byte(s)/row */
static const unsigned char char_035[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000   // 🟦
};

/* '''  ASCII 39  width=1px  1 byte(s)/row */
static const unsigned char char_039[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000   // 🟦
};

/* '('  ASCII 40  width=3px  1 byte(s)/row */
static const unsigned char char_040[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000110,  // 🟨🟨🟦
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000110,  // 🟨🟨🟦
    0b00000111,  // 🟨🟨🟨
    0b00000011,  // 🟦🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* ')'  ASCII 41  width=3px  1 byte(s)/row */
static const unsigned char char_041[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000011,  // 🟦🟨🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000011,  // 🟦🟨🟨
    0b00000111,  // 🟨🟨🟨
    0b00000110,  // 🟨🟨🟦
    0b00000000   // 🟦🟦🟦
};

/* '*'  ASCII 42  width=7px  1 byte(s)/row */
static const unsigned char char_042[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001000,  // 🟦🟦🟦🟨🟦🟦🟦
    0b00001000,  // 🟦🟦🟦🟨🟦🟦🟦
    0b00011100,  // 🟦🟦🟨🟨🟨🟦🟦
    0b00011100,  // 🟦🟦🟨🟨🟨🟦🟦
    0b01111111,  // 🟨🟨🟨🟨🟨🟨🟨
    0b00111110,  // 🟦🟨🟨🟨🟨🟨🟦
    0b00011100,  // 🟦🟦🟨🟨🟨🟦🟦
    0b00110110,  // 🟦🟨🟨🟦🟨🟨🟦
    0b00100010   // 🟦🟨🟦🟦🟦🟨🟦
};

/* '+'  ASCII 43  width=7px  1 byte(s)/row */
static const unsigned char char_043[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001000,  // 🟦🟦🟦🟨🟦🟦🟦
    0b00001000,  // 🟦🟦🟦🟨🟦🟦🟦
    0b00010100,  // 🟦🟦🟨🟦🟨🟦🟦
    0b00010100,  // 🟦🟦🟨🟦🟨🟦🟦
    0b01100011,  // 🟨🟨🟦🟦🟦🟨🟨
    0b00100010,  // 🟦🟨🟦🟦🟦🟨🟦
    0b00011100,  // 🟦🟦🟨🟨🟨🟦🟦
    0b00110110,  // 🟦🟨🟨🟦🟨🟨🟦
    0b00100010   // 🟦🟨🟦🟦🟦🟨🟦
};

/* ','  ASCII 44  width=2px  1 byte(s)/row */
static const unsigned char char_044[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000011   // 🟨🟨
};

/* '-'  ASCII 45  width=4px  1 byte(s)/row */
static const unsigned char char_045[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* '.'  ASCII 46  width=1px  1 byte(s)/row */
static const unsigned char char_046[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000000,  // 🟦
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000000   // 🟦
};

/* '0x2F'  ASCII 47  width=2px  1 byte(s)/row */
static const unsigned char char_047[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000011,  // 🟨🟨
    0b00000010,  // 🟨🟦
    0b00000010,  // 🟨🟦
    0b00000010,  // 🟨🟦
    0b00000010   // 🟨🟦
};

/* '0'  ASCII 48  width=4px  1 byte(s)/row */
static const unsigned char char_048[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00000110,  // 🟦🟨🟨🟦
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* '1'  ASCII 49  width=2px  1 byte(s)/row */
static const unsigned char char_049[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦
    0b00000001,  // 🟦🟨
    0b00000011,  // 🟨🟨
    0b00000011,  // 🟨🟨
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000000   // 🟦🟦
};

/* '2'  ASCII 50  width=4px  1 byte(s)/row */
static const unsigned char char_050[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00000001,  // 🟦🟦🟦🟨
    0b00000011,  // 🟦🟦🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00001100,  // 🟨🟨🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* '3'  ASCII 51  width=4px  1 byte(s)/row */
static const unsigned char char_051[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00000110,  // 🟦🟨🟨🟦
    0b00001001,  // 🟨🟦🟦🟨
    0b00000010,  // 🟦🟦🟨🟦
    0b00000001,  // 🟦🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* '4'  ASCII 52  width=4px  1 byte(s)/row */
static const unsigned char char_052[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001010,  // 🟨🟦🟨🟦
    0b00001010,  // 🟨🟦🟨🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000010,  // 🟦🟦🟨🟦
    0b00000010,  // 🟦🟦🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* '5'  ASCII 53  width=4px  1 byte(s)/row */
static const unsigned char char_053[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001000,  // 🟨🟦🟦🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00000001,  // 🟦🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* '6'  ASCII 54  width=4px  1 byte(s)/row */
static const unsigned char char_054[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00000111,  // 🟦🟨🟨🟨
    0b00001000,  // 🟨🟦🟦🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* '7'  ASCII 55  width=4px  1 byte(s)/row */
static const unsigned char char_055[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000001,  // 🟦🟦🟦🟨
    0b00000010,  // 🟦🟦🟨🟦
    0b00000100,  // 🟦🟨🟦🟦
    0b00000100,  // 🟦🟨🟦🟦
    0b00000100,  // 🟦🟨🟦🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* '8'  ASCII 56  width=4px  1 byte(s)/row */
static const unsigned char char_056[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00000110,  // 🟦🟨🟨🟦
    0b00001001,  // 🟨🟦🟦🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* '9'  ASCII 57  width=4px  1 byte(s)/row */
static const unsigned char char_057[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00000110,  // 🟦🟨🟨🟦
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000111,  // 🟦🟨🟨🟨
    0b00000001,  // 🟦🟦🟦🟨
    0b00000001,  // 🟦🟦🟦🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* ':'  ASCII 58  width=2px  1 byte(s)/row */
static const unsigned char char_058[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000011,  // 🟨🟨
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000011,  // 🟨🟨
    0b00000011,  // 🟨🟨
    0b00000000   // 🟦🟦
};

/* ';'  ASCII 59  width=2px  1 byte(s)/row */
static const unsigned char char_059[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000011,  // 🟨🟨
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000011,  // 🟨🟨
    0b00000011,  // 🟨🟨
    0b00000001   // 🟦🟨
};

/* '<'  ASCII 60  width=4px  1 byte(s)/row */
static const unsigned char char_060[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00000010,  // 🟦🟦🟨🟦
    0b00000100,  // 🟦🟨🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001100,  // 🟨🟨🟦🟦
    0b00000110,  // 🟦🟨🟨🟦
    0b00000111,  // 🟦🟨🟨🟨
    0b00000011,  // 🟦🟦🟨🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* '='  ASCII 61  width=4px  1 byte(s)/row */
static const unsigned char char_061[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00000000,  // 🟦🟦🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* '>'  ASCII 62  width=4px  1 byte(s)/row */
static const unsigned char char_062[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00000100,  // 🟦🟨🟦🟦
    0b00000010,  // 🟦🟦🟨🟦
    0b00000001,  // 🟦🟦🟦🟨
    0b00000011,  // 🟦🟦🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00001100,  // 🟨🟨🟦🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* '?'  ASCII 63  width=3px  1 byte(s)/row */
static const unsigned char char_063[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000001,  // 🟦🟦🟨
    0b00000011,  // 🟦🟨🟨
    0b00000110,  // 🟨🟨🟦
    0b00000100,  // 🟨🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000000   // 🟦🟦🟦
};

/* 'A'  ASCII 65  width=4px  1 byte(s)/row */
static const unsigned char char_065[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000010,  // 🟦🟦🟨🟦
    0b00000111,  // 🟦🟨🟨🟨
    0b00001101,  // 🟨🟨🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* 'B'  ASCII 66  width=4px  1 byte(s)/row */
static const unsigned char char_066[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001110,  // 🟨🟨🟨🟦
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001110,  // 🟨🟨🟨🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001110,  // 🟨🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* 'C'  ASCII 67  width=4px  1 byte(s)/row */
static const unsigned char char_067[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000011,  // 🟦🟦🟨🟨
    0b00000111,  // 🟦🟨🟨🟨
    0b00001100,  // 🟨🟨🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* 'D'  ASCII 68  width=4px  1 byte(s)/row */
static const unsigned char char_068[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001100,  // 🟨🟨🟦🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00001011,  // 🟨🟦🟨🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001110,  // 🟨🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* 'E'  ASCII 69  width=4px  1 byte(s)/row */
static const unsigned char char_069[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001000,  // 🟨🟦🟦🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* 'F'  ASCII 70  width=4px  1 byte(s)/row */
static const unsigned char char_070[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001000,  // 🟨🟦🟦🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* 'G'  ASCII 71  width=4px  1 byte(s)/row */
static const unsigned char char_071[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000011,  // 🟦🟦🟨🟨
    0b00000111,  // 🟦🟨🟨🟨
    0b00001100,  // 🟨🟨🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001011,  // 🟨🟦🟨🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000111,  // 🟦🟨🟨🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* 'H'  ASCII 72  width=4px  1 byte(s)/row */
static const unsigned char char_072[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* 'I'  ASCII 73  width=3px  1 byte(s)/row */
static const unsigned char char_073[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000111,  // 🟨🟨🟨
    0b00000111,  // 🟨🟨🟨
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000111,  // 🟨🟨🟨
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* 'J'  ASCII 74  width=3px  1 byte(s)/row */
static const unsigned char char_074[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000110,  // 🟨🟨🟦
    0b00000000   // 🟦🟦🟦
};

/* 'K'  ASCII 75  width=4px  1 byte(s)/row */
static const unsigned char char_075[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001001,  // 🟨🟦🟦🟨
    0b00001011,  // 🟨🟦🟨🟨
    0b00001110,  // 🟨🟨🟨🟦
    0b00001100,  // 🟨🟨🟦🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00001011,  // 🟨🟦🟨🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* 'L'  ASCII 76  width=4px  1 byte(s)/row */
static const unsigned char char_076[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* 'M'  ASCII 77  width=5px  1 byte(s)/row */
static const unsigned char char_077[FONTCOMPACT_FONT_HEIGHT] = {
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00011011,  // 🟨🟨🟦🟨🟨
    0b00011111,  // 🟨🟨🟨🟨🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00000000   // 🟦🟦🟦🟦🟦
};

/* 'N'  ASCII 78  width=5px  1 byte(s)/row */
static const unsigned char char_078[FONTCOMPACT_FONT_HEIGHT] = {
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00011001,  // 🟨🟨🟦🟦🟨
    0b00011101,  // 🟨🟨🟨🟦🟨
    0b00010111,  // 🟨🟦🟨🟨🟨
    0b00010011,  // 🟨🟦🟦🟨🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00000000   // 🟦🟦🟦🟦🟦
};

/* 'O'  ASCII 79  width=4px  1 byte(s)/row */
static const unsigned char char_079[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000110,  // 🟦🟨🟨🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* 'P'  ASCII 80  width=4px  1 byte(s)/row */
static const unsigned char char_080[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001110,  // 🟨🟨🟨🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001110,  // 🟨🟨🟨🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* 'Q'  ASCII 81  width=4px  1 byte(s)/row */
static const unsigned char char_081[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000110,  // 🟦🟨🟨🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001011,  // 🟨🟦🟨🟨
    0b00001110,  // 🟨🟨🟨🟦
    0b00000101,  // 🟦🟨🟦🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* 'R'  ASCII 82  width=4px  1 byte(s)/row */
static const unsigned char char_082[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001110,  // 🟨🟨🟨🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001110,  // 🟨🟨🟨🟦
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* 'S'  ASCII 83  width=4px  1 byte(s)/row */
static const unsigned char char_083[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000111,  // 🟦🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001000,  // 🟨🟦🟦🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00000111,  // 🟦🟨🟨🟨
    0b00000001,  // 🟦🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001110,  // 🟨🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* 'T'  ASCII 84  width=3px  1 byte(s)/row */
static const unsigned char char_084[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000111,  // 🟨🟨🟨
    0b00000111,  // 🟨🟨🟨
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000000   // 🟦🟦🟦
};

/* 'U'  ASCII 85  width=4px  1 byte(s)/row */
static const unsigned char char_085[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* 'V'  ASCII 86  width=4px  1 byte(s)/row */
static const unsigned char char_086[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001011,  // 🟨🟦🟨🟨
    0b00001110,  // 🟨🟨🟨🟦
    0b00001110,  // 🟨🟨🟨🟦
    0b00000100,  // 🟦🟨🟦🟦
    0b00000100,  // 🟦🟨🟦🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* 'W'  ASCII 87  width=5px  1 byte(s)/row */
static const unsigned char char_087[FONTCOMPACT_FONT_HEIGHT] = {
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00011111,  // 🟨🟨🟨🟨🟨
    0b00011011,  // 🟨🟨🟦🟨🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00000000   // 🟦🟦🟦🟦🟦
};

/* 'X'  ASCII 88  width=5px  1 byte(s)/row */
static const unsigned char char_088[FONTCOMPACT_FONT_HEIGHT] = {
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00011011,  // 🟨🟨🟦🟨🟨
    0b00001110,  // 🟦🟨🟨🟨🟦
    0b00000100,  // 🟦🟦🟨🟦🟦
    0b00001110,  // 🟦🟨🟨🟨🟦
    0b00011011,  // 🟨🟨🟦🟨🟨
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00000000   // 🟦🟦🟦🟦🟦
};

/* 'Y'  ASCII 89  width=4px  1 byte(s)/row */
static const unsigned char char_089[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001001,  // 🟨🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000111,  // 🟦🟨🟨🟨
    0b00000001,  // 🟦🟦🟦🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00001110,  // 🟨🟨🟨🟦
    0b00000000   // 🟦🟦🟦🟦
};

/* 'Z'  ASCII 90  width=4px  1 byte(s)/row */
static const unsigned char char_090[FONTCOMPACT_FONT_HEIGHT] = {
    0b00001111,  // 🟨🟨🟨🟨
    0b00000001,  // 🟦🟦🟦🟨
    0b00000011,  // 🟦🟦🟨🟨
    0b00000110,  // 🟦🟨🟨🟦
    0b00001100,  // 🟨🟨🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* '['  ASCII 91  width=3px  1 byte(s)/row */
static const unsigned char char_091[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* '0x5C'  ASCII 92  width=4px  1 byte(s)/row */
static const unsigned char char_092[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00001000,  // 🟨🟦🟦🟦
    0b00000100,  // 🟦🟨🟦🟦
    0b00000100,  // 🟦🟨🟦🟦
    0b00000110,  // 🟦🟨🟨🟦
    0b00000010,  // 🟦🟦🟨🟦
    0b00000011,  // 🟦🟦🟨🟨
    0b00000011,  // 🟦🟦🟨🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* ']'  ASCII 93  width=3px  1 byte(s)/row */
static const unsigned char char_093[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* '^'  ASCII 94  width=2px  1 byte(s)/row */
static const unsigned char char_094[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦
    0b00000011,  // 🟨🟨
    0b00000001,  // 🟦🟨
    0b00000010,  // 🟨🟦
    0b00000011,  // 🟨🟨
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000   // 🟦🟦
};

/* '_'  ASCII 95  width=4px  1 byte(s)/row */
static const unsigned char char_095[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦
    0b00001111,  // 🟨🟨🟨🟨
    0b00001111,  // 🟨🟨🟨🟨
    0b00000000   // 🟦🟦🟦🟦
};

/* '`'  ASCII 96  width=2px  1 byte(s)/row */
static const unsigned char char_096[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000010,  // 🟨🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000000   // 🟦🟦
};

/* 'a'  ASCII 97  width=3px  1 byte(s)/row */
static const unsigned char char_097[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000001,  // 🟦🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* 'b'  ASCII 98  width=3px  1 byte(s)/row */
static const unsigned char char_098[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* 'c'  ASCII 99  width=3px  1 byte(s)/row */
static const unsigned char char_099[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* 'd'  ASCII 100  width=3px  1 byte(s)/row */
static const unsigned char char_100[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* 'e'  ASCII 101  width=3px  1 byte(s)/row */
static const unsigned char char_101[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000100,  // 🟨🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* 'f'  ASCII 102  width=3px  1 byte(s)/row */
static const unsigned char char_102[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000011,  // 🟦🟨🟨
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000111,  // 🟨🟨🟨
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000000   // 🟦🟦🟦
};

/* 'g'  ASCII 103  width=3px  1 byte(s)/row */
static const unsigned char char_103[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000001,  // 🟦🟦🟨
    0b00000111   // 🟨🟨🟨
};

/* 'h'  ASCII 104  width=3px  1 byte(s)/row */
static const unsigned char char_104[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000000   // 🟦🟦🟦
};

/* 'i'  ASCII 105  width=1px  1 byte(s)/row */
static const unsigned char char_105[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000001,  // 🟨
    0b00000000,  // 🟦
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000000   // 🟦
};

/* 'j'  ASCII 106  width=2px  1 byte(s)/row */
static const unsigned char char_106[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000001,  // 🟦🟨
    0b00000000,  // 🟦🟦
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000001,  // 🟦🟨
    0b00000011   // 🟨🟨
};

/* 'k'  ASCII 107  width=3px  1 byte(s)/row */
static const unsigned char char_107[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000100,  // 🟨🟦🟦
    0b00000100,  // 🟨🟦🟦
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000110,  // 🟨🟨🟦
    0b00000110,  // 🟨🟨🟦
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000000   // 🟦🟦🟦
};

/* 'l'  ASCII 108  width=1px  1 byte(s)/row */
static const unsigned char char_108[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000001,  // 🟨
    0b00000000   // 🟦
};

/* 'm'  ASCII 109  width=5px  1 byte(s)/row */
static const unsigned char char_109[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦🟦
    0b00011111,  // 🟨🟨🟨🟨🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00000000   // 🟦🟦🟦🟦🟦
};

/* 'n'  ASCII 110  width=3px  1 byte(s)/row */
static const unsigned char char_110[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000000   // 🟦🟦🟦
};

/* 'o'  ASCII 111  width=3px  1 byte(s)/row */
static const unsigned char char_111[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* 'p'  ASCII 112  width=3px  1 byte(s)/row */
static const unsigned char char_112[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000100,  // 🟨🟦🟦
    0b00000100   // 🟨🟦🟦
};

/* 'q'  ASCII 113  width=3px  1 byte(s)/row */
static const unsigned char char_113[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001   // 🟦🟦🟨
};

/* 'r'  ASCII 114  width=2px  1 byte(s)/row */
static const unsigned char char_114[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦
    0b00000000,  // 🟦🟦
    0b00000011,  // 🟨🟨
    0b00000010,  // 🟨🟦
    0b00000010,  // 🟨🟦
    0b00000010,  // 🟨🟦
    0b00000010,  // 🟨🟦
    0b00000010,  // 🟨🟦
    0b00000000   // 🟦🟦
};

/* 's'  ASCII 115  width=3px  1 byte(s)/row */
static const unsigned char char_115[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000100,  // 🟨🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000001,  // 🟦🟦🟨
    0b00000001,  // 🟦🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* 't'  ASCII 116  width=2px  1 byte(s)/row */
static const unsigned char char_116[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000010,  // 🟨🟦
    0b00000010,  // 🟨🟦
    0b00000011,  // 🟨🟨
    0b00000010,  // 🟨🟦
    0b00000010,  // 🟨🟦
    0b00000010,  // 🟨🟦
    0b00000010,  // 🟨🟦
    0b00000011,  // 🟨🟨
    0b00000000   // 🟦🟦
};

/* 'u'  ASCII 117  width=3px  1 byte(s)/row */
static const unsigned char char_117[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

/* 'v'  ASCII 118  width=3px  1 byte(s)/row */
static const unsigned char char_118[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000010,  // 🟦🟨🟦
    0b00000000   // 🟦🟦🟦
};

/* 'w'  ASCII 119  width=5px  1 byte(s)/row */
static const unsigned char char_119[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦🟦🟦
    0b00000000,  // 🟦🟦🟦🟦🟦
    0b00010001,  // 🟨🟦🟦🟦🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00010101,  // 🟨🟦🟨🟦🟨
    0b00011111,  // 🟨🟨🟨🟨🟨
    0b00000000   // 🟦🟦🟦🟦🟦
};

/* 'x'  ASCII 120  width=3px  1 byte(s)/row */
static const unsigned char char_120[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000111,  // 🟨🟨🟨
    0b00000101,  // 🟨🟦🟨
    0b00000000   // 🟦🟦🟦
};

/* 'y'  ASCII 121  width=3px  1 byte(s)/row */
static const unsigned char char_121[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000101,  // 🟨🟦🟨
    0b00000111,  // 🟨🟨🟨
    0b00000001,  // 🟦🟦🟨
    0b00000111   // 🟨🟨🟨
};

/* 'z'  ASCII 122  width=3px  1 byte(s)/row */
static const unsigned char char_122[FONTCOMPACT_FONT_HEIGHT] = {
    0b00000000,  // 🟦🟦🟦
    0b00000000,  // 🟦🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000001,  // 🟦🟦🟨
    0b00000010,  // 🟦🟨🟦
    0b00000010,  // 🟦🟨🟦
    0b00000100,  // 🟨🟦🟦
    0b00000111,  // 🟨🟨🟨
    0b00000000   // 🟦🟦🟦
};

const unsigned char fontcompact_charWidths[] = {
      1  /* ' ' ASCII 32 */,
      1  /* '!' ASCII 33 */,
      1  /* '0x22' ASCII 34 */,
      1  /* '#' ASCII 35 */,
      0  /* '$' ASCII 36 */,
      0  /* '%' ASCII 37 */,
      0  /* '&' ASCII 38 */,
      1  /* ''' ASCII 39 */,
      3  /* '(' ASCII 40 */,
      3  /* ')' ASCII 41 */,
      7  /* '*' ASCII 42 */,
      7  /* '+' ASCII 43 */,
      2  /* ',' ASCII 44 */,
      4  /* '-' ASCII 45 */,
      1  /* '.' ASCII 46 */,
      2  /* '/' ASCII 47 */,
      4  /* '0' ASCII 48 */,
      2  /* '1' ASCII 49 */,
      4  /* '2' ASCII 50 */,
      4  /* '3' ASCII 51 */,
      4  /* '4' ASCII 52 */,
      4  /* '5' ASCII 53 */,
      4  /* '6' ASCII 54 */,
      4  /* '7' ASCII 55 */,
      4  /* '8' ASCII 56 */,
      4  /* '9' ASCII 57 */,
      2  /* ':' ASCII 58 */,
      2  /* ';' ASCII 59 */,
      4  /* '<' ASCII 60 */,
      4  /* '=' ASCII 61 */,
      4  /* '>' ASCII 62 */,
      3  /* '?' ASCII 63 */,
      0  /* '@' ASCII 64 */,
      4  /* 'A' ASCII 65 */,
      4  /* 'B' ASCII 66 */,
      4  /* 'C' ASCII 67 */,
      4  /* 'D' ASCII 68 */,
      4  /* 'E' ASCII 69 */,
      4  /* 'F' ASCII 70 */,
      4  /* 'G' ASCII 71 */,
      4  /* 'H' ASCII 72 */,
      3  /* 'I' ASCII 73 */,
      3  /* 'J' ASCII 74 */,
      4  /* 'K' ASCII 75 */,
      4  /* 'L' ASCII 76 */,
      5  /* 'M' ASCII 77 */,
      5  /* 'N' ASCII 78 */,
      4  /* 'O' ASCII 79 */,
      4  /* 'P' ASCII 80 */,
      4  /* 'Q' ASCII 81 */,
      4  /* 'R' ASCII 82 */,
      4  /* 'S' ASCII 83 */,
      3  /* 'T' ASCII 84 */,
      4  /* 'U' ASCII 85 */,
      4  /* 'V' ASCII 86 */,
      5  /* 'W' ASCII 87 */,
      5  /* 'X' ASCII 88 */,
      4  /* 'Y' ASCII 89 */,
      4  /* 'Z' ASCII 90 */,
      3  /* '[' ASCII 91 */,
      4  /* '0x5C' ASCII 92 */,
      3  /* ']' ASCII 93 */,
      2  /* '^' ASCII 94 */,
      4  /* '_' ASCII 95 */,
      2  /* '`' ASCII 96 */,
      3  /* 'a' ASCII 97 */,
      3  /* 'b' ASCII 98 */,
      3  /* 'c' ASCII 99 */,
      3  /* 'd' ASCII 100 */,
      3  /* 'e' ASCII 101 */,
      3  /* 'f' ASCII 102 */,
      3  /* 'g' ASCII 103 */,
      3  /* 'h' ASCII 104 */,
      1  /* 'i' ASCII 105 */,
      2  /* 'j' ASCII 106 */,
      3  /* 'k' ASCII 107 */,
      1  /* 'l' ASCII 108 */,
      5  /* 'm' ASCII 109 */,
      3  /* 'n' ASCII 110 */,
      3  /* 'o' ASCII 111 */,
      3  /* 'p' ASCII 112 */,
      3  /* 'q' ASCII 113 */,
      2  /* 'r' ASCII 114 */,
      3  /* 's' ASCII 115 */,
      2  /* 't' ASCII 116 */,
      3  /* 'u' ASCII 117 */,
      3  /* 'v' ASCII 118 */,
      5  /* 'w' ASCII 119 */,
      3  /* 'x' ASCII 120 */,
      3  /* 'y' ASCII 121 */,
      3  /* 'z' ASCII 122 */,
      0  /* '{' ASCII 123 */,
      0  /* '|' ASCII 124 */,
      0  /* '}' ASCII 125 */,
      0  /* '~' ASCII 126 */
};

/* fontcompact_asciiTable[i] → character for ASCII (i + 32), 0 if no glyph */
const unsigned char *fontcompact_asciiTable[95] = {
    0  /* ' ' ASCII 32 */,
    char_033  /* '!' ASCII 33 */,
    char_034  /* '0x22' ASCII 34 */,
    char_035  /* '#' ASCII 35 */,
    0  /* '$' ASCII 36 */,
    0  /* '%' ASCII 37 */,
    0  /* '&' ASCII 38 */,
    char_039  /* ''' ASCII 39 */,
    char_040  /* '(' ASCII 40 */,
    char_041  /* ')' ASCII 41 */,
    char_042  /* '*' ASCII 42 */,
    char_043  /* '+' ASCII 43 */,
    char_044  /* ',' ASCII 44 */,
    char_045  /* '-' ASCII 45 */,
    char_046  /* '.' ASCII 46 */,
    char_047  /* '/' ASCII 47 */,
    char_048  /* '0' ASCII 48 */,
    char_049  /* '1' ASCII 49 */,
    char_050  /* '2' ASCII 50 */,
    char_051  /* '3' ASCII 51 */,
    char_052  /* '4' ASCII 52 */,
    char_053  /* '5' ASCII 53 */,
    char_054  /* '6' ASCII 54 */,
    char_055  /* '7' ASCII 55 */,
    char_056  /* '8' ASCII 56 */,
    char_057  /* '9' ASCII 57 */,
    char_058  /* ':' ASCII 58 */,
    char_059  /* ';' ASCII 59 */,
    char_060  /* '<' ASCII 60 */,
    char_061  /* '=' ASCII 61 */,
    char_062  /* '>' ASCII 62 */,
    char_063  /* '?' ASCII 63 */,
    0  /* '@' ASCII 64 */,
    char_065  /* 'A' ASCII 65 */,
    char_066  /* 'B' ASCII 66 */,
    char_067  /* 'C' ASCII 67 */,
    char_068  /* 'D' ASCII 68 */,
    char_069  /* 'E' ASCII 69 */,
    char_070  /* 'F' ASCII 70 */,
    char_071  /* 'G' ASCII 71 */,
    char_072  /* 'H' ASCII 72 */,
    char_073  /* 'I' ASCII 73 */,
    char_074  /* 'J' ASCII 74 */,
    char_075  /* 'K' ASCII 75 */,
    char_076  /* 'L' ASCII 76 */,
    char_077  /* 'M' ASCII 77 */,
    char_078  /* 'N' ASCII 78 */,
    char_079  /* 'O' ASCII 79 */,
    char_080  /* 'P' ASCII 80 */,
    char_081  /* 'Q' ASCII 81 */,
    char_082  /* 'R' ASCII 82 */,
    char_083  /* 'S' ASCII 83 */,
    char_084  /* 'T' ASCII 84 */,
    char_085  /* 'U' ASCII 85 */,
    char_086  /* 'V' ASCII 86 */,
    char_087  /* 'W' ASCII 87 */,
    char_088  /* 'X' ASCII 88 */,
    char_089  /* 'Y' ASCII 89 */,
    char_090  /* 'Z' ASCII 90 */,
    char_091  /* '[' ASCII 91 */,
    char_092  /* '0x5C' ASCII 92 */,
    char_093  /* ']' ASCII 93 */,
    char_094  /* '^' ASCII 94 */,
    char_095  /* '_' ASCII 95 */,
    char_096  /* '`' ASCII 96 */,
    char_097  /* 'a' ASCII 97 */,
    char_098  /* 'b' ASCII 98 */,
    char_099  /* 'c' ASCII 99 */,
    char_100  /* 'd' ASCII 100 */,
    char_101  /* 'e' ASCII 101 */,
    char_102  /* 'f' ASCII 102 */,
    char_103  /* 'g' ASCII 103 */,
    char_104  /* 'h' ASCII 104 */,
    char_105  /* 'i' ASCII 105 */,
    char_106  /* 'j' ASCII 106 */,
    char_107  /* 'k' ASCII 107 */,
    char_108  /* 'l' ASCII 108 */,
    char_109  /* 'm' ASCII 109 */,
    char_110  /* 'n' ASCII 110 */,
    char_111  /* 'o' ASCII 111 */,
    char_112  /* 'p' ASCII 112 */,
    char_113  /* 'q' ASCII 113 */,
    char_114  /* 'r' ASCII 114 */,
    char_115  /* 's' ASCII 115 */,
    char_116  /* 't' ASCII 116 */,
    char_117  /* 'u' ASCII 117 */,
    char_118  /* 'v' ASCII 118 */,
    char_119  /* 'w' ASCII 119 */,
    char_120  /* 'x' ASCII 120 */,
    char_121  /* 'y' ASCII 121 */,
    char_122  /* 'z' ASCII 122 */,
    0  /* '{' ASCII 123 */,
    0  /* '|' ASCII 124 */,
    0  /* '}' ASCII 125 */,
    0  /* '~' ASCII 126 */
};
