/* Auto-generated by charset_to_c.py  —  DO NOT EDIT */
/* Source: ../alphanumeric/fontcompact.png  size: 464x9  chars: 95 */

#ifndef FONTCOMPACT_H
#define FONTCOMPACT_H

#include <stdint.h>

#define FONTCOMPACT_FONT_HEIGHT      9
#define FONTCOMPACT_FONT_FIRST_CHAR  32
#define FONTCOMPACT_FONT_CHAR_COUNT  95

extern const unsigned char *fontcompact_asciiTable[95];
extern const unsigned char  fontcompact_charWidths[95];

#endif /* FONTCOMPACT_H */
