/* Auto-generated by spinningGlobe/cset.py from "bloodworld.png" */
#pragma once

#define BLOODWORLD_CHARSET_SIZE 40
#define BLOODWORLD_MAP_SIZE     122
#define BLOODWORLD_CHAR_WIDTH   5
#define BLOODWORLD_CHAR_HEIGHT  10
#define BLOODWORLD_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char bloodworld_ntsc_palette[3];

/* Charset: 40 characters, each 30 bytes */
extern const unsigned char * const bloodworld_charset[40];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char bloodworld_map[122];


