/* Auto-generated by img2tiles.py from "blood2.png" */
#pragma once

#define BLOOD2_CHARSET_SIZE 68
#define BLOOD2_MAP_SIZE     122
#define BLOOD2_CHAR_WIDTH   5
#define BLOOD2_CHAR_HEIGHT  10
#define BLOOD2_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char blood2_ntsc_palette[3];

/* Charset: 68 characters, each 30 bytes */
extern const unsigned char * const blood2_charset[68];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char blood2_map[122];


