/* Auto-generated by img2tiles.py from "blood2.png" */
/* Adaptive palette: 8 colours built from 3 EM-optimised primaries (NTSC-snapped). */
/* Index bits: bit0=P1, bit1=P2, bit2=P3 (P1/P2/P3 = single-bit primaries). */
/* Character: 5 pixels wide x 10 trixels deep (30 scanlines). */
/* Trixel: 1 pixel wide x 3 scanlines deep, 3-bit palette index. */
/* Character storage: 10 trixel-rows x 3 bytes (bit0-plane, bit1-plane, bit2-plane) = 30 bytes. */
/* Byte bit layout: bit4=col0(left) .. bit0=col4(right), bits7-5 unused. */
/* Map: byte0=width(chars, +10 wrap buffer), byte1=height(chars), then row-major indices. */

static const unsigned char blood2_palette[8][3] = {
    {   0,   0,   0 },  /* 0: origin */
    {  68,  40,   0 },  /* 1: +P1 */
    { 100,  72,  24 },  /* 2: +P2 */
    {  84,  56,  12 },  /* 3: +P1+P2 */
    { 144, 144, 144 },  /* 4: +P3 */
    { 106,  92,  72 },  /* 5: +P1+P3 */
    { 122, 108,  84 },  /* 6: +P2+P3 */
    { 104,  85,  56 },  /* 7: +P1+P2+P3 */
};

/* NTSC Atari 2600 companion palette: nearest TIA register values for
 * palette primaries (indices 1, 2, 4 — the single-bit entries). */
const unsigned char blood2_ntsc_palette[3] = {
    0xF0,  /* palette[1] = (68,40,0) */
    0xF2,  /* palette[2] = (100,72,24) */
    0x06,  /* palette[4] = (144,144,144) */
};

static const unsigned char blood2_char_000[30] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static const unsigned char blood2_char_001[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_002[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char blood2_char_003[30] = { 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0 };
static const unsigned char blood2_char_004[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char blood2_char_005[30] = { 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31 };
static const unsigned char blood2_char_006[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char blood2_char_007[30] = { 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31 };
static const unsigned char blood2_char_008[30] = { 0, 0, 31, 0, 31, 31, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_009[30] = { 0, 0, 31, 0, 31, 31, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 28, 0, 31, 6, 0, 31, 6, 0, 31, 0, 0 };
static const unsigned char blood2_char_010[30] = { 0, 0, 31, 0, 31, 31, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 7, 0, 31, 0, 0 };
static const unsigned char blood2_char_011[30] = { 0, 0, 31, 28, 19, 31, 31, 15, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0, 31, 0, 0 };
static const unsigned char blood2_char_012[30] = { 0, 0, 31, 15, 22, 31, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 0, 31, 0, 0 };
static const unsigned char blood2_char_013[30] = { 0, 0, 31, 29, 6, 31, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 0, 31, 31, 0, 31, 0, 0 };
static const unsigned char blood2_char_014[30] = { 0, 0, 31, 23, 15, 31, 31, 24, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 18, 0, 15, 23, 0, 28, 31, 0, 31, 0, 0 };
static const unsigned char blood2_char_015[30] = { 0, 0, 31, 24, 31, 24, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 3, 0, 24, 15, 0, 24, 15, 0, 24, 23, 0, 31, 7, 0 };
static const unsigned char blood2_char_016[30] = { 0, 0, 31, 24, 31, 24, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 11, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31, 31, 0 };
static const unsigned char blood2_char_017[30] = { 0, 0, 31, 24, 31, 24, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 11, 0, 0, 31, 0, 0, 31, 0, 27, 31, 0, 31, 26, 0 };
static const unsigned char blood2_char_018[30] = { 0, 0, 31, 3, 31, 3, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0, 0, 31, 0, 30, 31, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_019[30] = { 0, 0, 31, 24, 31, 24, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 3, 0, 0, 31, 0, 17, 31, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_020[30] = { 0, 0, 31, 31, 19, 31, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 2, 0, 0, 31, 0, 31, 10, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_021[30] = { 0, 0, 31, 14, 17, 31, 31, 19, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 1, 31, 0, 31, 8, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_022[30] = { 0, 0, 31, 0, 31, 31, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 3, 31, 0, 31, 24, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_023[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 0 };
static const unsigned char blood2_char_024[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 28, 15, 0 };
static const unsigned char blood2_char_025[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 2, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0 };
static const unsigned char blood2_char_026[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 3, 0, 28, 3, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0 };
static const unsigned char blood2_char_027[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 23, 0, 15, 23, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0 };
static const unsigned char blood2_char_028[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 0, 24, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 21, 31, 0 };
static const unsigned char blood2_char_029[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 30, 0, 1, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 0 };
static const unsigned char blood2_char_030[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 26, 0 };
static const unsigned char blood2_char_031[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 5, 0 };
static const unsigned char blood2_char_032[30] = { 31, 0, 0, 31, 0, 0, 31, 4, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 23, 28, 0 };
static const unsigned char blood2_char_033[30] = { 31, 0, 0, 31, 0, 0, 31, 30, 0, 31, 14, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_034[30] = { 31, 0, 0, 31, 0, 0, 30, 11, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_035[30] = { 31, 0, 0, 31, 0, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_036[30] = { 31, 0, 0, 31, 2, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 3, 0 };
static const unsigned char blood2_char_037[30] = { 28, 31, 0, 31, 7, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_038[30] = { 0, 31, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_039[30] = { 17, 31, 0, 31, 6, 0, 31, 0, 0, 31, 0, 0, 31, 8, 0, 31, 8, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_040[30] = { 23, 31, 0, 31, 8, 0, 31, 0, 0, 31, 0, 0, 27, 6, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_041[30] = { 31, 30, 0, 31, 29, 0, 31, 0, 0, 31, 0, 0, 31, 3, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 2, 0 };
static const unsigned char blood2_char_042[30] = { 31, 7, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 31, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_043[30] = { 31, 0, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 11, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char blood2_char_044[30] = { 31, 11, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0, 31, 31, 0, 31, 0, 0, 31, 13, 0, 31, 0, 0, 31, 11, 0 };
static const unsigned char blood2_char_045[30] = { 31, 15, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 22, 0, 31, 8, 0, 28, 31, 0, 28, 3, 0, 20, 31, 0 };
static const unsigned char blood2_char_046[30] = { 31, 31, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char blood2_char_047[30] = { 31, 11, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char blood2_char_048[30] = { 31, 11, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 8, 31, 12, 0, 31, 4, 0, 31, 0 };
static const unsigned char blood2_char_049[30] = { 31, 31, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0, 0, 31, 0, 31, 30, 0 };
static const unsigned char blood2_char_050[30] = { 31, 12, 0, 31, 28, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0, 15, 31, 0, 31, 24, 0 };
static const unsigned char blood2_char_051[30] = { 8, 31, 0, 31, 30, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0, 31, 0, 0 };
static const unsigned char blood2_char_052[30] = { 31, 28, 0, 31, 29, 0, 31, 0, 0, 31, 0, 0, 31, 3, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 2, 0 };
static const unsigned char blood2_char_053[30] = { 31, 0, 0, 31, 0, 0, 31, 31, 0, 24, 31, 24, 7, 31, 0, 31, 0, 0, 31, 0, 0, 3, 31, 0, 6, 25, 31, 0, 0, 31 };
static const unsigned char blood2_char_054[30] = { 31, 0, 0, 31, 0, 0, 31, 30, 0, 0, 31, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 31, 0, 2, 29, 31, 0, 0, 31 };
static const unsigned char blood2_char_055[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 9, 31, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 30, 0, 7, 24, 31, 0, 0, 31 };
static const unsigned char blood2_char_056[30] = { 31, 1, 0, 31, 1, 0, 31, 0, 0, 9, 31, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0, 0, 0, 31 };
static const unsigned char blood2_char_057[30] = { 24, 31, 0, 31, 29, 0, 31, 0, 0, 9, 31, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0, 0, 0, 31 };
static const unsigned char blood2_char_058[30] = { 0, 31, 0, 28, 31, 0, 31, 0, 0, 5, 31, 0, 31, 31, 0, 29, 7, 0, 31, 2, 0, 31, 0, 0, 0, 31, 0, 0, 0, 31 };
static const unsigned char blood2_char_059[30] = { 18, 31, 2, 6, 29, 6, 31, 0, 0, 17, 31, 0, 31, 15, 0, 16, 31, 0, 30, 7, 0, 31, 0, 0, 0, 31, 0, 0, 0, 31 };
static const unsigned char blood2_char_060[30] = { 0, 31, 0, 0, 31, 0, 31, 0, 0, 22, 31, 0, 2, 31, 0, 0, 31, 0, 16, 31, 0, 31, 0, 0, 6, 31, 6, 0, 0, 31 };
static const unsigned char blood2_char_061[30] = { 0, 31, 0, 13, 31, 0, 31, 0, 0, 1, 31, 0, 12, 27, 0, 2, 31, 0, 8, 31, 0, 31, 5, 0, 15, 30, 15, 0, 0, 31 };
static const unsigned char blood2_char_062[30] = { 3, 31, 0, 7, 28, 0, 31, 0, 0, 0, 31, 0, 14, 31, 0, 10, 31, 0, 10, 31, 0, 31, 23, 0, 27, 4, 31, 0, 0, 31 };
static const unsigned char blood2_char_063[30] = { 31, 12, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0, 0, 31, 0, 31, 16, 0, 31, 7, 0, 31, 31, 0, 2, 29, 31, 0, 0, 31 };
static const unsigned char blood2_char_064[30] = { 31, 12, 0, 31, 0, 0, 31, 0, 0, 0, 31, 0, 0, 31, 0, 31, 0, 0, 31, 0, 0, 31, 31, 0, 0, 31, 31, 0, 0, 31 };
static const unsigned char blood2_char_065[30] = { 31, 0, 0, 31, 0, 0, 31, 1, 0, 0, 31, 0, 1, 31, 0, 31, 0, 0, 31, 0, 0, 29, 31, 0, 2, 29, 31, 0, 0, 31 };
static const unsigned char blood2_char_066[30] = { 31, 0, 0, 31, 0, 0, 31, 24, 0, 0, 31, 0, 28, 31, 0, 31, 0, 0, 31, 0, 0, 15, 31, 0, 24, 7, 31, 0, 0, 31 };
static const unsigned char blood2_char_067[30] = { 31, 0, 0, 31, 0, 0, 31, 7, 0, 0, 31, 0, 31, 31, 0, 31, 0, 0, 31, 0, 0, 7, 31, 0, 0, 31, 31, 0, 0, 31 };

const unsigned char * const blood2_charset[68] = {
    blood2_char_000,
    blood2_char_001,
    blood2_char_002,
    blood2_char_003,
    blood2_char_004,
    blood2_char_005,
    blood2_char_006,
    blood2_char_007,
    blood2_char_008,
    blood2_char_009,
    blood2_char_010,
    blood2_char_011,
    blood2_char_012,
    blood2_char_013,
    blood2_char_014,
    blood2_char_015,
    blood2_char_016,
    blood2_char_017,
    blood2_char_018,
    blood2_char_019,
    blood2_char_020,
    blood2_char_021,
    blood2_char_022,
    blood2_char_023,
    blood2_char_024,
    blood2_char_025,
    blood2_char_026,
    blood2_char_027,
    blood2_char_028,
    blood2_char_029,
    blood2_char_030,
    blood2_char_031,
    blood2_char_032,
    blood2_char_033,
    blood2_char_034,
    blood2_char_035,
    blood2_char_036,
    blood2_char_037,
    blood2_char_038,
    blood2_char_039,
    blood2_char_040,
    blood2_char_041,
    blood2_char_042,
    blood2_char_043,
    blood2_char_044,
    blood2_char_045,
    blood2_char_046,
    blood2_char_047,
    blood2_char_048,
    blood2_char_049,
    blood2_char_050,
    blood2_char_051,
    blood2_char_052,
    blood2_char_053,
    blood2_char_054,
    blood2_char_055,
    blood2_char_056,
    blood2_char_057,
    blood2_char_058,
    blood2_char_059,
    blood2_char_060,
    blood2_char_061,
    blood2_char_062,
    blood2_char_063,
    blood2_char_064,
    blood2_char_065,
    blood2_char_066,
    blood2_char_067,
};

const unsigned char blood2_map[122] = {
    30, 4,
    8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 8, 9, 10, 11, 12, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
    23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 1, 36, 23, 24, 25, 26, 27, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
    37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 37, 38, 39, 40, 52, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
    53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 53, 54, 55, 56, 57, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
};

