/* Auto-generated by img2tiles.py from "bloodworld.png" */
/* Adaptive palette: 8 colours built from 3 EM-optimised primaries (NTSC-snapped). */
/* Index bits: bit0=P1, bit1=P2, bit2=P3 (P1/P2/P3 = single-bit primaries). */
/* Character: 5 pixels wide x 10 trixels deep (30 scanlines). */
/* Trixel: 1 pixel wide x 3 scanlines deep, 3-bit palette index. */
/* Character storage: 10 trixel-rows x 3 bytes (bit0-plane, bit1-plane, bit2-plane) = 30 bytes. */
/* Byte bit layout: bit4=col0(left) .. bit0=col4(right), bits7-5 unused. */
/* Map: byte0=width(chars, +10 wrap buffer), byte1=height(chars), then row-major indices. */

static const unsigned char bloodworld_palette[8][3] = {
    {   0,   0,   0 },  /* 0: origin */
    {  68,  40,   0 },  /* 1: +P1 */
    { 100,  72,  24 },  /* 2: +P2 */
    {  84,  56,  12 },  /* 3: +P1+P2 */
    { 144, 144, 144 },  /* 4: +P3 */
    { 106,  92,  72 },  /* 5: +P1+P3 */
    { 122, 108,  84 },  /* 6: +P2+P3 */
    { 104,  85,  56 },  /* 7: +P1+P2+P3 */
};

/* NTSC Atari 2600 companion palette: nearest TIA register values for
 * palette primaries (indices 1, 2, 4 — the single-bit entries). */
const unsigned char bloodworld_ntsc_palette[3] = {
    0xF0,  /* palette[1] = (68,40,0) */
    0xF2,  /* palette[2] = (100,72,24) */
    0x06,  /* palette[4] = (144,144,144) */
};

static const unsigned char bloodworld_char_000[30] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static const unsigned char bloodworld_char_001[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_002[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char bloodworld_char_003[30] = { 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0 };
static const unsigned char bloodworld_char_004[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char bloodworld_char_005[30] = { 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31 };
static const unsigned char bloodworld_char_006[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char bloodworld_char_007[30] = { 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31 };
static const unsigned char bloodworld_char_008[30] = { 0, 0, 31, 0, 0, 31, 31, 31, 31, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_009[30] = { 31, 0, 0, 31, 0, 0, 7, 28, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 8, 15, 24, 8, 31, 24, 0, 31, 0, 0, 31, 0 };
static const unsigned char bloodworld_char_010[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 15, 30, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char bloodworld_char_011[30] = { 31, 0, 0, 31, 0, 0, 27, 14, 0, 16, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char bloodworld_char_012[30] = { 31, 0, 0, 30, 3, 0, 30, 3, 0, 28, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char bloodworld_char_013[30] = { 31, 0, 0, 31, 24, 0, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char bloodworld_char_014[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 29, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char bloodworld_char_015[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 28, 7, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 2, 31, 3, 3, 30, 3, 1, 31, 1 };
static const unsigned char bloodworld_char_016[30] = { 31, 0, 0, 31, 0, 0, 12, 31, 0, 0, 31, 0, 1, 31, 1, 4, 28, 7, 24, 16, 31, 1, 26, 31, 18, 15, 30, 28, 31, 28 };
static const unsigned char bloodworld_char_017[30] = { 31, 0, 0, 27, 12, 0, 3, 30, 0, 1, 31, 0, 8, 23, 24, 4, 15, 24, 0, 15, 24, 4, 31, 28, 8, 31, 8, 0, 31, 0 };
static const unsigned char bloodworld_char_018[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 23, 28, 0, 3, 30, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char bloodworld_char_019[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 7, 0, 16, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char bloodworld_char_020[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 28, 0, 3, 30, 0, 1, 31, 0, 0, 31, 0, 12, 31, 12, 1, 18, 31, 0, 16, 31 };
static const unsigned char bloodworld_char_021[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 30, 3, 0, 24, 15, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 31, 16, 8, 7, 24 };
static const unsigned char bloodworld_char_022[30] = { 31, 0, 0, 31, 3, 0, 16, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 3, 31, 3, 15, 26, 15, 9, 31, 9, 0, 31, 0 };
static const unsigned char bloodworld_char_023[30] = { 31, 0, 0, 31, 0, 0, 7, 31, 0, 0, 31, 0, 0, 31, 0, 16, 31, 16, 12, 22, 31, 0, 12, 31, 1, 25, 31, 8, 23, 12 };
static const unsigned char bloodworld_char_024[30] = { 0, 31, 0, 0, 31, 0, 7, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_025[30] = { 0, 31, 0, 0, 31, 0, 28, 15, 0, 28, 3, 0, 28, 3, 0, 28, 7, 0, 29, 7, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_026[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 24, 7, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_027[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 31, 0, 3, 30, 0, 3, 30, 0, 15, 28, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_028[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 15, 31, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_029[30] = { 4, 31, 0, 14, 19, 0, 15, 17, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_030[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 15, 0, 25, 7, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_031[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31, 30, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_032[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 24, 15, 0, 28, 7, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_033[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 25, 15, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_034[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 31, 0, 7, 28, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_035[30] = { 16, 1, 31, 28, 31, 28, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31, 3, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_036[30] = { 12, 23, 24, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 31, 0, 7, 28, 0, 7, 24, 0, 31, 8, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_037[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 15, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_038[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char bloodworld_char_039[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 0, 31, 31, 31, 0, 0, 31, 0, 0, 31 };

const unsigned char * const bloodworld_charset[40] = {
    bloodworld_char_000,
    bloodworld_char_001,
    bloodworld_char_002,
    bloodworld_char_003,
    bloodworld_char_004,
    bloodworld_char_005,
    bloodworld_char_006,
    bloodworld_char_007,
    bloodworld_char_008,
    bloodworld_char_009,
    bloodworld_char_010,
    bloodworld_char_011,
    bloodworld_char_012,
    bloodworld_char_013,
    bloodworld_char_014,
    bloodworld_char_015,
    bloodworld_char_016,
    bloodworld_char_017,
    bloodworld_char_018,
    bloodworld_char_019,
    bloodworld_char_020,
    bloodworld_char_021,
    bloodworld_char_022,
    bloodworld_char_023,
    bloodworld_char_024,
    bloodworld_char_025,
    bloodworld_char_026,
    bloodworld_char_027,
    bloodworld_char_028,
    bloodworld_char_029,
    bloodworld_char_030,
    bloodworld_char_031,
    bloodworld_char_032,
    bloodworld_char_033,
    bloodworld_char_034,
    bloodworld_char_035,
    bloodworld_char_036,
    bloodworld_char_037,
    bloodworld_char_038,
    bloodworld_char_039,
};

const unsigned char bloodworld_map[122] = {
    30, 4,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
    9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 9, 10, 11, 12, 13, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
    24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 24, 25, 26, 27, 28, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
    39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
};

