/* Auto-generated by img2tiles.py from "deathstar.png" */
/* Adaptive palette: 8 colours built from 3 EM-optimised primaries (NTSC-snapped). */
/* Index bits: bit0=P1, bit1=P2, bit2=P3 (P1/P2/P3 = single-bit primaries). */
/* Character: 5 pixels wide x 10 trixels deep (30 scanlines). */
/* Trixel: 1 pixel wide x 3 scanlines deep, 3-bit palette index. */
/* Character storage: 10 trixel-rows x 3 bytes (bit0-plane, bit1-plane, bit2-plane) = 30 bytes. */
/* Byte bit layout: bit4=col0(left) .. bit0=col4(right), bits7-5 unused. */
/* Map: byte0=width(chars, +10 wrap buffer), byte1=height(chars), then row-major indices. */

static const unsigned char deathstar_palette[8][3] = {
    {   0,   0,   0 },  /* 0: origin */
    { 108, 108, 108 },  /* 1: +P1 */
    { 132, 140,  76 },  /* 2: +P2 */
    { 120, 124,  92 },  /* 3: +P1+P2 */
    { 144, 144, 144 },  /* 4: +P3 */
    { 126, 126, 126 },  /* 5: +P1+P3 */
    { 138, 142, 110 },  /* 6: +P2+P3 */
    { 128, 131, 109 },  /* 7: +P1+P2+P3 */
};

/* NTSC Atari 2600 companion palette: nearest TIA register values for
 * palette primaries (indices 1, 2, 4 — the single-bit entries). */
const unsigned char deathstar_ntsc_palette[3] = {
    0x04,  /* palette[1] = (108,108,108) */
    0xE6,  /* palette[2] = (132,140,76) */
    0x06,  /* palette[4] = (144,144,144) */
};

static const unsigned char deathstar_char_000[30] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static const unsigned char deathstar_char_001[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_002[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char deathstar_char_003[30] = { 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0 };
static const unsigned char deathstar_char_004[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char deathstar_char_005[30] = { 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31 };
static const unsigned char deathstar_char_006[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char deathstar_char_007[30] = { 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31 };
static const unsigned char deathstar_char_008[30] = { 31, 0, 0, 31, 0, 0, 20, 0, 15, 16, 0, 15, 23, 0, 15, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 8, 31, 0, 4 };
static const unsigned char deathstar_char_009[30] = { 31, 0, 0, 31, 0, 0, 16, 0, 31, 1, 0, 31, 27, 0, 31, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0, 11 };
static const unsigned char deathstar_char_010[30] = { 31, 0, 0, 31, 0, 0, 4, 0, 31, 18, 0, 31, 31, 0, 13, 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 14 };
static const unsigned char deathstar_char_011[30] = { 31, 0, 0, 31, 0, 0, 24, 0, 31, 2, 0, 31, 20, 0, 31, 30, 0, 3, 31, 0, 0, 31, 0, 8, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_012[30] = { 31, 0, 0, 31, 0, 1, 8, 0, 31, 8, 0, 31, 15, 0, 31, 31, 0, 17, 31, 0, 0, 31, 0, 2, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_013[30] = { 31, 0, 0, 31, 0, 0, 18, 0, 31, 0, 0, 31, 25, 0, 31, 31, 0, 0, 31, 0, 4, 31, 0, 4, 31, 0, 4, 31, 0, 7 };
static const unsigned char deathstar_char_014[30] = { 31, 0, 0, 31, 0, 0, 20, 0, 31, 0, 0, 31, 11, 0, 31, 31, 0, 26, 31, 0, 26, 31, 0, 30, 31, 0, 30, 31, 0, 26 };
static const unsigned char deathstar_char_015[30] = { 31, 0, 0, 31, 0, 0, 16, 0, 31, 21, 0, 31, 15, 0, 31, 31, 0, 0, 31, 0, 0, 31, 0, 4, 31, 0, 4, 31, 0, 4 };
static const unsigned char deathstar_char_016[30] = { 31, 0, 0, 31, 0, 0, 10, 0, 31, 16, 0, 31, 23, 0, 31, 31, 0, 17, 31, 0, 3, 31, 0, 11, 31, 0, 11, 30, 0, 3 };
static const unsigned char deathstar_char_017[30] = { 31, 0, 0, 31, 0, 0, 8, 0, 31, 4, 0, 31, 15, 0, 31, 31, 0, 12, 31, 0, 12, 31, 0, 12, 31, 0, 12, 31, 0, 12 };
static const unsigned char deathstar_char_018[30] = { 31, 0, 0, 31, 0, 0, 0, 0, 31, 16, 0, 31, 15, 0, 31, 31, 0, 24, 31, 0, 26, 31, 0, 26, 31, 0, 26, 31, 0, 26 };
static const unsigned char deathstar_char_019[30] = { 31, 0, 0, 31, 0, 0, 17, 0, 31, 0, 0, 31, 30, 0, 31, 31, 0, 1, 31, 0, 16, 31, 0, 0, 31, 0, 1, 31, 0, 17 };
static const unsigned char deathstar_char_020[30] = { 31, 0, 0, 31, 0, 0, 0, 0, 31, 0, 0, 31, 27, 0, 31, 31, 0, 6, 27, 0, 14, 27, 0, 14, 31, 0, 4, 31, 0, 6 };
static const unsigned char deathstar_char_021[30] = { 31, 0, 0, 31, 0, 0, 4, 0, 31, 0, 0, 31, 30, 0, 31, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1 };
static const unsigned char deathstar_char_022[30] = { 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0, 19, 30, 0, 19, 31, 0, 27, 31, 0, 2, 31, 0, 10 };
static const unsigned char deathstar_char_023[30] = { 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 0, 31, 0, 31, 31, 0, 0, 31, 0, 2 };
static const unsigned char deathstar_char_024[30] = { 31, 0, 5, 31, 0, 0, 31, 0, 3, 31, 0, 7, 31, 0, 6, 31, 0, 7, 30, 0, 7, 27, 0, 15, 31, 0, 5, 31, 0, 7 };
static const unsigned char deathstar_char_025[30] = { 15, 0, 24, 15, 0, 24, 31, 0, 6, 31, 0, 7, 31, 0, 17, 31, 0, 20, 15, 0, 24, 31, 0, 28, 31, 0, 16, 31, 0, 24 };
static const unsigned char deathstar_char_026[30] = { 31, 0, 8, 31, 0, 0, 31, 0, 26, 28, 0, 27, 12, 0, 27, 30, 0, 31, 31, 0, 29, 31, 0, 1, 31, 0, 7, 31, 0, 15 };
static const unsigned char deathstar_char_027[30] = { 31, 0, 28, 31, 0, 12, 31, 0, 12, 31, 0, 12, 31, 0, 12, 31, 0, 13, 31, 0, 13, 31, 0, 31, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_028[30] = { 31, 0, 26, 31, 0, 24, 31, 0, 26, 31, 0, 24, 31, 0, 24, 31, 0, 24, 31, 0, 24, 31, 0, 31, 31, 0, 20, 31, 0, 20 };
static const unsigned char deathstar_char_029[30] = { 31, 0, 17, 31, 0, 0, 31, 0, 17, 31, 0, 1, 31, 0, 1, 31, 0, 16, 31, 0, 0, 31, 0, 27, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_030[30] = { 31, 0, 18, 31, 0, 16, 31, 0, 16, 31, 0, 18, 31, 0, 16, 31, 0, 22, 31, 0, 20, 31, 0, 31, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_031[30] = { 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 17, 31, 0, 17, 31, 0, 31, 31, 0, 1, 31, 0, 1 };
static const unsigned char deathstar_char_032[30] = { 31, 0, 20, 31, 0, 20, 31, 0, 20, 31, 0, 20, 31, 0, 20, 31, 0, 20, 31, 0, 20, 31, 0, 31, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_033[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 4, 31, 0, 1, 31, 0, 0, 31, 0, 0, 31, 0, 4, 31, 0, 30, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_034[30] = { 31, 0, 4, 31, 0, 0, 31, 0, 15, 31, 0, 11, 31, 0, 3, 31, 0, 3, 31, 0, 11, 31, 0, 10, 21, 0, 15, 31, 0, 15 };
static const unsigned char deathstar_char_035[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 31, 31, 0, 10, 31, 0, 10, 31, 0, 10, 31, 0, 18, 31, 0, 18, 13, 0, 31, 31, 0, 14 };
static const unsigned char deathstar_char_036[30] = { 31, 0, 2, 31, 0, 2, 29, 0, 31, 31, 0, 2, 31, 0, 2, 31, 0, 2, 31, 0, 2, 31, 0, 2, 27, 0, 30, 31, 0, 31 };
static const unsigned char deathstar_char_037[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 31, 31, 0, 6, 31, 0, 6, 31, 0, 0, 31, 0, 2, 31, 0, 2, 29, 0, 31, 31, 0, 29 };
static const unsigned char deathstar_char_038[30] = { 31, 0, 1, 31, 0, 0, 31, 0, 27, 31, 0, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 2, 29, 0, 31, 31, 0, 29 };
static const unsigned char deathstar_char_039[30] = { 31, 0, 1, 31, 0, 1, 31, 0, 31, 31, 0, 14, 31, 0, 9, 31, 0, 25, 23, 0, 12, 31, 0, 8, 23, 0, 31, 31, 0, 31 };
static const unsigned char deathstar_char_040[30] = { 31, 0, 26, 31, 0, 30, 27, 0, 30, 19, 0, 30, 23, 0, 31, 31, 0, 27, 31, 0, 25, 31, 0, 1, 30, 0, 31, 31, 0, 28 };
static const unsigned char deathstar_char_041[30] = { 22, 0, 15, 31, 0, 31, 31, 0, 13, 31, 0, 9, 31, 0, 0, 29, 0, 6, 31, 0, 14, 31, 0, 16, 31, 0, 31, 31, 0, 31 };
static const unsigned char deathstar_char_042[30] = { 31, 0, 20, 31, 0, 0, 31, 0, 31, 31, 0, 4, 31, 0, 0, 31, 0, 8, 31, 0, 0, 31, 0, 0, 27, 0, 31, 31, 0, 30 };
static const unsigned char deathstar_char_043[30] = { 31, 0, 4, 31, 0, 0, 31, 0, 31, 31, 0, 5, 31, 0, 5, 31, 0, 12, 31, 0, 12, 31, 0, 4, 27, 0, 31, 31, 0, 31 };
static const unsigned char deathstar_char_044[30] = { 31, 0, 0, 31, 0, 4, 31, 0, 23, 31, 0, 16, 31, 0, 0, 31, 0, 16, 31, 0, 0, 31, 0, 16, 15, 0, 31, 31, 0, 15 };
static const unsigned char deathstar_char_045[30] = { 31, 0, 16, 31, 0, 16, 31, 0, 29, 31, 0, 16, 31, 0, 17, 31, 0, 16, 31, 0, 16, 31, 0, 16, 15, 0, 31, 31, 0, 19 };
static const unsigned char deathstar_char_046[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 31, 29, 0, 2, 31, 0, 3, 31, 0, 2, 31, 0, 23, 31, 0, 2, 28, 0, 31, 31, 0, 29 };
static const unsigned char deathstar_char_047[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 30, 31, 0, 18, 31, 0, 18, 31, 0, 18, 31, 0, 18, 31, 0, 2, 15, 0, 31, 31, 0, 29 };
static const unsigned char deathstar_char_048[30] = { 31, 0, 17, 31, 0, 1, 31, 0, 31, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 30, 0, 31, 31, 0, 23 };
static const unsigned char deathstar_char_049[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 29, 31, 0, 3, 31, 0, 3, 31, 0, 17, 31, 0, 1, 31, 0, 0, 31, 0, 31, 31, 0, 23 };
static const unsigned char deathstar_char_050[30] = { 31, 0, 0, 16, 0, 15, 31, 0, 8, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 12 };
static const unsigned char deathstar_char_051[30] = { 31, 0, 0, 0, 0, 31, 31, 0, 24, 31, 0, 8, 31, 0, 8, 31, 0, 24, 23, 0, 24, 23, 0, 8, 23, 0, 8, 23, 0, 29 };
static const unsigned char deathstar_char_052[30] = { 31, 0, 0, 1, 0, 31, 31, 0, 12, 31, 0, 0, 31, 0, 8, 31, 0, 0, 31, 0, 12, 31, 0, 8, 31, 0, 13, 31, 0, 15 };
static const unsigned char deathstar_char_053[30] = { 31, 0, 0, 16, 0, 31, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 31, 0, 16, 15, 0, 26, 31, 0, 19 };
static const unsigned char deathstar_char_054[30] = { 31, 0, 0, 0, 0, 31, 31, 0, 3, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 3, 31, 0, 1, 30, 0, 3, 30, 0, 3 };
static const unsigned char deathstar_char_055[30] = { 31, 0, 0, 17, 0, 31, 31, 0, 6, 31, 0, 4, 31, 0, 4, 31, 0, 4, 31, 0, 4, 27, 0, 4, 31, 0, 4, 31, 0, 31 };
static const unsigned char deathstar_char_056[30] = { 31, 0, 0, 19, 0, 31, 31, 0, 18, 31, 0, 18, 31, 0, 0, 31, 0, 16, 31, 0, 19, 31, 0, 18, 31, 0, 19, 31, 0, 31 };
static const unsigned char deathstar_char_057[30] = { 31, 0, 0, 0, 0, 31, 31, 0, 6, 31, 0, 4, 31, 0, 4, 31, 0, 6, 31, 0, 6, 31, 0, 6, 31, 0, 6, 31, 0, 23 };
static const unsigned char deathstar_char_058[30] = { 31, 0, 0, 0, 0, 31, 31, 0, 26, 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 9 };
static const unsigned char deathstar_char_059[30] = { 31, 0, 0, 4, 0, 31, 31, 0, 27, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 29, 0, 2, 29, 0, 2 };
static const unsigned char deathstar_char_060[30] = { 31, 0, 0, 0, 0, 31, 31, 0, 11, 31, 0, 0, 31, 0, 0, 31, 0, 2, 31, 0, 2, 31, 0, 4, 27, 0, 12, 31, 0, 28 };
static const unsigned char deathstar_char_061[30] = { 31, 0, 0, 16, 0, 31, 23, 0, 24, 31, 0, 8, 31, 0, 8, 23, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 8, 23, 0, 15 };
static const unsigned char deathstar_char_062[30] = { 31, 0, 0, 16, 0, 31, 31, 0, 26, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 10, 31, 0, 0, 31, 0, 0, 31, 0, 10 };
static const unsigned char deathstar_char_063[30] = { 31, 0, 0, 0, 0, 31, 31, 0, 22, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 4, 31, 0, 4, 31, 0, 4, 31, 0, 21 };
static const unsigned char deathstar_char_064[30] = { 31, 0, 0, 0, 0, 31, 31, 0, 28, 31, 0, 0, 31, 0, 0, 31, 0, 4, 31, 0, 12, 31, 0, 8, 23, 0, 24, 31, 0, 29 };
static const unsigned char deathstar_char_065[30] = { 31, 0, 4, 31, 0, 4, 31, 0, 4, 31, 0, 29, 31, 0, 4, 31, 0, 0, 31, 0, 4, 31, 0, 0, 31, 0, 4, 31, 0, 5 };
static const unsigned char deathstar_char_066[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 25, 31, 0, 17, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 17, 31, 0, 31 };
static const unsigned char deathstar_char_067[30] = { 31, 0, 16, 31, 0, 0, 31, 0, 0, 31, 0, 26, 31, 0, 12, 31, 0, 8, 31, 0, 8, 31, 0, 0, 31, 0, 0, 31, 0, 15 };
static const unsigned char deathstar_char_068[30] = { 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 22, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 31, 0, 16, 31, 0, 27 };
static const unsigned char deathstar_char_069[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0, 2, 31, 0, 0, 31, 0, 0, 31, 0, 31 };
static const unsigned char deathstar_char_070[30] = { 31, 0, 16, 31, 0, 0, 31, 0, 17, 31, 0, 22, 31, 0, 2, 31, 0, 0, 31, 0, 0, 31, 0, 2, 31, 0, 2, 31, 0, 31 };
static const unsigned char deathstar_char_071[30] = { 31, 0, 6, 31, 0, 4, 31, 0, 6, 31, 0, 22, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 0, 31, 0, 16, 31, 0, 23 };
static const unsigned char deathstar_char_072[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 8, 31, 0, 4, 31, 0, 0, 31, 0, 8, 31, 0, 4, 31, 0, 4, 31, 0, 31 };
static const unsigned char deathstar_char_073[30] = { 31, 0, 16, 31, 0, 0, 31, 0, 0, 31, 0, 30, 31, 0, 10, 31, 0, 8, 31, 0, 10, 31, 0, 0, 31, 0, 1, 31, 0, 31 };
static const unsigned char deathstar_char_074[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 2, 31, 0, 2, 31, 0, 2, 31, 0, 2, 31, 0, 10 };
static const unsigned char deathstar_char_075[30] = { 31, 0, 6, 31, 0, 4, 31, 0, 4, 31, 0, 6, 31, 0, 0, 31, 0, 0, 31, 0, 4, 31, 0, 4, 31, 0, 4, 31, 0, 30 };
static const unsigned char deathstar_char_076[30] = { 31, 0, 8, 31, 0, 0, 31, 0, 4, 31, 0, 5, 31, 0, 20, 31, 0, 4, 31, 0, 4, 31, 0, 0, 31, 0, 0, 31, 0, 21 };
static const unsigned char deathstar_char_077[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 8, 18, 0, 15, 20, 0, 15, 21, 0, 15, 16, 0, 15, 30, 0, 15, 31, 0, 1 };
static const unsigned char deathstar_char_078[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 26, 0, 31, 0, 0, 31, 16, 0, 31, 0, 0, 31, 29, 0, 31, 31, 0, 0 };
static const unsigned char deathstar_char_079[30] = { 31, 0, 10, 31, 0, 0, 31, 0, 8, 31, 0, 8, 29, 0, 31, 0, 0, 31, 3, 0, 31, 0, 0, 31, 22, 0, 31, 31, 0, 1 };
static const unsigned char deathstar_char_080[30] = { 31, 0, 2, 31, 0, 0, 31, 0, 2, 31, 0, 2, 15, 0, 31, 18, 0, 31, 0, 0, 31, 0, 0, 31, 29, 0, 31, 31, 0, 0 };
static const unsigned char deathstar_char_081[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31, 0, 0, 31, 12, 0, 31, 8, 0, 31, 22, 0, 31, 31, 0, 12 };
static const unsigned char deathstar_char_082[30] = { 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 12, 18, 0, 31, 0, 0, 31, 0, 0, 31, 28, 0, 31, 23, 0, 31, 31, 0, 8 };
static const unsigned char deathstar_char_083[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 8, 27, 0, 31, 16, 0, 31, 14, 0, 31, 9, 0, 31, 31, 0, 31, 31, 0, 0 };
static const unsigned char deathstar_char_084[30] = { 31, 0, 1, 31, 0, 1, 31, 0, 3, 31, 0, 3, 13, 0, 31, 18, 0, 31, 7, 0, 31, 1, 0, 31, 19, 0, 31, 31, 0, 8 };
static const unsigned char deathstar_char_085[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 3, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 31, 31, 0, 31, 31, 0, 0 };
static const unsigned char deathstar_char_086[30] = { 31, 0, 1, 31, 0, 0, 31, 0, 1, 31, 0, 1, 22, 0, 31, 2, 0, 31, 8, 0, 31, 0, 0, 31, 22, 0, 31, 31, 0, 0 };
static const unsigned char deathstar_char_087[30] = { 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16, 15, 0, 31, 0, 0, 31, 12, 0, 31, 4, 0, 31, 31, 0, 31, 31, 0, 0 };
static const unsigned char deathstar_char_088[30] = { 31, 0, 2, 31, 0, 0, 31, 0, 2, 31, 0, 2, 13, 0, 31, 0, 0, 31, 19, 0, 31, 0, 0, 31, 30, 0, 31, 31, 0, 0 };
static const unsigned char deathstar_char_089[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 25, 0, 31, 1, 0, 31, 12, 0, 31, 17, 0, 31, 31, 0, 31, 31, 0, 1 };
static const unsigned char deathstar_char_090[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 4, 31, 0, 4, 15, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 31, 27, 0, 31, 31, 0, 4 };
static const unsigned char deathstar_char_091[30] = { 31, 0, 3, 31, 0, 2, 31, 0, 3, 31, 0, 3, 5, 0, 31, 12, 0, 31, 3, 0, 31, 1, 0, 31, 23, 0, 31, 31, 0, 12 };
static const unsigned char deathstar_char_092[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 28, 0, 31, 1, 0, 31, 25, 0, 31, 4, 0, 31, 30, 0, 31, 31, 0, 1 };
static const unsigned char deathstar_char_093[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 8, 29, 0, 31, 0, 0, 31, 12, 0, 31, 0, 0, 31, 31, 0, 31, 31, 0, 0 };
static const unsigned char deathstar_char_094[30] = { 31, 0, 2, 31, 0, 0, 31, 0, 0, 31, 0, 0, 5, 0, 31, 0, 0, 31, 1, 0, 31, 4, 0, 31, 27, 0, 31, 31, 0, 12 };
static const unsigned char deathstar_char_095[30] = { 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 8, 7, 0, 31, 4, 0, 31, 19, 0, 31, 0, 0, 31, 15, 0, 31, 31, 0, 4 };
static const unsigned char deathstar_char_096[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 15, 0, 31, 4, 0, 31, 0, 0, 31, 0, 0, 31, 30, 0, 31, 31, 0, 0 };
static const unsigned char deathstar_char_097[30] = { 23, 0, 8, 23, 0, 8, 31, 0, 9, 31, 0, 8, 31, 0, 8, 23, 0, 8, 31, 0, 8, 23, 0, 8, 31, 0, 8, 31, 0, 8 };
static const unsigned char deathstar_char_098[30] = { 27, 0, 6, 31, 0, 4, 27, 0, 4, 31, 0, 6, 31, 0, 4, 27, 0, 6, 27, 0, 4, 27, 0, 4, 27, 0, 4, 31, 0, 12 };
static const unsigned char deathstar_char_099[30] = { 31, 0, 8, 31, 0, 8, 23, 0, 8, 31, 0, 8, 31, 0, 8, 23, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 8, 23, 0, 8 };
static const unsigned char deathstar_char_100[30] = { 31, 0, 12, 31, 0, 12, 31, 0, 8, 31, 0, 12, 31, 0, 12, 31, 0, 12, 31, 0, 8, 31, 0, 8, 23, 0, 8, 23, 0, 8 };
static const unsigned char deathstar_char_101[30] = { 27, 0, 4, 31, 0, 4, 31, 0, 4, 27, 0, 4, 27, 0, 4, 27, 0, 4, 31, 0, 4, 27, 0, 4, 27, 0, 4, 27, 0, 12 };
static const unsigned char deathstar_char_102[30] = { 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 9, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1 };
static const unsigned char deathstar_char_103[30] = { 31, 0, 24, 31, 0, 16, 31, 0, 16, 31, 0, 24, 31, 0, 16, 31, 0, 16, 31, 0, 20, 31, 0, 29, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_104[30] = { 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 8, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31 };
static const unsigned char deathstar_char_105[30] = { 27, 0, 4, 31, 0, 4, 31, 0, 4, 31, 0, 4, 31, 0, 4, 27, 0, 4, 27, 0, 4, 31, 0, 4, 31, 0, 4, 31, 0, 4 };
static const unsigned char deathstar_char_106[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 11, 31, 0, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 15 };
static const unsigned char deathstar_char_107[30] = { 31, 0, 0, 31, 0, 0, 12, 0, 31, 0, 0, 31, 11, 0, 31, 31, 0, 24, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16 };
static const unsigned char deathstar_char_108[30] = { 31, 0, 0, 31, 0, 0, 0, 0, 31, 0, 0, 31, 31, 0, 31, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 17 };
static const unsigned char deathstar_char_109[30] = { 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 8, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 11, 31, 0, 8, 31, 0, 0 };
static const unsigned char deathstar_char_110[30] = { 31, 0, 0, 31, 0, 16, 31, 0, 31, 31, 0, 0, 31, 0, 8, 31, 0, 0, 31, 0, 8, 31, 0, 0, 27, 0, 31, 31, 0, 27 };
static const unsigned char deathstar_char_111[30] = { 31, 0, 0, 0, 0, 31, 30, 0, 25, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 29 };
static const unsigned char deathstar_char_112[30] = { 31, 0, 0, 1, 0, 31, 31, 0, 22, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 31, 0, 25 };
static const unsigned char deathstar_char_113[30] = { 31, 0, 4, 31, 0, 0, 31, 0, 4, 31, 0, 13, 31, 0, 16, 31, 0, 0, 31, 0, 16, 31, 0, 0, 31, 0, 0, 31, 0, 23 };
static const unsigned char deathstar_char_114[30] = { 31, 0, 8, 31, 0, 8, 31, 0, 8, 31, 0, 12, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31 };
static const unsigned char deathstar_char_115[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 18, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 29 };
static const unsigned char deathstar_char_116[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 14, 0, 31, 4, 0, 31, 5, 0, 31, 0, 0, 31, 31, 0, 31, 31, 0, 16 };
static const unsigned char deathstar_char_117[30] = { 31, 0, 4, 31, 0, 0, 31, 0, 0, 31, 0, 4, 27, 0, 31, 0, 0, 31, 12, 0, 31, 0, 0, 31, 27, 0, 31, 31, 0, 16 };
static const unsigned char deathstar_char_118[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 25, 0, 31, 0, 0, 31, 3, 0, 31, 16, 0, 31, 31, 0, 31, 31, 0, 0 };
static const unsigned char deathstar_char_119[30] = { 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 17 };
static const unsigned char deathstar_char_120[30] = { 31, 0, 12, 31, 0, 4, 31, 0, 12, 31, 0, 12, 31, 0, 4, 31, 0, 12, 31, 0, 12, 31, 0, 12, 31, 0, 12, 31, 0, 12 };
static const unsigned char deathstar_char_121[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 30, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31, 31, 0, 23 };
static const unsigned char deathstar_char_122[30] = { 31, 0, 0, 31, 0, 0, 0, 0, 31, 16, 0, 31, 27, 0, 31, 31, 0, 22, 31, 0, 22, 31, 0, 6, 31, 0, 6, 31, 0, 7 };
static const unsigned char deathstar_char_123[30] = { 31, 0, 0, 31, 0, 0, 0, 0, 31, 0, 0, 31, 31, 0, 31, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_124[30] = { 31, 0, 22, 31, 0, 6, 31, 0, 6, 31, 0, 6, 31, 0, 6, 31, 0, 22, 31, 0, 22, 31, 0, 15, 31, 0, 0, 31, 0, 0 };
static const unsigned char deathstar_char_125[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 31, 31, 0, 4, 31, 0, 12, 31, 0, 0, 31, 0, 4, 31, 0, 0, 31, 0, 15, 31, 0, 31 };
static const unsigned char deathstar_char_126[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 31, 15, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 16, 15, 0, 31, 31, 0, 29 };
static const unsigned char deathstar_char_127[30] = { 31, 0, 0, 0, 0, 31, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 23 };

const unsigned char * const deathstar_charset[128] = {
    deathstar_char_000,
    deathstar_char_001,
    deathstar_char_002,
    deathstar_char_003,
    deathstar_char_004,
    deathstar_char_005,
    deathstar_char_006,
    deathstar_char_007,
    deathstar_char_008,
    deathstar_char_009,
    deathstar_char_010,
    deathstar_char_011,
    deathstar_char_012,
    deathstar_char_013,
    deathstar_char_014,
    deathstar_char_015,
    deathstar_char_016,
    deathstar_char_017,
    deathstar_char_018,
    deathstar_char_019,
    deathstar_char_020,
    deathstar_char_021,
    deathstar_char_022,
    deathstar_char_023,
    deathstar_char_024,
    deathstar_char_025,
    deathstar_char_026,
    deathstar_char_027,
    deathstar_char_028,
    deathstar_char_029,
    deathstar_char_030,
    deathstar_char_031,
    deathstar_char_032,
    deathstar_char_033,
    deathstar_char_034,
    deathstar_char_035,
    deathstar_char_036,
    deathstar_char_037,
    deathstar_char_038,
    deathstar_char_039,
    deathstar_char_040,
    deathstar_char_041,
    deathstar_char_042,
    deathstar_char_043,
    deathstar_char_044,
    deathstar_char_045,
    deathstar_char_046,
    deathstar_char_047,
    deathstar_char_048,
    deathstar_char_049,
    deathstar_char_050,
    deathstar_char_051,
    deathstar_char_052,
    deathstar_char_053,
    deathstar_char_054,
    deathstar_char_055,
    deathstar_char_056,
    deathstar_char_057,
    deathstar_char_058,
    deathstar_char_059,
    deathstar_char_060,
    deathstar_char_061,
    deathstar_char_062,
    deathstar_char_063,
    deathstar_char_064,
    deathstar_char_065,
    deathstar_char_066,
    deathstar_char_067,
    deathstar_char_068,
    deathstar_char_069,
    deathstar_char_070,
    deathstar_char_071,
    deathstar_char_072,
    deathstar_char_073,
    deathstar_char_074,
    deathstar_char_075,
    deathstar_char_076,
    deathstar_char_077,
    deathstar_char_078,
    deathstar_char_079,
    deathstar_char_080,
    deathstar_char_081,
    deathstar_char_082,
    deathstar_char_083,
    deathstar_char_084,
    deathstar_char_085,
    deathstar_char_086,
    deathstar_char_087,
    deathstar_char_088,
    deathstar_char_089,
    deathstar_char_090,
    deathstar_char_091,
    deathstar_char_092,
    deathstar_char_093,
    deathstar_char_094,
    deathstar_char_095,
    deathstar_char_096,
    deathstar_char_097,
    deathstar_char_098,
    deathstar_char_099,
    deathstar_char_100,
    deathstar_char_101,
    deathstar_char_102,
    deathstar_char_103,
    deathstar_char_104,
    deathstar_char_105,
    deathstar_char_106,
    deathstar_char_107,
    deathstar_char_108,
    deathstar_char_109,
    deathstar_char_110,
    deathstar_char_111,
    deathstar_char_112,
    deathstar_char_113,
    deathstar_char_114,
    deathstar_char_115,
    deathstar_char_116,
    deathstar_char_117,
    deathstar_char_118,
    deathstar_char_119,
    deathstar_char_120,
    deathstar_char_121,
    deathstar_char_122,
    deathstar_char_123,
    deathstar_char_124,
    deathstar_char_125,
    deathstar_char_126,
    deathstar_char_127,
};

const unsigned char deathstar_map[402] = {
    40, 10,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    8, 122, 107, 9, 10, 123, 11, 12, 13, 14, 123, 122, 108, 123, 123, 15, 16, 17, 123, 18, 123, 123, 123, 19, 20, 107, 21, 108, 123, 123, 8, 122, 107, 9, 10, 123, 11, 12, 13, 14,
    109, 124, 103, 22, 23, 1, 1, 1, 24, 25, 26, 124, 103, 1, 1, 1, 109, 27, 1, 28, 1, 1, 1, 29, 124, 30, 31, 32, 1, 33, 109, 124, 103, 22, 23, 1, 1, 1, 24, 25,
    34, 121, 35, 36, 37, 110, 121, 38, 39, 40, 41, 42, 125, 125, 121, 110, 126, 43, 44, 45, 126, 121, 121, 46, 121, 47, 48, 49, 121, 121, 34, 121, 35, 36, 37, 110, 121, 38, 39, 40,
    50, 51, 111, 112, 52, 53, 127, 127, 54, 127, 55, 127, 56, 127, 127, 127, 57, 127, 58, 59, 60, 112, 127, 127, 61, 111, 62, 63, 64, 127, 50, 51, 111, 112, 52, 53, 127, 127, 54, 127,
    106, 114, 65, 106, 66, 67, 114, 115, 104, 106, 68, 69, 70, 113, 115, 115, 71, 114, 115, 72, 73, 113, 104, 74, 106, 75, 106, 115, 76, 115, 106, 114, 65, 106, 66, 67, 114, 115, 104, 106,
    77, 116, 78, 79, 118, 80, 81, 82, 118, 83, 84, 85, 118, 117, 86, 87, 116, 118, 88, 118, 89, 90, 91, 92, 93, 94, 95, 96, 117, 118, 77, 116, 78, 79, 118, 80, 81, 82, 118, 83,
    102, 119, 1, 1, 1, 1, 120, 97, 1, 1, 120, 1, 1, 1, 1, 1, 119, 1, 1, 1, 1, 105, 120, 1, 1, 98, 1, 1, 1, 1, 102, 119, 1, 1, 1, 1, 120, 97, 1, 1,
    102, 119, 1, 1, 1, 1, 120, 99, 1, 1, 100, 1, 1, 1, 1, 1, 119, 1, 1, 1, 1, 105, 120, 1, 1, 101, 1, 1, 1, 1, 102, 119, 1, 1, 1, 1, 120, 99, 1, 1,
};

