/* Auto-generated by img2tiles.py from "deathstar.png" */
#pragma once

#define DEATHSTAR_CHARSET_SIZE 128
#define DEATHSTAR_MAP_SIZE     402
#define DEATHSTAR_CHAR_WIDTH   5
#define DEATHSTAR_CHAR_HEIGHT  10
#define DEATHSTAR_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char deathstar_ntsc_palette[3];

/* Charset: 128 characters, each 30 bytes */
extern const unsigned char * const deathstar_charset[128];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char deathstar_map[402];


