/* Auto-generated by img2tiles.py from "earth_clouds.jpg" */
/* Adaptive palette: 8 colours built from 3 EM-optimised primaries (NTSC-snapped). */
/* Index bits: bit0=P1, bit1=P2, bit2=P3 (P1/P2/P3 = single-bit primaries). */
/* Character: 5 pixels wide x 10 trixels deep (30 scanlines). */
/* Trixel: 1 pixel wide x 3 scanlines deep, 3-bit palette index. */
/* Character storage: 10 trixel-rows x 3 bytes (bit0-plane, bit1-plane, bit2-plane) = 30 bytes. */
/* Byte bit layout: bit4=col0(left) .. bit0=col4(right), bits7-5 unused. */
/* Map: byte0=width(chars, +10 wrap buffer), byte1=height(chars), then row-major indices. */

static const unsigned char earth_clouds_palette[8][3] = {
    {   0,   0,   0 },  /* 0: origin */
    {  28,  76, 120 },  /* 1: +P1 */
    { 116, 180, 148 },  /* 2: +P2 */
    {  72, 128, 134 },  /* 3: +P1+P2 */
    { 212, 188, 248 },  /* 4: +P3 */
    { 120, 132, 184 },  /* 5: +P1+P3 */
    { 164, 184, 198 },  /* 6: +P2+P3 */
    { 119, 148, 172 },  /* 7: +P1+P2+P3 */
};

/* NTSC Atari 2600 companion palette: nearest TIA register values for
 * palette primaries (indices 1, 2, 4 — the single-bit entries). */
const unsigned char earth_clouds_ntsc_palette[3] = {
    0xA2,  /* palette[1] = (28,76,120) */
    0xB8,  /* palette[2] = (116,180,148) */
    0x6E,  /* palette[4] = (212,188,248) */
};

static const unsigned char earth_clouds_char_000[30] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static const unsigned char earth_clouds_char_001[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_002[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char earth_clouds_char_003[30] = { 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0 };
static const unsigned char earth_clouds_char_004[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_005[30] = { 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31 };
static const unsigned char earth_clouds_char_006[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char earth_clouds_char_007[30] = { 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31 };
static const unsigned char earth_clouds_char_008[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 7, 31, 6, 7, 29, 3, 9, 28, 14, 31, 27, 23, 23, 28, 1, 3, 31 };
static const unsigned char earth_clouds_char_009[30] = { 0, 0, 31, 0, 0, 31, 2, 15, 31, 0, 26, 31, 16, 25, 31, 7, 7, 30, 28, 30, 19, 24, 24, 31, 17, 17, 15, 16, 30, 15 };
static const unsigned char earth_clouds_char_010[30] = { 0, 0, 31, 0, 0, 31, 0, 28, 31, 14, 30, 25, 29, 31, 1, 28, 31, 3, 8, 30, 31, 7, 23, 29, 16, 19, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_011[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 15, 31, 29, 31, 6, 24, 31, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_012[30] = { 0, 8, 31, 31, 31, 31, 19, 31, 22, 30, 31, 18, 19, 31, 30, 3, 7, 28, 3, 2, 30, 1, 1, 30, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_013[30] = { 0, 0, 31, 0, 0, 31, 16, 24, 31, 16, 24, 31, 16, 28, 31, 28, 28, 15, 16, 25, 15, 16, 24, 15, 16, 24, 15, 0, 8, 31 };
static const unsigned char earth_clouds_char_014[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 3, 7, 31, 31, 31, 31, 24, 28, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_015[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 4, 31, 28, 26, 19, 8, 28, 31, 0, 0, 31, 12, 30, 27, 28, 19, 3 };
static const unsigned char earth_clouds_char_016[30] = { 4, 12, 31, 4, 7, 31, 0, 2, 31, 0, 0, 31, 0, 1, 31, 0, 11, 31, 1, 23, 31, 2, 7, 29, 0, 4, 31, 2, 19, 29 };
static const unsigned char earth_clouds_char_017[30] = { 16, 22, 31, 0, 17, 31, 17, 17, 31, 17, 18, 14, 19, 20, 28, 7, 15, 28, 7, 7, 26, 7, 7, 25, 31, 31, 17, 31, 31, 0 };
static const unsigned char earth_clouds_char_018[30] = { 8, 8, 23, 0, 24, 31, 0, 16, 31, 24, 28, 31, 16, 16, 31, 26, 10, 15, 31, 1, 1, 31, 23, 1, 31, 31, 1, 31, 15, 1 };
static const unsigned char earth_clouds_char_019[30] = { 0, 8, 31, 0, 0, 31, 1, 3, 30, 7, 6, 28, 7, 20, 24, 7, 4, 28, 15, 12, 28, 7, 12, 28, 7, 28, 24, 31, 24, 24 };
static const unsigned char earth_clouds_char_020[30] = { 6, 6, 25, 7, 5, 25, 31, 27, 9, 30, 3, 3, 30, 7, 3, 31, 7, 3, 29, 23, 3, 29, 31, 15, 24, 13, 7, 28, 5, 3 };
static const unsigned char earth_clouds_char_021[30] = { 1, 1, 31, 0, 27, 31, 0, 30, 31, 16, 22, 31, 0, 23, 31, 0, 19, 31, 0, 11, 31, 15, 15, 27, 13, 31, 23, 25, 31, 7 };
static const unsigned char earth_clouds_char_022[30] = { 0, 23, 31, 25, 31, 31, 10, 15, 31, 0, 10, 31, 0, 18, 31, 0, 1, 31, 4, 31, 31, 31, 31, 25, 31, 31, 0, 31, 31, 29 };
static const unsigned char earth_clouds_char_023[30] = { 1, 23, 31, 1, 19, 31, 3, 3, 30, 7, 15, 31, 30, 31, 31, 24, 31, 7, 8, 31, 31, 12, 31, 31, 29, 31, 15, 28, 31, 23 };
static const unsigned char earth_clouds_char_024[30] = { 28, 23, 3, 29, 31, 3, 28, 31, 7, 16, 30, 31, 0, 6, 31, 0, 28, 31, 0, 28, 31, 0, 28, 31, 24, 28, 31, 24, 29, 15 };
static const unsigned char earth_clouds_char_025[30] = { 0, 0, 31, 4, 13, 31, 4, 13, 31, 8, 31, 31, 8, 31, 23, 24, 31, 15, 16, 14, 15, 16, 31, 15, 19, 31, 31, 16, 23, 31 };
static const unsigned char earth_clouds_char_026[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 8, 28, 31, 31, 31, 21, 11, 31, 31, 0, 0, 31, 0, 31, 31, 16, 31, 7, 24, 29, 3 };
static const unsigned char earth_clouds_char_027[30] = { 3, 3, 31, 2, 7, 29, 6, 7, 27, 2, 23, 31, 19, 27, 28, 3, 31, 30, 0, 31, 31, 0, 31, 19, 0, 31, 11, 0, 31, 0 };
static const unsigned char earth_clouds_char_028[30] = { 0, 25, 31, 8, 28, 31, 24, 28, 31, 16, 24, 31, 16, 24, 31, 16, 21, 31, 17, 25, 31, 0, 27, 31, 15, 31, 31, 13, 31, 15 };
static const unsigned char earth_clouds_char_029[30] = { 17, 17, 30, 31, 30, 6, 11, 31, 30, 19, 23, 14, 19, 26, 12, 25, 27, 14, 25, 25, 31, 24, 29, 23, 5, 29, 23, 5, 15, 31 };
static const unsigned char earth_clouds_char_030[30] = { 19, 26, 28, 29, 31, 14, 28, 29, 23, 22, 30, 23, 28, 2, 1, 28, 30, 3, 30, 31, 22, 27, 30, 14, 21, 23, 13, 20, 23, 15 };
static const unsigned char earth_clouds_char_031[30] = { 31, 31, 10, 31, 31, 14, 31, 31, 31, 7, 15, 28, 7, 7, 29, 7, 7, 31, 7, 22, 28, 23, 28, 12, 19, 29, 12, 27, 11, 15 };
static const unsigned char earth_clouds_char_032[30] = { 24, 24, 15, 24, 28, 23, 8, 28, 31, 28, 28, 31, 0, 30, 31, 28, 22, 7, 30, 6, 5, 30, 6, 3, 30, 26, 1, 22, 30, 29 };
static const unsigned char earth_clouds_char_033[30] = { 1, 1, 31, 1, 1, 31, 0, 1, 31, 1, 3, 31, 1, 2, 30, 2, 3, 31, 0, 1, 31, 1, 3, 31, 3, 7, 28, 7, 15, 27 };
static const unsigned char earth_clouds_char_034[30] = { 15, 24, 24, 31, 24, 0, 31, 16, 0, 15, 27, 0, 31, 27, 0, 31, 31, 16, 31, 31, 29, 30, 31, 15, 16, 31, 31, 7, 31, 31 };
static const unsigned char earth_clouds_char_035[30] = { 28, 7, 3, 28, 7, 3, 28, 31, 3, 31, 31, 7, 31, 30, 12, 23, 30, 28, 23, 31, 29, 22, 31, 31, 19, 31, 31, 16, 31, 31 };
static const unsigned char earth_clouds_char_036[30] = { 30, 31, 15, 30, 31, 31, 24, 31, 31, 6, 31, 31, 30, 26, 19, 28, 30, 3, 24, 28, 31, 0, 24, 31, 0, 19, 31, 16, 18, 31 };
static const unsigned char earth_clouds_char_037[30] = { 7, 31, 28, 7, 31, 29, 31, 31, 28, 15, 31, 18, 7, 31, 28, 7, 15, 28, 3, 31, 30, 0, 18, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_038[30] = { 28, 31, 31, 30, 31, 3, 31, 7, 1, 31, 31, 3, 31, 15, 1, 31, 3, 1, 31, 3, 1, 31, 17, 16, 15, 27, 18, 7, 31, 27 };
static const unsigned char earth_clouds_char_039[30] = { 25, 27, 14, 19, 30, 28, 19, 27, 15, 25, 31, 30, 25, 31, 30, 23, 31, 31, 9, 31, 31, 24, 31, 31, 16, 30, 15, 0, 31, 31 };
static const unsigned char earth_clouds_char_040[30] = { 6, 31, 31, 30, 27, 25, 30, 19, 17, 29, 23, 0, 24, 15, 6, 25, 31, 13, 4, 15, 31, 0, 13, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char earth_clouds_char_041[30] = { 0, 31, 31, 0, 31, 31, 0, 6, 31, 0, 6, 31, 0, 28, 31, 0, 24, 15, 0, 26, 23, 8, 30, 7, 24, 30, 1, 12, 31, 1 };
static const unsigned char earth_clouds_char_042[30] = { 0, 31, 31, 0, 31, 31, 0, 3, 31, 0, 3, 31, 0, 3, 30, 0, 3, 30, 0, 7, 28, 0, 7, 24, 0, 15, 24, 4, 31, 16 };
static const unsigned char earth_clouds_char_043[30] = { 0, 6, 31, 2, 30, 15, 0, 30, 11, 0, 30, 3, 8, 31, 7, 24, 31, 7, 8, 31, 3, 8, 31, 7, 24, 31, 7, 24, 15, 3 };
static const unsigned char earth_clouds_char_044[30] = { 0, 0, 31, 0, 0, 31, 0, 24, 7, 8, 28, 3, 8, 30, 3, 0, 28, 15, 0, 24, 31, 0, 23, 31, 1, 31, 30, 3, 31, 28 };
static const unsigned char earth_clouds_char_045[30] = { 0, 23, 31, 6, 23, 31, 19, 31, 29, 28, 30, 7, 28, 29, 7, 24, 31, 15, 16, 31, 15, 29, 31, 31, 24, 31, 31, 28, 31, 31 };
static const unsigned char earth_clouds_char_046[30] = { 0, 31, 3, 0, 31, 26, 0, 18, 31, 0, 18, 31, 0, 15, 29, 0, 15, 31, 0, 15, 24, 0, 15, 25, 2, 7, 24, 0, 7, 28 };
static const unsigned char earth_clouds_char_047[30] = { 24, 31, 31, 28, 12, 7, 24, 31, 7, 0, 31, 6, 25, 31, 15, 0, 31, 7, 22, 31, 3, 30, 31, 1, 30, 31, 0, 4, 31, 1 };
static const unsigned char earth_clouds_char_048[30] = { 4, 19, 30, 4, 7, 31, 12, 15, 31, 14, 31, 27, 7, 31, 27, 31, 31, 18, 15, 31, 18, 29, 31, 23, 29, 31, 1, 30, 31, 2 };
static const unsigned char earth_clouds_char_049[30] = { 1, 27, 14, 1, 29, 30, 21, 31, 18, 15, 31, 4, 11, 31, 4, 23, 31, 22, 23, 31, 31, 31, 31, 15, 31, 31, 17, 15, 31, 1 };
static const unsigned char earth_clouds_char_050[30] = { 18, 30, 13, 16, 8, 15, 24, 14, 15, 26, 30, 15, 24, 30, 15, 24, 30, 31, 30, 30, 31, 30, 31, 25, 14, 31, 27, 15, 31, 31 };
static const unsigned char earth_clouds_char_051[30] = { 0, 0, 31, 1, 1, 31, 1, 3, 30, 3, 2, 28, 3, 2, 28, 3, 4, 28, 7, 5, 28, 7, 5, 28, 7, 21, 24, 23, 27, 25 };
static const unsigned char earth_clouds_char_052[30] = { 14, 19, 19, 28, 23, 3, 28, 7, 3, 31, 15, 7, 31, 15, 15, 31, 17, 0, 31, 17, 16, 31, 19, 16, 15, 31, 19, 23, 31, 31 };
static const unsigned char earth_clouds_char_053[30] = { 16, 31, 31, 0, 16, 31, 0, 28, 31, 0, 25, 31, 0, 31, 31, 12, 31, 31, 0, 31, 31, 19, 31, 29, 31, 31, 9, 31, 25, 25 };
static const unsigned char earth_clouds_char_054[30] = { 0, 18, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 1, 3, 31, 2, 31, 30, 7, 31, 24, 7, 15, 16, 6, 29, 16, 7, 31, 16 };
static const unsigned char earth_clouds_char_055[30] = { 6, 31, 22, 26, 31, 22, 24, 15, 0, 24, 31, 0, 19, 31, 0, 15, 31, 0, 24, 31, 0, 28, 31, 2, 29, 31, 0, 28, 15, 0 };
static const unsigned char earth_clouds_char_056[30] = { 20, 30, 3, 24, 30, 3, 16, 31, 3, 8, 29, 11, 24, 31, 0, 25, 31, 4, 19, 31, 4, 19, 31, 0, 23, 31, 8, 7, 27, 0 };
static const unsigned char earth_clouds_char_057[30] = { 0, 29, 31, 0, 31, 30, 0, 31, 31, 0, 31, 28, 0, 31, 7, 0, 31, 7, 0, 31, 11, 16, 31, 3, 24, 31, 1, 24, 31, 1 };
static const unsigned char earth_clouds_char_058[30] = { 0, 31, 28, 2, 31, 28, 3, 31, 28, 3, 31, 28, 1, 31, 28, 1, 30, 28, 3, 30, 28, 3, 30, 28, 3, 31, 8, 3, 30, 0 };
static const unsigned char earth_clouds_char_059[30] = { 16, 25, 31, 24, 29, 31, 28, 30, 15, 28, 31, 15, 30, 31, 23, 14, 31, 29, 15, 31, 31, 15, 31, 30, 7, 31, 24, 15, 31, 24 };
static const unsigned char earth_clouds_char_060[30] = { 7, 29, 16, 3, 31, 24, 1, 31, 0, 3, 31, 16, 7, 15, 24, 7, 31, 16, 6, 31, 24, 4, 31, 25, 16, 31, 25, 26, 31, 8 };
static const unsigned char earth_clouds_char_061[30] = { 20, 31, 1, 24, 30, 3, 16, 30, 7, 0, 29, 7, 0, 29, 6, 0, 29, 7, 16, 25, 15, 0, 24, 31, 0, 8, 31, 0, 28, 31 };
static const unsigned char earth_clouds_char_062[30] = { 0, 7, 29, 1, 7, 28, 1, 7, 28, 1, 23, 28, 1, 19, 12, 17, 27, 4, 9, 31, 0, 9, 31, 16, 13, 30, 0, 13, 31, 0 };
static const unsigned char earth_clouds_char_063[30] = { 3, 31, 28, 3, 31, 30, 20, 31, 31, 20, 31, 31, 23, 31, 31, 22, 31, 27, 28, 31, 15, 17, 27, 14, 1, 30, 14, 31, 30, 12 };
static const unsigned char earth_clouds_char_064[30] = { 31, 23, 17, 31, 23, 7, 30, 19, 3, 31, 27, 19, 31, 31, 31, 31, 31, 12, 31, 15, 0, 31, 13, 9, 30, 13, 13, 30, 3, 1 };
static const unsigned char earth_clouds_char_065[30] = { 31, 31, 29, 31, 31, 29, 26, 31, 31, 23, 31, 28, 7, 31, 30, 7, 31, 24, 15, 31, 24, 31, 30, 24, 15, 24, 16, 15, 30, 24 };
static const unsigned char earth_clouds_char_066[30] = { 31, 29, 28, 31, 30, 4, 27, 31, 6, 31, 15, 7, 29, 7, 0, 29, 7, 6, 25, 31, 2, 23, 31, 4, 23, 31, 12, 6, 31, 24 };
static const unsigned char earth_clouds_char_067[30] = { 16, 25, 30, 17, 27, 13, 31, 31, 28, 31, 31, 16, 29, 27, 0, 31, 11, 0, 31, 11, 0, 31, 31, 0, 31, 23, 16, 31, 31, 16 };
static const unsigned char earth_clouds_char_068[30] = { 31, 4, 0, 31, 28, 0, 31, 13, 0, 31, 9, 0, 31, 27, 0, 28, 31, 0, 28, 23, 3, 24, 31, 3, 24, 31, 6, 25, 31, 4 };
static const unsigned char earth_clouds_char_069[30] = { 30, 7, 0, 18, 31, 0, 0, 31, 0, 0, 31, 17, 0, 23, 12, 3, 31, 24, 3, 31, 12, 19, 30, 0, 3, 31, 0, 3, 31, 0 };
static const unsigned char earth_clouds_char_070[30] = { 0, 31, 22, 1, 31, 6, 4, 31, 8, 12, 31, 1, 14, 31, 0, 7, 31, 0, 7, 31, 0, 22, 31, 0, 31, 29, 1, 3, 31, 0 };
static const unsigned char earth_clouds_char_071[30] = { 3, 23, 24, 3, 29, 24, 3, 30, 12, 3, 30, 12, 3, 31, 28, 3, 31, 28, 2, 31, 24, 13, 31, 16, 24, 31, 18, 30, 31, 0 };
static const unsigned char earth_clouds_char_072[30] = { 31, 31, 0, 27, 31, 4, 24, 15, 4, 0, 31, 12, 0, 23, 15, 0, 31, 31, 0, 31, 15, 0, 31, 15, 0, 31, 15, 0, 31, 15 };
static const unsigned char earth_clouds_char_073[30] = { 7, 25, 16, 7, 25, 16, 15, 27, 16, 7, 10, 16, 7, 9, 24, 7, 29, 24, 2, 21, 24, 3, 31, 16, 15, 31, 0, 3, 29, 0 };
static const unsigned char earth_clouds_char_074[30] = { 31, 31, 0, 28, 23, 0, 28, 15, 0, 16, 31, 2, 0, 31, 15, 0, 31, 8, 4, 31, 16, 4, 31, 27, 16, 31, 1, 0, 31, 1 };
static const unsigned char earth_clouds_char_075[30] = { 31, 15, 2, 27, 12, 0, 19, 29, 0, 27, 31, 1, 27, 31, 3, 30, 31, 3, 2, 31, 7, 13, 31, 7, 13, 23, 7, 13, 23, 3 };
static const unsigned char earth_clouds_char_076[30] = { 7, 31, 29, 31, 31, 29, 31, 31, 29, 31, 31, 25, 31, 31, 17, 31, 27, 17, 30, 19, 1, 15, 19, 17, 31, 19, 1, 31, 19, 1 };
static const unsigned char earth_clouds_char_077[30] = { 0, 31, 31, 1, 31, 0, 17, 31, 0, 24, 31, 2, 8, 31, 2, 2, 31, 16, 0, 15, 28, 7, 31, 16, 2, 31, 16, 7, 29, 16 };
static const unsigned char earth_clouds_char_078[30] = { 31, 29, 0, 31, 24, 0, 31, 28, 0, 18, 29, 8, 18, 31, 9, 16, 31, 4, 16, 31, 4, 25, 31, 6, 24, 31, 2, 28, 31, 0 };
static const unsigned char earth_clouds_char_079[30] = { 30, 3, 3, 30, 3, 3, 30, 3, 3, 31, 7, 3, 25, 15, 6, 27, 14, 6, 27, 30, 28, 27, 28, 12, 23, 28, 8, 31, 24, 24 };
static const unsigned char earth_clouds_char_080[30] = { 3, 30, 28, 3, 31, 30, 31, 31, 22, 31, 31, 0, 31, 30, 4, 31, 15, 0, 31, 15, 0, 31, 15, 1, 31, 6, 0, 31, 4, 0 };
static const unsigned char earth_clouds_char_081[30] = { 14, 27, 18, 31, 16, 0, 31, 17, 0, 31, 3, 0, 30, 15, 0, 30, 29, 4, 31, 17, 0, 31, 1, 0, 31, 4, 0, 31, 12, 0 };
static const unsigned char earth_clouds_char_082[30] = { 0, 31, 0, 16, 31, 0, 1, 31, 0, 7, 31, 0, 3, 31, 24, 11, 31, 8, 29, 15, 15, 21, 15, 14, 17, 15, 15, 25, 15, 7 };
static const unsigned char earth_clouds_char_083[30] = { 0, 31, 30, 2, 31, 30, 3, 31, 6, 0, 31, 6, 0, 31, 24, 0, 23, 28, 0, 7, 30, 6, 7, 28, 3, 15, 24, 7, 31, 30 };
static const unsigned char earth_clouds_char_084[30] = { 7, 31, 16, 0, 31, 24, 0, 31, 27, 0, 30, 31, 0, 28, 31, 0, 31, 15, 16, 31, 7, 0, 31, 3, 0, 31, 1, 0, 31, 16 };
static const unsigned char earth_clouds_char_085[30] = { 31, 27, 0, 7, 27, 0, 7, 27, 16, 7, 11, 26, 7, 15, 24, 3, 15, 28, 3, 7, 29, 3, 7, 28, 3, 7, 28, 3, 7, 30 };
static const unsigned char earth_clouds_char_086[30] = { 31, 1, 1, 31, 11, 1, 31, 7, 2, 31, 7, 2, 31, 6, 2, 31, 6, 2, 31, 6, 6, 31, 14, 4, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_087[30] = { 31, 15, 4, 29, 7, 7, 15, 19, 16, 7, 31, 24, 7, 31, 24, 15, 31, 27, 31, 31, 30, 31, 31, 30, 31, 31, 28, 31, 31, 19 };
static const unsigned char earth_clouds_char_088[30] = { 20, 31, 28, 31, 31, 24, 31, 27, 0, 31, 27, 8, 31, 25, 24, 31, 25, 0, 30, 25, 0, 31, 25, 16, 31, 25, 17, 30, 31, 17 };
static const unsigned char earth_clouds_char_089[30] = { 17, 31, 4, 1, 27, 12, 1, 27, 30, 0, 17, 31, 0, 16, 31, 0, 9, 31, 0, 8, 31, 2, 31, 31, 23, 31, 0, 31, 25, 0 };
static const unsigned char earth_clouds_char_090[30] = { 31, 16, 0, 31, 0, 0, 31, 1, 0, 30, 19, 17, 15, 24, 16, 15, 24, 16, 27, 31, 23, 25, 31, 23, 30, 31, 7, 31, 23, 0 };
static const unsigned char earth_clouds_char_091[30] = { 31, 15, 0, 27, 15, 0, 29, 14, 0, 25, 15, 8, 25, 31, 8, 25, 31, 0, 31, 23, 1, 28, 15, 3, 24, 15, 3, 24, 31, 15 };
static const unsigned char earth_clouds_char_092[30] = { 31, 16, 0, 31, 16, 0, 31, 2, 0, 31, 0, 0, 31, 0, 0, 31, 10, 0, 1, 31, 26, 1, 31, 30, 1, 9, 30, 0, 17, 31 };
static const unsigned char earth_clouds_char_093[30] = { 31, 4, 0, 15, 31, 16, 23, 31, 20, 17, 31, 16, 25, 31, 1, 31, 31, 1, 19, 31, 29, 1, 31, 28, 1, 31, 28, 2, 31, 11 };
static const unsigned char earth_clouds_char_094[30] = { 27, 7, 7, 26, 7, 6, 30, 23, 6, 29, 7, 5, 31, 7, 5, 31, 23, 3, 31, 31, 16, 19, 31, 26, 31, 31, 7, 31, 31, 0 };
static const unsigned char earth_clouds_char_095[30] = { 0, 28, 7, 16, 24, 15, 0, 24, 31, 0, 25, 31, 0, 17, 15, 0, 17, 31, 0, 17, 31, 0, 19, 31, 16, 19, 15, 16, 31, 13 };
static const unsigned char earth_clouds_char_096[30] = { 0, 31, 1, 8, 31, 10, 16, 31, 18, 16, 31, 6, 24, 23, 2, 12, 31, 2, 4, 31, 2, 12, 27, 1, 30, 19, 1, 28, 30, 1 };
static const unsigned char earth_clouds_char_097[30] = { 3, 31, 0, 31, 30, 0, 2, 31, 0, 5, 31, 3, 8, 29, 3, 16, 25, 15, 0, 17, 15, 0, 1, 31, 0, 3, 30, 0, 3, 28 };
static const unsigned char earth_clouds_char_098[30] = { 7, 31, 1, 7, 31, 0, 3, 31, 24, 27, 31, 29, 25, 22, 23, 1, 26, 30, 1, 22, 28, 3, 30, 24, 15, 23, 16, 14, 27, 16 };
static const unsigned char earth_clouds_char_099[30] = { 7, 12, 30, 23, 30, 30, 31, 27, 14, 31, 18, 2, 31, 2, 2, 31, 7, 2, 31, 6, 2, 19, 30, 6, 31, 28, 8, 31, 28, 0 };
static const unsigned char earth_clouds_char_100[30] = { 30, 31, 31, 2, 6, 29, 2, 7, 29, 0, 3, 31, 4, 7, 31, 7, 27, 24, 15, 24, 24, 15, 16, 16, 31, 16, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_101[30] = { 31, 31, 19, 31, 31, 25, 31, 29, 24, 31, 31, 0, 31, 31, 17, 31, 31, 31, 27, 31, 12, 31, 7, 7, 31, 7, 3, 30, 3, 1 };
static const unsigned char earth_clouds_char_102[30] = { 16, 25, 22, 16, 27, 30, 17, 31, 14, 31, 15, 14, 27, 15, 12, 31, 31, 0, 31, 19, 0, 15, 26, 16, 31, 24, 16, 31, 24, 0 };
static const unsigned char earth_clouds_char_103[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 31, 1, 1, 30, 3, 1, 30, 3, 1, 30, 3, 3, 28, 7, 3 };
static const unsigned char earth_clouds_char_104[30] = { 16, 31, 15, 16, 15, 15, 16, 15, 15, 16, 27, 15, 0, 23, 15, 4, 31, 13, 22, 22, 29, 4, 30, 27, 8, 31, 27, 2, 31, 25 };
static const unsigned char earth_clouds_char_105[30] = { 0, 31, 31, 0, 7, 31, 1, 31, 31, 27, 31, 7, 24, 31, 30, 14, 31, 30, 15, 31, 13, 8, 31, 12, 4, 31, 19, 0, 31, 27 };
static const unsigned char earth_clouds_char_106[30] = { 14, 27, 19, 4, 31, 27, 16, 28, 31, 24, 30, 31, 12, 31, 31, 4, 29, 31, 0, 29, 7, 8, 25, 31, 0, 31, 29, 4, 31, 13 };
static const unsigned char earth_clouds_char_107[30] = { 31, 1, 0, 6, 31, 25, 0, 31, 26, 1, 15, 28, 1, 31, 28, 1, 30, 30, 1, 30, 14, 1, 31, 14, 1, 31, 15, 0, 31, 30 };
static const unsigned char earth_clouds_char_108[30] = { 3, 31, 7, 17, 31, 23, 16, 31, 31, 0, 30, 15, 16, 30, 11, 16, 31, 1, 24, 23, 0, 24, 15, 0, 28, 15, 4, 24, 15, 5 };
static const unsigned char earth_clouds_char_109[30] = { 31, 31, 20, 15, 31, 20, 31, 31, 24, 31, 15, 8, 27, 31, 7, 15, 23, 20, 15, 27, 16, 15, 30, 28, 3, 30, 28, 7, 31, 30 };
static const unsigned char earth_clouds_char_110[30] = { 26, 31, 25, 26, 31, 25, 24, 31, 24, 26, 31, 10, 30, 31, 9, 28, 7, 1, 28, 31, 21, 28, 7, 3, 30, 3, 3, 30, 11, 3 };
static const unsigned char earth_clouds_char_111[30] = { 0, 31, 12, 16, 31, 13, 20, 30, 3, 0, 31, 27, 0, 14, 31, 0, 12, 31, 0, 5, 31, 0, 31, 31, 0, 31, 21, 2, 31, 16 };
static const unsigned char earth_clouds_char_112[30] = { 31, 22, 0, 31, 6, 0, 25, 30, 2, 9, 29, 7, 11, 31, 7, 26, 31, 4, 28, 15, 1, 30, 3, 0, 30, 1, 0, 30, 1, 0 };
static const unsigned char earth_clouds_char_113[30] = { 31, 0, 0, 31, 0, 0, 15, 19, 3, 28, 7, 7, 31, 3, 2, 31, 7, 3, 31, 7, 3, 29, 3, 3, 30, 19, 3, 15, 31, 16 };
static const unsigned char earth_clouds_char_114[30] = { 27, 31, 3, 28, 23, 2, 28, 23, 1, 12, 23, 7, 12, 31, 22, 12, 31, 31, 7, 31, 29, 5, 15, 30, 1, 15, 30, 0, 15, 31 };
static const unsigned char earth_clouds_char_115[30] = { 1, 31, 31, 1, 12, 30, 1, 26, 30, 3, 30, 12, 31, 28, 0, 31, 24, 0, 31, 0, 0, 31, 0, 0, 31, 4, 0, 15, 24, 16 };
static const unsigned char earth_clouds_char_116[30] = { 6, 31, 16, 3, 31, 16, 0, 31, 18, 1, 29, 31, 3, 30, 28, 3, 28, 24, 19, 28, 28, 19, 28, 12, 19, 28, 8, 19, 28, 24 };
static const unsigned char earth_clouds_char_117[30] = { 0, 31, 30, 1, 27, 15, 17, 31, 14, 1, 31, 6, 1, 31, 18, 16, 31, 6, 0, 31, 28, 19, 31, 28, 29, 31, 28, 8, 31, 30 };
static const unsigned char earth_clouds_char_118[30] = { 15, 25, 0, 31, 17, 1, 31, 17, 1, 31, 1, 1, 31, 1, 1, 30, 2, 1, 28, 18, 3, 28, 21, 3, 29, 23, 3, 31, 23, 1 };
static const unsigned char earth_clouds_char_119[30] = { 3, 5, 28, 3, 4, 28, 7, 4, 24, 15, 8, 24, 31, 17, 16, 31, 17, 16, 31, 16, 16, 15, 24, 16, 7, 8, 24, 7, 8, 24 };
static const unsigned char earth_clouds_char_120[30] = { 31, 0, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0, 15, 26, 18, 15, 15, 30, 31, 28, 16, 31, 8, 8, 31, 13, 12, 31, 13, 13 };
static const unsigned char earth_clouds_char_121[30] = { 19, 30, 28, 19, 14, 12, 31, 31, 14, 29, 31, 14, 29, 7, 3, 30, 15, 1, 30, 13, 9, 31, 13, 0, 31, 19, 2, 13, 19, 19 };
static const unsigned char earth_clouds_char_122[30] = { 31, 3, 1, 31, 0, 0, 31, 16, 0, 31, 17, 0, 31, 17, 0, 15, 30, 20, 31, 28, 16, 31, 0, 0, 31, 5, 1, 31, 13, 0 };
static const unsigned char earth_clouds_char_123[30] = { 31, 24, 16, 31, 17, 1, 30, 19, 1, 30, 30, 31, 16, 20, 31, 24, 29, 15, 29, 15, 2, 31, 10, 0, 31, 2, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_124[30] = { 31, 28, 0, 31, 31, 0, 6, 22, 29, 7, 5, 28, 3, 12, 28, 31, 28, 28, 31, 0, 0, 31, 2, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_125[30] = { 31, 16, 0, 31, 0, 0, 31, 6, 2, 31, 6, 6, 31, 31, 6, 31, 31, 0, 31, 9, 0, 31, 8, 0, 31, 14, 0, 31, 7, 0 };
static const unsigned char earth_clouds_char_126[30] = { 30, 31, 24, 6, 31, 18, 31, 7, 4, 29, 7, 4, 28, 31, 4, 30, 15, 4, 31, 31, 4, 25, 31, 0, 24, 31, 8, 24, 15, 12 };
static const unsigned char earth_clouds_char_127[30] = { 31, 0, 0, 31, 18, 0, 31, 16, 16, 31, 28, 8, 31, 30, 0, 15, 18, 0, 29, 31, 0, 29, 31, 1, 28, 27, 1, 30, 19, 0 };
static const unsigned char earth_clouds_char_128[30] = { 31, 1, 0, 30, 7, 3, 28, 6, 7, 24, 6, 7, 29, 15, 11, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0 };
static const unsigned char earth_clouds_char_129[30] = { 31, 0, 0, 31, 24, 16, 15, 12, 24, 15, 28, 24, 3, 30, 28, 31, 30, 20, 31, 2, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_130[30] = { 12, 30, 1, 2, 31, 17, 0, 31, 31, 0, 14, 31, 0, 29, 31, 19, 31, 15, 31, 15, 7, 31, 3, 2, 31, 1, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_131[30] = { 0, 15, 23, 0, 31, 31, 0, 23, 30, 0, 31, 31, 16, 31, 31, 28, 31, 31, 31, 31, 17, 31, 15, 1, 30, 31, 9, 28, 27, 3 };
static const unsigned char earth_clouds_char_132[30] = { 0, 31, 20, 0, 31, 6, 0, 31, 0, 2, 31, 18, 0, 31, 3, 16, 29, 7, 24, 5, 7, 24, 31, 7, 0, 31, 1, 12, 31, 0 };
static const unsigned char earth_clouds_char_133[30] = { 0, 28, 23, 0, 31, 19, 6, 31, 2, 8, 31, 6, 0, 31, 22, 0, 15, 27, 0, 15, 25, 0, 15, 26, 6, 31, 30, 2, 31, 30 };
static const unsigned char earth_clouds_char_134[30] = { 0, 12, 31, 0, 12, 31, 0, 31, 30, 0, 31, 31, 0, 31, 31, 1, 31, 29, 1, 31, 30, 1, 30, 30, 3, 18, 28, 7, 28, 28 };
static const unsigned char earth_clouds_char_135[30] = { 27, 30, 28, 15, 28, 20, 31, 30, 16, 31, 30, 26, 31, 31, 12, 17, 31, 14, 17, 27, 30, 17, 27, 31, 30, 31, 15, 31, 15, 3 };
static const unsigned char earth_clouds_char_136[30] = { 31, 19, 3, 30, 31, 15, 30, 31, 3, 30, 1, 1, 31, 23, 1, 31, 31, 31, 12, 31, 31, 30, 31, 27, 8, 31, 31, 9, 31, 23 };
static const unsigned char earth_clouds_char_137[30] = { 15, 27, 31, 29, 31, 27, 23, 26, 20, 31, 28, 16, 7, 28, 24, 7, 23, 24, 19, 29, 24, 19, 30, 16, 15, 30, 18, 31, 30, 18 };
static const unsigned char earth_clouds_char_138[30] = { 31, 7, 1, 31, 15, 1, 31, 31, 3, 30, 3, 3, 28, 7, 3, 29, 31, 9, 29, 31, 1, 29, 31, 16, 17, 31, 0, 17, 31, 9 };
static const unsigned char earth_clouds_char_139[30] = { 15, 24, 24, 31, 28, 24, 15, 12, 24, 15, 28, 24, 23, 24, 24, 15, 24, 24, 31, 24, 16, 31, 16, 0, 31, 24, 24, 23, 25, 24 };
static const unsigned char earth_clouds_char_140[30] = { 31, 13, 13, 31, 13, 8, 31, 8, 0, 31, 0, 0, 31, 6, 4, 31, 31, 0, 31, 19, 0, 31, 17, 17, 31, 17, 1, 31, 17, 0 };
static const unsigned char earth_clouds_char_141[30] = { 13, 27, 19, 31, 26, 18, 31, 24, 16, 31, 0, 0, 31, 4, 0, 31, 8, 0, 23, 28, 12, 19, 28, 28, 23, 30, 30, 3, 30, 30 };
static const unsigned char earth_clouds_char_142[30] = { 31, 5, 0, 31, 0, 0, 31, 0, 0, 31, 4, 0, 31, 12, 12, 19, 30, 14, 31, 30, 14, 31, 14, 2, 31, 6, 2, 31, 6, 2 };
static const unsigned char earth_clouds_char_143[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 16, 15, 31, 18, 31, 31, 4, 31, 15, 4 };
static const unsigned char earth_clouds_char_144[30] = { 24, 31, 12, 16, 31, 25, 18, 31, 24, 19, 30, 24, 19, 30, 8, 25, 30, 28, 29, 30, 20, 31, 22, 16, 15, 30, 24, 7, 31, 28 };
static const unsigned char earth_clouds_char_145[30] = { 0, 31, 29, 0, 31, 29, 0, 31, 31, 16, 31, 12, 27, 14, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_146[30] = { 7, 12, 28, 7, 8, 24, 7, 8, 24, 15, 24, 16, 15, 24, 0, 15, 24, 0, 15, 24, 0, 31, 28, 12, 23, 28, 0, 7, 29, 0 };
static const unsigned char earth_clouds_char_147[30] = { 31, 0, 0, 31, 24, 24, 7, 14, 24, 27, 30, 30, 31, 6, 0, 31, 0, 0, 31, 7, 0, 31, 4, 4, 31, 0, 0, 31, 15, 0 };
static const unsigned char earth_clouds_char_148[30] = { 30, 31, 7, 31, 3, 1, 31, 0, 0, 31, 1, 0, 31, 3, 1, 31, 31, 6, 31, 18, 16, 31, 25, 0, 31, 1, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_149[30] = { 31, 31, 7, 31, 31, 15, 23, 31, 30, 31, 27, 26, 31, 2, 0, 31, 24, 0, 31, 25, 0, 31, 31, 26, 23, 31, 24, 23, 31, 24 };
static const unsigned char earth_clouds_char_150[30] = { 15, 29, 24, 7, 11, 24, 15, 27, 19, 31, 25, 0, 31, 3, 0, 31, 16, 0, 31, 4, 0, 31, 12, 0, 31, 1, 0, 31, 1, 1 };
static const unsigned char earth_clouds_char_151[30] = { 31, 24, 16, 27, 30, 0, 24, 31, 2, 24, 31, 0, 28, 31, 30, 28, 31, 29, 28, 31, 7, 30, 3, 1, 31, 17, 0, 31, 24, 0 };
static const unsigned char earth_clouds_char_152[30] = { 19, 31, 29, 31, 15, 12, 31, 14, 0, 31, 23, 0, 11, 30, 4, 15, 30, 16, 15, 30, 24, 23, 30, 28, 31, 31, 6, 31, 13, 1 };
static const unsigned char earth_clouds_char_153[30] = { 15, 24, 16, 15, 24, 24, 7, 20, 24, 23, 23, 28, 19, 23, 28, 19, 26, 14, 19, 11, 14, 25, 11, 14, 25, 15, 7, 28, 6, 7 };
static const unsigned char earth_clouds_char_154[30] = { 31, 6, 0, 31, 12, 0, 31, 6, 0, 25, 6, 0, 27, 14, 6, 25, 15, 6, 27, 15, 7, 17, 15, 7, 17, 31, 7, 28, 15, 7 };
static const unsigned char earth_clouds_char_155[30] = { 7, 29, 4, 7, 28, 0, 7, 25, 8, 14, 27, 24, 28, 31, 16, 30, 23, 0, 30, 3, 0, 30, 3, 1, 28, 3, 0, 28, 3, 0 };
static const unsigned char earth_clouds_char_156[30] = { 21, 31, 31, 25, 31, 15, 31, 31, 7, 31, 23, 3, 31, 15, 0, 31, 4, 0, 31, 24, 16, 31, 28, 8, 31, 14, 0, 31, 29, 0 };
static const unsigned char earth_clouds_char_157[30] = { 31, 0, 0, 31, 16, 0, 15, 16, 16, 15, 24, 24, 7, 24, 24, 23, 28, 28, 27, 28, 12, 31, 6, 4, 31, 6, 2, 31, 3, 3 };
static const unsigned char earth_clouds_char_158[30] = { 31, 1, 0, 31, 7, 0, 28, 7, 0, 30, 15, 0, 19, 15, 0, 16, 31, 8, 0, 31, 8, 0, 31, 0, 1, 31, 0, 21, 31, 0 };
static const unsigned char earth_clouds_char_159[30] = { 31, 25, 0, 31, 25, 0, 31, 27, 0, 30, 31, 0, 4, 31, 0, 1, 31, 8, 0, 31, 6, 8, 31, 0, 27, 31, 0, 24, 31, 0 };
static const unsigned char earth_clouds_char_160[30] = { 27, 7, 4, 29, 23, 3, 30, 27, 1, 31, 17, 0, 31, 16, 0, 31, 16, 0, 31, 24, 0, 23, 31, 0, 7, 28, 0, 23, 28, 0 };
static const unsigned char earth_clouds_char_161[30] = { 31, 23, 20, 31, 31, 22, 15, 31, 27, 23, 29, 25, 27, 13, 5, 31, 7, 0, 31, 3, 0, 31, 1, 1, 31, 1, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_162[30] = { 31, 19, 17, 31, 19, 0, 31, 17, 0, 31, 17, 16, 15, 17, 16, 15, 24, 16, 15, 24, 16, 31, 24, 16, 7, 28, 24, 23, 29, 28 };
static const unsigned char earth_clouds_char_163[30] = { 31, 0, 0, 31, 12, 0, 29, 14, 6, 29, 11, 2, 31, 3, 3, 31, 7, 5, 31, 6, 2, 29, 7, 2, 29, 3, 3, 28, 3, 3 };
static const unsigned char earth_clouds_char_164[30] = { 7, 28, 28, 7, 28, 28, 7, 28, 28, 3, 6, 28, 3, 30, 28, 19, 30, 28, 19, 27, 30, 17, 19, 15, 17, 25, 15, 17, 31, 15 };
static const unsigned char earth_clouds_char_165[30] = { 0, 29, 7, 1, 25, 15, 1, 27, 30, 1, 19, 30, 1, 3, 30, 3, 31, 31, 2, 31, 31, 3, 31, 15, 7, 31, 14, 15, 27, 26 };
static const unsigned char earth_clouds_char_166[30] = { 29, 15, 1, 31, 23, 3, 31, 15, 6, 31, 2, 0, 31, 1, 0, 31, 29, 1, 15, 30, 24, 31, 22, 2, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_167[30] = { 31, 16, 0, 31, 0, 0, 31, 16, 0, 7, 28, 24, 3, 26, 28, 29, 30, 22, 29, 23, 3, 28, 31, 3, 30, 3, 3, 31, 3, 1 };
static const unsigned char earth_clouds_char_168[30] = { 31, 31, 0, 31, 31, 0, 31, 31, 0, 15, 31, 16, 3, 31, 0, 3, 23, 8, 1, 31, 12, 1, 26, 6, 1, 26, 6, 1, 26, 30 };
static const unsigned char earth_clouds_char_169[30] = { 3, 30, 20, 1, 30, 28, 17, 26, 12, 17, 30, 14, 17, 30, 6, 17, 30, 0, 31, 30, 0, 31, 28, 0, 31, 28, 0, 31, 24, 0 };
static const unsigned char earth_clouds_char_170[30] = { 31, 13, 8, 31, 12, 12, 31, 14, 6, 29, 7, 7, 25, 15, 6, 31, 6, 6, 31, 7, 4, 31, 7, 6, 29, 7, 2, 31, 19, 1 };
static const unsigned char earth_clouds_char_171[30] = { 31, 28, 8, 31, 12, 8, 31, 12, 4, 31, 28, 4, 31, 30, 4, 31, 22, 20, 31, 30, 18, 31, 31, 26, 21, 31, 31, 20, 31, 31 };
static const unsigned char earth_clouds_char_172[30] = { 31, 24, 0, 31, 24, 0, 31, 8, 0, 31, 16, 0, 31, 3, 0, 29, 3, 3, 31, 6, 2, 29, 6, 2, 28, 7, 7, 31, 7, 7 };
static const unsigned char earth_clouds_char_173[30] = { 31, 25, 0, 31, 24, 8, 23, 8, 8, 31, 12, 8, 31, 12, 4, 31, 12, 4, 31, 13, 8, 31, 13, 1, 31, 21, 1, 31, 29, 12 };
static const unsigned char earth_clouds_char_174[30] = { 25, 31, 15, 25, 31, 15, 24, 31, 15, 24, 31, 7, 24, 31, 7, 24, 29, 15, 24, 29, 31, 24, 30, 31, 0, 31, 31, 7, 31, 31 };
static const unsigned char earth_clouds_char_175[30] = { 23, 28, 24, 23, 28, 24, 23, 24, 8, 31, 24, 0, 31, 0, 0, 31, 0, 0, 31, 4, 0, 31, 22, 0, 31, 28, 16, 31, 24, 0 };
static const unsigned char earth_clouds_char_176[30] = { 31, 18, 0, 31, 4, 0, 31, 7, 0, 31, 15, 3, 30, 7, 7, 28, 7, 3, 30, 7, 3, 28, 7, 3, 28, 7, 3, 24, 15, 7 };
static const unsigned char earth_clouds_char_177[30] = { 19, 30, 28, 25, 11, 14, 29, 21, 7, 28, 26, 3, 30, 10, 1, 30, 23, 1, 31, 17, 1, 31, 1, 0, 31, 24, 0, 31, 28, 8 };
static const unsigned char earth_clouds_char_178[30] = { 31, 1, 0, 31, 1, 0, 31, 0, 0, 31, 16, 16, 15, 8, 24, 7, 14, 24, 7, 6, 28, 3, 23, 30, 19, 19, 31, 17, 11, 15 };
static const unsigned char earth_clouds_char_179[30] = { 1, 17, 31, 16, 23, 31, 30, 31, 9, 24, 31, 23, 31, 31, 19, 28, 31, 15, 24, 31, 15, 28, 31, 15, 28, 31, 3, 30, 7, 3 };
static const unsigned char earth_clouds_char_180[30] = { 30, 7, 0, 31, 3, 0, 30, 17, 16, 30, 25, 17, 15, 27, 25, 31, 31, 31, 30, 31, 31, 6, 31, 27, 13, 31, 31, 23, 31, 25 };
static const unsigned char earth_clouds_char_181[30] = { 31, 28, 0, 15, 24, 0, 15, 24, 0, 15, 27, 16, 15, 27, 26, 29, 31, 27, 13, 31, 31, 2, 31, 31, 3, 31, 29, 17, 31, 15 };
static const unsigned char earth_clouds_char_182[30] = { 31, 27, 17, 15, 31, 16, 7, 31, 24, 31, 31, 28, 7, 30, 28, 23, 31, 15, 24, 15, 15, 25, 15, 7, 30, 7, 7, 31, 7, 3 };
static const unsigned char earth_clouds_char_183[30] = { 31, 24, 0, 31, 28, 24, 31, 30, 28, 31, 31, 26, 0, 31, 31, 8, 31, 31, 7, 31, 30, 31, 28, 24, 31, 16, 0, 31, 16, 0 };
static const unsigned char earth_clouds_char_184[30] = { 31, 7, 3, 31, 3, 3, 31, 8, 0, 31, 16, 0, 15, 28, 24, 1, 31, 31, 24, 31, 15, 28, 7, 3, 31, 1, 1, 31, 15, 0 };
static const unsigned char earth_clouds_char_185[30] = { 31, 31, 6, 31, 23, 1, 31, 24, 16, 31, 24, 0, 31, 16, 0, 31, 16, 16, 15, 24, 16, 7, 28, 24, 3, 30, 28, 19, 30, 30 };
static const unsigned char earth_clouds_char_186[30] = { 16, 31, 31, 24, 31, 15, 24, 29, 7, 28, 21, 7, 28, 5, 3, 28, 5, 3, 28, 7, 7, 29, 7, 3, 28, 3, 3, 30, 3, 3 };
static const unsigned char earth_clouds_char_187[30] = { 31, 6, 0, 31, 7, 7, 29, 7, 7, 29, 7, 3, 31, 3, 1, 31, 3, 1, 31, 1, 1, 31, 17, 0, 15, 17, 16, 31, 16, 16 };
static const unsigned char earth_clouds_char_188[30] = { 31, 29, 25, 31, 31, 11, 30, 7, 3, 28, 7, 7, 24, 15, 15, 24, 31, 15, 24, 31, 31, 27, 31, 31, 31, 31, 31, 23, 31, 15 };
static const unsigned char earth_clouds_char_189[30] = { 30, 15, 7, 30, 7, 7, 28, 7, 3, 28, 15, 7, 28, 15, 7, 31, 15, 3, 31, 0, 0, 31, 0, 0, 31, 16, 0, 15, 24, 24 };
static const unsigned char earth_clouds_char_190[30] = { 31, 1, 0, 31, 17, 0, 31, 25, 16, 31, 30, 16, 31, 31, 24, 31, 30, 24, 31, 31, 16, 31, 31, 31, 3, 31, 31, 1, 31, 30 };
static const unsigned char earth_clouds_char_191[30] = { 31, 31, 22, 31, 31, 18, 31, 31, 1, 31, 31, 1, 31, 23, 20, 31, 19, 17, 15, 27, 17, 15, 31, 25, 7, 15, 31, 3, 31, 31 };
static const unsigned char earth_clouds_char_192[30] = { 31, 31, 0, 15, 30, 6, 31, 30, 22, 29, 31, 3, 29, 15, 3, 28, 7, 3, 30, 3, 3, 30, 3, 1, 31, 1, 1, 31, 29, 0 };
static const unsigned char earth_clouds_char_193[30] = { 19, 30, 28, 19, 31, 14, 29, 31, 15, 30, 15, 7, 31, 7, 1, 31, 3, 1, 31, 3, 1, 31, 25, 16, 31, 16, 0, 31, 26, 0 };
static const unsigned char earth_clouds_char_194[30] = { 31, 3, 1, 31, 1, 0, 31, 1, 0, 31, 16, 16, 15, 24, 16, 7, 31, 28, 3, 31, 30, 17, 31, 31, 28, 31, 7, 30, 31, 7 };
static const unsigned char earth_clouds_char_195[30] = { 23, 31, 28, 31, 31, 30, 31, 31, 30, 14, 31, 31, 7, 31, 30, 3, 30, 28, 7, 28, 24, 31, 24, 16, 31, 16, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_196[30] = { 30, 3, 1, 31, 5, 0, 31, 16, 0, 31, 24, 16, 31, 25, 8, 31, 15, 8, 31, 3, 0, 31, 7, 0, 31, 6, 6, 31, 31, 9 };
static const unsigned char earth_clouds_char_197[30] = { 31, 31, 9, 15, 15, 31, 3, 23, 30, 25, 31, 14, 29, 7, 6, 29, 7, 7, 29, 7, 7, 29, 7, 7, 30, 31, 7, 29, 31, 7 };
static const unsigned char earth_clouds_char_198[30] = { 31, 31, 28, 31, 31, 24, 15, 31, 26, 13, 31, 30, 12, 31, 31, 12, 31, 31, 28, 31, 23, 28, 31, 19, 30, 27, 19, 30, 27, 17 };
static const unsigned char earth_clouds_char_199[30] = { 23, 28, 24, 31, 28, 12, 31, 30, 28, 27, 31, 30, 27, 30, 30, 1, 31, 30, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char earth_clouds_char_200[30] = { 31, 25, 8, 31, 29, 0, 31, 22, 16, 31, 19, 0, 31, 31, 0, 31, 19, 0, 31, 24, 16, 27, 31, 30, 16, 28, 31, 16, 27, 31 };
static const unsigned char earth_clouds_char_201[30] = { 15, 31, 31, 15, 31, 31, 6, 31, 29, 14, 31, 25, 15, 25, 24, 31, 25, 17, 31, 25, 0, 31, 25, 0, 31, 31, 0, 27, 31, 6 };
static const unsigned char earth_clouds_char_202[30] = { 31, 28, 28, 31, 30, 20, 31, 29, 24, 15, 27, 24, 15, 31, 31, 15, 30, 20, 15, 28, 16, 31, 16, 16, 31, 17, 0, 31, 23, 2 };
static const unsigned char earth_clouds_char_203[30] = { 14, 31, 27, 6, 31, 31, 0, 31, 31, 0, 31, 31, 0, 15, 31, 6, 15, 31, 13, 15, 31, 7, 30, 30, 31, 28, 24, 31, 28, 24 };
static const unsigned char earth_clouds_char_204[30] = { 29, 31, 7, 9, 31, 30, 3, 30, 28, 3, 30, 28, 11, 30, 28, 31, 30, 20, 31, 30, 4, 31, 14, 4, 31, 14, 12, 31, 15, 0 };
static const unsigned char earth_clouds_char_205[30] = { 31, 3, 0, 31, 19, 2, 31, 31, 4, 30, 31, 19, 31, 31, 25, 31, 25, 17, 31, 1, 0, 31, 3, 0, 31, 0, 0, 31, 1, 0 };
static const unsigned char earth_clouds_char_206[30] = { 31, 30, 22, 27, 31, 28, 3, 31, 28, 3, 31, 28, 4, 30, 31, 4, 28, 31, 0, 24, 31, 16, 24, 31, 16, 24, 31, 16, 25, 15 };
static const unsigned char earth_clouds_char_207[30] = { 3, 31, 30, 3, 30, 30, 1, 27, 30, 1, 19, 30, 1, 3, 30, 3, 3, 30, 3, 23, 30, 16, 24, 31, 0, 16, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_208[30] = { 24, 31, 15, 16, 31, 15, 16, 31, 31, 16, 31, 15, 16, 30, 15, 24, 15, 15, 16, 27, 31, 0, 1, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_209[30] = { 31, 31, 27, 31, 31, 16, 31, 29, 24, 31, 31, 16, 0, 28, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_210[30] = { 31, 28, 28, 31, 25, 8, 31, 24, 0, 31, 12, 4, 3, 16, 28, 2, 3, 31, 0, 1, 31, 0, 1, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_211[30] = { 7, 31, 31, 29, 31, 31, 31, 15, 7, 30, 15, 15, 16, 30, 31, 0, 12, 31, 0, 16, 31, 0, 16, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_212[30] = { 29, 31, 2, 29, 31, 23, 31, 31, 27, 15, 31, 24, 15, 31, 29, 15, 15, 28, 7, 15, 24, 3, 7, 28, 1, 3, 31, 1, 1, 30 };
static const unsigned char earth_clouds_char_213[30] = { 31, 28, 12, 31, 12, 4, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 4, 0, 31, 6, 0, 31, 1, 1, 16, 30, 15 };
static const unsigned char earth_clouds_char_214[30] = { 31, 13, 1, 31, 13, 0, 31, 1, 0, 31, 1, 1, 31, 1, 1, 30, 3, 1, 22, 27, 9, 16, 23, 31, 0, 16, 31, 0, 16, 31 };
static const unsigned char earth_clouds_char_215[30] = { 28, 7, 7, 31, 23, 3, 31, 3, 3, 31, 3, 0, 30, 3, 1, 28, 2, 3, 28, 4, 7, 24, 8, 15, 16, 8, 15, 0, 0, 31 };
static const unsigned char earth_clouds_char_216[30] = { 31, 31, 0, 31, 7, 0, 31, 0, 0, 31, 16, 16, 15, 8, 24, 15, 8, 16, 15, 0, 16, 15, 16, 16, 15, 16, 16, 31, 16, 0 };
static const unsigned char earth_clouds_char_217[30] = { 31, 6, 0, 31, 4, 0, 31, 3, 0, 28, 4, 7, 16, 24, 15, 0, 16, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_218[30] = { 31, 28, 24, 17, 27, 15, 0, 16, 31, 0, 0, 31, 0, 0, 31, 0, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_219[30] = { 31, 31, 15, 31, 31, 15, 31, 31, 7, 31, 15, 7, 31, 15, 7, 31, 7, 7, 31, 7, 5, 31, 1, 1, 31, 1, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_220[30] = { 30, 31, 0, 28, 31, 2, 24, 31, 4, 18, 31, 4, 18, 31, 2, 18, 31, 2, 17, 31, 0, 25, 31, 0, 31, 15, 0, 31, 4, 0 };
static const unsigned char earth_clouds_char_221[30] = { 30, 7, 3, 30, 3, 3, 28, 3, 3, 30, 3, 1, 31, 1, 1, 31, 1, 1, 31, 3, 1, 31, 1, 0, 31, 1, 0, 31, 17, 0 };
static const unsigned char earth_clouds_char_222[30] = { 25, 31, 15, 30, 15, 7, 30, 2, 3, 30, 2, 3, 28, 2, 3, 28, 6, 3, 30, 15, 3, 31, 1, 0, 31, 1, 0, 31, 8, 0 };
static const unsigned char earth_clouds_char_223[30] = { 31, 3, 1, 30, 3, 3, 31, 3, 2, 31, 7, 2, 31, 7, 6, 31, 11, 1, 30, 31, 3, 31, 7, 0, 31, 7, 0, 31, 7, 3 };
static const unsigned char earth_clouds_char_224[30] = { 31, 4, 0, 31, 6, 0, 27, 30, 28, 3, 3, 31, 0, 2, 31, 0, 2, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_225[30] = { 28, 5, 3, 28, 19, 3, 28, 3, 3, 28, 3, 3, 28, 3, 3, 28, 3, 3, 28, 7, 3, 28, 3, 1, 28, 7, 0, 31, 3, 2 };
static const unsigned char earth_clouds_char_226[30] = { 7, 31, 1, 1, 31, 24, 0, 7, 28, 4, 31, 28, 8, 31, 31, 9, 31, 31, 0, 31, 30, 0, 31, 26, 1, 31, 30, 0, 31, 30 };
static const unsigned char earth_clouds_char_227[30] = { 31, 0, 0, 31, 0, 0, 31, 9, 1, 30, 1, 1, 31, 7, 1, 31, 6, 2, 31, 28, 28, 7, 12, 24, 31, 24, 16, 31, 16, 0 };
static const unsigned char earth_clouds_char_228[30] = { 31, 3, 1, 31, 3, 1, 31, 3, 0, 31, 0, 0, 31, 0, 0, 30, 26, 17, 12, 30, 23, 0, 30, 31, 0, 6, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_229[30] = { 31, 16, 16, 31, 24, 16, 31, 24, 16, 15, 24, 24, 15, 24, 16, 15, 25, 16, 31, 22, 16, 15, 25, 16, 15, 25, 24, 15, 29, 24 };
static const unsigned char earth_clouds_char_230[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 15, 31, 1, 31, 0, 31, 31, 0, 31, 23, 0 };
static const unsigned char earth_clouds_char_231[30] = { 7, 15, 27, 15, 14, 24, 15, 26, 24, 15, 24, 16, 31, 16, 16, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_232[30] = { 31, 29, 24, 31, 24, 16, 31, 16, 16, 31, 17, 0, 31, 25, 1, 31, 3, 1, 31, 3, 1, 31, 3, 1, 31, 3, 1, 31, 5, 1 };
static const unsigned char earth_clouds_char_233[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 22, 0, 27, 31, 6, 23, 31, 28, 31, 9, 0, 31, 0, 0 };
static const unsigned char earth_clouds_char_234[30] = { 31, 16, 16, 31, 16, 0, 31, 16, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 15, 8, 16, 7, 30, 24 };
static const unsigned char earth_clouds_char_235[30] = { 3, 23, 29, 1, 7, 31, 0, 19, 31, 0, 17, 31, 0, 17, 31, 0, 17, 31, 0, 25, 31, 0, 20, 31, 16, 20, 31, 0, 16, 31 };
static const unsigned char earth_clouds_char_236[30] = { 31, 31, 0, 31, 31, 8, 31, 30, 28, 31, 28, 0, 31, 24, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0, 31, 14, 4, 31, 14, 14 };
static const unsigned char earth_clouds_char_237[30] = { 0, 31, 0, 2, 31, 0, 0, 31, 0, 1, 31, 0, 2, 31, 0, 6, 31, 0, 31, 28, 0, 15, 27, 0, 15, 28, 0, 15, 28, 0 };
static const unsigned char earth_clouds_char_238[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 9, 31, 25, 31, 15, 16, 27, 31, 0, 15, 31, 3, 7, 31 };
static const unsigned char earth_clouds_char_239[30] = { 0, 31, 31, 0, 31, 31, 8, 31, 31, 16, 31, 31, 16, 31, 15, 24, 15, 15, 30, 15, 7, 31, 7, 3, 31, 3, 1, 31, 1, 0 };
static const unsigned char earth_clouds_char_240[30] = { 3, 15, 31, 1, 31, 31, 0, 31, 31, 0, 31, 31, 2, 31, 31, 0, 31, 15, 15, 31, 15, 15, 31, 2, 31, 31, 0, 31, 18, 0 };
static const unsigned char earth_clouds_char_241[30] = { 31, 26, 16, 23, 31, 13, 27, 31, 12, 31, 29, 8, 31, 19, 0, 31, 2, 0, 31, 4, 0, 31, 0, 0, 31, 16, 0, 31, 16, 0 };
static const unsigned char earth_clouds_char_242[30] = { 25, 31, 12, 24, 31, 0, 28, 23, 0, 30, 31, 6, 25, 31, 6, 24, 31, 6, 24, 31, 7, 24, 29, 15, 16, 29, 31, 16, 31, 29 };
static const unsigned char earth_clouds_char_243[30] = { 31, 31, 6, 28, 23, 3, 31, 16, 0, 31, 16, 0, 31, 24, 0, 31, 28, 0, 31, 28, 0, 31, 28, 0, 31, 6, 0, 31, 28, 0 };
static const unsigned char earth_clouds_char_244[30] = { 31, 16, 0, 31, 0, 0, 31, 0, 0, 23, 8, 8, 7, 24, 24, 12, 15, 31, 8, 8, 31, 0, 8, 31, 0, 8, 31, 0, 16, 31 };
static const unsigned char earth_clouds_char_245[30] = { 31, 3, 1, 31, 3, 3, 12, 28, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_clouds_char_246[30] = { 0, 15, 31, 1, 15, 19, 1, 31, 30, 1, 31, 31, 0, 31, 8, 19, 31, 0, 31, 31, 0, 31, 31, 0, 31, 29, 0, 31, 17, 0 };
static const unsigned char earth_clouds_char_247[30] = { 31, 31, 26, 31, 31, 28, 23, 31, 30, 23, 30, 24, 15, 28, 24, 15, 26, 16, 15, 24, 16, 31, 24, 16, 31, 16, 0, 31, 16, 0 };
static const unsigned char earth_clouds_char_248[30] = { 29, 7, 1, 24, 31, 1, 28, 31, 1, 28, 31, 1, 22, 31, 0, 30, 31, 0, 1, 31, 1, 1, 31, 25, 1, 31, 3, 0, 31, 6 };
static const unsigned char earth_clouds_char_249[30] = { 27, 31, 0, 29, 31, 0, 7, 31, 0, 3, 31, 16, 7, 15, 16, 7, 29, 24, 3, 31, 24, 21, 31, 16, 23, 31, 16, 15, 31, 12 };
static const unsigned char earth_clouds_char_250[30] = { 31, 20, 0, 31, 16, 0, 31, 16, 0, 15, 16, 0, 15, 24, 0, 23, 28, 16, 19, 30, 0, 23, 28, 0, 31, 28, 16, 23, 31, 16 };
static const unsigned char earth_clouds_char_251[30] = { 16, 29, 3, 12, 29, 3, 12, 31, 3, 12, 31, 3, 28, 31, 1, 26, 31, 0, 30, 7, 0, 31, 23, 0, 31, 23, 0, 25, 31, 0 };
static const unsigned char earth_clouds_char_252[30] = { 31, 8, 0, 31, 8, 0, 31, 8, 0, 31, 24, 0, 31, 18, 0, 31, 31, 0, 31, 31, 23, 31, 31, 24, 15, 31, 31, 29, 15, 15 };
static const unsigned char earth_clouds_char_253[30] = { 7, 30, 28, 7, 28, 24, 15, 24, 24, 31, 30, 16, 31, 31, 0, 31, 31, 0, 31, 31, 8, 27, 31, 30, 25, 31, 31, 29, 31, 15 };
static const unsigned char earth_clouds_char_254[30] = { 15, 28, 16, 15, 20, 16, 15, 25, 16, 15, 28, 16, 15, 31, 25, 31, 31, 19, 31, 31, 23, 29, 31, 23, 29, 31, 23, 31, 31, 31 };
static const unsigned char earth_clouds_char_255[30] = { 31, 6, 4, 31, 15, 2, 31, 7, 3, 30, 7, 1, 31, 3, 1, 31, 3, 1, 31, 3, 3, 31, 7, 3, 31, 7, 1, 31, 3, 1 };

const unsigned char * const earth_clouds_charset[256] = {
    earth_clouds_char_000,
    earth_clouds_char_001,
    earth_clouds_char_002,
    earth_clouds_char_003,
    earth_clouds_char_004,
    earth_clouds_char_005,
    earth_clouds_char_006,
    earth_clouds_char_007,
    earth_clouds_char_008,
    earth_clouds_char_009,
    earth_clouds_char_010,
    earth_clouds_char_011,
    earth_clouds_char_012,
    earth_clouds_char_013,
    earth_clouds_char_014,
    earth_clouds_char_015,
    earth_clouds_char_016,
    earth_clouds_char_017,
    earth_clouds_char_018,
    earth_clouds_char_019,
    earth_clouds_char_020,
    earth_clouds_char_021,
    earth_clouds_char_022,
    earth_clouds_char_023,
    earth_clouds_char_024,
    earth_clouds_char_025,
    earth_clouds_char_026,
    earth_clouds_char_027,
    earth_clouds_char_028,
    earth_clouds_char_029,
    earth_clouds_char_030,
    earth_clouds_char_031,
    earth_clouds_char_032,
    earth_clouds_char_033,
    earth_clouds_char_034,
    earth_clouds_char_035,
    earth_clouds_char_036,
    earth_clouds_char_037,
    earth_clouds_char_038,
    earth_clouds_char_039,
    earth_clouds_char_040,
    earth_clouds_char_041,
    earth_clouds_char_042,
    earth_clouds_char_043,
    earth_clouds_char_044,
    earth_clouds_char_045,
    earth_clouds_char_046,
    earth_clouds_char_047,
    earth_clouds_char_048,
    earth_clouds_char_049,
    earth_clouds_char_050,
    earth_clouds_char_051,
    earth_clouds_char_052,
    earth_clouds_char_053,
    earth_clouds_char_054,
    earth_clouds_char_055,
    earth_clouds_char_056,
    earth_clouds_char_057,
    earth_clouds_char_058,
    earth_clouds_char_059,
    earth_clouds_char_060,
    earth_clouds_char_061,
    earth_clouds_char_062,
    earth_clouds_char_063,
    earth_clouds_char_064,
    earth_clouds_char_065,
    earth_clouds_char_066,
    earth_clouds_char_067,
    earth_clouds_char_068,
    earth_clouds_char_069,
    earth_clouds_char_070,
    earth_clouds_char_071,
    earth_clouds_char_072,
    earth_clouds_char_073,
    earth_clouds_char_074,
    earth_clouds_char_075,
    earth_clouds_char_076,
    earth_clouds_char_077,
    earth_clouds_char_078,
    earth_clouds_char_079,
    earth_clouds_char_080,
    earth_clouds_char_081,
    earth_clouds_char_082,
    earth_clouds_char_083,
    earth_clouds_char_084,
    earth_clouds_char_085,
    earth_clouds_char_086,
    earth_clouds_char_087,
    earth_clouds_char_088,
    earth_clouds_char_089,
    earth_clouds_char_090,
    earth_clouds_char_091,
    earth_clouds_char_092,
    earth_clouds_char_093,
    earth_clouds_char_094,
    earth_clouds_char_095,
    earth_clouds_char_096,
    earth_clouds_char_097,
    earth_clouds_char_098,
    earth_clouds_char_099,
    earth_clouds_char_100,
    earth_clouds_char_101,
    earth_clouds_char_102,
    earth_clouds_char_103,
    earth_clouds_char_104,
    earth_clouds_char_105,
    earth_clouds_char_106,
    earth_clouds_char_107,
    earth_clouds_char_108,
    earth_clouds_char_109,
    earth_clouds_char_110,
    earth_clouds_char_111,
    earth_clouds_char_112,
    earth_clouds_char_113,
    earth_clouds_char_114,
    earth_clouds_char_115,
    earth_clouds_char_116,
    earth_clouds_char_117,
    earth_clouds_char_118,
    earth_clouds_char_119,
    earth_clouds_char_120,
    earth_clouds_char_121,
    earth_clouds_char_122,
    earth_clouds_char_123,
    earth_clouds_char_124,
    earth_clouds_char_125,
    earth_clouds_char_126,
    earth_clouds_char_127,
    earth_clouds_char_128,
    earth_clouds_char_129,
    earth_clouds_char_130,
    earth_clouds_char_131,
    earth_clouds_char_132,
    earth_clouds_char_133,
    earth_clouds_char_134,
    earth_clouds_char_135,
    earth_clouds_char_136,
    earth_clouds_char_137,
    earth_clouds_char_138,
    earth_clouds_char_139,
    earth_clouds_char_140,
    earth_clouds_char_141,
    earth_clouds_char_142,
    earth_clouds_char_143,
    earth_clouds_char_144,
    earth_clouds_char_145,
    earth_clouds_char_146,
    earth_clouds_char_147,
    earth_clouds_char_148,
    earth_clouds_char_149,
    earth_clouds_char_150,
    earth_clouds_char_151,
    earth_clouds_char_152,
    earth_clouds_char_153,
    earth_clouds_char_154,
    earth_clouds_char_155,
    earth_clouds_char_156,
    earth_clouds_char_157,
    earth_clouds_char_158,
    earth_clouds_char_159,
    earth_clouds_char_160,
    earth_clouds_char_161,
    earth_clouds_char_162,
    earth_clouds_char_163,
    earth_clouds_char_164,
    earth_clouds_char_165,
    earth_clouds_char_166,
    earth_clouds_char_167,
    earth_clouds_char_168,
    earth_clouds_char_169,
    earth_clouds_char_170,
    earth_clouds_char_171,
    earth_clouds_char_172,
    earth_clouds_char_173,
    earth_clouds_char_174,
    earth_clouds_char_175,
    earth_clouds_char_176,
    earth_clouds_char_177,
    earth_clouds_char_178,
    earth_clouds_char_179,
    earth_clouds_char_180,
    earth_clouds_char_181,
    earth_clouds_char_182,
    earth_clouds_char_183,
    earth_clouds_char_184,
    earth_clouds_char_185,
    earth_clouds_char_186,
    earth_clouds_char_187,
    earth_clouds_char_188,
    earth_clouds_char_189,
    earth_clouds_char_190,
    earth_clouds_char_191,
    earth_clouds_char_192,
    earth_clouds_char_193,
    earth_clouds_char_194,
    earth_clouds_char_195,
    earth_clouds_char_196,
    earth_clouds_char_197,
    earth_clouds_char_198,
    earth_clouds_char_199,
    earth_clouds_char_200,
    earth_clouds_char_201,
    earth_clouds_char_202,
    earth_clouds_char_203,
    earth_clouds_char_204,
    earth_clouds_char_205,
    earth_clouds_char_206,
    earth_clouds_char_207,
    earth_clouds_char_208,
    earth_clouds_char_209,
    earth_clouds_char_210,
    earth_clouds_char_211,
    earth_clouds_char_212,
    earth_clouds_char_213,
    earth_clouds_char_214,
    earth_clouds_char_215,
    earth_clouds_char_216,
    earth_clouds_char_217,
    earth_clouds_char_218,
    earth_clouds_char_219,
    earth_clouds_char_220,
    earth_clouds_char_221,
    earth_clouds_char_222,
    earth_clouds_char_223,
    earth_clouds_char_224,
    earth_clouds_char_225,
    earth_clouds_char_226,
    earth_clouds_char_227,
    earth_clouds_char_228,
    earth_clouds_char_229,
    earth_clouds_char_230,
    earth_clouds_char_231,
    earth_clouds_char_232,
    earth_clouds_char_233,
    earth_clouds_char_234,
    earth_clouds_char_235,
    earth_clouds_char_236,
    earth_clouds_char_237,
    earth_clouds_char_238,
    earth_clouds_char_239,
    earth_clouds_char_240,
    earth_clouds_char_241,
    earth_clouds_char_242,
    earth_clouds_char_243,
    earth_clouds_char_244,
    earth_clouds_char_245,
    earth_clouds_char_246,
    earth_clouds_char_247,
    earth_clouds_char_248,
    earth_clouds_char_249,
    earth_clouds_char_250,
    earth_clouds_char_251,
    earth_clouds_char_252,
    earth_clouds_char_253,
    earth_clouds_char_254,
    earth_clouds_char_255,
};

const unsigned char earth_clouds_map[882] = {
    40, 22,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 8, 9, 10, 11, 4, 12, 13, 4, 4, 14, 238, 238, 15, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 9, 10,
    4, 4, 4, 4, 4, 4, 16, 6, 17, 18, 4, 4, 4, 19, 20, 7, 21, 22, 23, 24, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 16, 6, 17, 18,
    25, 6, 4, 26, 27, 28, 235, 29, 30, 31, 32, 4, 33, 34, 35, 7, 36, 37, 38, 39, 40, 4, 4, 41, 42, 43, 6, 44, 230, 230, 25, 6, 4, 26, 27, 28, 235, 29, 30, 31,
    45, 6, 6, 46, 2, 47, 6, 240, 48, 49, 50, 51, 52, 240, 53, 235, 54, 246, 55, 2, 238, 2, 3, 56, 3, 251, 57, 58, 3, 3, 45, 6, 6, 46, 2, 47, 6, 240, 48, 49,
    7, 7, 7, 59, 60, 61, 62, 3, 3, 3, 63, 64, 65, 236, 66, 67, 3, 68, 249, 69, 70, 71, 72, 73, 74, 237, 3, 232, 75, 7, 7, 7, 7, 59, 60, 61, 62, 3, 3, 3,
    76, 247, 1, 253, 242, 77, 237, 78, 249, 3, 1, 79, 80, 3, 81, 3, 3, 237, 220, 82, 2, 242, 83, 2, 2, 84, 85, 3, 7, 6, 76, 247, 1, 253, 242, 77, 237, 78, 249, 3,
    86, 1, 255, 87, 88, 2, 3, 248, 89, 90, 227, 1, 1, 241, 91, 92, 1, 1, 93, 94, 3, 95, 226, 96, 97, 98, 99, 222, 100, 231, 86, 1, 255, 87, 88, 2, 3, 248, 89, 90,
    1, 1, 1, 101, 3, 102, 3, 236, 243, 1, 1, 1, 1, 103, 104, 105, 106, 107, 108, 109, 110, 111, 6, 6, 2, 234, 1, 1, 1, 1, 1, 1, 1, 101, 3, 102, 3, 236, 243, 1,
    1, 1, 1, 1, 1, 1, 1, 112, 1, 113, 1, 1, 1, 225, 6, 6, 6, 6, 114, 115, 255, 116, 232, 117, 118, 119, 120, 121, 122, 234, 1, 1, 1, 1, 1, 1, 1, 112, 1, 113,
    1, 123, 124, 1, 1, 1, 125, 3, 126, 2, 127, 128, 129, 1, 130, 131, 132, 133, 134, 1, 223, 135, 136, 137, 138, 139, 140, 141, 142, 241, 1, 123, 124, 1, 1, 1, 125, 3, 126, 2,
    233, 143, 1, 1, 1, 1, 3, 7, 144, 145, 1, 3, 1, 1, 1, 243, 3, 3, 146, 1, 147, 148, 149, 1, 241, 150, 151, 152, 243, 233, 233, 143, 1, 1, 1, 1, 3, 7, 144, 145,
    1, 1, 153, 1, 1, 3, 241, 3, 7, 250, 1, 154, 234, 3, 1, 1, 2, 248, 155, 1, 1, 3, 156, 157, 1, 158, 159, 160, 161, 162, 1, 1, 153, 1, 1, 3, 241, 3, 7, 250,
    1, 163, 221, 239, 231, 3, 1, 219, 237, 251, 3, 221, 164, 3, 250, 1, 7, 165, 166, 167, 234, 241, 3, 243, 255, 168, 220, 169, 1, 170, 1, 163, 221, 239, 231, 3, 1, 219, 237, 251,
    1, 225, 229, 3, 252, 3, 3, 3, 171, 3, 172, 173, 174, 3, 175, 223, 241, 176, 250, 1, 177, 178, 1, 241, 7, 179, 180, 181, 227, 3, 1, 225, 229, 3, 252, 3, 3, 3, 171, 3,
    229, 182, 226, 183, 184, 7, 7, 185, 186, 253, 187, 188, 7, 7, 248, 7, 254, 189, 254, 190, 1, 222, 191, 255, 249, 1, 3, 221, 250, 192, 229, 182, 226, 183, 184, 7, 7, 185, 186, 253,
    193, 194, 234, 252, 7, 7, 240, 195, 196, 197, 252, 7, 7, 198, 7, 7, 7, 199, 7, 6, 200, 234, 6, 7, 201, 7, 7, 254, 202, 3, 193, 194, 234, 252, 7, 7, 240, 195, 196, 197,
    7, 3, 239, 203, 204, 241, 3, 205, 7, 206, 247, 219, 246, 3, 239, 246, 3, 6, 207, 208, 4, 4, 4, 4, 245, 209, 210, 211, 212, 3, 7, 3, 239, 203, 204, 241, 3, 205, 7, 206,
    1, 1, 1, 213, 214, 228, 244, 228, 245, 4, 3, 1, 1, 215, 245, 245, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 216, 1, 1, 1, 213, 214, 228, 244, 228, 245, 4,
    217, 224, 245, 4, 4, 4, 4, 4, 4, 4, 224, 218, 245, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 244, 217, 224, 245, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
};

