/* Auto-generated by spinningGlobe/cset.py from "earth.jpg" */
#pragma once

#define EARTH_CHARSET_SIZE 73
#define EARTH_MAP_SIZE     122
#define EARTH_CHAR_WIDTH   5
#define EARTH_CHAR_HEIGHT  10
#define EARTH_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char earth_ntsc_palette[3];

/* Charset: 73 characters, each 30 bytes */
extern const unsigned char * const earth_charset[73];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char earth_map[122];


