/* Auto-generated by img2tiles.py from "earth_clouds.jpg" */
#pragma once

#define EARTH_CLOUDS_CHARSET_SIZE 256
#define EARTH_CLOUDS_MAP_SIZE     882
#define EARTH_CLOUDS_CHAR_WIDTH   5
#define EARTH_CLOUDS_CHAR_HEIGHT  10
#define EARTH_CLOUDS_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char earth_clouds_ntsc_palette[3];

/* Charset: 256 characters, each 30 bytes */
extern const unsigned char * const earth_clouds_charset[256];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char earth_clouds_map[882];


