/* Auto-generated by img2tiles.py from "earth.jpg" */
/* Adaptive palette: 8 colours built from 3 EM-optimised primaries (NTSC-snapped). */
/* Index bits: bit0=P1, bit1=P2, bit2=P3 (P1/P2/P3 = single-bit primaries). */
/* Character: 5 pixels wide x 10 trixels deep (30 scanlines). */
/* Trixel: 1 pixel wide x 3 scanlines deep, 3-bit palette index. */
/* Character storage: 10 trixel-rows x 3 bytes (bit0-plane, bit1-plane, bit2-plane) = 30 bytes. */
/* Byte bit layout: bit4=col0(left) .. bit0=col4(right), bits7-5 unused. */
/* Map: byte0=width(chars, +10 wrap buffer), byte1=height(chars), then row-major indices. */

static const unsigned char earth_palette[8][3] = {
    {   0,   0,   0 },  /* 0: origin */
    {  28,  76, 120 },  /* 1: +P1 */
    { 108, 108, 108 },  /* 2: +P2 */
    {  68,  92, 114 },  /* 3: +P1+P2 */
    { 220, 220, 220 },  /* 4: +P3 */
    { 124, 148, 170 },  /* 5: +P1+P3 */
    { 164, 164, 164 },  /* 6: +P2+P3 */
    { 119, 135, 149 },  /* 7: +P1+P2+P3 */
};

/* NTSC Atari 2600 companion palette: nearest TIA register values for
 * palette primaries (indices 1, 2, 4 — the single-bit entries). */
const unsigned char earth_ntsc_palette[3] = {
    0xA2,  /* palette[1] = (28,76,120) */
    0x04,  /* palette[2] = (108,108,108) */
    0x0C,  /* palette[4] = (220,220,220) */
};

static const unsigned char earth_char_000[30] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static const unsigned char earth_char_001[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_002[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char earth_char_003[30] = { 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0 };
static const unsigned char earth_char_004[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_005[30] = { 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31 };
static const unsigned char earth_char_006[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char earth_char_007[30] = { 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31 };
static const unsigned char earth_char_008[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 6, 31, 7, 31, 16, 0, 31, 0, 30, 15, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_009[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 7, 31, 28, 31, 0, 0, 31, 0, 8, 31, 0, 15, 24, 0, 31, 8, 0, 31, 0, 0 };
static const unsigned char earth_char_010[30] = { 0, 0, 31, 0, 0, 31, 0, 1, 31, 31, 13, 24, 2, 31, 3, 0, 31, 0, 23, 31, 16, 29, 15, 0, 31, 31, 0, 28, 7, 0 };
static const unsigned char earth_char_011[30] = { 0, 0, 31, 0, 0, 31, 7, 25, 31, 30, 29, 23, 4, 31, 7, 30, 31, 0, 31, 31, 0, 17, 31, 0, 25, 31, 0, 6, 31, 6 };
static const unsigned char earth_char_012[30] = { 0, 0, 31, 0, 0, 31, 23, 25, 30, 0, 7, 31, 0, 31, 31, 8, 31, 0, 31, 31, 0, 31, 31, 0, 24, 31, 0, 0, 31, 2 };
static const unsigned char earth_char_013[30] = { 0, 0, 31, 0, 0, 31, 31, 0, 0, 15, 28, 24, 1, 31, 31, 29, 31, 0, 31, 31, 0, 30, 31, 0, 0, 31, 0, 16, 31, 16 };
static const unsigned char earth_char_014[30] = { 0, 0, 31, 0, 15, 31, 31, 14, 0, 31, 19, 1, 14, 31, 16, 17, 31, 0, 31, 31, 0, 3, 31, 0, 0, 31, 0, 2, 31, 15 };
static const unsigned char earth_char_015[30] = { 0, 0, 31, 0, 31, 31, 31, 0, 0, 31, 0, 0, 31, 16, 0, 31, 31, 0, 31, 31, 0, 15, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char earth_char_016[30] = { 0, 0, 31, 0, 16, 31, 31, 7, 3, 31, 0, 0, 31, 31, 0, 31, 31, 0, 31, 16, 0, 31, 30, 0, 0, 31, 0, 16, 31, 0 };
static const unsigned char earth_char_017[30] = { 0, 0, 31, 0, 15, 31, 31, 8, 24, 31, 0, 0, 31, 16, 0, 15, 24, 0, 27, 14, 0, 31, 12, 0, 3, 31, 0, 24, 31, 0 };
static const unsigned char earth_char_018[30] = { 0, 0, 31, 0, 30, 31, 31, 1, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 31, 0, 0, 31, 24, 0, 15, 28, 0, 31, 16, 0 };
static const unsigned char earth_char_019[30] = { 0, 0, 31, 0, 16, 31, 16, 0, 31, 16, 24, 15, 28, 10, 7, 31, 17, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_020[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 1, 31, 17, 25, 30, 31, 2, 4, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_021[30] = { 0, 0, 31, 0, 0, 31, 0, 1, 31, 15, 24, 16, 30, 3, 1, 28, 7, 3, 31, 3, 1, 28, 7, 4, 31, 15, 0, 31, 1, 0 };
static const unsigned char earth_char_022[30] = { 0, 0, 31, 0, 0, 31, 16, 8, 31, 24, 14, 15, 12, 19, 31, 31, 16, 19, 15, 24, 24, 15, 25, 0, 31, 31, 0, 31, 28, 0 };
static const unsigned char earth_char_023[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31, 31, 5, 27, 31, 16, 15, 0, 31, 31, 0, 28, 15, 0, 16, 31, 0 };
static const unsigned char earth_char_024[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 31, 7, 27, 31, 3, 31, 0, 31, 31, 0, 31, 31, 0, 7, 31, 0, 5, 30, 0 };
static const unsigned char earth_char_025[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 30, 31, 31, 31, 0, 1, 31, 0, 8, 31, 0, 31, 24, 0, 31, 16, 0, 31, 0, 0 };
static const unsigned char earth_char_026[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31, 0, 22, 31, 0, 27, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_027[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 12, 31, 7, 29, 23, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_028[30] = { 31, 3, 0, 31, 9, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_029[30] = { 0, 31, 3, 24, 15, 0, 16, 15, 0, 25, 15, 0, 28, 7, 0, 31, 1, 0, 31, 8, 0, 31, 0, 0, 31, 0, 0, 31, 6, 0 };
static const unsigned char earth_char_030[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 3, 1, 31, 1, 6, 31, 0, 25, 30, 0, 3, 30, 0, 15, 24, 0, 31, 0, 0, 31, 12, 0 };
static const unsigned char earth_char_031[30] = { 4, 31, 28, 0, 31, 31, 0, 31, 30, 0, 31, 25, 2, 31, 3, 16, 31, 0, 25, 7, 2, 29, 6, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_032[30] = { 0, 30, 15, 0, 31, 15, 0, 31, 31, 0, 31, 31, 5, 31, 17, 30, 18, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_033[30] = { 27, 30, 16, 22, 31, 6, 0, 29, 31, 16, 27, 31, 16, 19, 30, 3, 3, 30, 19, 31, 29, 26, 15, 10, 24, 15, 12, 24, 7, 0 };
static const unsigned char earth_char_034[30] = { 24, 23, 0, 7, 30, 0, 31, 18, 0, 0, 24, 31, 16, 16, 31, 0, 17, 31, 0, 27, 31, 0, 31, 4, 2, 31, 0, 15, 31, 0 };
static const unsigned char earth_char_035[30] = { 31, 29, 0, 31, 4, 0, 16, 13, 7, 0, 21, 31, 0, 15, 31, 0, 0, 31, 0, 7, 31, 16, 31, 28, 1, 31, 0, 31, 28, 0 };
static const unsigned char earth_char_036[30] = { 7, 28, 0, 7, 28, 0, 7, 28, 16, 3, 14, 28, 1, 9, 30, 1, 0, 31, 0, 31, 30, 1, 31, 0, 7, 28, 0, 31, 0, 0 };
static const unsigned char earth_char_037[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0 };
static const unsigned char earth_char_038[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 7, 0, 24, 15, 0, 31, 31, 0 };
static const unsigned char earth_char_039[30] = { 28, 31, 0, 28, 15, 0, 31, 7, 0, 31, 6, 0, 31, 4, 0, 31, 0, 0, 31, 1, 0, 31, 18, 0, 15, 24, 0, 31, 24, 0 };
static const unsigned char earth_char_040[30] = { 1, 31, 1, 1, 31, 1, 16, 31, 3, 24, 15, 3, 24, 7, 2, 25, 6, 0, 31, 28, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_041[30] = { 17, 30, 16, 1, 30, 28, 19, 28, 24, 7, 24, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_042[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 8, 0, 31, 4, 0 };
static const unsigned char earth_char_043[30] = { 31, 0, 0, 31, 1, 0, 31, 0, 0, 31, 1, 0, 30, 3, 0, 28, 7, 0, 28, 7, 0, 28, 3, 0, 31, 1, 0, 31, 0, 0 };
static const unsigned char earth_char_044[30] = { 31, 8, 0, 31, 24, 0, 31, 6, 0, 8, 31, 0, 0, 31, 0, 16, 31, 24, 0, 31, 8, 7, 28, 0, 31, 16, 0, 31, 0, 0 };
static const unsigned char earth_char_045[30] = { 31, 2, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 7, 28, 0, 3, 30, 0, 3, 28, 0, 31, 28, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_046[30] = { 31, 8, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_047[30] = { 30, 3, 0, 30, 1, 0, 30, 1, 0, 30, 13, 0, 27, 12, 0, 31, 4, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_048[30] = { 7, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 31, 3, 16, 15, 1, 31, 7, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_049[30] = { 15, 24, 0, 15, 24, 0, 15, 16, 0, 7, 24, 0, 15, 24, 16, 31, 16, 16, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_050[30] = { 31, 15, 0, 1, 31, 0, 17, 31, 0, 16, 15, 0, 24, 15, 0, 30, 3, 0, 30, 1, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_051[30] = { 31, 31, 0, 31, 31, 0, 31, 31, 0, 13, 31, 1, 9, 31, 3, 4, 31, 2, 0, 31, 0, 0, 31, 0, 24, 15, 0, 28, 3, 0 };
static const unsigned char earth_char_052[30] = { 31, 12, 0, 31, 12, 0, 7, 24, 0, 15, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char earth_char_053[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 3, 1, 30, 3, 3, 31, 19, 31, 0, 31, 31, 0, 0, 31 };
static const unsigned char earth_char_054[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 16, 12, 31, 0, 0, 31, 0, 16, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_055[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 7, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_056[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 18, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_057[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 14, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_058[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0, 1, 2, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_059[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 1, 16, 24, 31, 0, 8, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_060[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 16, 1, 2, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_061[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 15, 23, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_062[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_063[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 28, 24, 0, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_064[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 15, 28, 24, 1, 2, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_065[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 6, 31, 6, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_066[30] = { 30, 3, 0, 30, 1, 0, 31, 0, 0, 31, 0, 0, 31, 14, 4, 25, 8, 7, 24, 8, 15, 3, 31, 3, 0, 30, 31, 0, 0, 31 };
static const unsigned char earth_char_067[30] = { 15, 16, 0, 15, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 0, 14, 31, 0, 24, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_068[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 3, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_069[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 30, 17, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_070[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 7, 30, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char earth_char_071[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 3, 13, 31, 0, 7, 31, 0, 0, 31 };
static const unsigned char earth_char_072[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 31, 0, 31, 31, 0, 0, 31 };

const unsigned char * const earth_charset[73] = {
    earth_char_000,
    earth_char_001,
    earth_char_002,
    earth_char_003,
    earth_char_004,
    earth_char_005,
    earth_char_006,
    earth_char_007,
    earth_char_008,
    earth_char_009,
    earth_char_010,
    earth_char_011,
    earth_char_012,
    earth_char_013,
    earth_char_014,
    earth_char_015,
    earth_char_016,
    earth_char_017,
    earth_char_018,
    earth_char_019,
    earth_char_020,
    earth_char_021,
    earth_char_022,
    earth_char_023,
    earth_char_024,
    earth_char_025,
    earth_char_026,
    earth_char_027,
    earth_char_028,
    earth_char_029,
    earth_char_030,
    earth_char_031,
    earth_char_032,
    earth_char_033,
    earth_char_034,
    earth_char_035,
    earth_char_036,
    earth_char_037,
    earth_char_038,
    earth_char_039,
    earth_char_040,
    earth_char_041,
    earth_char_042,
    earth_char_043,
    earth_char_044,
    earth_char_045,
    earth_char_046,
    earth_char_047,
    earth_char_048,
    earth_char_049,
    earth_char_050,
    earth_char_051,
    earth_char_052,
    earth_char_053,
    earth_char_054,
    earth_char_055,
    earth_char_056,
    earth_char_057,
    earth_char_058,
    earth_char_059,
    earth_char_060,
    earth_char_061,
    earth_char_062,
    earth_char_063,
    earth_char_064,
    earth_char_065,
    earth_char_066,
    earth_char_067,
    earth_char_068,
    earth_char_069,
    earth_char_070,
    earth_char_071,
    earth_char_072,
};

const unsigned char earth_map[122] = {
    30, 4,
    8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
    1, 1, 28, 29, 30, 31, 32, 33, 34, 35, 36, 1, 37, 38, 39, 40, 41, 1, 1, 1, 1, 1, 28, 29, 30, 31, 32, 33, 34, 35,
    42, 43, 44, 45, 46, 1, 1, 47, 48, 49, 1, 1, 50, 51, 52, 1, 1, 1, 1, 1, 42, 43, 44, 45, 46, 1, 1, 47, 48, 49,
    53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
};

