/* Auto-generated by spinningGlobe/cset.py from "green1.png" */
#pragma once

#define GREEN1_CHARSET_SIZE 88
#define GREEN1_MAP_SIZE     122
#define GREEN1_CHAR_WIDTH   5
#define GREEN1_CHAR_HEIGHT  10
#define GREEN1_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char green1_ntsc_palette[3];

/* Charset: 88 characters, each 30 bytes */
extern const unsigned char * const green1_charset[88];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char green1_map[122];


