/* Auto-generated by img2tiles.py from "io.jpg" */
/* Adaptive palette: 8 colours built from 3 EM-optimised primaries (NTSC-snapped). */
/* Index bits: bit0=P1, bit1=P2, bit2=P3 (P1/P2/P3 = single-bit primaries). */
/* Character: 4 pixels wide x 4 trixels deep (12 scanlines). */
/* Trixel: 1 pixel wide x 3 scanlines deep, 3-bit palette index. */
/* Character storage: 4 trixel-rows x 3 bytes (bit0-plane, bit1-plane, bit2-plane) = 12 bytes. */
/* Byte bit layout: bit3=col0(left) .. bit0=col3(right), bits7-4 unused. */
/* Map: byte0=width(chars, +10 wrap buffer), byte1=height(chars), then row-major indices. */

static const unsigned char io_palette[8][3] = {
    {   0,   0,   0 },  /* 0: origin */
    { 132, 104,  48 },  /* 1: +P1 */
    { 172, 120,  64 },  /* 2: +P2 */
    { 152, 112,  56 },  /* 3: +P1+P2 */
    { 204, 160,  92 },  /* 4: +P3 */
    { 168, 132,  70 },  /* 5: +P1+P3 */
    { 188, 140,  78 },  /* 6: +P2+P3 */
    { 169, 128,  68 },  /* 7: +P1+P2+P3 */
};

/* NTSC Atari 2600 companion palette: nearest TIA register values for
 * palette primaries (indices 1, 2, 4 — the single-bit entries). */
const unsigned char io_ntsc_palette[3] = {
    0xF4,  /* palette[1] = (132,104,48) */
    0x26,  /* palette[2] = (172,120,64) */
    0x2A,  /* palette[4] = (204,160,92) */
};

static const unsigned char io_char_000[12] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static const unsigned char io_char_001[12] = { 15, 0, 0, 15, 0, 0, 15, 0, 0, 15, 0, 0 };
static const unsigned char io_char_002[12] = { 0, 15, 0, 0, 15, 0, 0, 15, 0, 0, 15, 0 };
static const unsigned char io_char_003[12] = { 15, 15, 0, 15, 15, 0, 15, 15, 0, 15, 15, 0 };
static const unsigned char io_char_004[12] = { 0, 0, 15, 0, 0, 15, 0, 0, 15, 0, 0, 15 };
static const unsigned char io_char_005[12] = { 15, 0, 15, 15, 0, 15, 15, 0, 15, 15, 0, 15 };
static const unsigned char io_char_006[12] = { 0, 15, 15, 0, 15, 15, 0, 15, 15, 0, 15, 15 };
static const unsigned char io_char_007[12] = { 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15 };
static const unsigned char io_char_008[12] = { 15, 0, 0, 15, 0, 0, 11, 6, 12, 9, 4, 7 };
static const unsigned char io_char_009[12] = { 1, 6, 15, 7, 8, 12, 15, 0, 7, 8, 0, 15 };
static const unsigned char io_char_010[12] = { 15, 0, 0, 15, 0, 1, 12, 0, 3, 12, 0, 7 };
static const unsigned char io_char_011[12] = { 15, 8, 7, 0, 0, 15, 0, 2, 15, 3, 0, 15 };
static const unsigned char io_char_012[12] = { 15, 0, 0, 15, 0, 0, 15, 1, 6, 1, 0, 15 };
static const unsigned char io_char_013[12] = { 15, 2, 1, 15, 2, 0, 15, 1, 6, 12, 8, 7 };
static const unsigned char io_char_014[12] = { 3, 4, 15, 15, 0, 0, 15, 0, 0, 0, 0, 15 };
static const unsigned char io_char_015[12] = { 15, 3, 8, 7, 4, 13, 0, 0, 15, 3, 0, 14 };
static const unsigned char io_char_016[12] = { 15, 0, 0, 15, 11, 0, 10, 14, 1, 15, 0, 0 };
static const unsigned char io_char_017[12] = { 15, 0, 0, 15, 8, 0, 7, 0, 8, 11, 8, 6 };
static const unsigned char io_char_018[12] = { 3, 12, 14, 15, 12, 8, 1, 6, 15, 14, 8, 3 };
static const unsigned char io_char_019[12] = { 15, 0, 0, 15, 0, 0, 1, 8, 14, 15, 0, 12 };
static const unsigned char io_char_020[12] = { 15, 0, 0, 11, 4, 7, 6, 10, 15, 0, 12, 15 };
static const unsigned char io_char_021[12] = { 8, 0, 15, 11, 4, 15, 7, 13, 8, 15, 4, 8 };
static const unsigned char io_char_022[12] = { 15, 0, 8, 15, 0, 8, 11, 4, 14, 9, 0, 15 };
static const unsigned char io_char_023[12] = { 14, 0, 15, 0, 12, 15, 15, 6, 0, 15, 0, 0 };
static const unsigned char io_char_024[12] = { 2, 5, 15, 15, 8, 5, 15, 0, 0, 15, 0, 0 };
static const unsigned char io_char_025[12] = { 7, 4, 9, 14, 1, 11, 15, 15, 2, 7, 13, 12 };
static const unsigned char io_char_026[12] = { 7, 2, 12, 15, 0, 0, 15, 0, 0, 11, 6, 12 };
static const unsigned char io_char_027[12] = { 15, 7, 4, 11, 4, 15, 9, 0, 15, 1, 6, 14 };
static const unsigned char io_char_028[12] = { 15, 0, 0, 14, 0, 1, 14, 0, 3, 3, 14, 8 };
static const unsigned char io_char_029[12] = { 14, 1, 3, 0, 0, 15, 0, 0, 15, 8, 0, 15 };
static const unsigned char io_char_030[12] = { 15, 0, 1, 14, 0, 3, 15, 0, 1, 15, 0, 0 };
static const unsigned char io_char_031[12] = { 15, 0, 0, 3, 4, 14, 1, 1, 15, 1, 2, 15 };
static const unsigned char io_char_032[12] = { 14, 3, 1, 12, 7, 0, 8, 15, 1, 0, 15, 8 };
static const unsigned char io_char_033[12] = { 15, 8, 0, 1, 13, 14, 1, 13, 15, 1, 14, 3 };
static const unsigned char io_char_034[12] = { 12, 0, 3, 15, 1, 0, 14, 6, 1, 14, 1, 1 };
static const unsigned char io_char_035[12] = { 7, 12, 8, 13, 13, 2, 9, 0, 15, 0, 0, 15 };
static const unsigned char io_char_036[12] = { 8, 0, 7, 8, 8, 7, 8, 8, 15, 15, 14, 0 };
static const unsigned char io_char_037[12] = { 15, 0, 0, 7, 0, 8, 15, 0, 8, 15, 0, 0 };
static const unsigned char io_char_038[12] = { 8, 5, 15, 8, 8, 15, 8, 4, 7, 12, 3, 3 };
static const unsigned char io_char_039[12] = { 8, 12, 7, 12, 10, 3, 6, 6, 11, 3, 3, 13 };
static const unsigned char io_char_040[12] = { 1, 0, 15, 7, 1, 14, 7, 8, 8, 7, 8, 0 };
static const unsigned char io_char_041[12] = { 15, 0, 0, 15, 0, 0, 15, 0, 0, 13, 0, 2 };
static const unsigned char io_char_042[12] = { 7, 8, 8, 7, 1, 9, 15, 0, 8, 7, 10, 13 };
static const unsigned char io_char_043[12] = { 15, 0, 3, 8, 4, 15, 15, 11, 2, 8, 8, 7 };
static const unsigned char io_char_044[12] = { 11, 0, 14, 3, 4, 12, 7, 0, 12, 7, 4, 12 };
static const unsigned char io_char_045[12] = { 15, 0, 0, 11, 12, 6, 11, 8, 4, 15, 12, 15 };
static const unsigned char io_char_046[12] = { 13, 2, 6, 15, 6, 6, 9, 7, 2, 15, 3, 1 };
static const unsigned char io_char_047[12] = { 15, 0, 0, 15, 0, 0, 13, 3, 3, 12, 0, 3 };
static const unsigned char io_char_048[12] = { 14, 0, 1, 14, 12, 3, 15, 1, 10, 6, 3, 8 };
static const unsigned char io_char_049[12] = { 4, 4, 11, 12, 8, 7, 8, 8, 7, 1, 8, 7 };
static const unsigned char io_char_050[12] = { 15, 0, 8, 5, 6, 9, 6, 14, 11, 14, 14, 9 };
static const unsigned char io_char_051[12] = { 15, 13, 6, 15, 7, 0, 7, 7, 8, 15, 4, 8 };
static const unsigned char io_char_052[12] = { 1, 2, 14, 7, 4, 12, 15, 1, 0, 15, 14, 0 };
static const unsigned char io_char_053[12] = { 13, 6, 11, 7, 10, 15, 15, 13, 2, 14, 11, 9 };
static const unsigned char io_char_054[12] = { 8, 1, 14, 4, 15, 12, 8, 3, 15, 4, 1, 15 };
static const unsigned char io_char_055[12] = { 8, 11, 14, 14, 13, 3, 5, 12, 3, 13, 12, 11 };
static const unsigned char io_char_056[12] = { 9, 2, 14, 15, 4, 8, 12, 8, 15, 14, 13, 3 };
static const unsigned char io_char_057[12] = { 8, 0, 7, 15, 0, 12, 7, 10, 12, 7, 8, 7 };
static const unsigned char io_char_058[12] = { 15, 12, 0, 15, 10, 12, 1, 2, 14, 0, 1, 15 };
static const unsigned char io_char_059[12] = { 8, 4, 7, 9, 0, 7, 15, 12, 6, 15, 2, 8 };
static const unsigned char io_char_060[12] = { 12, 0, 3, 12, 0, 3, 12, 4, 3, 12, 4, 7 };
static const unsigned char io_char_061[12] = { 6, 15, 9, 0, 8, 15, 1, 14, 15, 1, 15, 14 };
static const unsigned char io_char_062[12] = { 5, 10, 3, 15, 8, 1, 15, 2, 1, 13, 2, 3 };
static const unsigned char io_char_063[12] = { 0, 8, 15, 3, 0, 14, 15, 0, 12, 3, 13, 15 };
static const unsigned char io_char_064[12] = { 11, 4, 12, 15, 0, 0, 11, 14, 6, 7, 2, 12 };
static const unsigned char io_char_065[12] = { 15, 15, 0, 15, 3, 2, 15, 0, 0, 14, 8, 5 };
static const unsigned char io_char_066[12] = { 15, 11, 0, 15, 13, 0, 1, 0, 14, 1, 0, 14 };
static const unsigned char io_char_067[12] = { 12, 12, 3, 12, 7, 3, 14, 7, 0, 15, 1, 0 };
static const unsigned char io_char_068[12] = { 15, 3, 13, 9, 14, 14, 12, 12, 3, 14, 8, 7 };
static const unsigned char io_char_069[12] = { 2, 1, 15, 11, 0, 15, 3, 2, 13, 3, 0, 12 };
static const unsigned char io_char_070[12] = { 5, 14, 8, 7, 4, 8, 12, 3, 0, 8, 6, 7 };
static const unsigned char io_char_071[12] = { 14, 9, 0, 6, 15, 1, 3, 15, 9, 7, 12, 9 };
static const unsigned char io_char_072[12] = { 5, 8, 7, 15, 0, 14, 15, 0, 8, 7, 1, 12 };
static const unsigned char io_char_073[12] = { 15, 15, 0, 15, 7, 3, 10, 1, 15, 8, 2, 15 };
static const unsigned char io_char_074[12] = { 0, 1, 15, 7, 11, 14, 15, 10, 1, 15, 9, 2 };
static const unsigned char io_char_075[12] = { 8, 4, 3, 0, 4, 15, 8, 6, 7, 8, 6, 3 };
static const unsigned char io_char_076[12] = { 15, 1, 2, 4, 15, 15, 2, 2, 15, 0, 0, 15 };
static const unsigned char io_char_077[12] = { 3, 8, 12, 3, 8, 12, 3, 8, 12, 15, 15, 8 };
static const unsigned char io_char_078[12] = { 3, 7, 12, 3, 2, 12, 3, 6, 12, 15, 7, 0 };
static const unsigned char io_char_079[12] = { 1, 1, 14, 9, 9, 6, 15, 6, 2, 15, 15, 0 };
static const unsigned char io_char_080[12] = { 15, 15, 0, 11, 15, 4, 15, 13, 5, 14, 11, 1 };
static const unsigned char io_char_081[12] = { 14, 15, 0, 14, 13, 3, 15, 15, 0, 3, 3, 12 };
static const unsigned char io_char_082[12] = { 15, 15, 0, 15, 13, 12, 14, 3, 5, 7, 11, 12 };
static const unsigned char io_char_083[12] = { 14, 7, 8, 1, 3, 14, 1, 0, 14, 1, 2, 14 };
static const unsigned char io_char_084[12] = { 9, 4, 3, 15, 2, 2, 15, 8, 0, 15, 14, 0 };
static const unsigned char io_char_085[12] = { 1, 9, 15, 12, 7, 10, 15, 1, 0, 15, 1, 0 };
static const unsigned char io_char_086[12] = { 3, 6, 12, 9, 14, 12, 1, 8, 14, 1, 11, 14 };
static const unsigned char io_char_087[12] = { 3, 0, 15, 1, 2, 15, 7, 2, 13, 9, 4, 15 };
static const unsigned char io_char_088[12] = { 2, 1, 15, 0, 2, 15, 0, 13, 15, 11, 4, 15 };
static const unsigned char io_char_089[12] = { 15, 0, 11, 13, 0, 7, 8, 0, 7, 0, 8, 15 };
static const unsigned char io_char_090[12] = { 14, 5, 3, 7, 8, 9, 7, 0, 12, 3, 3, 12 };
static const unsigned char io_char_091[12] = { 15, 15, 2, 15, 13, 1, 7, 12, 12, 3, 5, 12 };
static const unsigned char io_char_092[12] = { 0, 8, 15, 0, 11, 14, 1, 3, 12, 0, 9, 14 };
static const unsigned char io_char_093[12] = { 0, 15, 1, 12, 7, 1, 12, 15, 3, 0, 15, 3 };
static const unsigned char io_char_094[12] = { 0, 15, 9, 1, 15, 6, 6, 15, 13, 6, 1, 9 };
static const unsigned char io_char_095[12] = { 0, 12, 15, 2, 12, 9, 14, 15, 1, 8, 5, 3 };
static const unsigned char io_char_096[12] = { 15, 7, 2, 8, 7, 6, 0, 15, 15, 0, 15, 11 };
static const unsigned char io_char_097[12] = { 14, 3, 1, 14, 15, 1, 0, 15, 2, 0, 9, 7 };
static const unsigned char io_char_098[12] = { 3, 15, 0, 3, 15, 12, 3, 10, 12, 1, 10, 6 };
static const unsigned char io_char_099[12] = { 15, 0, 15, 12, 0, 15, 4, 3, 15, 15, 4, 11 };
static const unsigned char io_char_100[12] = { 15, 0, 0, 15, 0, 0, 11, 0, 12, 15, 4, 0 };
static const unsigned char io_char_101[12] = { 8, 4, 7, 14, 3, 5, 14, 8, 7, 8, 8, 7 };
static const unsigned char io_char_102[12] = { 2, 7, 13, 0, 15, 15, 0, 15, 11, 0, 0, 15 };
static const unsigned char io_char_103[12] = { 9, 14, 8, 2, 15, 8, 0, 15, 12, 2, 5, 8 };
static const unsigned char io_char_104[12] = { 0, 9, 14, 0, 1, 15, 4, 13, 11, 4, 9, 11 };
static const unsigned char io_char_105[12] = { 14, 15, 1, 12, 2, 1, 8, 12, 7, 0, 12, 15 };
static const unsigned char io_char_106[12] = { 4, 3, 11, 4, 1, 10, 4, 0, 11, 4, 8, 11 };
static const unsigned char io_char_107[12] = { 1, 14, 6, 3, 10, 4, 0, 15, 4, 0, 15, 0 };
static const unsigned char io_char_108[12] = { 0, 14, 15, 0, 14, 11, 0, 15, 4, 11, 5, 0 };
static const unsigned char io_char_109[12] = { 0, 10, 15, 1, 3, 14, 1, 13, 14, 4, 11, 6 };
static const unsigned char io_char_110[12] = { 0, 9, 6, 0, 9, 7, 0, 9, 15, 0, 9, 14 };
static const unsigned char io_char_111[12] = { 0, 15, 3, 0, 15, 7, 0, 15, 15, 12, 4, 3 };
static const unsigned char io_char_112[12] = { 6, 5, 11, 0, 1, 15, 8, 2, 15, 6, 2, 13 };
static const unsigned char io_char_113[12] = { 1, 0, 14, 1, 8, 15, 2, 1, 15, 3, 0, 15 };
static const unsigned char io_char_114[12] = { 15, 0, 0, 15, 0, 1, 14, 1, 9, 7, 0, 15 };
static const unsigned char io_char_115[12] = { 2, 4, 15, 2, 5, 12, 0, 7, 13, 0, 6, 15 };
static const unsigned char io_char_116[12] = { 0, 4, 15, 0, 8, 15, 0, 13, 15, 0, 15, 9 };
static const unsigned char io_char_117[12] = { 0, 13, 15, 0, 14, 7, 6, 14, 5, 2, 4, 9 };
static const unsigned char io_char_118[12] = { 1, 10, 6, 1, 3, 14, 0, 6, 15, 0, 6, 11 };
static const unsigned char io_char_119[12] = { 4, 15, 0, 0, 15, 8, 0, 7, 12, 0, 7, 15 };
static const unsigned char io_char_120[12] = { 1, 14, 0, 1, 14, 2, 7, 9, 8, 0, 15, 8 };
static const unsigned char io_char_121[12] = { 14, 15, 1, 0, 14, 3, 8, 6, 3, 8, 7, 2 };
static const unsigned char io_char_122[12] = { 0, 15, 9, 1, 15, 12, 1, 15, 10, 0, 14, 11 };
static const unsigned char io_char_123[12] = { 0, 9, 15, 0, 3, 15, 8, 10, 15, 0, 8, 7 };
static const unsigned char io_char_124[12] = { 8, 7, 3, 8, 9, 7, 8, 15, 15, 7, 9, 13 };
static const unsigned char io_char_125[12] = { 0, 14, 15, 0, 12, 7, 8, 15, 0, 8, 15, 2 };
static const unsigned char io_char_126[12] = { 0, 2, 13, 6, 7, 8, 14, 3, 3, 14, 1, 1 };
static const unsigned char io_char_127[12] = { 12, 0, 3, 12, 4, 3, 0, 12, 7, 0, 6, 15 };
static const unsigned char io_char_128[12] = { 6, 15, 8, 6, 7, 8, 4, 7, 9, 0, 15, 9 };
static const unsigned char io_char_129[12] = { 2, 8, 15, 6, 9, 15, 14, 3, 15, 8, 9, 15 };
static const unsigned char io_char_130[12] = { 12, 2, 3, 12, 3, 3, 0, 15, 3, 0, 15, 7 };
static const unsigned char io_char_131[12] = { 3, 0, 14, 3, 0, 12, 3, 0, 12, 3, 8, 12 };
static const unsigned char io_char_132[12] = { 0, 0, 15, 0, 4, 15, 1, 5, 11, 0, 13, 11 };
static const unsigned char io_char_133[12] = { 4, 6, 15, 2, 15, 12, 1, 14, 4, 0, 15, 6 };
static const unsigned char io_char_134[12] = { 12, 6, 3, 8, 12, 3, 0, 2, 15, 0, 6, 9 };
static const unsigned char io_char_135[12] = { 0, 3, 15, 1, 8, 6, 3, 10, 4, 3, 12, 11 };
static const unsigned char io_char_136[12] = { 0, 6, 15, 0, 12, 11, 1, 4, 14, 0, 1, 15 };
static const unsigned char io_char_137[12] = { 0, 15, 11, 4, 11, 9, 0, 15, 7, 0, 11, 15 };
static const unsigned char io_char_138[12] = { 1, 8, 14, 1, 8, 15, 15, 8, 7, 12, 0, 15 };
static const unsigned char io_char_139[12] = { 12, 15, 2, 12, 15, 2, 8, 15, 0, 8, 3, 6 };
static const unsigned char io_char_140[12] = { 0, 4, 11, 4, 4, 11, 0, 4, 15, 0, 4, 15 };
static const unsigned char io_char_141[12] = { 3, 12, 8, 7, 15, 8, 0, 13, 10, 0, 15, 8 };
static const unsigned char io_char_142[12] = { 0, 8, 15, 9, 1, 14, 13, 11, 6, 7, 8, 15 };
static const unsigned char io_char_143[12] = { 11, 9, 12, 4, 11, 15, 0, 15, 14, 0, 9, 15 };
static const unsigned char io_char_144[12] = { 8, 3, 6, 0, 15, 4, 10, 15, 4, 2, 15, 0 };
static const unsigned char io_char_145[12] = { 4, 14, 11, 6, 13, 9, 2, 15, 12, 0, 15, 12 };
static const unsigned char io_char_146[12] = { 0, 12, 7, 4, 12, 3, 0, 15, 15, 0, 15, 12 };
static const unsigned char io_char_147[12] = { 0, 0, 15, 0, 8, 7, 9, 0, 15, 12, 8, 15 };
static const unsigned char io_char_148[12] = { 0, 15, 7, 8, 14, 7, 0, 14, 7, 0, 1, 15 };
static const unsigned char io_char_149[12] = { 11, 4, 15, 3, 5, 12, 12, 7, 11, 12, 15, 3 };
static const unsigned char io_char_150[12] = { 0, 12, 7, 0, 12, 7, 0, 12, 7, 8, 12, 7 };
static const unsigned char io_char_151[12] = { 8, 4, 3, 8, 13, 3, 0, 15, 1, 0, 15, 1 };
static const unsigned char io_char_152[12] = { 0, 6, 9, 0, 7, 13, 0, 7, 9, 7, 5, 12 };
static const unsigned char io_char_153[12] = { 1, 8, 15, 0, 8, 15, 2, 4, 15, 15, 7, 11 };
static const unsigned char io_char_154[12] = { 9, 3, 15, 1, 14, 11, 1, 15, 10, 9, 14, 8 };
static const unsigned char io_char_155[12] = { 8, 12, 7, 8, 7, 7, 10, 9, 7, 10, 11, 7 };
static const unsigned char io_char_156[12] = { 12, 14, 15, 2, 15, 13, 3, 11, 15, 3, 13, 10 };
static const unsigned char io_char_157[12] = { 0, 3, 15, 0, 12, 15, 0, 12, 15, 14, 13, 1 };
static const unsigned char io_char_158[12] = { 0, 15, 12, 4, 11, 10, 12, 1, 10, 0, 5, 14 };
static const unsigned char io_char_159[12] = { 0, 15, 15, 12, 7, 2, 12, 3, 0, 4, 15, 0 };
static const unsigned char io_char_160[12] = { 0, 3, 15, 0, 1, 15, 0, 3, 15, 5, 10, 11 };
static const unsigned char io_char_161[12] = { 13, 15, 8, 4, 15, 7, 8, 13, 15, 15, 12, 11 };
static const unsigned char io_char_162[12] = { 8, 9, 6, 8, 5, 7, 12, 2, 1, 14, 1, 1 };
static const unsigned char io_char_163[12] = { 6, 11, 0, 12, 11, 0, 0, 13, 11, 1, 15, 3 };
static const unsigned char io_char_164[12] = { 3, 3, 12, 3, 3, 12, 5, 11, 8, 4, 15, 10 };
static const unsigned char io_char_165[12] = { 2, 14, 1, 0, 8, 15, 1, 10, 15, 8, 13, 7 };
static const unsigned char io_char_166[12] = { 0, 15, 13, 0, 15, 15, 0, 12, 7, 4, 12, 3 };
static const unsigned char io_char_167[12] = { 1, 15, 0, 12, 15, 8, 6, 7, 8, 3, 7, 8 };
static const unsigned char io_char_168[12] = { 14, 14, 13, 8, 14, 7, 12, 7, 7, 14, 12, 3 };
static const unsigned char io_char_169[12] = { 1, 0, 14, 1, 0, 14, 0, 0, 15, 0, 0, 15 };
static const unsigned char io_char_170[12] = { 12, 4, 7, 8, 5, 7, 1, 2, 13, 3, 0, 12 };
static const unsigned char io_char_171[12] = { 10, 15, 2, 15, 12, 3, 12, 8, 7, 9, 0, 6 };
static const unsigned char io_char_172[12] = { 14, 14, 3, 14, 9, 0, 15, 15, 10, 7, 11, 14 };
static const unsigned char io_char_173[12] = { 3, 15, 6, 8, 7, 14, 0, 15, 15, 1, 15, 14 };
static const unsigned char io_char_174[12] = { 9, 8, 6, 15, 8, 0, 15, 9, 0, 14, 6, 1 };
static const unsigned char io_char_175[12] = { 12, 1, 7, 9, 1, 7, 9, 0, 15, 0, 0, 15 };
static const unsigned char io_char_176[12] = { 13, 10, 1, 11, 15, 4, 15, 4, 4, 15, 0, 0 };
static const unsigned char io_char_177[12] = { 1, 7, 12, 4, 7, 14, 12, 15, 8, 3, 15, 8 };
static const unsigned char io_char_178[12] = { 12, 7, 1, 0, 15, 3, 0, 15, 7, 0, 15, 7 };
static const unsigned char io_char_179[12] = { 7, 6, 8, 7, 12, 9, 10, 4, 7, 7, 8, 12 };
static const unsigned char io_char_180[12] = { 15, 8, 0, 7, 4, 8, 7, 0, 12, 7, 11, 12 };
static const unsigned char io_char_181[12] = { 11, 15, 14, 15, 6, 13, 15, 3, 8, 11, 8, 6 };
static const unsigned char io_char_182[12] = { 8, 14, 15, 8, 5, 15, 11, 4, 14, 15, 10, 4 };
static const unsigned char io_char_183[12] = { 3, 1, 12, 11, 0, 12, 15, 0, 0, 15, 1, 0 };
static const unsigned char io_char_184[12] = { 12, 2, 3, 12, 4, 3, 11, 0, 7, 8, 3, 7 };
static const unsigned char io_char_185[12] = { 6, 8, 15, 15, 2, 4, 3, 12, 12, 7, 12, 8 };
static const unsigned char io_char_186[12] = { 0, 15, 0, 12, 14, 7, 0, 9, 15, 2, 7, 12 };
static const unsigned char io_char_187[12] = { 13, 14, 6, 12, 11, 15, 15, 9, 0, 15, 0, 0 };
static const unsigned char io_char_188[12] = { 15, 2, 0, 15, 8, 0, 7, 0, 8, 3, 0, 12 };
static const unsigned char io_char_189[12] = { 12, 0, 7, 12, 0, 3, 14, 0, 3, 15, 0, 1 };
static const unsigned char io_char_190[12] = { 15, 0, 8, 7, 3, 15, 15, 3, 12, 7, 0, 15 };
static const unsigned char io_char_191[12] = { 15, 12, 3, 15, 8, 4, 15, 8, 4, 15, 7, 7 };
static const unsigned char io_char_192[12] = { 14, 2, 1, 12, 3, 0, 14, 3, 3, 14, 1, 0 };
static const unsigned char io_char_193[12] = { 15, 2, 0, 15, 4, 3, 11, 13, 6, 5, 2, 15 };
static const unsigned char io_char_194[12] = { 15, 0, 0, 15, 1, 0, 14, 0, 1, 7, 13, 9 };
static const unsigned char io_char_195[12] = { 12, 0, 3, 8, 0, 7, 0, 0, 15, 0, 12, 15 };
static const unsigned char io_char_196[12] = { 1, 0, 14, 1, 0, 15, 8, 0, 15, 9, 12, 7 };
static const unsigned char io_char_197[12] = { 15, 1, 8, 7, 4, 8, 15, 0, 0, 15, 6, 0 };
static const unsigned char io_char_198[12] = { 15, 2, 1, 15, 4, 1, 15, 1, 12, 15, 9, 7 };
static const unsigned char io_char_199[12] = { 15, 2, 12, 3, 14, 12, 7, 8, 7, 15, 3, 0 };
static const unsigned char io_char_200[12] = { 15, 3, 2, 15, 1, 2, 15, 6, 12, 15, 1, 1 };
static const unsigned char io_char_201[12] = { 15, 15, 8, 15, 9, 0, 14, 3, 1, 15, 0, 0 };
static const unsigned char io_char_202[12] = { 11, 4, 15, 15, 12, 2, 15, 0, 0, 15, 11, 4 };
static const unsigned char io_char_203[12] = { 8, 10, 7, 14, 1, 7, 10, 15, 4, 2, 15, 13 };
static const unsigned char io_char_204[12] = { 15, 8, 0, 7, 0, 12, 0, 1, 15, 0, 0, 15 };
static const unsigned char io_char_205[12] = { 15, 4, 8, 1, 2, 14, 3, 6, 14, 15, 0, 0 };
static const unsigned char io_char_206[12] = { 15, 14, 5, 14, 11, 1, 15, 0, 0, 15, 0, 0 };
static const unsigned char io_char_207[12] = { 6, 3, 15, 7, 2, 12, 15, 0, 0, 15, 0, 0 };
static const unsigned char io_char_208[12] = { 15, 0, 9, 15, 1, 6, 15, 0, 0, 14, 1, 1 };
static const unsigned char io_char_209[12] = { 0, 0, 15, 12, 0, 15, 11, 6, 4, 9, 4, 14 };
static const unsigned char io_char_210[12] = { 15, 0, 0, 15, 0, 0, 15, 0, 0, 14, 0, 3 };
static const unsigned char io_char_211[12] = { 8, 4, 15, 15, 3, 0, 15, 0, 0, 15, 0, 0 };
static const unsigned char io_char_212[12] = { 15, 8, 0, 15, 8, 0, 7, 8, 0, 1, 15, 7 };
static const unsigned char io_char_213[12] = { 1, 11, 14, 1, 3, 15, 3, 0, 15, 3, 15, 14 };
static const unsigned char io_char_214[12] = { 0, 0, 15, 0, 0, 15, 0, 4, 15, 7, 13, 8 };
static const unsigned char io_char_215[12] = { 15, 0, 0, 7, 14, 0, 0, 15, 0, 0, 15, 4 };
static const unsigned char io_char_216[12] = { 2, 13, 13, 11, 0, 15, 0, 10, 15, 0, 13, 7 };
static const unsigned char io_char_217[12] = { 3, 14, 0, 15, 8, 0, 15, 0, 1, 14, 3, 1 };
static const unsigned char io_char_218[12] = { 0, 12, 11, 0, 6, 15, 0, 7, 13, 0, 7, 13 };
static const unsigned char io_char_219[12] = { 15, 2, 13, 14, 1, 15, 8, 4, 15, 0, 0, 15 };
static const unsigned char io_char_220[12] = { 0, 0, 15, 0, 0, 15, 2, 1, 15, 3, 3, 12 };
static const unsigned char io_char_221[12] = { 15, 0, 0, 15, 2, 1, 12, 4, 7, 15, 10, 1 };
static const unsigned char io_char_222[12] = { 0, 11, 15, 8, 1, 7, 8, 12, 7, 8, 4, 15 };
static const unsigned char io_char_223[12] = { 14, 1, 15, 15, 7, 1, 14, 1, 0, 14, 2, 1 };
static const unsigned char io_char_224[12] = { 15, 0, 8, 15, 8, 4, 15, 12, 8, 15, 9, 0 };
static const unsigned char io_char_225[12] = { 15, 0, 0, 15, 0, 0, 14, 1, 3, 9, 8, 7 };
static const unsigned char io_char_226[12] = { 1, 7, 12, 1, 15, 0, 13, 15, 4, 9, 15, 8 };
static const unsigned char io_char_227[12] = { 0, 15, 14, 1, 15, 12, 1, 15, 12, 3, 15, 8 };
static const unsigned char io_char_228[12] = { 6, 7, 8, 0, 3, 15, 0, 0, 15, 0, 0, 15 };
static const unsigned char io_char_229[12] = { 15, 8, 0, 7, 0, 12, 11, 0, 12, 15, 0, 0 };
static const unsigned char io_char_230[12] = { 0, 15, 0, 4, 15, 0, 6, 9, 1, 14, 11, 0 };
static const unsigned char io_char_231[12] = { 0, 0, 15, 0, 8, 7, 12, 8, 7, 12, 4, 7 };
static const unsigned char io_char_232[12] = { 0, 0, 15, 0, 2, 15, 0, 15, 13, 2, 15, 5 };
static const unsigned char io_char_233[12] = { 14, 9, 9, 10, 15, 0, 6, 15, 14, 0, 7, 13 };
static const unsigned char io_char_234[12] = { 10, 7, 12, 12, 11, 4, 12, 3, 4, 12, 7, 0 };
static const unsigned char io_char_235[12] = { 9, 14, 4, 11, 7, 0, 15, 3, 0, 15, 1, 0 };
static const unsigned char io_char_236[12] = { 14, 0, 7, 14, 8, 7, 14, 0, 3, 12, 15, 3 };
static const unsigned char io_char_237[12] = { 0, 12, 7, 0, 8, 15, 0, 10, 15, 0, 13, 15 };
static const unsigned char io_char_238[12] = { 0, 1, 15, 0, 1, 15, 0, 9, 14, 0, 11, 15 };
static const unsigned char io_char_239[12] = { 8, 0, 15, 12, 9, 7, 15, 0, 0, 15, 0, 0 };
static const unsigned char io_char_240[12] = { 0, 15, 4, 1, 14, 4, 8, 15, 12, 1, 3, 14 };
static const unsigned char io_char_241[12] = { 3, 15, 14, 3, 12, 15, 3, 4, 15, 9, 15, 5 };
static const unsigned char io_char_242[12] = { 15, 0, 0, 15, 12, 8, 15, 4, 8, 7, 0, 12 };
static const unsigned char io_char_243[12] = { 3, 1, 12, 4, 2, 15, 5, 8, 15, 4, 8, 15 };
static const unsigned char io_char_244[12] = { 6, 7, 12, 2, 7, 8, 0, 7, 15, 0, 15, 15 };
static const unsigned char io_char_245[12] = { 12, 2, 3, 14, 2, 3, 15, 0, 0, 15, 12, 0 };
static const unsigned char io_char_246[12] = { 11, 15, 12, 3, 12, 0, 3, 12, 0, 3, 14, 0 };
static const unsigned char io_char_247[12] = { 11, 6, 15, 3, 4, 15, 1, 15, 9, 5, 6, 15 };
static const unsigned char io_char_248[12] = { 14, 0, 3, 15, 0, 0, 15, 0, 0, 12, 15, 3 };
static const unsigned char io_char_249[12] = { 15, 5, 11, 15, 1, 14, 11, 5, 12, 3, 15, 12 };
static const unsigned char io_char_250[12] = { 7, 8, 15, 15, 6, 1, 15, 0, 15, 1, 12, 15 };
static const unsigned char io_char_251[12] = { 8, 4, 15, 8, 1, 15, 8, 3, 14, 2, 15, 14 };
static const unsigned char io_char_252[12] = { 8, 15, 3, 0, 15, 7, 0, 3, 15, 0, 1, 15 };
static const unsigned char io_char_253[12] = { 0, 15, 6, 8, 15, 6, 8, 15, 7, 0, 14, 3 };
static const unsigned char io_char_254[12] = { 1, 2, 15, 3, 1, 15, 0, 1, 15, 0, 1, 15 };
static const unsigned char io_char_255[12] = { 7, 15, 0, 14, 15, 0, 14, 15, 3, 8, 14, 3 };

const unsigned char * const io_charset[256] = {
    io_char_000,
    io_char_001,
    io_char_002,
    io_char_003,
    io_char_004,
    io_char_005,
    io_char_006,
    io_char_007,
    io_char_008,
    io_char_009,
    io_char_010,
    io_char_011,
    io_char_012,
    io_char_013,
    io_char_014,
    io_char_015,
    io_char_016,
    io_char_017,
    io_char_018,
    io_char_019,
    io_char_020,
    io_char_021,
    io_char_022,
    io_char_023,
    io_char_024,
    io_char_025,
    io_char_026,
    io_char_027,
    io_char_028,
    io_char_029,
    io_char_030,
    io_char_031,
    io_char_032,
    io_char_033,
    io_char_034,
    io_char_035,
    io_char_036,
    io_char_037,
    io_char_038,
    io_char_039,
    io_char_040,
    io_char_041,
    io_char_042,
    io_char_043,
    io_char_044,
    io_char_045,
    io_char_046,
    io_char_047,
    io_char_048,
    io_char_049,
    io_char_050,
    io_char_051,
    io_char_052,
    io_char_053,
    io_char_054,
    io_char_055,
    io_char_056,
    io_char_057,
    io_char_058,
    io_char_059,
    io_char_060,
    io_char_061,
    io_char_062,
    io_char_063,
    io_char_064,
    io_char_065,
    io_char_066,
    io_char_067,
    io_char_068,
    io_char_069,
    io_char_070,
    io_char_071,
    io_char_072,
    io_char_073,
    io_char_074,
    io_char_075,
    io_char_076,
    io_char_077,
    io_char_078,
    io_char_079,
    io_char_080,
    io_char_081,
    io_char_082,
    io_char_083,
    io_char_084,
    io_char_085,
    io_char_086,
    io_char_087,
    io_char_088,
    io_char_089,
    io_char_090,
    io_char_091,
    io_char_092,
    io_char_093,
    io_char_094,
    io_char_095,
    io_char_096,
    io_char_097,
    io_char_098,
    io_char_099,
    io_char_100,
    io_char_101,
    io_char_102,
    io_char_103,
    io_char_104,
    io_char_105,
    io_char_106,
    io_char_107,
    io_char_108,
    io_char_109,
    io_char_110,
    io_char_111,
    io_char_112,
    io_char_113,
    io_char_114,
    io_char_115,
    io_char_116,
    io_char_117,
    io_char_118,
    io_char_119,
    io_char_120,
    io_char_121,
    io_char_122,
    io_char_123,
    io_char_124,
    io_char_125,
    io_char_126,
    io_char_127,
    io_char_128,
    io_char_129,
    io_char_130,
    io_char_131,
    io_char_132,
    io_char_133,
    io_char_134,
    io_char_135,
    io_char_136,
    io_char_137,
    io_char_138,
    io_char_139,
    io_char_140,
    io_char_141,
    io_char_142,
    io_char_143,
    io_char_144,
    io_char_145,
    io_char_146,
    io_char_147,
    io_char_148,
    io_char_149,
    io_char_150,
    io_char_151,
    io_char_152,
    io_char_153,
    io_char_154,
    io_char_155,
    io_char_156,
    io_char_157,
    io_char_158,
    io_char_159,
    io_char_160,
    io_char_161,
    io_char_162,
    io_char_163,
    io_char_164,
    io_char_165,
    io_char_166,
    io_char_167,
    io_char_168,
    io_char_169,
    io_char_170,
    io_char_171,
    io_char_172,
    io_char_173,
    io_char_174,
    io_char_175,
    io_char_176,
    io_char_177,
    io_char_178,
    io_char_179,
    io_char_180,
    io_char_181,
    io_char_182,
    io_char_183,
    io_char_184,
    io_char_185,
    io_char_186,
    io_char_187,
    io_char_188,
    io_char_189,
    io_char_190,
    io_char_191,
    io_char_192,
    io_char_193,
    io_char_194,
    io_char_195,
    io_char_196,
    io_char_197,
    io_char_198,
    io_char_199,
    io_char_200,
    io_char_201,
    io_char_202,
    io_char_203,
    io_char_204,
    io_char_205,
    io_char_206,
    io_char_207,
    io_char_208,
    io_char_209,
    io_char_210,
    io_char_211,
    io_char_212,
    io_char_213,
    io_char_214,
    io_char_215,
    io_char_216,
    io_char_217,
    io_char_218,
    io_char_219,
    io_char_220,
    io_char_221,
    io_char_222,
    io_char_223,
    io_char_224,
    io_char_225,
    io_char_226,
    io_char_227,
    io_char_228,
    io_char_229,
    io_char_230,
    io_char_231,
    io_char_232,
    io_char_233,
    io_char_234,
    io_char_235,
    io_char_236,
    io_char_237,
    io_char_238,
    io_char_239,
    io_char_240,
    io_char_241,
    io_char_242,
    io_char_243,
    io_char_244,
    io_char_245,
    io_char_246,
    io_char_247,
    io_char_248,
    io_char_249,
    io_char_250,
    io_char_251,
    io_char_252,
    io_char_253,
    io_char_254,
    io_char_255,
};

const unsigned char io_map[882] = {
    40, 22,
    8, 1, 1, 3, 212, 3, 1, 239, 9, 1, 10, 11, 7, 242, 1, 1, 1, 1, 12, 13, 14, 15, 1, 1, 16, 17, 1, 1, 1, 225, 8, 1, 1, 3, 212, 3, 1, 239, 9, 1,
    1, 1, 1, 223, 18, 19, 210, 20, 21, 22, 23, 24, 25, 246, 1, 1, 1, 248, 26, 1, 211, 246, 1, 3, 221, 27, 215, 28, 29, 254, 1, 1, 1, 223, 18, 19, 210, 20, 21, 22,
    1, 30, 31, 32, 33, 229, 34, 247, 35, 36, 37, 1, 1, 1, 1, 1, 38, 39, 40, 1, 1, 1, 1, 41, 221, 4, 228, 42, 43, 44, 1, 30, 31, 32, 33, 229, 34, 247, 35, 36,
    3, 45, 46, 2, 217, 47, 48, 49, 4, 50, 242, 1, 3, 242, 51, 1, 245, 52, 3, 1, 1, 229, 3, 236, 53, 54, 55, 56, 57, 1, 3, 45, 46, 2, 217, 47, 48, 49, 4, 50,
    58, 251, 2, 3, 59, 60, 61, 62, 63, 3, 64, 1, 217, 242, 3, 242, 65, 66, 2, 215, 3, 242, 67, 5, 68, 69, 70, 71, 72, 73, 58, 251, 2, 3, 59, 60, 61, 62, 63, 3,
    74, 3, 7, 2, 2, 75, 254, 76, 77, 78, 79, 80, 81, 82, 83, 235, 84, 85, 2, 230, 2, 86, 3, 87, 7, 88, 254, 224, 89, 90, 74, 3, 7, 2, 2, 75, 254, 76, 77, 78,
    91, 7, 92, 93, 233, 94, 95, 6, 255, 96, 2, 97, 4, 230, 213, 3, 3, 3, 3, 3, 3, 98, 2, 6, 249, 99, 254, 100, 101, 238, 91, 7, 92, 93, 233, 94, 95, 6, 255, 96,
    102, 103, 104, 105, 254, 106, 107, 2, 108, 218, 109, 6, 7, 7, 7, 3, 3, 2, 2, 228, 2, 110, 111, 247, 6, 112, 113, 114, 4, 247, 102, 103, 104, 105, 254, 106, 107, 2, 108, 218,
    115, 244, 116, 117, 118, 252, 119, 120, 121, 254, 122, 123, 6, 3, 5, 2, 124, 2, 125, 126, 6, 253, 127, 128, 7, 4, 238, 219, 4, 228, 115, 244, 116, 117, 118, 252, 119, 120, 121, 254,
    4, 213, 6, 4, 4, 4, 6, 6, 6, 6, 6, 238, 7, 240, 129, 233, 216, 226, 2, 130, 227, 2, 7, 2, 219, 6, 4, 4, 4, 4, 4, 213, 6, 4, 4, 4, 6, 6, 6, 6,
    237, 6, 237, 4, 4, 4, 4, 254, 7, 6, 6, 6, 6, 131, 3, 7, 7, 2, 7, 2, 2, 3, 2, 2, 7, 6, 6, 4, 132, 133, 237, 6, 237, 4, 4, 4, 4, 254, 7, 6,
    4, 4, 134, 4, 135, 222, 136, 238, 137, 2, 6, 7, 5, 138, 7, 2, 7, 6, 6, 2, 2, 2, 139, 2, 2, 5, 6, 6, 7, 6, 4, 4, 134, 4, 135, 222, 136, 238, 137, 2,
    6, 254, 2, 4, 140, 4, 220, 6, 6, 141, 7, 247, 6, 142, 250, 7, 7, 6, 143, 246, 230, 246, 144, 2, 2, 236, 4, 254, 2, 232, 6, 254, 2, 4, 140, 4, 220, 6, 6, 141,
    2, 145, 244, 146, 238, 147, 4, 254, 2, 2, 252, 6, 148, 6, 149, 2, 2, 7, 227, 2, 2, 2, 7, 212, 246, 150, 4, 4, 228, 6, 2, 145, 244, 146, 238, 147, 4, 254, 2, 2,
    7, 240, 253, 227, 151, 237, 152, 232, 254, 252, 4, 244, 153, 154, 2, 3, 234, 230, 3, 2, 2, 2, 240, 251, 3, 155, 6, 218, 220, 2, 7, 240, 253, 227, 151, 237, 152, 232, 254, 252,
    156, 157, 158, 2, 159, 227, 226, 3, 222, 4, 4, 160, 161, 3, 3, 215, 2, 2, 2, 234, 2, 246, 162, 2, 3, 238, 163, 216, 164, 253, 156, 157, 158, 2, 159, 227, 226, 3, 222, 4,
    3, 165, 238, 166, 254, 167, 2, 2, 168, 169, 170, 7, 3, 1, 3, 171, 3, 2, 3, 172, 2, 246, 1, 241, 7, 173, 255, 249, 255, 2, 3, 165, 238, 166, 254, 167, 2, 2, 168, 169,
    3, 174, 175, 176, 231, 177, 178, 246, 3, 231, 243, 179, 180, 1, 1, 1, 3, 3, 3, 7, 7, 6, 3, 3, 1, 181, 182, 241, 250, 2, 3, 174, 175, 176, 231, 177, 178, 246, 3, 231,
    1, 210, 2, 1, 245, 183, 2, 3, 1, 184, 185, 1, 1, 1, 3, 1, 3, 3, 1, 223, 186, 232, 2, 7, 1, 1, 187, 3, 235, 1, 1, 210, 2, 1, 245, 183, 2, 3, 1, 184,
    1, 248, 188, 1, 1, 1, 1, 3, 1, 189, 190, 212, 3, 1, 191, 3, 3, 1, 1, 192, 2, 3, 1, 248, 193, 1, 1, 225, 194, 1, 1, 248, 188, 1, 1, 1, 1, 3, 1, 189,
    195, 232, 196, 1, 1, 239, 197, 3, 242, 198, 232, 232, 2, 1, 1, 199, 200, 1, 1, 1, 1, 201, 224, 211, 202, 1, 3, 203, 243, 204, 195, 232, 196, 1, 1, 239, 197, 3, 242, 198,
    6, 214, 214, 205, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 211, 3, 206, 207, 208, 209, 6, 214, 214, 205, 1, 1, 1, 1, 1, 1,
};

