/* Auto-generated by img2tiles.py from "io.jpg" */
#pragma once

#define IO_CHARSET_SIZE 256
#define IO_MAP_SIZE     882
#define IO_CHAR_WIDTH   4
#define IO_CHAR_HEIGHT  4
#define IO_CHAR_BYTES   12

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char io_ntsc_palette[3];

/* Charset: 256 characters, each 12 bytes */
extern const unsigned char * const io_charset[256];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char io_map[882];


