/* Auto-generated by img2tiles.py from "jupiter.jpg" */
#pragma once

#define JUPITER_CHARSET_SIZE 256
#define JUPITER_MAP_SIZE     882
#define JUPITER_CHAR_WIDTH   5
#define JUPITER_CHAR_HEIGHT  10
#define JUPITER_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char jupiter_ntsc_palette[3];

/* Charset: 256 characters, each 30 bytes */
extern const unsigned char * const jupiter_charset[256];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char jupiter_map[882];


