/* Auto-generated by spinningGlobe/cset.py from "lava.png" */
#pragma once

#define LAVA_CHARSET_SIZE 51
#define LAVA_MAP_SIZE     122
#define LAVA_CHAR_WIDTH   5
#define LAVA_CHAR_HEIGHT  10
#define LAVA_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char lava_ntsc_palette[3];

/* Charset: 51 characters, each 30 bytes */
extern const unsigned char * const lava_charset[51];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char lava_map[122];


