/* Auto-generated by img2tiles.py from "mercury.jpg" */
#pragma once

#define MERCURY_CHARSET_SIZE 256
#define MERCURY_MAP_SIZE     882
#define MERCURY_CHAR_WIDTH   5
#define MERCURY_CHAR_HEIGHT  10
#define MERCURY_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char mercury_ntsc_palette[3];

/* Charset: 256 characters, each 30 bytes */
extern const unsigned char * const mercury_charset[256];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char mercury_map[882];


