/* Auto-generated by spinningGlobe/cset.py from "moon.png" */
#pragma once

#define MOON_CHARSET_SIZE 84
#define MOON_MAP_SIZE     122
#define MOON_CHAR_WIDTH   5
#define MOON_CHAR_HEIGHT  10
#define MOON_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char moon_ntsc_palette[3];

/* Charset: 84 characters, each 30 bytes */
extern const unsigned char * const moon_charset[84];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char moon_map[122];


