/* Auto-generated by img2tiles.py from "moon.png" */
/* Adaptive palette: 8 colours built from 3 EM-optimised primaries (NTSC-snapped). */
/* Index bits: bit0=P1, bit1=P2, bit2=P3 (P1/P2/P3 = single-bit primaries). */
/* Character: 5 pixels wide x 10 trixels deep (30 scanlines). */
/* Trixel: 1 pixel wide x 3 scanlines deep, 3-bit palette index. */
/* Character storage: 10 trixel-rows x 3 bytes (bit0-plane, bit1-plane, bit2-plane) = 30 bytes. */
/* Byte bit layout: bit4=col0(left) .. bit0=col4(right), bits7-5 unused. */
/* Map: byte0=width(chars, +10 wrap buffer), byte1=height(chars), then row-major indices. */

static const unsigned char moon_palette[8][3] = {
    {   0,   0,   0 },  /* 0: origin */
    { 108, 108, 108 },  /* 1: +P1 */
    { 144, 144, 144 },  /* 2: +P2 */
    { 126, 126, 126 },  /* 3: +P1+P2 */
    { 176, 176, 176 },  /* 4: +P3 */
    { 142, 142, 142 },  /* 5: +P1+P3 */
    { 160, 160, 160 },  /* 6: +P2+P3 */
    { 143, 143, 143 },  /* 7: +P1+P2+P3 */
};

/* NTSC Atari 2600 companion palette: nearest TIA register values for
 * palette primaries (indices 1, 2, 4 — the single-bit entries). */
const unsigned char moon_ntsc_palette[3] = {
    0x04,  /* palette[1] = (108,108,108) */
    0x06,  /* palette[2] = (144,144,144) */
    0x08,  /* palette[4] = (176,176,176) */
};

static const unsigned char moon_char_000[30] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static const unsigned char moon_char_001[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char moon_char_002[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char moon_char_003[30] = { 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0 };
static const unsigned char moon_char_004[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char moon_char_005[30] = { 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31 };
static const unsigned char moon_char_006[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char moon_char_007[30] = { 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31 };
static const unsigned char moon_char_008[30] = { 0, 15, 31, 0, 25, 31, 0, 26, 31, 0, 2, 31, 0, 13, 31, 0, 8, 31, 0, 14, 31, 0, 16, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char moon_char_009[30] = { 0, 31, 31, 0, 29, 31, 0, 31, 31, 0, 31, 31, 0, 29, 31, 0, 24, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 2, 31 };
static const unsigned char moon_char_010[30] = { 1, 31, 17, 0, 31, 31, 0, 23, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 27, 31, 0, 24, 31, 0, 16, 31, 0, 1, 31 };
static const unsigned char moon_char_011[30] = { 0, 27, 31, 0, 5, 30, 0, 31, 18, 0, 31, 11, 0, 31, 31, 0, 31, 30, 0, 23, 31, 0, 31, 31, 0, 31, 23, 0, 25, 31 };
static const unsigned char moon_char_012[30] = { 0, 31, 31, 0, 19, 15, 0, 31, 31, 0, 29, 31, 0, 30, 31, 0, 30, 31, 0, 14, 31, 0, 31, 27, 0, 31, 31, 0, 31, 31 };
static const unsigned char moon_char_013[30] = { 0, 31, 9, 0, 31, 27, 0, 31, 31, 0, 27, 15, 0, 31, 31, 0, 15, 31, 0, 31, 30, 1, 31, 16, 3, 30, 26, 15, 20, 24 };
static const unsigned char moon_char_014[30] = { 0, 31, 24, 4, 27, 21, 0, 15, 31, 0, 23, 31, 0, 16, 31, 0, 29, 31, 0, 31, 28, 31, 11, 4, 31, 0, 0, 31, 0, 0 };
static const unsigned char moon_char_015[30] = { 4, 27, 20, 4, 31, 29, 0, 26, 31, 0, 30, 31, 0, 15, 31, 1, 30, 25, 23, 25, 22, 31, 28, 0, 31, 3, 0, 28, 7, 0 };
static const unsigned char moon_char_016[30] = { 0, 31, 0, 0, 31, 1, 0, 31, 31, 0, 31, 31, 22, 9, 22, 31, 24, 7, 31, 16, 0, 31, 8, 0, 15, 22, 8, 31, 16, 0 };
static const unsigned char moon_char_017[30] = { 0, 31, 15, 0, 31, 15, 0, 31, 31, 0, 31, 31, 0, 31, 19, 30, 25, 6, 31, 0, 0, 31, 4, 0, 30, 27, 0, 31, 1, 0 };
static const unsigned char moon_char_018[30] = { 0, 31, 28, 0, 31, 14, 0, 19, 31, 0, 27, 30, 1, 30, 25, 30, 1, 30, 31, 15, 0, 31, 0, 0, 31, 0, 16, 31, 7, 24 };
static const unsigned char moon_char_019[30] = { 0, 31, 29, 0, 31, 30, 0, 31, 31, 0, 31, 13, 2, 31, 2, 31, 10, 23, 31, 22, 1, 31, 0, 0, 31, 0, 0, 31, 15, 16 };
static const unsigned char moon_char_020[30] = { 0, 31, 19, 0, 31, 31, 0, 31, 28, 0, 31, 11, 0, 31, 31, 16, 15, 19, 16, 15, 23, 24, 15, 7, 24, 31, 9, 21, 14, 23 };
static const unsigned char moon_char_021[30] = { 0, 31, 1, 0, 31, 3, 0, 31, 19, 2, 29, 3, 0, 31, 31, 0, 8, 31, 0, 15, 31, 18, 13, 30, 17, 14, 31, 24, 23, 14 };
static const unsigned char moon_char_022[30] = { 0, 31, 25, 0, 31, 21, 24, 7, 27, 2, 29, 3, 0, 23, 31, 0, 2, 31, 8, 31, 31, 30, 3, 17, 16, 15, 31, 8, 31, 15 };
static const unsigned char moon_char_023[30] = { 0, 31, 31, 0, 28, 27, 0, 30, 31, 0, 15, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char moon_char_024[30] = { 0, 31, 31, 0, 31, 29, 0, 30, 31, 0, 28, 31, 0, 13, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 31, 0, 0, 31 };
static const unsigned char moon_char_025[30] = { 0, 31, 25, 0, 31, 23, 0, 29, 31, 0, 13, 31, 0, 16, 31, 0, 0, 31, 0, 6, 31, 0, 8, 31, 0, 17, 31, 0, 0, 31 };
static const unsigned char moon_char_026[30] = { 4, 31, 20, 0, 31, 31, 0, 16, 31, 0, 17, 31, 0, 26, 31, 0, 0, 31, 0, 1, 31, 0, 12, 31, 0, 17, 31, 0, 12, 31 };
static const unsigned char moon_char_027[30] = { 0, 31, 31, 0, 15, 31, 0, 31, 31, 0, 26, 31, 0, 18, 31, 0, 16, 31, 0, 16, 31, 0, 1, 31, 0, 16, 31, 0, 16, 31 };
static const unsigned char moon_char_028[30] = { 0, 12, 31, 0, 15, 31, 0, 7, 31, 0, 3, 31, 0, 3, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char moon_char_029[30] = { 0, 7, 31, 0, 31, 31, 0, 31, 22, 0, 31, 27, 0, 30, 31, 0, 14, 31, 0, 14, 31, 0, 6, 31, 0, 1, 31, 0, 0, 31 };
static const unsigned char moon_char_030[30] = { 31, 12, 16, 31, 4, 24, 15, 16, 8, 15, 24, 0, 15, 24, 16, 7, 8, 28, 3, 14, 24, 1, 31, 28, 0, 25, 31, 0, 15, 31 };
static const unsigned char moon_char_031[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 15, 24, 0, 7, 24, 16 };
static const unsigned char moon_char_032[30] = { 31, 7, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 8, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 31, 0, 1, 31, 0, 0 };
static const unsigned char moon_char_033[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 4, 0, 30, 3, 5, 31, 3, 0, 31, 1, 0 };
static const unsigned char moon_char_034[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 31, 0, 0, 31, 24, 0, 31, 1, 0, 31, 0, 0 };
static const unsigned char moon_char_035[30] = { 30, 17, 14, 27, 14, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0, 31, 0, 16, 31, 0, 0, 31, 0, 0, 29, 30, 0, 17, 26, 15 };
static const unsigned char moon_char_036[30] = { 31, 15, 16, 31, 16, 0, 31, 2, 0, 30, 1, 0, 30, 1, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char moon_char_037[30] = { 25, 22, 9, 19, 30, 3, 16, 31, 4, 0, 31, 31, 7, 24, 23, 27, 12, 10, 25, 14, 6, 29, 2, 1, 31, 1, 0, 31, 0, 0 };
static const unsigned char moon_char_038[30] = { 30, 9, 23, 2, 29, 30, 3, 29, 27, 0, 31, 9, 30, 25, 6, 31, 1, 0, 31, 1, 0, 31, 0, 3, 7, 24, 4, 31, 5, 0 };
static const unsigned char moon_char_039[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 7, 0, 28, 31, 0, 25, 31, 0, 31, 25, 15, 29, 0, 15, 20, 8, 19, 15, 16, 31, 20, 8 };
static const unsigned char moon_char_040[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 14, 27, 0, 31, 15, 0, 31, 31, 16, 15, 23, 24, 7, 15, 24, 5, 31, 16, 12, 7 };
static const unsigned char moon_char_041[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 0, 31 };
static const unsigned char moon_char_042[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char moon_char_043[30] = { 0, 4, 31, 0, 0, 31, 0, 0, 31, 24, 4, 23, 24, 4, 7, 0, 2, 31, 0, 0, 31, 0, 8, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char moon_char_044[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 31, 0, 31, 1, 31, 31, 1, 31, 9, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0 };
static const unsigned char moon_char_045[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31, 31, 30, 13, 31, 31, 28, 1, 31, 1, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char moon_char_046[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 31, 0, 12, 31, 0, 18, 31, 0, 16, 31, 16, 30, 15, 16, 15, 6, 29, 10, 5 };
static const unsigned char moon_char_047[30] = { 0, 4, 31, 0, 4, 31, 0, 4, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 30, 31, 0, 31, 31, 0, 31, 31, 24, 7, 29 };
static const unsigned char moon_char_048[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 3, 31, 7, 0, 28, 0, 3, 28, 0, 6, 31, 0, 20, 31, 0, 30, 31, 0, 31, 27 };
static const unsigned char moon_char_049[30] = { 0, 15, 29, 0, 15, 31, 0, 15, 31, 0, 31, 31, 0, 11, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0, 31, 31, 0, 23, 31 };
static const unsigned char moon_char_050[30] = { 15, 24, 0, 27, 12, 4, 3, 28, 30, 9, 22, 13, 1, 26, 31, 0, 17, 31, 0, 31, 31, 0, 31, 28, 1, 30, 7, 3, 30, 30 };
static const unsigned char moon_char_051[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 6, 0, 23, 28, 0, 7, 24, 16, 7, 12, 24, 7, 31, 24, 22, 11, 20, 20, 11, 20 };
static const unsigned char moon_char_052[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 3, 0, 30, 21, 3, 0, 31, 3, 0, 30, 19 };
static const unsigned char moon_char_053[30] = { 31, 5, 2, 28, 7, 0, 31, 2, 1, 30, 3, 0, 30, 1, 2, 30, 3, 1, 28, 0, 7, 0, 24, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char moon_char_054[30] = { 16, 15, 31, 0, 27, 15, 16, 14, 23, 0, 31, 7, 0, 31, 3, 0, 31, 23, 0, 7, 31, 0, 6, 31, 0, 3, 31, 0, 3, 29 };
static const unsigned char moon_char_055[30] = { 14, 25, 16, 14, 1, 24, 3, 30, 24, 3, 20, 28, 3, 25, 30, 0, 19, 31, 0, 7, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char moon_char_056[30] = { 31, 16, 0, 15, 16, 0, 23, 28, 0, 31, 9, 14, 31, 30, 0, 0, 31, 23, 0, 28, 31, 0, 12, 31, 0, 30, 31, 0, 27, 30 };
static const unsigned char moon_char_057[30] = { 31, 3, 0, 31, 6, 1, 27, 12, 3, 31, 11, 0, 23, 13, 18, 0, 31, 28, 0, 7, 31, 0, 7, 30, 0, 31, 24, 31, 8, 31 };
static const unsigned char moon_char_058[30] = { 31, 16, 8, 15, 21, 8, 8, 23, 11, 0, 31, 3, 0, 31, 1, 26, 13, 18, 25, 22, 9, 7, 25, 4, 15, 20, 8, 31, 30, 0 };
static const unsigned char moon_char_059[30] = { 16, 30, 15, 0, 27, 31, 0, 7, 29, 0, 7, 31, 0, 25, 31, 1, 30, 29, 18, 31, 16, 30, 25, 6, 31, 28, 3, 31, 10, 5 };
static const unsigned char moon_char_060[30] = { 0, 8, 31, 0, 4, 31, 0, 12, 31, 0, 26, 31, 0, 24, 31, 0, 31, 31, 8, 23, 15, 0, 19, 31, 0, 23, 31, 16, 31, 31 };
static const unsigned char moon_char_061[30] = { 0, 0, 31, 0, 0, 31, 0, 1, 31, 0, 2, 31, 16, 8, 31, 0, 17, 31, 0, 27, 31, 0, 31, 27, 0, 31, 19, 0, 30, 25 };
static const unsigned char moon_char_062[30] = { 0, 0, 31, 0, 0, 31, 0, 2, 31, 0, 4, 31, 0, 19, 29, 0, 3, 31, 1, 14, 31, 25, 22, 15, 17, 14, 21, 3, 15, 24 };
static const unsigned char moon_char_063[30] = { 0, 24, 31, 0, 0, 31, 0, 0, 31, 0, 17, 31, 0, 27, 14, 7, 26, 31, 31, 8, 23, 31, 7, 0, 31, 26, 4, 31, 13, 0 };
static const unsigned char moon_char_064[30] = { 31, 24, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 19, 0, 31, 23, 8, 15, 31, 0, 0, 31, 16, 31, 0, 31 };
static const unsigned char moon_char_065[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 1, 31, 30, 1, 9, 23, 8, 0, 31, 14 };
static const unsigned char moon_char_066[30] = { 31, 0, 3, 31, 3, 0, 31, 0, 0, 31, 0, 0, 31, 2, 0, 31, 27, 4, 15, 16, 0, 31, 27, 4, 4, 27, 5, 0, 31, 24 };
static const unsigned char moon_char_067[30] = { 20, 11, 22, 28, 27, 13, 30, 11, 5, 31, 12, 3, 31, 28, 3, 31, 14, 17, 31, 3, 28, 23, 31, 16, 0, 31, 27, 0, 28, 7 };
static const unsigned char moon_char_068[30] = { 0, 31, 24, 3, 30, 31, 0, 15, 30, 0, 31, 31, 16, 15, 17, 4, 27, 5, 26, 31, 14, 17, 10, 29, 0, 31, 8, 0, 15, 31 };
static const unsigned char moon_char_069[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 29, 31, 19, 14, 25, 1, 30, 5, 0, 31, 25, 28, 11, 21, 8, 31, 3, 0, 31, 22 };
static const unsigned char moon_char_070[30] = { 1, 31, 29, 3, 28, 19, 0, 31, 16, 0, 31, 31, 8, 22, 11, 0, 28, 31, 0, 15, 23, 24, 23, 10, 15, 16, 31, 15, 16, 15 };
static const unsigned char moon_char_071[30] = { 31, 4, 27, 31, 10, 17, 15, 20, 11, 0, 31, 31, 0, 31, 30, 0, 23, 31, 0, 19, 30, 0, 31, 20, 28, 3, 29, 31, 24, 7 };
static const unsigned char moon_char_072[30] = { 0, 31, 29, 0, 30, 3, 9, 30, 15, 1, 30, 7, 0, 31, 31, 8, 23, 26, 16, 15, 20, 25, 6, 31, 1, 30, 31, 1, 31, 15 };
static const unsigned char moon_char_073[30] = { 0, 0, 31, 0, 0, 31, 24, 7, 31, 0, 31, 5, 0, 14, 31, 0, 31, 31, 0, 31, 25, 2, 24, 31, 0, 31, 9, 31, 8, 23 };
static const unsigned char moon_char_074[30] = { 0, 7, 28, 0, 23, 30, 0, 31, 31, 0, 31, 31, 0, 29, 31, 0, 28, 15, 0, 30, 31, 0, 31, 27, 4, 30, 3, 31, 15, 16 };
static const unsigned char moon_char_075[30] = { 0, 31, 3, 0, 31, 5, 0, 31, 29, 0, 31, 31, 0, 31, 31, 0, 27, 31, 0, 31, 31, 1, 31, 20, 0, 27, 31, 31, 0, 31 };
static const unsigned char moon_char_076[30] = { 1, 22, 29, 3, 28, 27, 9, 30, 27, 0, 31, 15, 0, 29, 15, 1, 26, 31, 1, 31, 31, 16, 15, 31, 0, 31, 29, 3, 28, 3 };
static const unsigned char moon_char_077[30] = { 19, 28, 19, 7, 27, 4, 18, 13, 18, 0, 31, 29, 2, 15, 26, 5, 27, 29, 2, 29, 6, 0, 31, 10, 6, 29, 18, 30, 13, 18 };
static const unsigned char moon_char_078[30] = { 31, 13, 0, 31, 1, 0, 31, 25, 6, 7, 27, 28, 31, 2, 29, 5, 31, 5, 5, 26, 5, 16, 9, 23, 7, 28, 31, 7, 30, 7 };
static const unsigned char moon_char_079[30] = { 29, 10, 21, 20, 11, 20, 31, 6, 25, 31, 4, 27, 0, 31, 15, 4, 27, 13, 0, 29, 27, 0, 15, 27, 8, 23, 11, 17, 31, 21 };
static const unsigned char moon_char_080[30] = { 24, 15, 31, 8, 31, 3, 0, 31, 19, 0, 31, 19, 8, 31, 30, 1, 30, 15, 7, 27, 16, 19, 12, 19, 16, 15, 22, 0, 31, 1 };
static const unsigned char moon_char_081[30] = { 0, 31, 31, 12, 23, 12, 31, 11, 16, 15, 24, 7, 3, 28, 31, 31, 1, 31, 31, 1, 0, 31, 4, 27, 3, 28, 11, 0, 31, 31 };
static const unsigned char moon_char_082[30] = { 31, 15, 16, 31, 28, 0, 31, 12, 16, 31, 28, 0, 31, 31, 0, 28, 15, 16, 17, 31, 12, 13, 22, 13, 12, 31, 7, 16, 31, 23 };
static const unsigned char moon_char_083[30] = { 31, 9, 0, 31, 25, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 31, 29, 0, 23, 10, 21, 2, 29, 18, 3, 28, 31, 7, 24, 7 };

const unsigned char * const moon_charset[84] = {
    moon_char_000,
    moon_char_001,
    moon_char_002,
    moon_char_003,
    moon_char_004,
    moon_char_005,
    moon_char_006,
    moon_char_007,
    moon_char_008,
    moon_char_009,
    moon_char_010,
    moon_char_011,
    moon_char_012,
    moon_char_013,
    moon_char_014,
    moon_char_015,
    moon_char_016,
    moon_char_017,
    moon_char_018,
    moon_char_019,
    moon_char_020,
    moon_char_021,
    moon_char_022,
    moon_char_023,
    moon_char_024,
    moon_char_025,
    moon_char_026,
    moon_char_027,
    moon_char_028,
    moon_char_029,
    moon_char_030,
    moon_char_031,
    moon_char_032,
    moon_char_033,
    moon_char_034,
    moon_char_035,
    moon_char_036,
    moon_char_037,
    moon_char_038,
    moon_char_039,
    moon_char_040,
    moon_char_041,
    moon_char_042,
    moon_char_043,
    moon_char_044,
    moon_char_045,
    moon_char_046,
    moon_char_047,
    moon_char_048,
    moon_char_049,
    moon_char_050,
    moon_char_051,
    moon_char_052,
    moon_char_053,
    moon_char_054,
    moon_char_055,
    moon_char_056,
    moon_char_057,
    moon_char_058,
    moon_char_059,
    moon_char_060,
    moon_char_061,
    moon_char_062,
    moon_char_063,
    moon_char_064,
    moon_char_065,
    moon_char_066,
    moon_char_067,
    moon_char_068,
    moon_char_069,
    moon_char_070,
    moon_char_071,
    moon_char_072,
    moon_char_073,
    moon_char_074,
    moon_char_075,
    moon_char_076,
    moon_char_077,
    moon_char_078,
    moon_char_079,
    moon_char_080,
    moon_char_081,
    moon_char_082,
    moon_char_083,
};

const unsigned char moon_map[122] = {
    30, 4,
    8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
    4, 4, 4, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 4, 4, 4, 4, 28, 29, 30, 31, 32, 33, 34,
    44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
    64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
};

