/* Auto-generated by spinningGlobe/cset.py from "neptune.jpg" */
#pragma once

#define NEPTUNE_CHARSET_SIZE 87
#define NEPTUNE_MAP_SIZE     122
#define NEPTUNE_CHAR_WIDTH   5
#define NEPTUNE_CHAR_HEIGHT  10
#define NEPTUNE_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char neptune_ntsc_palette[3];

/* Charset: 87 characters, each 30 bytes */
extern const unsigned char * const neptune_charset[87];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char neptune_map[122];


