/* Auto-generated by img2tiles.py from "p1.png" */
#pragma once

#define P1_CHARSET_SIZE 105
#define P1_MAP_SIZE     402
#define P1_CHAR_WIDTH   5
#define P1_CHAR_HEIGHT  10
#define P1_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char p1_ntsc_palette[3];

/* Charset: 105 characters, each 30 bytes */
extern const unsigned char * const p1_charset[105];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char p1_map[402];


