/* Auto-generated by spinningGlobe/cset.py from "pangea.png" */
#pragma once

#define PANGEA_CHARSET_SIZE 45
#define PANGEA_MAP_SIZE     122
#define PANGEA_CHAR_WIDTH   5
#define PANGEA_CHAR_HEIGHT  10
#define PANGEA_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char pangea_ntsc_palette[3];

/* Charset: 45 characters, each 30 bytes */
extern const unsigned char * const pangea_charset[45];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char pangea_map[122];


