/* Auto-generated by img2tiles.py from "purple1.png" */
/* Adaptive palette: 8 colours built from 3 EM-optimised primaries (NTSC-snapped). */
/* Index bits: bit0=P1, bit1=P2, bit2=P3 (P1/P2/P3 = single-bit primaries). */
/* Character: 5 pixels wide x 10 trixels deep (30 scanlines). */
/* Trixel: 1 pixel wide x 3 scanlines deep, 3-bit palette index. */
/* Character storage: 10 trixel-rows x 3 bytes (bit0-plane, bit1-plane, bit2-plane) = 30 bytes. */
/* Byte bit layout: bit4=col0(left) .. bit0=col4(right), bits7-5 unused. */
/* Map: byte0=width(chars, +10 wrap buffer), byte1=height(chars), then row-major indices. */

static const unsigned char purple1_palette[8][3] = {
    {0, 0, 0},       /* 0: origin */
    {0, 60, 44},     /* 1: +P1 */
    {64, 64, 64},    /* 2: +P2 */
    {32, 62, 54},    /* 3: +P1+P2 */
    {144, 144, 144}, /* 4: +P3 */
    {72, 102, 94},   /* 5: +P1+P3 */
    {104, 104, 104}, /* 6: +P2+P3 */
    {69, 89, 84},    /* 7: +P1+P2+P3 */
};

/* NTSC Atari 2600 companion palette: nearest TIA register values for
 * palette primaries (indices 1, 2, 4 — the single-bit entries). */
const unsigned char purple1_ntsc_palette[3] = {
    0x86, /* palette[1] = (0,60,44) */
    0x96, /* palette[2] = (64,64,64) */
    0xD6, /* palette[4] = (144,144,144) */
};

static const unsigned char purple1_char_000[30] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const unsigned char purple1_char_001[30] = {31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0,
                                                   31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0};
static const unsigned char purple1_char_002[30] = {0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0,
                                                   0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0};
static const unsigned char purple1_char_003[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_004[30] = {0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31,
                                                   0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31};
static const unsigned char purple1_char_005[30] = {31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31,
                                                   31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31};
static const unsigned char purple1_char_006[30] = {0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31,
                                                   0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31};
static const unsigned char purple1_char_007[30] = {31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
                                                   31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31};
static const unsigned char purple1_char_008[30] = {0,  0,  31, 0,  0,  31, 0,  31, 31, 31, 29, 31, 31, 31, 3,
                                                   31, 31, 0,  31, 31, 0,  31, 31, 0,  31, 31, 0,  31, 31, 0};
static const unsigned char purple1_char_009[30] = {0,  0,  31, 0,  0,  31, 0,  31, 31, 31, 31, 31, 31, 31, 0,
                                                   31, 31, 0,  31, 30, 0,  31, 28, 0,  31, 16, 0,  31, 16, 0};
static const unsigned char purple1_char_010[30] = {0,  0,  31, 0,  0,  31, 0,  31, 31, 31, 31, 31, 31, 31, 0,
                                                   31, 31, 0,  31, 31, 0,  31, 31, 0,  31, 1,  0,  31, 0,  0};
static const unsigned char purple1_char_011[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   31, 15, 0, 31, 15, 0, 31, 15, 0, 31, 14, 0, 31, 14, 0};
static const unsigned char purple1_char_012[30] = {31, 0, 0, 31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0,
                                                   31, 3, 0, 31, 15, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_013[30] = {31, 14, 0, 31, 14, 0, 31, 14, 0, 31, 14, 0, 31, 30, 0,
                                                   31, 30, 0, 31, 30, 0, 31, 30, 0, 31, 28, 0, 31, 28, 0};
static const unsigned char purple1_char_014[30] = {31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 1,  0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 30, 31, 0, 30, 31, 0};
static const unsigned char purple1_char_015[30] = {31, 0,  0, 31, 0,  0, 31, 4,  0, 31, 15, 0, 31, 31, 0,
                                                   31, 31, 0, 23, 31, 0, 7,  31, 0, 7,  31, 0, 7,  31, 0};
static const unsigned char purple1_char_016[30] = {31, 0, 0, 31, 1, 0, 31, 1, 0, 31, 1,  0, 31, 1,  0,
                                                   31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 12, 0, 31, 30, 0};
static const unsigned char purple1_char_017[30] = {31, 16, 0, 31, 24, 0, 31, 16, 0, 31, 7,  0, 31, 31, 0,
                                                   31, 15, 0, 31, 15, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_018[30] = {31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 24, 0, 31, 31, 0,
                                                   31, 31, 0, 31, 31, 0, 25, 31, 0, 24, 31, 0, 24, 31, 0};
static const unsigned char purple1_char_019[30] = {31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 6,  0, 31, 7,  0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 7,  31, 0};
static const unsigned char purple1_char_020[30] = {31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0,
                                                   31, 16, 0, 31, 16, 0, 31, 16, 0, 31, 28, 0, 31, 30, 0};
static const unsigned char purple1_char_021[30] = {31, 0, 0, 31, 3,  0, 31, 3,  0, 31, 3,  0, 31, 7,  0,
                                                   31, 7, 0, 31, 15, 0, 31, 31, 0, 24, 31, 0, 16, 31, 0};
static const unsigned char purple1_char_022[30] = {31, 16, 0, 31, 28, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   31, 31, 0, 19, 31, 0, 1,  31, 0, 1,  31, 0, 0,  31, 0};
static const unsigned char purple1_char_023[30] = {31, 8,  0, 31, 30, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_024[30] = {31, 0, 0, 31, 0,  0, 31, 0,  0, 31, 3,  0, 31, 7,  0,
                                                   31, 7, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_025[30] = {31, 0,  0, 31, 4,  0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   31, 31, 0, 31, 31, 0, 30, 31, 0, 28, 31, 0, 28, 31, 0};
static const unsigned char purple1_char_026[30] = {31, 0, 0, 31, 0, 0, 31, 0,  0, 31, 0,  0, 31, 0,  0,
                                                   31, 0, 0, 31, 0, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_027[30] = {31, 0, 0, 31, 0, 0, 31, 0,  0, 31, 0,  0, 31, 0,  0,
                                                   31, 0, 0, 31, 8, 0, 31, 28, 0, 31, 28, 0, 31, 31, 0};
static const unsigned char purple1_char_028[30] = {31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0,  0,
                                                   31, 0, 0, 31, 6, 0, 31, 7, 0, 29, 7, 0, 24, 15, 0};
static const unsigned char purple1_char_029[30] = {31, 1,  0, 31, 1,  0, 31, 1,  0, 31, 3,  0, 31, 3,  0,
                                                   31, 15, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_030[30] = {31, 28, 0, 31, 28, 0, 31, 28, 0, 31, 30, 0, 31, 31, 0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_031[30] = {30, 31, 0, 28, 31, 0, 24, 31, 0, 24, 31, 0, 28, 31, 0,
                                                   30, 31, 0, 30, 31, 0, 28, 31, 0, 0,  31, 0, 0,  31, 0};
static const unsigned char purple1_char_032[30] = {7, 31, 0, 7, 31, 0, 6, 31, 0, 4, 31, 0, 4, 31, 0,
                                                   0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0};
static const unsigned char purple1_char_033[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 1, 31, 0,
                                                   1,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0, 0, 31, 0};
static const unsigned char purple1_char_034[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   30, 31, 0, 30, 31, 0, 8,  31, 0, 0,  31, 0, 0,  31, 0};
static const unsigned char purple1_char_035[30] = {31, 31, 0, 15, 31, 0, 15, 31, 0, 7, 31, 0, 0, 31, 0,
                                                   0,  31, 0, 0,  31, 0, 0,  31, 0, 1, 31, 0, 0, 31, 0};
static const unsigned char purple1_char_036[30] = {31, 16, 0, 31, 16, 0, 31, 24, 0, 31, 28, 0, 15, 31, 0,
                                                   7,  27, 0, 15, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_037[30] = {31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 25, 0, 31, 27, 0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 30, 31, 0};
static const unsigned char purple1_char_038[30] = {31, 2,  0, 31, 3,  0, 30, 3,  0, 30, 31, 0, 28, 31, 0,
                                                   16, 31, 0, 16, 31, 0, 16, 31, 0, 0,  31, 0, 0,  31, 0};
static const unsigned char purple1_char_039[30] = {31, 14, 0, 31, 31, 0, 31, 31, 0, 16, 31, 0, 0, 31, 0,
                                                   0,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0, 0, 31, 0};
static const unsigned char purple1_char_040[30] = {30, 15, 0, 24, 31, 0, 16, 31, 0, 0, 31, 0, 0, 31, 0,
                                                   0,  31, 0, 0,  31, 0, 0,  31, 0, 0, 31, 0, 0, 31, 0};
static const unsigned char purple1_char_041[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 28, 31, 0, 12, 31, 0,
                                                   14, 31, 0, 4,  31, 0, 4,  31, 0, 0,  31, 0, 0,  31, 0};
static const unsigned char purple1_char_042[30] = {24, 15, 0, 17, 31, 0, 3, 31, 0, 18, 31, 0, 16, 31, 0,
                                                   0,  31, 0, 0,  31, 0, 0, 31, 0, 0,  31, 0, 0,  31, 0};
static const unsigned char purple1_char_043[30] = {31, 7,  0, 31, 15, 0, 28, 31, 0, 16, 31, 0, 0, 31, 0,
                                                   0,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0, 0, 31, 0};
static const unsigned char purple1_char_044[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 15, 31, 0, 15, 31, 0,
                                                   7,  31, 0, 1,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0};
static const unsigned char purple1_char_045[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   31, 31, 0, 15, 31, 0, 7,  31, 0, 0,  31, 0, 0,  31, 0};
static const unsigned char purple1_char_046[30] = {0, 31, 0,  0,  31, 0,  0, 31, 0,  0, 31, 0,  0,  31, 12,
                                                   0, 31, 14, 16, 31, 30, 0, 31, 30, 0, 31, 28, 16, 31, 16};
static const unsigned char purple1_char_047[30] = {0, 31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 7,  0, 31, 15,
                                                   0, 24, 31, 0, 28, 31, 0, 24, 31, 0, 9,  31, 0, 3,  31};
static const unsigned char purple1_char_048[30] = {0, 31, 0,  16, 31, 24, 0, 31, 30, 0, 31, 31, 0, 31, 31,
                                                   0, 25, 31, 0,  1,  31, 0, 1,  31, 0, 7,  30, 0, 31, 30};
static const unsigned char purple1_char_049[30] = {0,  31, 0,  0, 31, 0, 0, 31, 0, 16, 31, 16, 0, 31, 16,
                                                   16, 31, 16, 0, 31, 0, 0, 31, 0, 0,  31, 0,  0, 31, 0};
static const unsigned char purple1_char_050[30] = {0, 31, 0, 0, 31, 0, 0, 31, 0,  0, 31, 0,  0,  31, 0,
                                                   0, 31, 0, 6, 31, 7, 0, 30, 15, 0, 24, 15, 16, 24, 31};
static const unsigned char purple1_char_051[30] = {0, 31, 0, 0,  31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,
                                                   0, 31, 0, 16, 31, 16, 8, 31, 24, 0, 15, 28, 0, 7,  28};
static const unsigned char purple1_char_052[30] = {0, 31, 1, 0, 30, 3, 0, 28, 7, 0, 29, 7, 5, 31, 7,
                                                   0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0};
static const unsigned char purple1_char_053[30] = {0, 3,  31, 0, 3,  31, 0, 23, 31, 0, 23, 31, 0, 16, 31,
                                                   0, 31, 15, 0, 31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0};
static const unsigned char purple1_char_054[30] = {0, 31, 30, 2, 31, 30, 0, 31, 28, 0, 31, 28, 0, 7,  28,
                                                   0, 23, 28, 0, 31, 12, 0, 31, 0,  0, 31, 0,  0, 31, 0};
static const unsigned char purple1_char_055[30] = {0, 31, 0, 1, 31, 1, 2, 31, 3, 0, 30, 3, 0, 30, 3,
                                                   0, 31, 3, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0};
static const unsigned char purple1_char_056[30] = {0, 31, 12, 0, 31, 28, 2, 7,  31, 0, 7,  31, 0, 15, 31,
                                                   1, 31, 17, 1, 31, 1,  0, 31, 0,  0, 31, 0,  0, 31, 0};
static const unsigned char purple1_char_057[30] = {16, 31, 17, 12, 31, 15, 0, 31, 7,  16, 31, 23, 0, 31, 31,
                                                   0,  30, 31, 0,  30, 31, 0, 31, 31, 0,  31, 7,  0, 31, 3};
static const unsigned char purple1_char_058[30] = {0, 16, 31, 0, 0, 31, 0, 0,  31, 0, 0,  31, 0, 0,  31,
                                                   0, 3,  31, 0, 7, 28, 0, 15, 28, 0, 31, 24, 8, 31, 24};
static const unsigned char purple1_char_059[30] = {2, 7,  30, 0, 7,  30, 0,  7,  30, 0, 7,  30, 2, 7,  30,
                                                   0, 19, 30, 1, 19, 31, 16, 31, 31, 8, 31, 15, 3, 31, 3};
static const unsigned char purple1_char_060[30] = {0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0,
                                                   0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 4, 31, 6};
static const unsigned char purple1_char_061[30] = {16, 31, 0, 18, 31, 0, 31, 31, 0, 23, 31, 0, 19, 31, 0,
                                                   23, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_062[30] = {0, 31, 0, 0,  31, 0, 0,  31, 0, 0, 31, 0, 1,  31, 0,
                                                   3, 31, 0, 15, 31, 0, 15, 31, 0, 7, 31, 0, 15, 31, 0};
static const unsigned char purple1_char_063[30] = {0,  31, 0, 0,  31, 0, 2,  31, 0, 3,  31, 0, 23, 31, 0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 15, 0};
static const unsigned char purple1_char_064[30] = {0,  31, 0, 0,  31, 0, 0,  31, 0, 1,  31, 0, 31, 31, 0,
                                                   30, 31, 0, 30, 31, 0, 30, 31, 0, 24, 31, 0, 16, 31, 0};
static const unsigned char purple1_char_065[30] = {1, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0,
                                                   3, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0, 7, 31, 0};
static const unsigned char purple1_char_066[30] = {0,  31, 0, 28, 31, 0, 30, 31, 0, 31, 31, 0, 31, 30, 0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 30, 0, 31, 28, 0};
static const unsigned char purple1_char_067[30] = {0,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0,
                                                   31, 31, 0, 31, 31, 0, 31, 16, 0, 31, 0,  0, 31, 0,  0};
static const unsigned char purple1_char_068[30] = {0,  31, 0, 0,  31, 0, 0,  31, 0, 3,  31, 0, 31, 31, 0,
                                                   31, 31, 0, 31, 15, 0, 31, 7,  0, 31, 3,  0, 31, 0,  0};
static const unsigned char purple1_char_069[30] = {0,  31, 0, 2,  31, 0, 3,  31, 0, 7,  31, 0, 31, 31, 0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 7,  0};
static const unsigned char purple1_char_070[30] = {3,  31, 0, 15, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   30, 31, 0, 30, 31, 0, 28, 31, 0, 30, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_071[30] = {24, 31, 0, 24, 31, 0, 24, 31, 0, 24, 31, 0, 16, 31, 0,
                                                   0,  31, 0, 0,  31, 0, 0,  31, 0, 1,  31, 0, 1,  31, 0};
static const unsigned char purple1_char_072[30] = {0, 31, 0, 0, 31, 0, 0, 31, 0, 0,  31, 0, 0,  31, 0,
                                                   0, 31, 0, 1, 31, 0, 3, 31, 0, 31, 31, 0, 31, 23, 0};
static const unsigned char purple1_char_073[30] = {0, 31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0,
                                                   0, 31, 0, 14, 31, 0, 15, 31, 0, 15, 31, 0, 31, 23, 0};
static const unsigned char purple1_char_074[30] = {0, 31, 6, 0, 31, 0, 0, 31, 0, 0,  31, 0, 0,  31, 0,
                                                   0, 31, 0, 0, 31, 0, 6, 31, 0, 15, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_075[30] = {0, 31, 0, 0, 31, 0, 0, 31, 0, 0,  31, 0, 1,  31, 0,
                                                   7, 31, 0, 7, 31, 0, 7, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_076[30] = {0,  31, 0, 0,  31, 0, 1,  31, 0, 3,  31, 0, 1,  31, 0,
                                                   27, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_077[30] = {31, 31, 0, 31, 31, 0, 31, 3, 0, 31, 1, 0, 31, 1, 0,
                                                   31, 1,  0, 31, 0,  0, 31, 0, 0, 31, 0, 0, 31, 0, 0};
static const unsigned char purple1_char_078[30] = {24, 31, 0, 24, 31, 0, 24, 31, 0, 28, 31, 0, 24, 31, 0,
                                                   24, 31, 0, 28, 31, 0, 31, 15, 0, 31, 7,  0, 31, 1,  0};
static const unsigned char purple1_char_079[30] = {0,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0, 24, 31, 0,
                                                   31, 31, 0, 31, 29, 0, 31, 24, 0, 31, 16, 0, 31, 16, 0};
static const unsigned char purple1_char_080[30] = {15, 31, 0, 15, 31, 0, 15, 31, 0, 31, 30, 0, 31, 30, 0,
                                                   31, 24, 0, 31, 24, 0, 31, 0,  0, 31, 0,  0, 31, 0,  0};
static const unsigned char purple1_char_081[30] = {31, 31, 0, 31, 15, 0, 31, 15, 0, 31, 1, 0, 31, 0, 0,
                                                   31, 0,  0, 31, 1,  0, 31, 0,  0, 31, 0, 0, 31, 0, 0};
static const unsigned char purple1_char_082[30] = {16, 31, 0, 24, 31, 0, 30, 31, 0, 30, 31, 0, 31, 31, 0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 1,  0, 31, 0,  0};
static const unsigned char purple1_char_083[30] = {4,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0,
                                                   24, 31, 0, 28, 31, 0, 28, 31, 0, 28, 31, 0, 25, 31, 0};
static const unsigned char purple1_char_084[30] = {15, 31, 0, 7, 31, 0, 7, 29, 0, 3,  31, 0, 1,  31, 0,
                                                   1,  31, 0, 1, 31, 0, 3, 31, 0, 15, 31, 0, 31, 30, 0};
static const unsigned char purple1_char_085[30] = {31, 28, 0, 31, 24, 0, 31, 16, 0, 31, 16, 0, 31, 16, 0,
                                                   31, 0,  0, 31, 16, 0, 31, 16, 0, 31, 0,  0, 31, 0,  0};
static const unsigned char purple1_char_086[30] = {3,  31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 15, 0,
                                                   31, 7,  0, 31, 7,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0};
static const unsigned char purple1_char_087[30] = {31, 15, 0, 31, 15, 0, 31, 6, 0, 31, 4, 0, 31, 0, 0,
                                                   31, 0,  0, 31, 0,  0, 31, 0, 0, 31, 0, 0, 31, 0, 0};
static const unsigned char purple1_char_088[30] = {31, 31, 0, 31, 7, 0, 31, 3, 0, 31, 3, 0, 31, 1, 0,
                                                   31, 1,  0, 31, 1, 0, 31, 1, 0, 31, 3, 0, 31, 7, 0};
static const unsigned char purple1_char_089[30] = {16, 31, 0, 16, 31, 0, 16, 31, 0, 23, 31, 0, 7,  31, 0,
                                                   15, 31, 0, 15, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_090[30] = {3,  31, 0, 3,  31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   31, 29, 0, 31, 30, 0, 31, 31, 0, 31, 30, 0, 31, 30, 0};
static const unsigned char purple1_char_091[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   31, 23, 0, 31, 7,  0, 31, 7,  0, 31, 3,  0, 31, 0,  0};
static const unsigned char purple1_char_092[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   31, 28, 0, 31, 28, 0, 31, 24, 0, 31, 28, 0, 31, 28, 0};
static const unsigned char purple1_char_093[30] = {31, 31, 0, 31, 31, 0, 31, 15, 0, 31, 7, 0, 31, 0, 0,
                                                   31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 1, 0, 31, 3, 0};
static const unsigned char purple1_char_094[30] = {31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0,
                                                   31, 16, 0, 31, 28, 0, 31, 28, 0, 31, 28, 0, 31, 24, 0};
static const unsigned char purple1_char_095[30] = {29, 31, 0, 31, 15, 0, 31, 15, 0, 31, 15, 0, 31, 4, 0,
                                                   31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0, 0};
static const unsigned char purple1_char_096[30] = {31, 28, 0, 31, 24, 0, 31, 24, 0, 31, 24, 0, 31, 0, 0,
                                                   31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0, 0};
static const unsigned char purple1_char_097[30] = {31, 7, 0, 31, 3, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0,
                                                   31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 31, 1, 0};
static const unsigned char purple1_char_098[30] = {31, 23, 0, 31, 8, 0, 31, 24, 0, 31, 24, 0, 31, 8, 0,
                                                   31, 0,  0, 31, 0, 0, 31, 0,  0, 31, 0,  0, 31, 0, 0};
static const unsigned char purple1_char_099[30] = {31, 30, 0, 31, 6, 0, 31, 0, 0, 31, 0, 0, 31, 0,  0,
                                                   31, 0,  0, 31, 0, 0, 31, 0, 0, 31, 8, 0, 31, 24, 0};
static const unsigned char purple1_char_100[30] = {31, 7,  0, 31, 7,  0,  31, 15, 0,  31, 14, 0,  31, 31, 0,
                                                   31, 31, 0, 31, 31, 31, 16, 15, 31, 0,  0,  31, 0,  0,  31};
static const unsigned char purple1_char_101[30] = {31, 24, 0, 31, 24, 0,  31, 0,  0,  31, 0, 0,  31, 31, 0,
                                                   31, 31, 0, 31, 31, 31, 1,  30, 31, 0,  0, 31, 0,  0,  31};
static const unsigned char purple1_char_102[30] = {31, 12, 0, 31, 15, 0,  31, 23, 0,  31, 15, 0,  31, 31, 0,
                                                   31, 31, 0, 31, 31, 31, 16, 15, 31, 0,  0,  31, 0,  0,  31};
static const unsigned char purple1_char_103[30] = {31, 24, 0, 31, 28, 0,  31, 28, 0,  31, 31, 0,  31, 31, 0,
                                                   31, 31, 0, 31, 31, 31, 0,  31, 31, 0,  0,  31, 0,  0,  31};
static const unsigned char purple1_char_104[30] = {0,  0, 31, 0,  0, 31, 31, 0, 31, 31, 31, 31, 31, 31, 0,
                                                   31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0,  0,  31, 0,  0};
static const unsigned char purple1_char_105[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0,
                                                   31, 31, 0, 31, 28, 0, 31, 24, 0, 31, 0,  0, 31, 0,  0};
static const unsigned char purple1_char_106[30] = {31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 28, 0, 31, 0, 0,
                                                   31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0, 0};
static const unsigned char purple1_char_107[30] = {0,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0, 16, 31, 0,
                                                   16, 31, 0, 23, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_108[30] = {0, 31, 0, 0, 31, 0, 0, 31, 0, 0,  31, 0, 0,  31, 0,
                                                   0, 31, 0, 0, 31, 0, 0, 31, 0, 24, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_109[30] = {31, 7, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0,
                                                   31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0};
static const unsigned char purple1_char_110[30] = {31, 31, 0, 31, 7, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0,
                                                   31, 0,  0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0};
static const unsigned char purple1_char_111[30] = {0, 31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0,
                                                   0, 31, 0, 16, 31, 0, 24, 31, 0, 30, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_112[30] = {0,  0,  31, 0,  0,  31, 0,  31, 31, 31, 31, 31, 31, 31, 0,
                                                   31, 31, 0,  31, 31, 0,  31, 31, 0,  31, 31, 0,  31, 31, 0};
static const unsigned char purple1_char_113[30] = {0,  0, 31, 0,  0, 31, 0,  31, 31, 31, 31, 31, 31, 31, 0,
                                                   31, 4, 0,  31, 0, 0,  31, 0,  0,  31, 0,  0,  31, 0,  0};
static const unsigned char purple1_char_114[30] = {31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0,  0, 31, 0,  0,
                                                   31, 0, 0, 31, 3, 0, 31, 7, 0, 31, 15, 0, 31, 15, 0};
static const unsigned char purple1_char_115[30] = {31, 28, 0, 31, 28, 0, 31, 31, 0, 15, 31, 0, 15, 31, 0,
                                                   8,  31, 0, 8,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0};
static const unsigned char purple1_char_116[30] = {31, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0,
                                                   0,  31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0};
static const unsigned char purple1_char_117[30] = {0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0,
                                                   0, 31, 0, 0, 31, 0, 3, 31, 0, 3, 31, 0, 3, 31, 0};
static const unsigned char purple1_char_118[30] = {31, 31, 0, 31, 31, 0, 31, 19, 0, 31, 17, 0, 31, 0, 0,
                                                   31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 0, 0};
static const unsigned char purple1_char_119[30] = {31, 0,  0, 31, 0,  0,  31, 0, 0,  31, 0, 0,  31, 0, 0,
                                                   31, 31, 0, 31, 31, 31, 31, 0, 31, 0,  0, 31, 0,  0, 31};
static const unsigned char purple1_char_120[30] = {31, 0,  0, 31, 0,  0,  31, 0,  0,  31, 0, 0,  31, 31, 0,
                                                   31, 31, 0, 31, 31, 31, 17, 14, 31, 0,  0, 31, 0,  0,  31};
static const unsigned char purple1_char_121[30] = {0,  0,  31, 0,  0, 31, 0,  31, 31, 31, 31, 31, 31, 31, 0,
                                                   31, 31, 0,  31, 0, 0,  31, 0,  0,  31, 0,  0,  31, 0,  0};
static const unsigned char purple1_char_122[30] = {0,  0, 31, 0,  0, 31, 24, 7, 31, 31, 31, 31, 31, 31, 0,
                                                   31, 7, 0,  31, 0, 0,  31, 0, 0,  31, 0,  0,  31, 0,  0};
static const unsigned char purple1_char_123[30] = {31, 0, 0, 31, 0, 0, 31, 0,  0, 31, 0,  0, 31, 0,  0,
                                                   31, 0, 0, 31, 0, 0, 31, 16, 0, 31, 16, 0, 31, 24, 0};
static const unsigned char purple1_char_124[30] = {31, 0,  0, 31, 0,  0, 31, 0,  0, 31, 28, 0, 31, 28, 0,
                                                   31, 30, 0, 31, 30, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};
static const unsigned char purple1_char_125[30] = {31, 31, 0, 31, 31, 0, 13, 31, 0, 8, 31, 0, 0, 31, 0,
                                                   0,  31, 0, 0,  31, 0, 0,  31, 0, 0, 31, 0, 0, 31, 0};
static const unsigned char purple1_char_126[30] = {7, 31, 0, 3, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0,
                                                   0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0};
static const unsigned char purple1_char_127[30] = {0,  31, 0, 0,  31, 0, 0,  31, 0, 0,  31, 0, 25, 31, 0,
                                                   31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0};

const unsigned char *const purple1_charset[128] = {
    purple1_char_000, purple1_char_001, purple1_char_002, purple1_char_003, purple1_char_004, purple1_char_005,
    purple1_char_006, purple1_char_007, purple1_char_008, purple1_char_009, purple1_char_010, purple1_char_011,
    purple1_char_012, purple1_char_013, purple1_char_014, purple1_char_015, purple1_char_016, purple1_char_017,
    purple1_char_018, purple1_char_019, purple1_char_020, purple1_char_021, purple1_char_022, purple1_char_023,
    purple1_char_024, purple1_char_025, purple1_char_026, purple1_char_027, purple1_char_028, purple1_char_029,
    purple1_char_030, purple1_char_031, purple1_char_032, purple1_char_033, purple1_char_034, purple1_char_035,
    purple1_char_036, purple1_char_037, purple1_char_038, purple1_char_039, purple1_char_040, purple1_char_041,
    purple1_char_042, purple1_char_043, purple1_char_044, purple1_char_045, purple1_char_046, purple1_char_047,
    purple1_char_048, purple1_char_049, purple1_char_050, purple1_char_051, purple1_char_052, purple1_char_053,
    purple1_char_054, purple1_char_055, purple1_char_056, purple1_char_057, purple1_char_058, purple1_char_059,
    purple1_char_060, purple1_char_061, purple1_char_062, purple1_char_063, purple1_char_064, purple1_char_065,
    purple1_char_066, purple1_char_067, purple1_char_068, purple1_char_069, purple1_char_070, purple1_char_071,
    purple1_char_072, purple1_char_073, purple1_char_074, purple1_char_075, purple1_char_076, purple1_char_077,
    purple1_char_078, purple1_char_079, purple1_char_080, purple1_char_081, purple1_char_082, purple1_char_083,
    purple1_char_084, purple1_char_085, purple1_char_086, purple1_char_087, purple1_char_088, purple1_char_089,
    purple1_char_090, purple1_char_091, purple1_char_092, purple1_char_093, purple1_char_094, purple1_char_095,
    purple1_char_096, purple1_char_097, purple1_char_098, purple1_char_099, purple1_char_100, purple1_char_101,
    purple1_char_102, purple1_char_103, purple1_char_104, purple1_char_105, purple1_char_106, purple1_char_107,
    purple1_char_108, purple1_char_109, purple1_char_110, purple1_char_111, purple1_char_112, purple1_char_113,
    purple1_char_114, purple1_char_115, purple1_char_116, purple1_char_117, purple1_char_118, purple1_char_119,
    purple1_char_120, purple1_char_121, purple1_char_122, purple1_char_123, purple1_char_124, purple1_char_125,
    purple1_char_126, purple1_char_127,
};

const unsigned char purple1_map[402] = {
    40,  10,  121, 104, 104, 104, 112, 112, 8,   9,   121, 104, 104, 122, 121, 121, 121, 113, 113, 104, 104, 104, 122,
    122, 121, 121, 121, 121, 121, 122, 10,  112, 121, 104, 104, 104, 112, 112, 8,   9,   121, 104, 1,   1,   1,   1,
    11,  105, 106, 1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
    1,   12,  13,  1,   1,   1,   1,   11,  105, 106, 1,   1,   1,   14,  15,  124, 123, 16,  17,  18,  19,  20,  1,
    1,   1,   21,  22,  23,  124, 123, 1,   114, 24,  25,  124, 26,  27,  28,  123, 114, 29,  3,   30,  14,  15,  124,
    123, 16,  17,  18,  19,  20,  1,   31,  32,  125, 33,  34,  125, 2,   2,   35,  36,  37,  38,  2,   2,   2,   126,
    115, 39,  40,  126, 2,   2,   116, 41,  42,  115, 43,  126, 44,  45,  31,  32,  125, 33,  34,  125, 2,   2,   35,
    36,  2,   2,   46,  2,   2,   2,   2,   2,   2,   116, 2,   2,   2,   2,   47,  48,  49,  2,   2,   2,   2,   2,
    50,  51,  2,   2,   2,   2,   2,   2,   2,   2,   46,  2,   2,   2,   2,   2,   2,   116, 2,   2,   2,   2,   2,
    2,   2,   2,   2,   2,   2,   2,   2,   52,  53,  54,  2,   2,   2,   55,  56,  57,  58,  59,  60,  2,   2,   2,
    2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   61,  107, 111, 2,   2,   2,   2,   62,  63,  127, 64,
    65,  3,   66,  67,  68,  69,  70,  71,  72,  107, 111, 73,  108, 74,  2,   117, 75,  127, 76,  61,  107, 111, 2,
    2,   2,   2,   62,  63,  127, 118, 106, 77,  78,  108, 117, 79,  80,  1,   81,  82,  83,  84,  85,  1,   1,   109,
    118, 86,  1,   109, 110, 1,   87,  88,  89,  90,  105, 91,  92,  118, 106, 77,  78,  108, 117, 79,  80,  1,   81,
    1,   1,   1,   1,   110, 93,  94,  1,   1,   1,   1,   95,  96,  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
    1,   97,  98,  99,  1,   1,   110, 1,   1,   1,   1,   110, 93,  94,  1,   1,   1,   119, 119, 119, 119, 119, 100,
    101, 120, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 120, 120, 102, 103, 120, 119,
    119, 119, 119, 119, 119, 119, 100, 101, 120, 119, 119,
};
