/* Auto-generated by img2tiles.py from "purple1.png" */
#pragma once

#define PURPLE1_CHARSET_SIZE 128
#define PURPLE1_MAP_SIZE     402
#define PURPLE1_CHAR_WIDTH   5
#define PURPLE1_CHAR_HEIGHT  10
#define PURPLE1_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char purple1_ntsc_palette[3];

/* Charset: 128 characters, each 30 bytes */
extern const unsigned char * const purple1_charset[128];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char purple1_map[402];


