/* Auto-generated by spinningGlobe/cset.py from "ridged.png" */
#pragma once

#define RIDGED_CHARSET_SIZE 88
#define RIDGED_MAP_SIZE     122
#define RIDGED_CHAR_WIDTH   5
#define RIDGED_CHAR_HEIGHT  10
#define RIDGED_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char ridged_ntsc_palette[3];

/* Charset: 88 characters, each 30 bytes */
extern const unsigned char * const ridged_charset[88];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char ridged_map[122];


