/* Auto-generated by img2tiles.py from "ridged.png" */
/* Adaptive palette: 8 colours built from 3 EM-optimised primaries (NTSC-snapped). */
/* Index bits: bit0=P1, bit1=P2, bit2=P3 (P1/P2/P3 = single-bit primaries). */
/* Character: 5 pixels wide x 10 trixels deep (30 scanlines). */
/* Trixel: 1 pixel wide x 3 scanlines deep, 3-bit palette index. */
/* Character storage: 10 trixel-rows x 3 bytes (bit0-plane, bit1-plane, bit2-plane) = 30 bytes. */
/* Byte bit layout: bit4=col0(left) .. bit0=col4(right), bits7-5 unused. */
/* Map: byte0=width(chars, +10 wrap buffer), byte1=height(chars), then row-major indices. */

static const unsigned char ridged_palette[8][3] = {
    {   0,   0,   0 },  /* 0: origin */
    {   0,  44,  92 },  /* 1: +P1 */
    {  64,  64,  64 },  /* 2: +P2 */
    {  32,  54,  78 },  /* 3: +P1+P2 */
    { 144, 144, 144 },  /* 4: +P3 */
    {  72,  94, 118 },  /* 5: +P1+P3 */
    { 104, 104, 104 },  /* 6: +P2+P3 */
    {  69,  84, 100 },  /* 7: +P1+P2+P3 */
};

/* NTSC Atari 2600 companion palette: nearest TIA register values for
 * palette primaries (indices 1, 2, 4 — the single-bit entries). */
const unsigned char ridged_ntsc_palette[3] = {
    0xA0,  /* palette[1] = (0,44,92) */
    0x02,  /* palette[2] = (64,64,64) */
    0x06,  /* palette[4] = (144,144,144) */
};

static const unsigned char ridged_char_000[30] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static const unsigned char ridged_char_001[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_002[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char ridged_char_003[30] = { 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0 };
static const unsigned char ridged_char_004[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_005[30] = { 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31 };
static const unsigned char ridged_char_006[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char ridged_char_007[30] = { 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31 };
static const unsigned char ridged_char_008[30] = { 0, 0, 31, 31, 0, 31, 31, 31, 13, 1, 31, 0, 28, 31, 0, 30, 3, 0, 31, 0, 0, 31, 1, 0, 31, 1, 0, 31, 29, 0 };
static const unsigned char ridged_char_009[30] = { 0, 0, 31, 0, 16, 31, 15, 31, 27, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 7, 28, 0, 1, 31, 0, 28, 23, 0 };
static const unsigned char ridged_char_010[30] = { 0, 0, 31, 31, 0, 31, 31, 31, 28, 23, 12, 0, 31, 8, 0, 31, 24, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 30, 19, 0 };
static const unsigned char ridged_char_011[30] = { 0, 0, 31, 31, 0, 31, 31, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 15, 24, 0, 3, 30, 0, 3, 30, 0 };
static const unsigned char ridged_char_012[30] = { 0, 0, 31, 19, 8, 31, 31, 31, 14, 25, 6, 0, 31, 12, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0 };
static const unsigned char ridged_char_013[30] = { 0, 0, 31, 31, 0, 31, 31, 31, 0, 31, 0, 0, 30, 1, 0, 31, 3, 0, 31, 2, 0, 30, 3, 0, 14, 27, 0, 7, 24, 0 };
static const unsigned char ridged_char_014[30] = { 0, 0, 31, 28, 2, 31, 31, 31, 0, 31, 0, 0, 11, 28, 0, 19, 30, 0, 27, 6, 0, 7, 30, 0, 3, 31, 0, 19, 31, 0 };
static const unsigned char ridged_char_015[30] = { 0, 0, 31, 0, 0, 31, 31, 31, 24, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 15, 24, 0 };
static const unsigned char ridged_char_016[30] = { 0, 0, 31, 15, 0, 31, 31, 31, 31, 30, 15, 0, 31, 1, 0, 28, 7, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 15, 24, 0 };
static const unsigned char ridged_char_017[30] = { 0, 0, 31, 7, 0, 31, 31, 31, 28, 31, 16, 0, 31, 16, 0, 31, 16, 0, 15, 16, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_018[30] = { 0, 0, 31, 4, 0, 31, 31, 31, 31, 17, 31, 0, 28, 3, 0, 30, 3, 0, 30, 1, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_019[30] = { 0, 0, 31, 15, 16, 31, 31, 31, 28, 19, 28, 0, 7, 28, 0, 7, 25, 0, 2, 31, 0, 0, 31, 0, 27, 31, 0, 27, 6, 0 };
static const unsigned char ridged_char_020[30] = { 0, 0, 31, 18, 0, 31, 31, 31, 13, 31, 12, 0, 23, 12, 0, 7, 24, 0, 31, 16, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_021[30] = { 0, 0, 31, 3, 0, 31, 31, 31, 24, 31, 0, 0, 31, 0, 0, 31, 1, 0, 30, 1, 0, 31, 0, 0, 31, 1, 0, 31, 27, 0 };
static const unsigned char ridged_char_022[30] = { 0, 0, 31, 28, 0, 31, 31, 31, 7, 27, 5, 0, 23, 12, 0, 15, 16, 0, 15, 31, 0, 25, 14, 0, 3, 30, 0, 3, 28, 0 };
static const unsigned char ridged_char_023[30] = { 0, 0, 31, 15, 16, 31, 31, 31, 16, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_024[30] = { 0, 0, 31, 0, 0, 31, 27, 31, 27, 25, 14, 0, 25, 14, 0, 25, 15, 0, 19, 13, 0, 31, 24, 0, 30, 1, 0, 30, 3, 0 };
static const unsigned char ridged_char_025[30] = { 0, 0, 31, 25, 2, 31, 31, 31, 31, 24, 7, 0, 31, 3, 0, 15, 16, 0, 31, 16, 0, 15, 24, 0, 15, 28, 0, 31, 22, 0 };
static const unsigned char ridged_char_026[30] = { 0, 0, 31, 24, 0, 31, 29, 31, 5, 28, 23, 0, 31, 29, 0, 19, 15, 0, 27, 6, 0, 29, 6, 0, 31, 6, 0, 27, 6, 0 };
static const unsigned char ridged_char_027[30] = { 0, 0, 31, 31, 0, 31, 31, 31, 0, 30, 1, 0, 28, 27, 0, 23, 14, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 28, 0 };
static const unsigned char ridged_char_028[30] = { 30, 17, 0, 31, 1, 0, 31, 0, 0, 31, 1, 0, 31, 24, 0, 31, 25, 0, 30, 1, 0, 30, 1, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_029[30] = { 14, 19, 0, 13, 19, 0, 0, 31, 0, 29, 30, 0, 28, 7, 2, 28, 15, 0, 0, 31, 0, 14, 31, 0, 31, 17, 0, 23, 31, 0 };
static const unsigned char ridged_char_030[30] = { 28, 3, 0, 29, 7, 0, 3, 30, 0, 29, 15, 0, 15, 26, 0, 15, 16, 0, 3, 28, 0, 1, 31, 0, 14, 19, 0, 28, 3, 0 };
static const unsigned char ridged_char_031[30] = { 24, 31, 0, 31, 7, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 3, 31, 0, 3, 30, 0, 7, 28, 0 };
static const unsigned char ridged_char_032[30] = { 24, 31, 0, 0, 31, 0, 31, 24, 0, 31, 0, 0, 31, 0, 0, 29, 7, 0, 30, 27, 0, 28, 7, 0, 24, 15, 0, 31, 6, 0 };
static const unsigned char ridged_char_033[30] = { 7, 28, 0, 3, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 15, 16, 0, 31, 0, 0, 31, 1, 0 };
static const unsigned char ridged_char_034[30] = { 30, 7, 0, 31, 0, 0, 31, 16, 0, 15, 24, 0, 7, 28, 0, 19, 28, 0, 29, 2, 0, 31, 14, 0, 19, 14, 0, 0, 31, 0 };
static const unsigned char ridged_char_035[30] = { 0, 31, 0, 16, 15, 0, 24, 15, 0, 30, 3, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 12, 0, 7, 30, 0 };
static const unsigned char ridged_char_036[30] = { 7, 24, 0, 7, 24, 0, 15, 24, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 3, 0 };
static const unsigned char ridged_char_037[30] = { 31, 0, 0, 31, 1, 0, 30, 3, 0, 30, 1, 0, 31, 0, 0, 7, 24, 0, 7, 28, 0, 3, 30, 0, 0, 31, 0, 28, 7, 0 };
static const unsigned char ridged_char_038[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 15, 25, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 19, 30, 0, 31, 1, 0, 14, 19, 0 };
static const unsigned char ridged_char_039[30] = { 28, 7, 0, 31, 3, 0, 31, 0, 0, 20, 31, 0, 0, 31, 0, 30, 31, 0, 30, 3, 0, 28, 7, 0, 16, 31, 8, 7, 28, 24 };
static const unsigned char ridged_char_040[30] = { 7, 31, 0, 19, 30, 0, 23, 24, 0, 15, 24, 0, 23, 24, 0, 27, 14, 0, 24, 7, 0, 24, 23, 0, 16, 31, 0, 28, 7, 0 };
static const unsigned char ridged_char_041[30] = { 31, 24, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 30, 3, 0, 30, 1, 0, 14, 25, 0, 6, 25, 0, 7, 29, 0, 6, 29, 0 };
static const unsigned char ridged_char_042[30] = { 31, 4, 0, 31, 0, 0, 30, 1, 0, 30, 31, 0, 15, 25, 0, 31, 0, 0, 31, 1, 0, 29, 3, 0, 29, 30, 0, 5, 30, 0 };
static const unsigned char ridged_char_043[30] = { 31, 0, 0, 31, 0, 0, 15, 27, 0, 0, 31, 0, 23, 28, 0, 23, 24, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_044[30] = { 29, 3, 0, 31, 12, 0, 23, 28, 0, 23, 24, 0, 31, 0, 0, 31, 0, 0, 31, 6, 0, 31, 4, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_045[30] = { 29, 3, 0, 25, 6, 0, 19, 14, 0, 27, 12, 0, 31, 4, 0, 31, 4, 0, 28, 7, 0, 31, 3, 0, 31, 1, 0, 30, 1, 0 };
static const unsigned char ridged_char_046[30] = { 24, 7, 0, 24, 7, 0, 25, 7, 0, 17, 15, 0, 25, 7, 0, 31, 13, 0, 1, 31, 0, 6, 31, 0, 4, 31, 0, 4, 31, 0 };
static const unsigned char ridged_char_047[30] = { 3, 28, 0, 27, 28, 0, 31, 0, 0, 31, 0, 0, 30, 1, 0, 31, 17, 0, 31, 16, 0, 31, 0, 0, 31, 16, 0, 15, 24, 0 };
static const unsigned char ridged_char_048[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 4, 0, 19, 28, 0, 3, 28, 0 };
static const unsigned char ridged_char_049[30] = { 31, 27, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 31, 17, 0, 23, 12, 0 };
static const unsigned char ridged_char_050[30] = { 29, 3, 0, 31, 6, 0, 27, 12, 0, 23, 12, 0, 23, 28, 0, 27, 13, 0, 25, 7, 0, 31, 18, 0, 31, 0, 0, 30, 3, 0 };
static const unsigned char ridged_char_051[30] = { 31, 14, 0, 31, 0, 0, 31, 12, 0, 27, 4, 0, 30, 3, 0, 12, 31, 0, 28, 7, 0, 30, 3, 0, 24, 7, 0, 1, 31, 0 };
static const unsigned char ridged_char_052[30] = { 31, 4, 0, 31, 4, 0, 19, 15, 0, 22, 31, 0, 3, 30, 0, 7, 28, 0, 15, 24, 0, 3, 30, 0, 1, 30, 0, 25, 7, 0 };
static const unsigned char ridged_char_053[30] = { 30, 3, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 12, 0, 19, 14, 0 };
static const unsigned char ridged_char_054[30] = { 0, 31, 0, 0, 31, 0, 29, 6, 0, 31, 3, 0, 30, 1, 0, 31, 1, 0, 31, 0, 0, 31, 2, 0, 27, 14, 0, 31, 12, 0 };
static const unsigned char ridged_char_055[30] = { 4, 31, 0, 2, 31, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0, 23, 24, 0, 7, 24, 0, 31, 24, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_056[30] = { 31, 19, 0, 13, 22, 0, 19, 30, 0, 31, 24, 0, 31, 24, 0, 28, 15, 0, 30, 1, 0, 30, 1, 0, 30, 3, 0, 31, 1, 0 };
static const unsigned char ridged_char_057[30] = { 28, 3, 0, 16, 15, 0, 27, 13, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 31, 16, 0, 31, 16, 0, 15, 24, 0 };
static const unsigned char ridged_char_058[30] = { 30, 17, 0, 31, 16, 0, 15, 24, 0, 31, 12, 0, 31, 6, 0, 30, 1, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_059[30] = { 31, 24, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 30, 1, 0, 13, 31, 0, 17, 30, 0, 29, 3, 0, 31, 1, 0, 31, 0, 0 };
static const unsigned char ridged_char_060[30] = { 30, 3, 0, 31, 1, 0, 31, 0, 0, 31, 16, 0, 15, 17, 0, 1, 31, 0, 31, 12, 0, 31, 1, 0, 30, 1, 0, 30, 3, 0 };
static const unsigned char ridged_char_061[30] = { 0, 31, 0, 14, 25, 0, 28, 7, 0, 25, 15, 0, 23, 28, 0, 31, 24, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 15, 16, 0 };
static const unsigned char ridged_char_062[30] = { 1, 30, 0, 0, 31, 0, 15, 31, 0, 31, 16, 0, 31, 0, 0, 30, 3, 0, 29, 7, 0, 31, 24, 0, 15, 24, 0, 31, 12, 0 };
static const unsigned char ridged_char_063[30] = { 31, 0, 0, 31, 24, 0, 7, 28, 0, 23, 28, 0, 15, 24, 0, 15, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_064[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 28, 7, 0 };
static const unsigned char ridged_char_065[30] = { 31, 1, 0, 31, 1, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0, 31, 14, 0, 27, 15, 0, 23, 28, 0, 15, 24, 0, 31, 0, 0 };
static const unsigned char ridged_char_066[30] = { 0, 31, 0, 3, 31, 0, 7, 28, 0, 23, 28, 0, 23, 12, 0, 16, 15, 0, 19, 31, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char ridged_char_067[30] = { 7, 24, 0, 15, 24, 0, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 15, 24, 0, 27, 4, 0, 29, 7, 0, 30, 1, 0 };
static const unsigned char ridged_char_068[30] = { 8, 31, 0, 8, 31, 0, 1, 30, 0, 29, 30, 0, 7, 24, 0, 15, 24, 0, 31, 0, 0, 31, 31, 16, 15, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_069[30] = { 16, 31, 0, 0, 31, 0, 30, 3, 0, 30, 3, 0, 31, 0, 0, 31, 8, 0, 31, 1, 0, 31, 31, 3, 25, 2, 31, 0, 0, 31 };
static const unsigned char ridged_char_070[30] = { 24, 31, 0, 0, 31, 0, 1, 31, 0, 1, 30, 0, 25, 15, 0, 25, 6, 0, 24, 31, 0, 15, 31, 31, 23, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_071[30] = { 1, 30, 0, 15, 20, 0, 30, 7, 0, 30, 1, 0, 31, 1, 0, 30, 1, 0, 24, 31, 0, 31, 31, 31, 30, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_072[30] = { 28, 3, 0, 30, 3, 0, 30, 3, 0, 8, 31, 0, 15, 31, 0, 31, 16, 0, 15, 16, 0, 15, 31, 24, 0, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_073[30] = { 31, 30, 0, 15, 16, 0, 15, 16, 0, 15, 16, 0, 31, 16, 0, 31, 0, 0, 31, 4, 0, 19, 31, 31, 2, 4, 31, 0, 0, 31 };
static const unsigned char ridged_char_074[30] = { 31, 24, 0, 31, 4, 0, 31, 7, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 23, 30, 0, 15, 31, 31, 12, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_075[30] = { 31, 0, 0, 31, 0, 0, 7, 28, 0, 19, 30, 0, 25, 15, 0, 31, 4, 0, 31, 1, 0, 31, 31, 3, 7, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_076[30] = { 31, 1, 0, 31, 1, 0, 31, 1, 0, 31, 5, 0, 16, 31, 0, 28, 7, 0, 28, 7, 0, 30, 31, 31, 16, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_077[30] = { 15, 24, 0, 0, 31, 0, 16, 31, 0, 1, 31, 0, 3, 28, 0, 31, 19, 0, 15, 25, 0, 15, 31, 24, 3, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_078[30] = { 31, 0, 0, 31, 16, 0, 15, 24, 0, 31, 24, 0, 23, 24, 0, 25, 15, 0, 12, 23, 0, 31, 31, 31, 31, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_079[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 30, 3, 0, 28, 7, 0, 21, 31, 0, 0, 31, 0, 27, 31, 27, 17, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_080[30] = { 28, 7, 0, 31, 0, 0, 31, 0, 0, 31, 24, 0, 23, 24, 0, 23, 28, 0, 7, 24, 0, 31, 31, 24, 31, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_081[30] = { 15, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 0, 31, 31, 3, 25, 4, 31, 0, 0, 31 };
static const unsigned char ridged_char_082[30] = { 31, 4, 0, 31, 4, 0, 31, 3, 0, 31, 1, 0, 31, 1, 0, 30, 1, 0, 29, 31, 0, 31, 31, 0, 31, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_083[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 15, 16, 0, 15, 16, 0, 0, 31, 0, 7, 29, 0, 31, 31, 15, 24, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_084[30] = { 28, 7, 0, 31, 1, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 0, 15, 24, 0, 15, 31, 24, 15, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_085[30] = { 31, 0, 0, 31, 16, 0, 31, 8, 0, 31, 6, 0, 31, 3, 0, 30, 3, 0, 28, 3, 0, 31, 31, 7, 25, 0, 31, 0, 0, 31 };
static const unsigned char ridged_char_086[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 31, 16, 3, 16, 31, 0, 0, 31 };
static const unsigned char ridged_char_087[30] = { 31, 0, 0, 31, 1, 0, 28, 3, 0, 30, 1, 0, 31, 1, 0, 31, 0, 0, 28, 3, 0, 29, 31, 5, 28, 0, 31, 0, 0, 31 };

const unsigned char * const ridged_charset[88] = {
    ridged_char_000,
    ridged_char_001,
    ridged_char_002,
    ridged_char_003,
    ridged_char_004,
    ridged_char_005,
    ridged_char_006,
    ridged_char_007,
    ridged_char_008,
    ridged_char_009,
    ridged_char_010,
    ridged_char_011,
    ridged_char_012,
    ridged_char_013,
    ridged_char_014,
    ridged_char_015,
    ridged_char_016,
    ridged_char_017,
    ridged_char_018,
    ridged_char_019,
    ridged_char_020,
    ridged_char_021,
    ridged_char_022,
    ridged_char_023,
    ridged_char_024,
    ridged_char_025,
    ridged_char_026,
    ridged_char_027,
    ridged_char_028,
    ridged_char_029,
    ridged_char_030,
    ridged_char_031,
    ridged_char_032,
    ridged_char_033,
    ridged_char_034,
    ridged_char_035,
    ridged_char_036,
    ridged_char_037,
    ridged_char_038,
    ridged_char_039,
    ridged_char_040,
    ridged_char_041,
    ridged_char_042,
    ridged_char_043,
    ridged_char_044,
    ridged_char_045,
    ridged_char_046,
    ridged_char_047,
    ridged_char_048,
    ridged_char_049,
    ridged_char_050,
    ridged_char_051,
    ridged_char_052,
    ridged_char_053,
    ridged_char_054,
    ridged_char_055,
    ridged_char_056,
    ridged_char_057,
    ridged_char_058,
    ridged_char_059,
    ridged_char_060,
    ridged_char_061,
    ridged_char_062,
    ridged_char_063,
    ridged_char_064,
    ridged_char_065,
    ridged_char_066,
    ridged_char_067,
    ridged_char_068,
    ridged_char_069,
    ridged_char_070,
    ridged_char_071,
    ridged_char_072,
    ridged_char_073,
    ridged_char_074,
    ridged_char_075,
    ridged_char_076,
    ridged_char_077,
    ridged_char_078,
    ridged_char_079,
    ridged_char_080,
    ridged_char_081,
    ridged_char_082,
    ridged_char_083,
    ridged_char_084,
    ridged_char_085,
    ridged_char_086,
    ridged_char_087,
};

const unsigned char ridged_map[122] = {
    30, 4,
    8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
    28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
    48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
    68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
};

