/* Auto-generated by img2tiles.py from "sun.jpg" */
#pragma once

#define SUN_CHARSET_SIZE 256
#define SUN_MAP_SIZE     882

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char sun_ntsc_palette[3];

/* Charset: 256 characters, each 30 bytes */
extern const unsigned char * const sun_charset[256];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char sun_map[882];


