/* Auto-generated by spinningGlobe/cset.py from "terra.png" */
#pragma once

#define TERRA_CHARSET_SIZE 72
#define TERRA_MAP_SIZE     122
#define TERRA_CHAR_WIDTH   5
#define TERRA_CHAR_HEIGHT  10
#define TERRA_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char terra_ntsc_palette[3];

/* Charset: 72 characters, each 30 bytes */
extern const unsigned char * const terra_charset[72];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char terra_map[122];


