/* Auto-generated by spinningGlobe/cset.py from "titan.png" */
#pragma once

#define TITAN_CHARSET_SIZE 80
#define TITAN_MAP_SIZE     122
#define TITAN_CHAR_WIDTH   5
#define TITAN_CHAR_HEIGHT  10
#define TITAN_CHAR_BYTES   30

/* NTSC TIA register values for primaries [1], [2], [4] */
extern const unsigned char titan_ntsc_palette[3];

/* Charset: 80 characters, each 30 bytes */
extern const unsigned char * const titan_charset[80];

/* Map: byte[0]=width, byte[1]=height, then row-major char indices */
extern const unsigned char titan_map[122];


