/* Auto-generated by img2tiles.py from "titan.png" */
/* Adaptive palette: 8 colours built from 3 EM-optimised primaries (NTSC-snapped). */
/* Index bits: bit0=P1, bit1=P2, bit2=P3 (P1/P2/P3 = single-bit primaries). */
/* Character: 5 pixels wide x 10 trixels deep (30 scanlines). */
/* Trixel: 1 pixel wide x 3 scanlines deep, 3-bit palette index. */
/* Character storage: 10 trixel-rows x 3 bytes (bit0-plane, bit1-plane, bit2-plane) = 30 bytes. */
/* Byte bit layout: bit4=col0(left) .. bit0=col4(right), bits7-5 unused. */
/* Map: byte0=width(chars, +10 wrap buffer), byte1=height(chars), then row-major indices. */

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-const-variable"
static const unsigned char titan_palette[8][3] = {
    {   0,   0,   0 },  /* 0: origin */
    { 100,  72,  24 },  /* 1: +P1 */
    { 100, 100,  16 },  /* 2: +P2 */
    { 100,  86,  20 },  /* 3: +P1+P2 */
    { 132, 104,  48 },  /* 4: +P3 */
    { 116,  88,  36 },  /* 5: +P1+P3 */
    { 116, 102,  32 },  /* 6: +P2+P3 */
    { 111,  92,  29 },  /* 7: +P1+P2+P3 */
};
#pragma GCC diagnostic pop

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-const-variable"
/* NTSC Atari 2600 companion palette: nearest TIA register values for
 * palette primaries (indices 1, 2, 4 — the single-bit entries). */
const unsigned char titan_ntsc_palette[3] = {
    0xF2,  /* palette[1] = (100,72,24) */
    0x12,  /* palette[2] = (100,100,16) */
    0xF4,  /* palette[4] = (132,104,48) */
};
#pragma GCC diagnostic pop

static const unsigned char titan_char_000[30] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static const unsigned char titan_char_001[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_002[30] = { 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0 };
static const unsigned char titan_char_003[30] = { 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0 };
static const unsigned char titan_char_004[30] = { 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31 };
static const unsigned char titan_char_005[30] = { 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31 };
static const unsigned char titan_char_006[30] = { 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31 };
static const unsigned char titan_char_007[30] = { 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31 };
static const unsigned char titan_char_008[30] = { 31, 0, 13, 31, 0, 7, 31, 8, 15, 31, 0, 7, 28, 0, 7, 28, 4, 7, 28, 6, 7, 29, 0, 3, 30, 0, 3, 31, 0, 0 };
static const unsigned char titan_char_009[30] = { 31, 0, 24, 31, 0, 27, 31, 0, 31, 31, 0, 31, 15, 0, 31, 15, 0, 31, 31, 0, 31, 19, 0, 31, 21, 0, 31, 31, 2, 1 };
static const unsigned char titan_char_010[30] = { 31, 0, 16, 31, 0, 30, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 7, 31, 0, 27, 7, 0, 30 };
static const unsigned char titan_char_011[30] = { 31, 0, 1, 31, 0, 7, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31 };
static const unsigned char titan_char_012[30] = { 4, 2, 31, 30, 4, 31, 23, 7, 31, 31, 1, 31, 29, 0, 31, 30, 0, 31, 23, 0, 31, 17, 0, 31, 28, 0, 31, 30, 0, 31 };
static const unsigned char titan_char_013[30] = { 0, 0, 31, 0, 0, 31, 16, 1, 31, 31, 31, 31, 29, 16, 31, 16, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 7, 6, 31 };
static const unsigned char titan_char_014[30] = { 0, 0, 31, 4, 10, 31, 12, 4, 31, 28, 28, 31, 28, 30, 31, 28, 28, 31, 28, 30, 31, 28, 28, 31, 24, 8, 31, 16, 0, 31 };
static const unsigned char titan_char_015[30] = { 13, 0, 31, 9, 0, 31, 28, 0, 31, 29, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 27, 2, 28, 7, 0, 28, 15, 0, 24 };
static const unsigned char titan_char_016[30] = { 3, 0, 31, 29, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 31, 0, 31, 19, 0, 31, 28, 0, 7, 30, 4, 3, 31, 7, 3 };
static const unsigned char titan_char_017[30] = { 30, 0, 17, 31, 0, 16, 31, 0, 0, 31, 0, 0, 31, 0, 16, 31, 0, 24, 31, 0, 31, 30, 0, 31, 3, 0, 31, 31, 30, 30 };
static const unsigned char titan_char_018[30] = { 15, 0, 25, 31, 0, 3, 31, 0, 2, 29, 0, 6, 29, 0, 6, 31, 0, 30, 19, 6, 30, 15, 5, 29, 30, 28, 31, 31, 0, 15 };
static const unsigned char titan_char_019[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 12, 0, 31, 20, 28, 7, 0, 31, 25, 0, 31 };
static const unsigned char titan_char_020[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 24, 27, 1, 31 };
static const unsigned char titan_char_021[30] = { 31, 0, 24, 31, 0, 15, 31, 0, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_022[30] = { 31, 0, 0, 31, 0, 28, 19, 0, 31, 28, 8, 15, 31, 2, 3, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_023[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 28, 7, 0, 31, 31, 16, 22, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_024[30] = { 31, 1, 3, 31, 0, 6, 27, 0, 28, 23, 4, 28, 31, 24, 24, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_025[30] = { 31, 0, 0, 31, 7, 7, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_026[30] = { 31, 6, 6, 27, 17, 31, 16, 16, 15, 24, 0, 15, 24, 0, 15, 24, 0, 15, 31, 6, 7, 31, 1, 1, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_027[30] = { 27, 24, 31, 25, 0, 31, 0, 0, 31, 0, 0, 31, 2, 0, 31, 0, 0, 31, 0, 0, 31, 31, 2, 31, 31, 16, 16, 31, 0, 0 };
static const unsigned char titan_char_028[30] = { 31, 0, 31, 25, 0, 31, 0, 0, 31, 6, 0, 31, 7, 0, 31, 7, 0, 31, 7, 0, 31, 0, 0, 31, 28, 4, 7, 31, 2, 3 };
static const unsigned char titan_char_029[30] = { 24, 0, 31, 24, 0, 31, 24, 0, 31, 28, 0, 31, 28, 0, 31, 24, 0, 31, 0, 0, 31, 15, 0, 31, 15, 0, 24, 7, 24, 24 };
static const unsigned char titan_char_030[30] = { 6, 0, 27, 12, 0, 27, 15, 7, 31, 28, 11, 31, 3, 1, 31, 3, 0, 30, 3, 6, 30, 31, 0, 24, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_031[30] = { 0, 4, 31, 15, 4, 31, 31, 28, 28, 3, 28, 31, 30, 20, 31, 31, 1, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_032[30] = { 7, 0, 24, 31, 8, 24, 31, 8, 8, 31, 12, 28, 15, 24, 24, 31, 16, 16, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_033[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 1, 1, 30, 3, 1, 28, 2, 3, 28, 4, 7, 30, 4, 3 };
static const unsigned char titan_char_034[30] = { 15, 0, 31, 23, 0, 31, 29, 16, 31, 20, 30, 31, 20, 19, 31, 1, 2, 31, 6, 0, 31, 7, 0, 31, 7, 0, 31, 7, 0, 31 };
static const unsigned char titan_char_035[30] = { 31, 0, 31, 31, 0, 3, 31, 0, 31, 2, 0, 31, 31, 7, 31, 31, 7, 30, 7, 7, 31, 19, 3, 31, 25, 1, 31, 29, 0, 31 };
static const unsigned char titan_char_036[30] = { 31, 0, 31, 31, 0, 31, 31, 0, 31, 15, 0, 31, 19, 0, 31, 24, 8, 15, 29, 16, 7, 31, 22, 19, 29, 16, 31, 23, 0, 31 };
static const unsigned char titan_char_037[30] = { 19, 1, 30, 28, 0, 31, 31, 0, 25, 31, 0, 30, 23, 0, 31, 24, 0, 31, 30, 0, 31, 7, 0, 31, 31, 0, 31, 31, 0, 24 };
static const unsigned char titan_char_038[30] = { 31, 1, 0, 30, 8, 27, 16, 0, 31, 17, 0, 31, 19, 0, 31, 7, 0, 30, 27, 0, 30, 31, 0, 31, 31, 0, 30, 31, 0, 31 };
static const unsigned char titan_char_039[30] = { 31, 18, 30, 1, 1, 31, 24, 0, 31, 22, 0, 31, 31, 3, 25, 31, 0, 12, 27, 0, 15, 31, 0, 7, 31, 0, 1, 31, 0, 1 };
static const unsigned char titan_char_040[30] = { 31, 0, 0, 31, 16, 16, 9, 0, 31, 30, 0, 31, 23, 0, 31, 23, 0, 31, 18, 0, 31, 31, 1, 25, 31, 0, 16, 31, 0, 1 };
static const unsigned char titan_char_041[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 16, 7, 0, 24, 19, 0, 30, 25, 0, 31, 15, 0, 30, 15, 0, 30, 31, 0, 28 };
static const unsigned char titan_char_042[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 31, 6, 3, 28, 4, 7, 29, 4, 7, 27, 0, 14 };
static const unsigned char titan_char_043[30] = { 31, 0, 0, 31, 0, 0, 31, 16, 31, 19, 0, 31, 23, 0, 31, 15, 0, 25, 31, 0, 21, 31, 0, 16, 31, 0, 16, 31, 0, 0 };
static const unsigned char titan_char_044[30] = { 31, 0, 0, 31, 0, 0, 31, 16, 16, 7, 0, 24, 23, 4, 28, 23, 0, 24, 31, 4, 28, 23, 2, 31, 17, 3, 31, 27, 2, 14 };
static const unsigned char titan_char_045[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 16, 16, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_046[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 28, 2, 3, 28, 1, 7 };
static const unsigned char titan_char_047[30] = { 31, 0, 0, 31, 0, 0, 31, 2, 0, 28, 8, 15, 24, 0, 15, 23, 0, 31, 7, 0, 31, 12, 0, 31, 1, 0, 31, 1, 4, 31 };
static const unsigned char titan_char_048[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 7, 31, 0, 0, 31, 24, 0, 31, 27, 0, 31, 28, 0, 31, 28, 0, 31, 24, 0, 31 };
static const unsigned char titan_char_049[30] = { 31, 0, 0, 31, 0, 0, 31, 2, 3, 28, 20, 23, 7, 0, 31, 15, 0, 28, 15, 0, 28, 7, 0, 28, 31, 0, 28, 31, 0, 16 };
static const unsigned char titan_char_050[30] = { 31, 0, 0, 31, 0, 0, 31, 5, 29, 3, 0, 31, 31, 0, 30, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_051[30] = { 24, 24, 31, 24, 24, 31, 17, 0, 31, 15, 0, 31, 31, 0, 28, 31, 0, 1, 31, 0, 1, 31, 0, 1, 31, 0, 8, 23, 0, 12 };
static const unsigned char titan_char_052[30] = { 31, 0, 31, 31, 0, 31, 24, 0, 31, 16, 0, 31, 27, 2, 31, 19, 3, 31, 23, 0, 28, 23, 0, 28, 27, 0, 28, 31, 0, 28 };
static const unsigned char titan_char_053[30] = { 31, 0, 31, 31, 0, 31, 31, 0, 31, 15, 0, 28, 15, 0, 30, 23, 16, 30, 31, 0, 12, 31, 0, 12, 31, 0, 4, 31, 0, 3 };
static const unsigned char titan_char_054[30] = { 31, 0, 28, 31, 0, 24, 31, 0, 0, 31, 0, 0, 31, 0, 0, 27, 0, 15, 23, 0, 15, 30, 0, 15, 31, 0, 7, 31, 0, 0 };
static const unsigned char titan_char_055[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 30, 0, 19, 28, 0, 31, 8, 0, 31, 19, 0, 28, 31, 0, 1 };
static const unsigned char titan_char_056[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 15, 24, 0, 31, 16, 0, 31, 3, 0, 31, 15, 0, 16, 31, 0, 7, 16, 0, 31, 31, 12, 29 };
static const unsigned char titan_char_057[30] = { 31, 0, 25, 31, 0, 1, 31, 0, 17, 3, 0, 28, 3, 0, 28, 31, 0, 24, 31, 0, 7, 14, 0, 31, 15, 6, 28, 15, 0, 30 };
static const unsigned char titan_char_058[30] = { 31, 0, 1, 31, 0, 0, 31, 0, 16, 15, 0, 16, 23, 0, 28, 24, 0, 31, 31, 1, 31, 7, 4, 28, 31, 8, 8, 31, 0, 0 };
static const unsigned char titan_char_059[30] = { 23, 4, 28, 7, 0, 24, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 16, 31, 16, 16, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_060[30] = { 31, 0, 30, 31, 0, 28, 31, 0, 0, 31, 0, 0, 31, 0, 8, 31, 0, 16, 31, 0, 24, 31, 0, 24, 15, 0, 30, 31, 0, 30 };
static const unsigned char titan_char_061[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 3, 31, 0, 31, 31, 0, 31, 31, 0, 15, 31, 0, 29 };
static const unsigned char titan_char_062[30] = { 31, 0, 6, 29, 1, 7, 30, 0, 3, 31, 0, 3, 30, 0, 15, 27, 3, 30, 27, 1, 30, 27, 1, 31, 1, 2, 30, 3, 2, 30 };
static const unsigned char titan_char_063[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 16, 15, 4, 24, 7, 0, 28, 31, 16, 28, 31, 30, 10, 25, 8, 15, 24, 0, 7, 24, 0, 7 };
static const unsigned char titan_char_064[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 17, 1, 12, 8, 31, 0, 0, 31 };
static const unsigned char titan_char_065[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 2, 3, 28, 4, 7, 30, 2, 3, 30, 4, 7, 17, 0, 31, 3, 0, 31, 1, 0, 31 };
static const unsigned char titan_char_066[30] = { 16, 9, 15, 16, 1, 31, 1, 1, 31, 3, 2, 30, 31, 0, 31, 31, 0, 28, 15, 0, 28, 31, 0, 25, 31, 0, 19, 31, 0, 22 };
static const unsigned char titan_char_067[30] = { 1, 24, 31, 27, 16, 31, 31, 0, 15, 31, 0, 31, 31, 0, 16, 31, 0, 0, 31, 0, 4, 23, 0, 24, 23, 0, 24, 15, 0, 24 };
static const unsigned char titan_char_068[30] = { 17, 0, 31, 23, 0, 31, 7, 0, 31, 31, 0, 31, 31, 0, 15, 31, 0, 3, 31, 0, 1, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_069[30] = { 31, 0, 16, 31, 0, 16, 31, 0, 16, 31, 0, 24, 31, 0, 31, 19, 0, 31, 31, 0, 31, 31, 0, 1, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_070[30] = { 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 31, 25, 0, 31, 12, 2, 31, 26, 28, 31, 23, 0, 28, 31, 0, 12, 31, 0, 6 };
static const unsigned char titan_char_071[30] = { 31, 0, 1, 31, 0, 1, 31, 0, 31, 27, 0, 31, 31, 0, 28, 31, 16, 16, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_072[30] = { 23, 0, 28, 22, 2, 31, 23, 0, 25, 31, 8, 24, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_073[30] = { 31, 0, 1, 31, 16, 16, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_074[30] = { 31, 0, 30, 27, 0, 15, 29, 0, 7, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_075[30] = { 29, 0, 15, 1, 0, 31, 31, 8, 24, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_076[30] = { 31, 12, 13, 31, 25, 25, 31, 0, 0, 31, 0, 0, 31, 0, 0, 31, 0, 1, 30, 0, 1, 31, 16, 19, 27, 24, 30, 31, 0, 14 };
static const unsigned char titan_char_077[30] = { 12, 0, 31, 31, 0, 31, 23, 0, 31, 31, 0, 31, 15, 0, 24, 31, 0, 19, 31, 0, 18, 31, 0, 0, 31, 0, 0, 31, 0, 0 };
static const unsigned char titan_char_078[30] = { 31, 30, 30, 27, 1, 31, 28, 0, 31, 31, 0, 31, 31, 0, 15, 31, 0, 31, 31, 0, 0, 31, 0, 1, 31, 0, 1, 31, 0, 1 };
static const unsigned char titan_char_079[30] = { 30, 2, 3, 28, 0, 7, 25, 0, 31, 31, 0, 30, 31, 0, 31, 31, 0, 7, 31, 0, 7, 30, 0, 31, 30, 0, 31, 31, 0, 31 };

const unsigned char * const titan_charset[80] = {
    titan_char_000,
    titan_char_001,
    titan_char_002,
    titan_char_003,
    titan_char_004,
    titan_char_005,
    titan_char_006,
    titan_char_007,
    titan_char_008,
    titan_char_009,
    titan_char_010,
    titan_char_011,
    titan_char_012,
    titan_char_013,
    titan_char_014,
    titan_char_015,
    titan_char_016,
    titan_char_017,
    titan_char_018,
    titan_char_019,
    titan_char_020,
    titan_char_021,
    titan_char_022,
    titan_char_023,
    titan_char_024,
    titan_char_025,
    titan_char_026,
    titan_char_027,
    titan_char_028,
    titan_char_029,
    titan_char_030,
    titan_char_031,
    titan_char_032,
    titan_char_033,
    titan_char_034,
    titan_char_035,
    titan_char_036,
    titan_char_037,
    titan_char_038,
    titan_char_039,
    titan_char_040,
    titan_char_041,
    titan_char_042,
    titan_char_043,
    titan_char_044,
    titan_char_045,
    titan_char_046,
    titan_char_047,
    titan_char_048,
    titan_char_049,
    titan_char_050,
    titan_char_051,
    titan_char_052,
    titan_char_053,
    titan_char_054,
    titan_char_055,
    titan_char_056,
    titan_char_057,
    titan_char_058,
    titan_char_059,
    titan_char_060,
    titan_char_061,
    titan_char_062,
    titan_char_063,
    titan_char_064,
    titan_char_065,
    titan_char_066,
    titan_char_067,
    titan_char_068,
    titan_char_069,
    titan_char_070,
    titan_char_071,
    titan_char_072,
    titan_char_073,
    titan_char_074,
    titan_char_075,
    titan_char_076,
    titan_char_077,
    titan_char_078,
    titan_char_079,
};

const unsigned char titan_map[122] = {
    30, 4,
    1, 1, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 1, 21, 22, 23, 24, 1, 1, 8, 9, 10, 11, 12, 13, 14, 15,
    1, 1, 25, 26, 27, 28, 29, 30, 31, 32, 1, 33, 34, 35, 36, 37, 38, 39, 40, 41, 1, 1, 25, 26, 27, 28, 29, 30, 31, 32,
    42, 43, 44, 45, 1, 1, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 42, 43, 44, 45, 1, 1, 46, 47, 48, 49,
    60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
};

