#!/usr/bin/env python3

"""
cset.py - Convert image files to C character set source/header files.

Usage:
    python3 cset.py --width W --depth D image1.png [image2.jpg ...]

    --width  W   Character cell width in pixels (1-8; packed into one byte per row)
    --depth  D   Character cell height in pixels (one byte per row, D rows per char)

Images may be JPG GIF PNG 

The image is divided into WxD pixel cells, left-to-right then top-to-bottom.
Each cell becomes D bytes. Within each byte, the leftmost pixel is the MSB (bit 7).
If W < 8 the remaining low bits in each byte are 0.

Output per input file:
    <basename>.c   - character table
    <basename>.h   - #defines for each character index + extern declaration
"""

import argparse
import os
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Pillow is required: pip install Pillow", file=sys.stderr)
    sys.exit(1)


def make_c_identifier(name: str) -> str:
    """Convert an arbitrary string to a valid C identifier."""
    result = []
    for ch in name:
        result.append(ch if (ch.isalnum() or ch == "_") else "_")
    if result and result[0].isdigit():
        result.insert(0, "_")
    return "".join(result)


def image_to_charset(image_path: Path, char_width: int, char_depth: int):
    """
    Load image and split into characters.

    Returns:
        chars      - list of characters; each character is a list of `char_depth`
                     ints (one byte per row, MSB = leftmost pixel, unused low bits = 0)
        num_chars  - total number of characters
        cols       - number of character columns
        rows       - number of character rows
    """
    img = Image.open(image_path).convert("1")  # 1-bit: pixel is 0 or 255
    img_w, img_h = img.size

    if img_w % char_width != 0:
        print(
            f"  Warning: image width {img_w}px is not a multiple of char width "
            f"{char_width}px — trailing pixels ignored.",
            file=sys.stderr,
        )
    if img_h % char_depth != 0:
        print(
            f"  Warning: image height {img_h}px is not a multiple of char depth "
            f"{char_depth}px — trailing rows ignored.",
            file=sys.stderr,
        )

    cols = img_w // char_width
    rows = img_h // char_depth

    if cols == 0 or rows == 0:
        raise ValueError(
            f"Image {img_w}x{img_h} is too small for a {char_width}x{char_depth} character cell."
        )

    pixels = img.load()
    chars = []

    for row in range(rows):
        for col in range(cols):
            char_bytes = []
            for dy in range(char_depth):
                byte = 0
                for dx in range(char_width):
                    px = col * char_width + dx
                    py = row * char_depth + dy
                    # PIL mode "1" returns 0 or 255
                    bit = 1 if pixels[px, py] else 0
                    # MSB = leftmost pixel; dx=0 → bit 7, dx=1 → bit 6, etc.
                    bit_pos = 7 - dx
                    byte |= bit << bit_pos
                char_bytes.append(byte)
            chars.append(char_bytes)

    return chars, len(chars), cols, rows


def write_c_file(c_path: Path, h_stem: str, prefix: str, chars, char_depth: int):
    table_name = f"{prefix}_charset"
    lines = [
        "/* Auto-generated by img2charset.py - do not edit */",
        f'#include "{h_stem}.h"',
        "",
        f"/* {len(chars)} characters, {char_depth} byte(s) per character */",
        f"const unsigned char {table_name}[{len(chars)}][{char_depth}] = {{",
    ]

    for i, char_bytes in enumerate(chars):
        hex_vals = ", ".join(f"0x{b:02X}" for b in char_bytes)
        comma = "," if i < len(chars) - 1 else " "
        lines.append(f"    {{ {hex_vals} }}{comma} /* {prefix}_{i} */")

    lines += ["};", ""]
    c_path.write_text("\n".join(lines))


def write_h_file(h_path: Path, prefix: str, num_chars: int, char_width: int, char_depth: int):
    table_name = f"{prefix}_charset"
    guard = f"{prefix.upper()}_H"

    lines = [
        "/* Auto-generated by img2charset.py - do not edit */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "/* Character cell dimensions */",
        f"#define {prefix.upper()}_CHAR_WIDTH   {char_width}",
        f"#define {prefix.upper()}_CHAR_DEPTH   {char_depth}",
        f"#define {prefix.upper()}_NUM_CHARS    {num_chars}",
        "",
        "/* Per-character index equates */",
    ]

    for i in range(num_chars):
        lines.append(f"#define {prefix}_{i}  {i}")

    lines += [
        "",
        "/* Table declaration */",
        f"extern const unsigned char {table_name}[{num_chars}][{char_depth}];",
        "",
        f"#endif /* {guard} */",
        "",
    ]
    h_path.write_text("\n".join(lines))


def process_file(image_path: Path, char_width: int, char_depth: int, output_dir: Path):
    stem = image_path.stem
    prefix = make_c_identifier(stem)

    print(f"Processing: {image_path}")

    chars, num_chars, cols, rows = image_to_charset(image_path, char_width, char_depth)
    print(f"  Grid: {cols} cols x {rows} rows = {num_chars} characters "
          f"({char_width}px wide x {char_depth}px deep, {char_depth} byte(s) each)")

    c_path = output_dir / f"{stem}.c"
    h_path = output_dir / f"{stem}.h"

    write_c_file(c_path, stem, prefix, chars, char_depth)
    write_h_file(h_path, prefix, num_chars, char_width, char_depth)

    print(f"  Wrote: {c_path.name}, {h_path.name}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert image files to C character set source/header files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--width", type=int, required=True,
        help="Character cell width in pixels (1-8).",
    )
    parser.add_argument(
        "--depth", type=int, required=True,
        help="Character cell height in pixels (one byte per row).",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=Path("."),
        help="Directory for output files (default: current directory).",
    )
    parser.add_argument(
        "images", nargs="+", type=Path,
        help="One or more image files to convert.",
    )

    args = parser.parse_args()

    if not (1 <= args.width <= 8):
        parser.error("--width must be between 1 and 8 (packed into one byte per row).")
    if args.depth < 1:
        parser.error("--depth must be >= 1.")

    args.output_dir.mkdir(parents=True, exist_ok=True)

    errors = 0
    for image_path in args.images:
        if not image_path.exists():
            print(f"Error: not found: {image_path}", file=sys.stderr)
            errors += 1
            continue
        try:
            process_file(image_path, args.width, args.depth, args.output_dir)
        except Exception as exc:
            print(f"Error processing {image_path}: {exc}", file=sys.stderr)
            errors += 1

    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()