#ifndef DONALD_H
#define DONALD_H

#include <stdint.h>

/* 3-frame vertically-blended scanline data.
 * Generated by atari_scanline_blend.py -- do not hand-edit.
 *
 * Screen is SCREEN_WIDTH x SCREEN_HEIGHT (48x128). Each ScanLine
 * holds one Atari colour byte (COLUP0/COLUP1/COLUBK register format:
 * bits 7-4 = hue, bits 3-1 = luminance, bit 0 = 0) and a SCREEN_WIDTH-bit
 * on/off bitmap (packed MSB-first, column 0 = bit 7 of bits[0]).
 *
 * ScanLine is defined once and shared verbatim across every file this
 * tool generates. The 3 individual frame arrays are file-local
 * (static) -- the only thing this translation unit exports is
 * donald_screen_frames, a table of 3 pointers in cycle order. Index it
 * by a running frame counter (mod SCREEN_NUM_FRAMES) exactly as usual --
 * the display-side code does not change at all versus the unrolled
 * scheme.
 *
 * IMPORTANT: --roll-scanlines was used (band height 24), so
 * these 3 arrays are NOT the raw per-frame solves -- they are
 * already-rolled composites. Array k's row y holds original solved frame
 * (k + y // 24) %% 3's row y data: every
 * 24-row BAND of the screen is staggered to a different
 * original frame, instead of the whole screen flipping between frames in
 * lockstep. Over one full 3-frame cycle every row still visits
 * all 3 original frames' data once each (same 1/3-weighted
 * temporal average as always -- this is a pure reordering, not a
 * re-solve), so the perceived static image is unchanged; what's
 * different is that frame-to-frame change is spread across bands instead
 * of hitting the whole screen at the same instant. Rows within a band's
 * interior have a fully self-consistent vertical-blend neighbourhood
 * (matching what the solver assumed); rows near a band boundary
 * straddle two original frames' data and will show a locally-wrong
 * blend there -- that's an unavoidable, quantified cost of this
 * technique, not a bug (an EARLIER version of this tool rolled at
 * 1-row granularity, which put ~100%% of rows in that "wrong blend"
 * state -- visibly broken colours, found and fixed). See
 * roll_scanlines() in atari_scanline_blend.py for the full history and
 * roll_seam_row_count() to quantify the boundary cost for your own
 * --height/--radius/--roll-band-height combination.
 */

#define SCREEN_NUM_FRAMES 3

#ifndef ATARI_SCANLINE_TYPE_H
#define ATARI_SCANLINE_TYPE_H

#define SCREEN_WIDTH  48
#define SCREEN_HEIGHT 128
#define SCREEN_BYTES_PER_ROW 6

typedef struct {
    uint8_t colour;
    uint8_t bits[SCREEN_BYTES_PER_ROW];
} ScanLine;

#endif /* ATARI_SCANLINE_TYPE_H */

/* e.g. donald_screen_frames[frame_counter % SCREEN_NUM_FRAMES] */
extern const ScanLine * const donald_screen_frames[SCREEN_NUM_FRAMES];

#endif /* DONALD_H */
