#ifndef LENA_SCANLINE_H
#define LENA_SCANLINE_H

#include <stdint.h>

/* 3-frame vertically-blended scanline data.
 * Generated by atari_scanline_blend.py -- do not hand-edit.
 *
 * Screen is SCREEN_WIDTH x SCREEN_HEIGHT (48x128). Each ScanLine
 * holds one Atari colour byte (COLUP0/COLUP1/COLUBK register format:
 * bits 7-4 = hue, bits 3-1 = luminance, bit 0 = 0) and a SCREEN_WIDTH-bit
 * on/off bitmap (packed MSB-first, column 0 = bit 7 of bits[0]).
 *
 * 3 full screens are supplied (screen_frame0, screen_frame1, screen_frame2). Cycle through them
 * one per video frame, in order, then wrap back to frame 0 and repeat
 * forever (frame0, frame1, frame2, frame0, ...).
 * Only frame0 was solved to look reasonable on its own; every later frame
 * was solved to correct whatever residual error the frames before it left
 * behind, so that the 1/3-weighted temporal average the eye
 * perceives from the full cycle (combined with the usual vertical
 * scanline blending within each individual frame) lands closer to the
 * source image than fewer frames could manage. Do not display any frame
 * after frame0 on its own expecting it to look like the picture -- it
 * won't; each is a correction term, not a picture in its own right.
 */

#define SCREEN_WIDTH  48
#define SCREEN_HEIGHT 128
#define SCREEN_BYTES_PER_ROW 6
#define SCREEN_NUM_FRAMES 3

typedef struct {
    uint8_t colour;
    uint8_t bits[SCREEN_BYTES_PER_ROW];
} ScanLine;

extern const ScanLine screen_frame0[SCREEN_HEIGHT];
extern const ScanLine screen_frame1[SCREEN_HEIGHT];
extern const ScanLine screen_frame2[SCREEN_HEIGHT];

#endif /* LENA_SCANLINE_H */
