#ifndef SKULL_H
#define SKULL_H

#include <stdint.h>

/* 3-frame vertically-blended scanline data.
 * Generated by atari_scanline_blend.py -- do not hand-edit.
 *
 * Screen is SCREEN_WIDTH x SCREEN_HEIGHT (48x128). Each ScanLine
 * holds one Atari colour byte (COLUP0/COLUP1/COLUBK register format:
 * bits 7-4 = hue, bits 3-1 = luminance, bit 0 = 0) and a SCREEN_WIDTH-bit
 * on/off bitmap (packed MSB-first, column 0 = bit 7 of bits[0]).
 *
 * ScanLine is defined once and shared verbatim across every file this
 * tool generates. The 3 individual frame arrays are file-local
 * (static) -- the only thing this translation unit exports is
 * skull_screen_frames, a table of 3 pointers in cycle order. Index it
 * by a running frame counter (mod SKULL_NUM_FRAMES): cycle frame 0, 1,
 * ..., 2, back to 0, forever. Only frame0 was solved to look
 * reasonable on its own; every later frame was solved to correct whatever
 * residual error the frames before it left behind, so that the
 * 1/3-weighted temporal average the eye perceives from the full
 * cycle (combined with the usual vertical scanline blending within each
 * individual frame) lands closer to the source image than fewer frames
 * could manage. Do not display any frame after frame0 on its own
 * expecting it to look like the picture -- it won't; each is a
 * correction term, not a picture in its own right.
 */

#define SKULL_NUM_FRAMES 3

#ifndef ATARI_SCANLINE_TYPE_H
#define ATARI_SCANLINE_TYPE_H

#define SCREEN_WIDTH  48
#define SCREEN_HEIGHT 128
#define SCREEN_BYTES_PER_ROW 6

typedef struct {
    uint8_t colour;
    uint8_t bits[SCREEN_BYTES_PER_ROW];
} ScanLine;

#endif /* ATARI_SCANLINE_TYPE_H */

#define SKULL_PARAMS "image=skull.png width=48 height=128 sigma=1.0 radius=3 rounds=10 sweeps=3 metric=luma seeds=4 smoothness=0.5 swaps=False saturation=1.0 brightness=1.0 frames=3 temporal_weight=0.0 frame_scheme=cumulative frame_mode=cyclic outer_rounds=10 line_exhaustive_k=None line_exhaustive_dither=None line_exhaustive_max_luma_spread=None line_exhaustive_flicker_weight=None line_exhaustive_spatial_dither=None roll_scanlines=False roll_band_height=None"

/* e.g. skull_screen_frames[frame_counter % SKULL_NUM_FRAMES] */
extern const ScanLine * const skull_screen_frames[SKULL_NUM_FRAMES];

#endif /* SKULL_H */
