#ifndef TEST_H
#define TEST_H

#include <stdint.h>

/* Optimal-colour "phased chronocolour" trixel data.
 * Generated by atari_chronocolour.py -- do not hand-edit.
 *
 * Screen is TRIXEL_WIDTH pixels wide, TRIXEL_ROWS trixel-lines deep
 * (TRIXEL_ROWS * 3 == 198 physical scanlines).
 *
 * Each TrixelLine holds:
 *   colour[3]   - the A, B, C Atari colour byte values for this line
 *                 (already in COLUP0/COLUP1/COLUBK register format,
 *                 i.e. bits 7-4 = hue, bits 3-1 = luminance, bit0 = 0)
 *   bits[3][5] - one 40-bit (packed MSB-first) on/off bitmap per
 *                 physical scanline of the trixel: bits[0]=top row,
 *                 bits[1]=middle row, bits[2]=bottom row. Column 0 is
 *                 bit 7 of bits[row][0].
 *
 * The colour actually shown on physical row r during video frame f is
 * colour[(r + f) % 3] -- i.e. row0:A,B,C  row1:B,C,A  row2:C,A,B across
 * frames 0,1,2 and repeating. That rolling is performed by your display
 * code; this data only supplies the fixed per-row bitmaps and the 3
 * colours to roll through.
 */

#define TRIXEL_WIDTH      40
#define TRIXEL_ROWS       66
#define TRIXEL_BYTES_PER_ROW 5

typedef struct {
    uint8_t colour[3];
    uint8_t bits[3][TRIXEL_BYTES_PER_ROW];
} TrixelLine;

extern const TrixelLine trixel_screen[TRIXEL_ROWS];

#endif /* TEST_H */
